force-app/main/default/objects/SSP_InterfaceDetail__mdt/SSP_InterfaceDetail__mdt.object-meta.xml
<CustomObject>
    <description>Holds information about interface</description>
    <label>Interface Detail</label>
    <pluralLabel>Interface Details</pluralLabel>
</CustomObject>

force-app/main/default/objects/SSP_InterfaceDetail__mdt/fields/Header__c.field-meta.xml
<CustomField>
    <fullName>Header__c</fullName>
    <description>Contains the details of header in JSON format</description>
    <label>Header</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SSP_InterfaceDetail__mdt/fields/SSP_Method__c.field-meta.xml
<CustomField>
    <fullName>SSP_Method__c</fullName>
    <description>This describes the method type of the interface</description>
    <label>SSP_Method</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_InterfaceDetail__mdt/fields/SSP_NamedCredential__c.field-meta.xml
<CustomField>
    <fullName>SSP_NamedCredential__c</fullName>
    <description>Stores the named credential name associated with the interface</description>
    <label>Named Credential</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_InterfaceDetail__mdt/fields/Timeout_Miliseconds__c.field-meta.xml
<CustomField>
    <fullName>Timeout_Miliseconds__c</fullName>
    <description>Contains timeout details in milliseconds</description>
    <label>Timeout (Miliseconds)</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/RestIntegrationService.cls
public abstract class RestIntegrationService implements IIntegrationService{

     /*
    * Method Name    : sendRequest
    * Description    : This framework method is used to create http request using custim metadata
    * Return Type    : Map<HttpRequest, HttpResponse> 
    * Parameter      : HttpRequest
    */
    public static HttpRequest generateRequest(String interfaceName, Map<String, object> mapInputParams){
        HttpRequest request = new HttpRequest();
        //Instantiate the class with the interface name
        Map<String, SObject> mdtMap = new SSP_CustomMetadataAccessor().getAllRecordsMap(SSP_InterfaceConstants.SSP_INTERFACE_DETAIL_MD);
        SSP_InterfaceDetail__mdt interfaceDetail;
        if(!mdtMap.isEmpty() && mdtMap.get(interfaceName)!=null){
            interfaceDetail = (SSP_InterfaceDetail__mdt)mdtMap.get(interfaceName);
        }
        request.setEndpoint(SSP_InterfaceConstants.SSP_CallOut+interfaceDetail.SSP_NamedCredential__c);
        // Set Method.
        if(interfaceDetail.SSP_Method__c != null) {
            request.setMethod(interfaceDetail.SSP_Method__c);
        }
        //set Headers.
        if(interfaceDetail.header__c != null){
            Map<String, Object> mapHeaders = (Map<String, Object>) JSON.deserializeUntyped(interfaceDetail.header__c);
            for(String skey : mapHeaders.keyset()) {
                request.setHeader(sKey,(String) mapHeaders.get(sKey));
            }
        }
        // Set Body
        if (mapInputParams.containsKey(SSP_InterfaceConstants.JSON_BODY)){
            request.setBody((String)mapInputParams.get(SSP_InterfaceConstants.JSON_BODY));
        }
        // Timeout
        if(interfaceDetail.Timeout_Miliseconds__c != null) {
            request.setTimeout(Integer.valueOf(interfaceDetail.Timeout_Miliseconds__c));
        }
        return request;
    }
    
     /*
    * Method Name    : sendRequest
    * Description    : This method is used to send Http request
    * Return Type    : Map<HttpRequest, HttpResponse> 
    * Parameter      : HttpRequest
    */
    public static HttpResponse sendRequest(HttpRequest request){ 
        // initiate call over HTTP.
        HttpResponse oHttpResponse = new HttpResponse();
        Http oHttp = new Http();
        // Send the request to get the response
        oHttpResponse = oHttp.Send(request);
        return oHttpResponse;   
    }
}