force-app/main/default/objects/SSP_Attendance__c/SSP_Attendance__c.object-meta.xml
<CustomObject>
    <description>Stores education and school related information</description>
    <label>SSP Attendance</label>
    <nameField>
        
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        
        <label>SSP_Attendance Name</label>
        
        <type>Text</type>
        
    </nameField>
    <pluralLabel>SSP Attendance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Attendance__c/fields/IsDeleted__c.field-meta.xml
<CustomField>
    <fullName>IsDeleted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to whether the current education record is deleted</description>
    <label>Is Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SSP_Attendance__c/fields/SSP_Member__c.field-meta.xml
<CustomField>
    <fullName>SSP_Member__c</fullName>
    <description>This field is used to indicate related member to an attendance record</description>
    <label>SSP_Member</label>
    <referenceTo>SSP_Member__c</referenceTo>
    <relationshipName>SSP_Attendance</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/SSP_Member__c.object-meta.xml
<CustomObject>
    <description>Stores details about an individual member of a case/application such as gatepost reponse, incarceration, disability, living arrangement, pregnancy, address details. Also repurposed to store information of different individuals in the form of individual alien, alien sponsor, care taker,  care coordinator etc.</description>
    <label>SSP Member</label>
    <nameField>
        
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        
        <label>SSP_Member Name</label>
        
        <type>Text</type>
        
    </nameField>
    <pluralLabel>SSP Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/SSP_AttendaceSelector.cls
/*
* classname 	: SSP_AttendaceSelector
* @description 	: A service class query attendace records.
* @author 		: Ajay Saini
* @date 		: DEC-9-2019
* MODIFICATION LOG:
* DEVELOPER 			DATE 			DESCRIPTION
* ---------------------------------------------------------------------------------------------
* Ajay Saini 		DEC-9-2019			Initial Version
*/
public class SSP_AttendaceSelector {
    private static final String OBJECTNAME = 'SSP_Attendance__c';
 
 
    /***************************************************************************************************
    * @author       Shrikant Raut
    * @date         01/03/2020
    * @methodname   queryAttendanceData
    * @description  This methods is to query records related to SSP_Attendance__c object
    * @return       List<SSP_Attendance__c>
    *****************************************************************************************************/ 
    public static List<SSP_Attendance__c> queryAttendanceData(Map<String, String> mapDetails, Set<String> setFields, Map<String, String> mapConditions){
        List<SSP_Attendance__c> lstAttendance = new List<SSP_Attendance__c>();
        lstAttendance = (List<SSP_Attendance__c>)SSP_Utility.fetchRecords(mapDetails, setFields, mapConditions);
        return lstAttendance;
    }

    /***************************************************************************************************
    * @author       Ajay Saini
    * @date         DEC-12-2019
    * @methodname   queryByMemberId
    * @description  This methods is used to query for SSP_Attendance__c records filtered on basis of member id.
    * @return       List of records
    *****************************************************************************************************/
     public static List<SSP_Attendance__c> queryByMemberId(Set<Id> setMemberIds, List<String> listFields, Boolean bIsDeleted) {
        List<SSP_Attendance__c> attendanceRecords = new List<SSP_Attendance__c>();
        Map<String, String> mapDetails = new Map<String, String>{'objectName' => OBJECTNAME,'IN'=>'SSP_Member__c', 'operator'=>'AND'};
       	Map<String, String> mapConditions = new Map<String, String>{'SSP_Member__c' => String.join(new List<Id>(setMemberIds), ','), 'IsDeleted__c' => String.valueOf(bIsDeleted)};
        Set<String> setFields = new Set<String>(listFields);
        if(ESAPI.accessController().isAuthorizedToView(SSP_Attendance__c.getSObjectType(), SSP_Utility.getFieldsForAuthorisedView(OBJECTNAME, setFields))) {
            attendanceRecords = (List<SSP_Attendance__c>)SSP_Utility.fetchRecords(mapDetails, setFields, mapConditions);
        }
        return attendanceRecords;
     }
}