force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/FridayClose__c.field-meta.xml
<CustomField>
    <fullName>FridayClose__c</fullName>
    <description>Indicates the closing time on Friday for the location</description>
    <label>FridayClose</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/FridayOpen__c.field-meta.xml
<CustomField>
    <fullName>FridayOpen__c</fullName>
    <description>Indicates the opening time on Friday for the location</description>
    <label>FridayOpen</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/MondayClose__c.field-meta.xml
<CustomField>
    <fullName>MondayClose__c</fullName>
    <description>Indicates the closing time on Monday for the location</description>
    <label>MondayClose</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/MondayOpen__c.field-meta.xml
<CustomField>
    <fullName>MondayOpen__c</fullName>
    <description>Indicates the opening time on Monday for the location</description>
    <label>MondayOpen</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Address Information</description>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/SaturdayClose__c.field-meta.xml
<CustomField>
    <fullName>SaturdayClose__c</fullName>
    <description>Indicates the closing time on Saturday for the location</description>
    <label>SaturdayClose</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/SaturdayOpen__c.field-meta.xml
<CustomField>
    <fullName>SaturdayOpen__c</fullName>
    <description>Indicates the opening time on Saturday for the location</description>
    <label>SaturdayOpen</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Indicates whether the status of location is active or inactive</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location__c/fields/SundayClose__c.field-meta.xml
<CustomField>
    <fullName>SundayClose__c</fullName>
    <description>Indicates the closing time on Sunday for the location</description>
    <label>SundayClose</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/SundayOpen__c.field-meta.xml
<CustomField>
    <fullName>SundayOpen__c</fullName>
    <description>Indicates the opening time on Sunday for the location</description>
    <label>SundayOpen</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/ThursdayClose__c.field-meta.xml
<CustomField>
    <fullName>ThursdayClose__c</fullName>
    <description>Indicates the closing time on Thursday for the location</description>
    <label>ThursdayClose</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/ThursdayOpen__c.field-meta.xml
<CustomField>
    <fullName>ThursdayOpen__c</fullName>
    <description>Indicates the opening time on Thursday for the location</description>
    <label>ThursdayOpen</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/TimeZone__c.field-meta.xml
<CustomField>
    <fullName>TimeZone__c</fullName>
    <description>Time zone in which the hours open/close for the location is recorded</description>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>USTimeZones</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location__c/fields/TuesdayClose__c.field-meta.xml
<CustomField>
    <fullName>TuesdayClose__c</fullName>
    <description>Indicates the closing time on Tuesday for the location</description>
    <label>TuesdayClose</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/TuesdayOpen__c.field-meta.xml
<CustomField>
    <fullName>TuesdayOpen__c</fullName>
    <description>Indicates the opening time on Tuesday for the location</description>
    <label>TuesdayOpen</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/WednesdayClose__c.field-meta.xml
<CustomField>
    <fullName>WednesdayClose__c</fullName>
    <description>Indicates the closing time on Wednesday for the location</description>
    <label>WednesdayClose</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/WednesdayOpen__c.field-meta.xml
<CustomField>
    <fullName>WednesdayOpen__c</fullName>
    <description>Indicates the opening time on Wednesday for the location</description>
    <label>WednesdayOpen</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Location__c/recordTypes/Location.recordType-meta.xml
<RecordType>
    <fullName>Location</fullName>
    <active>true</active>
    <description>This record type is used for  location object</description>
    <label>Location</label>
</RecordType>

force-app/main/default/objects/LocationResource__c/LocationResource__c.object-meta.xml
<CustomObject>
    <label>Location Resource</label>
    <nameField>
        <label>Location Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Location Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LocationResource__c/fields/AgesServed__c.field-meta.xml
<CustomField>
    <fullName>AgesServed__c</fullName>
    <label>Ages Served</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Infants (0-1)</fullName>
            </value>
            <value>
                <fullName>Pre-K (1-5)</fullName>
            </value>
            <value>
                <fullName>Children (6-12)</fullName>
            </value>
            <value>
                <fullName>Teenagers (13-19)</fullName>
            </value>
            <value>
                <fullName>Adults (20-55)</fullName>
            </value>
            <value>
                <fullName>Seniors (55+)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/EligibilityDescription__c.field-meta.xml
<CustomField>
    <fullName>EligibilityDescription__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Eligibility Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/FirstPointofContactEmail__c.field-meta.xml
<CustomField>
    <fullName>FirstPointofContactEmail__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>First Point of Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/FirstPointOfContactName__c.field-meta.xml
<CustomField>
    <fullName>FirstPointOfContactName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>First Point Of Contact Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/FirstPointofContactPhone__c.field-meta.xml
<CustomField>
    <fullName>FirstPointofContactPhone__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>First Point of Contact Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/FirstPointOfContactTitle__c.field-meta.xml
<CustomField>
    <fullName>FirstPointOfContactTitle__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>First Point Of Contact Title</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/FridayClose__c.field-meta.xml
<CustomField>
    <fullName>FridayClose__c</fullName>
    <label>FridayClose</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/FridayOpen__c.field-meta.xml
<CustomField>
    <fullName>FridayOpen__c</fullName>
    <label>FridayOpen</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/Geography_Served__c.field-meta.xml
<CustomField>
    <fullName>Geography_Served__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Geography Served</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>The location record to which the location resource is related to</description>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Location Resources</relationshipLabel>
    <relationshipName>Location_Resources</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/MondayClose__c.field-meta.xml
<CustomField>
    <fullName>MondayClose__c</fullName>
    <label>MondayClose</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/MondayOpen__c.field-meta.xml
<CustomField>
    <fullName>MondayOpen__c</fullName>
    <label>MondayOpen</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <description>The resource record to which the location resource is related to</description>
    <label>Resource</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Location Resources</relationshipLabel>
    <relationshipName>Location_Resources</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/ResourceDescription__c.field-meta.xml
<CustomField>
    <fullName>ResourceDescription__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Resource Description</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/SaturdayClose__c.field-meta.xml
<CustomField>
    <fullName>SaturdayClose__c</fullName>
    <label>SaturdayClose</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/SaturdayOpen__c.field-meta.xml
<CustomField>
    <fullName>SaturdayOpen__c</fullName>
    <label>SaturdayOpen</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/SecondPointofContactEmail__c.field-meta.xml
<CustomField>
    <fullName>SecondPointofContactEmail__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Second Point of Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/SecondPointOfContactName__c.field-meta.xml
<CustomField>
    <fullName>SecondPointOfContactName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Second Point Of Contact Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/SecondPointofContactPhone__c.field-meta.xml
<CustomField>
    <fullName>SecondPointofContactPhone__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Second Point of Contact Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/SecondPointOfContactTitle__c.field-meta.xml
<CustomField>
    <fullName>SecondPointOfContactTitle__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Second Point Of Contact Title</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Not Used</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/SundayClose__c.field-meta.xml
<CustomField>
    <fullName>SundayClose__c</fullName>
    <label>SundayClose</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/SundayOpen__c.field-meta.xml
<CustomField>
    <fullName>SundayOpen__c</fullName>
    <label>SundayOpen</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/ThursdayClose__c.field-meta.xml
<CustomField>
    <fullName>ThursdayClose__c</fullName>
    <label>ThursdayClose</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/ThursdayOpen__c.field-meta.xml
<CustomField>
    <fullName>ThursdayOpen__c</fullName>
    <label>ThursdayOpen</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/TollFree__c.field-meta.xml
<CustomField>
    <fullName>TollFree__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>TollFree</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/TuesdayClose__c.field-meta.xml
<CustomField>
    <fullName>TuesdayClose__c</fullName>
    <label>TuesdayClose</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/TuesdayOpen__c.field-meta.xml
<CustomField>
    <fullName>TuesdayOpen__c</fullName>
    <label>TuesdayOpen</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/WednesdayClose__c.field-meta.xml
<CustomField>
    <fullName>WednesdayClose__c</fullName>
    <label>WednesdayClose</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/WednesdayOpen__c.field-meta.xml
<CustomField>
    <fullName>WednesdayOpen__c</fullName>
    <label>WednesdayOpen</label>
    <type>Time</type>
</CustomField>

force-app/main/default/globalValueSets/USTimeZones.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>EST</fullName>
        
        
        <label>EST</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>CST</fullName>
        
        
        <label>CST</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>MST</fullName>
        
        
        <label>MST</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>PST</fullName>
        
        
        <label>PST</label>
        
    </customValue>
    
    <masterLabel>US Time Zones</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/classes/RE_ResourceLocationCtrl.cls
/**
* Class Name    : RE_ResourceLocationCtrl
* Owner         : DELOITTE
* Created Date  : 01/28/2020
* Description   : Adding and updating the Location Resource details
*
*                            M O D I F I C A T I O N   L O G                                          
*
*  Date        Developer       Description                                                         
*  ----------  -----------     -------------------------------------------------------------------
*  01/28/2020  SRIKANTH       Initial Version
*  
**/
public with sharing class RE_ResourceLocationCtrl {
    
    /*********************************************************************************************************************************
* @author       Kojashree Kakariya
* @date         01/28/2020
* @methodname   updateLocationResource()
* @description  This updates the Resource Location details
* @param        
* @return       RE_CreateLightningServerResponse  
************************************************************************************************************************************/
    @AuraEnabled
    public static RE_CreateLightningServerResponse updateResourceLocation(String locRes, String resID){
        String strResId=String.isNotBlank(resID)?String.escapeSingleQuotes(resID):'';
        RE_ResourceLocationCtrl.LocationResourceWrapper locationResource = (RE_ResourceLocationCtrl.LocationResourceWrapper)JSON.deserialize(locRes, RE_ResourceLocationCtrl.LocationResourceWrapper.class);
        GeneralUtility.isAuthenticatedUser();
        Boolean bSuccess = false;
        Map<String, Object> mapResponse = new Map<String, Object>();
        Map<String, Object> errorMap = new Map<String, Object>();
        try {
            //will update logic for updating Location Resource
            
            
            /* Location__c parentLocationObj = [Select MondayOpen__c,MondayClose__c,TuesdayOpen__c,TuesdayClose__c,WednesdayOpen__c,WednesdayClose__c,
ThursdayOpen__c,ThursdayClose__c,FridayOpen__c,FridayClose__c,SaturdayOpen__c,SaturdayClose__c,
SundayOpen__c,SundayClose__c from Location__c where id =: locationResource.slocationResOffering];*/
            
            String LocId =   String.escapeSingleQuotes(locationResource.slocationResOffering);
            Location__c parentLocationObj;
            String sFieldsApiNamesForDays = RE_DataBaseQueryFields.sDaysFieldsQueryLocation;       
            String sWhereClauseForDays = RE_DataBaseQueryFields.sWhereClauseForDays ;
            String sQuery;
            
            Map<String,String> mapQueryParameters = new Map<String,String>();
            mapQueryParameters.put(RE_GlobalConstants.sWhereClauseKey, sWhereClauseForDays);
            mapQueryParameters.put(RE_GlobalConstants.sLimitKey, '1');
            
            Map<Boolean,String> mapLocation = RE_DataAccessChecker.getFieldsAccessibility('Location__c',sFieldsApiNamesForDays,mapQueryParameters);
            if(mapLocation.get(true) != null){
                sQuery =  mapLocation.get(true);
                parentLocationObj = Database.query(sQuery);
                
            }else{
                LOG_LogMessageUtility.logMessage(LOG_LogMessageUtility.LOG_LogLevel.Error,'RE_ResourceLocationCtrl','updateResourceLocation','***FLS Violation***'+mapLocation.get(false),true);
            }
            
            LocationResource__c resLocData = new LocationResource__c();
          //  resLocData.Id = locationResource.sLocationResourceId;
            if(locationResource.sLocationResourceId == '' || locationResource.sLocationResourceId == null){
               resLocData.Resource__c = strResId; 
               resLocData.Location__c = locationResource.slocationResOffering;
            }else{
                resLocData.Id = strResId;
            }
          
            resLocData.Status__c = locationResource.slocationResStatus;
            resLocData.Phone__c = locationResource.slocationResPhone;
            resLocData.Fax__c = locationResource.slocationResFax;
            resLocData.TollFree__c = locationResource.slocationResTollFree;
            resLocData.AgesServed__c = locationResource.slocationResAgesServed;
            resLocData.ResourceDescription__c = locationResource.slocationResDescription;
            resLocData.EligibilityDescription__c = locationResource.slocationResEligibilty;
            resLocData.Geography_Served__c = locationResource.slocationResGeoAgesServed;
            resLocData.FirstPointOfContactName__c = locationResource.slocationResFirstPOCName;
            resLocData.FirstPointofContactEmail__c = locationResource.slocationResFirstPOCEmail;
            resLocData.FirstPointofContactPhone__c = locationResource.slocationResFirstPOCPhone;
            resLocData.FirstPointOfContactTitle__c = locationResource.slocationResFirstPOCTitle;
            resLocData.SecondPointOfContactName__c = locationResource.slocationResSecondPOCName;
            resLocData.SecondPointOfContactTitle__c = locationResource.slocationResSecondPOCTitle;
            resLocData.SecondPointofContactPhone__c = locationResource.slocationResSecondPOCPhone;
            resLocData.SecondPointofContactEmail__c = locationResource.slocationResSecondPOCEmail;
            resLocData.TimeZone__c = locationResource.slocationResTimeZone;
            resLocData.Fees__c = locationResource.slocationResFees;
            resLocData.Notes__c = locationResource.slocationResNotes;
            resLocData.NextSteps__c = locationResource.slocationResNextSteps;
            resLocData.WhatToBring__c = locationResource.slocationResWhatToBring;
            resLocData.EligibilitySNAP__c = locationResource.blocationResSNAP;
            resLocData.EligibilityCCAP__c = locationResource.blocationResCCAP;
            resLocData.EligibilityTANF__c = locationResource.blocationResTANF;
            resLocData.EligibilityMedicaid__c = locationResource.blocationResMedicaid;
            resLocData.ResourceDescription__c = locationResource.slocationResDescription;
            resLocData.DaysClosed__c = locationResource.sDaysLocationClosed;
            
          //  resLocData.MondayOpen__c = locationResource.tlocationResMondayOpen != null?convertToLocalTime(locationResource.tlocationResMondayOpen):parentLocationObj.MondayOpen__c;
              
            if(locationResource.tlocationResMondayOpen != null ){
                resLocData.MondayOpen__c = convertToLocalTime(locationResource.tlocationResMondayOpen);
            }
            else{
                resLocData.MondayOpen__c = null;
            }
           
            if(locationResource.tlocationResMondayClose != null ){
                resLocData.MondayClose__c = convertToLocalTime(locationResource.tlocationResMondayClose);
            }
            else{
                resLocData.MondayClose__c = null;
            }
           
            if(locationResource.tlocationResTuesdayOpen != null ){
                resLocData.TuesdayOpen__c = convertToLocalTime(locationResource.tlocationResTuesdayOpen);
            }
            else{
                resLocData.TuesdayOpen__c = null;
            }
           
            if(locationResource.tlocationResTuesdayClose != null ){
                resLocData.TuesdayClose__c = convertToLocalTime(locationResource.tlocationResTuesdayClose);
            }
            else{
                resLocData.TuesdayClose__c = null;
            }
            
            if(locationResource.tlocationResWednesdayOpen != null ){
                resLocData.WednesdayOpen__c = convertToLocalTime(locationResource.tlocationResWednesdayOpen);
            }
            else{
                resLocData.WednesdayOpen__c = null;
            }
           
            if(locationResource.tlocationResWednesdayClose != null ){
                resLocData.WednesdayClose__c = convertToLocalTime(locationResource.tlocationResWednesdayClose);
            }
            else{
                  resLocData.WednesdayClose__c = null;
            }
            if(locationResource.tlocationResThursdayOpen != null ){
                resLocData.ThursdayOpen__c = convertToLocalTime(locationResource.tlocationResThursdayOpen);
            }
            else{
                resLocData.ThursdayOpen__c  = null;
            }
           
            if(locationResource.tlocationResThursdayClose != null ){
                resLocData.ThursdayClose__c = convertToLocalTime(locationResource.tlocationResThursdayClose);
            }else{
                //RE_Release 1.1 – Defect 359098- Payal Dubela– Opertaing hour issue
                resLocData.ThursdayClose__c=null;
            }
          
             if(locationResource.tlocationResFridayOpen != null ){
                resLocData.FridayOpen__c = convertToLocalTime(locationResource.tlocationResFridayOpen);
            }
            else{
                resLocData.FridayOpen__c = null;
            }
           
          
            if(locationResource.tlocationResFridayClose != null ){
                resLocData.FridayClose__c = convertToLocalTime(locationResource.tlocationResFridayClose);
            }
            else{
                resLocData.FridayClose__c = null;
            }
            if(locationResource.tlocationResSaturdayOpen != null ){
                resLocData.SaturdayOpen__c = convertToLocalTime(locationResource.tlocationResSaturdayOpen);
            }
            else{
                resLocData.SaturdayOpen__c = null;
            }
           
            if(locationResource.tlocationResSaturdayClose != null ){
                resLocData.SaturdayClose__c = convertToLocalTime(locationResource.tlocationResSaturdayClose);
            }
            else{
                resLocData.SaturdayClose__c = null;
            }
            if(locationResource.tlocationResSundayOpen != null ){
                resLocData.SundayOpen__c = convertToLocalTime(locationResource.tlocationResSundayOpen);
            }
            else{
                resLocData.SundayOpen__c = null;
            }
           
          
            if(locationResource.tlocationResSundayClose != null ){
                resLocData.SundayClose__c = convertToLocalTime(locationResource.tlocationResSundayClose);
            }
            else{
                resLocData.SundayClose__c  = null;
            }

            
            if(locationResource.sLocationResourceId == null || locationResource.sLocationResourceId == ''){
                //insert the location resource record
                RE_DataAccessChecker.insertObject(LocationResource__c.getSObjectType(), resLocData);
                bSuccess = true;
            }else{
                //update the record
                RE_DataAccessChecker.updateObject(LocationResource__c.getSObjectType(),resLocData);
                bSuccess = true;
            }
            

        } catch (Exception e) {
            errorMap.put('error', e.getMessage());
            bSuccess = false;
            LOG_LogMessageUtility.logMessage(LOG_LogMessageUtility.LOG_LogLevel.Error, 'RE_ResourceLocation','updateResourceLocation', e.getMessage(), true);
        }
        return new RE_CreateLightningServerResponse(bSuccess, errorMap, mapResponse); 
    }
    
    
    
    public static Time convertToLocalTime(String inputTime){
        
        /*Date dToday = system.today();
        
        Datetime dateToday =  Datetime.newInstanceGmt(dToday,inputTime);

        TimeZone tz = UserInfo.getTimeZone();
        
        String local = dateToday.format('HH:mm:ss');
        List<String> lstTimeParams = local.split(':');*/
        
        List<String> lstTimeParams = inputTime.split(':');
        Time timeData = Time.newInstance(integer.valueOf(lstTimeParams[0]),integer.valueOf(lstTimeParams[1]),0,0);

        return timeData;
        
    }
    
    /**************************************************************************************
* @author       Kojashree Kakariya
* @methodname   getPickListValues()
* @description  This methods is used to get the picklist values from given sObject
* @param        objectName          (String)   : sObject Name
* @param        lstFields           (String)   : Multiple picklists separated by (,)
* @return       RE_CreateLightningServerResponse 
******************************************************************************************/
    @AuraEnabled
    public static RE_CreateLightningServerResponse getPickListValues(String objectName, String lstFields){
        GeneralUtility.isAuthenticatedUser();
        Boolean bSuccess = false;
        Map<String, Object> errorMap = new Map<String, Object>{};
            Map<String, Object> mapResponse = new Map<String, Object>{};
                try {
                    Map<String,Map<String,String>> values = GeneralUtility.fetchFieldsPicklistValueAPIName(String.escapeSingleQuotes(objectName), String.escapeSingleQuotes(lstFields));
                    bSuccess = true;
                    mapResponse.put('picklistvalues', values);
                    RE_ResourceLocationCtrl.LocationResourceWrapper objLocRes = new RE_ResourceLocationCtrl.LocationResourceWrapper(new LocationResource__c());
                    mapResponse.put('objLocRes', objLocRes);
                    
                } catch (Exception e) {
                    LOG_LogMessageUtility.logMessage(LOG_LogMessageUtility.LOG_LogLevel.Error, 'RE_ResourceLocation','getPickListValues',e.getMessage(), true);
                }
        return new RE_CreateLightningServerResponse(bSuccess, errorMap, mapResponse);
    }
    
    @AuraEnabled
    public Static RE_CreateLightningServerResponse getResourceLocationDetails(String strRecordId) {
        String sRecordId = String.escapeSingleQuotes(strRecordId);
        GeneralUtility.isAuthenticatedUser();
        String sResult;
        Boolean bSuccess = false;
        Map<String, Object> mapResult = new Map<String, Object>();
        Map<String, Object> errorMap = new Map<String, Object>();
        try{
            if(strRecordId != null){
                
            String sFieldsApiName = RE_DataBaseQueryFields.sFieldsToQueryOnLocationResourceCtrl;
            String sWhereClause = RE_DataBaseQueryFields.sWhereClauseOnLocationResourceCtrl;
            String sQuery;
            
            Map<String,String> mapQueryParameters = new Map<String,String>();
            
            mapQueryParameters.put(RE_GlobalConstants.sWhereClauseKey, sWhereClause);
            mapQueryParameters.put(RE_GlobalConstants.sLimitKey, '1');
            
            Map<Boolean,String> mapResponse = RE_DataAccessChecker.getFieldsAccessibility('LocationResource__c',sFieldsApiName,mapQueryParameters);
            RE_GlobalConstants.SWITCH_CONSTANTS switchCaseKey = (mapResponse.get(true) != null) ? RE_GlobalConstants.SWITCH_CONSTANTS.SWITCH_SUCCESS : RE_GlobalConstants.SWITCH_CONSTANTS.SWITCH_FAILURE;                                                                           
            switch on (switchCaseKey) {
                when SWITCH_SUCCESS {
                    sQuery =  mapResponse.get(true);
                    
                    List<LocationResource__c> lstLocationResource = Database.query(sQuery); 
                    if (lstLocationResource.isEmpty() == false) {//SIT Error Log Fix - Suresh
                        bSuccess = true;
                        mapResult.put('result',JSON.serialize(new LocationResourceWrapper(lstLocationResource[0])));
                        /*:::: Added by Suresh Starts ::::*/
                         Boolean bHasPermission = RE_OrganizationDetailsCtrl.userPermissionAccess();
                         mapResult.put('isAdminUser', bHasPermission);
                         /*:::: Added by Suresh Ends ::::*/
                        Boolean bAgencyHasPermission = RE_OrganizationDetailsCtrl.agencyUserPermissionAccess();
                        mapResult.put('isAgencyUser', bAgencyHasPermission);
                        //sResult = JSON.serialize(lstLocations[0]);
                    } 
                } 
                when SWITCH_FAILURE {
                    bSuccess = false; errorMap.put('error', 'Field access error.'); LOG_LogMessageUtility.logMessage(LOG_LogMessageUtility.LOG_LogLevel.Error, 'RE_LocationCtrl','getLocationDetails','Some Fields doesn\'t have the required access :: '+mapResponse.get(false), true);
                    
                }
            }
            }
        }catch(Exception e){
            bSuccess = false;
            errorMap.put('error', e.getMessage());
            LOG_LogMessageUtility.logMessage(LOG_LogMessageUtility.LOG_LogLevel.Error, 'RE_ResourceLocation','getResourceLocationDetails',e.getMessage(),true);
        }
        return new RE_CreateLightningServerResponse(bSuccess, errorMap, mapResult); 
    }

    @AuraEnabled
    public static RE_CreateLightningServerResponse checkResourceLocation(String strLocId,String strRecID) {
        GeneralUtility.isAuthenticatedUser();
        Boolean bSuccess = false;
        String locId=String.isNotBlank(strLocId)?String.escapeSingleQuotes(strLocId):'';
        String recId=String.isNotBlank(strRecID)?String.escapeSingleQuotes(strRecID):'';
        Map<String, Object> mapResult = new Map<String, Object>();
        Map<String, Object> errorMap = new Map<String, Object>();
        try{
        String sWhereClause = RE_DataBaseQueryFields.sWhereClauseForLocationResource;
        String sFieldsApiName = RE_DataBaseQueryFields.sFieldsToQueryOnLocationResource;
        Map<String, String> mapQueryParameters = new Map<String, String>();
        String sQuery;
        
        List<LocationResource__c> lstRecords=new List<LocationResource__c>();
        mapQueryParameters.put(RE_GlobalConstants.sWhereClauseKey, sWhereClause);
        
        Map<Boolean, String> mapResponsesObjectName = RE_DataAccessChecker.getFieldsAccessibility('LocationResource__c', sFieldsApiName, mapQueryParameters);
        
        if (mapResponsesObjectName.get(true) != null) {
            sQuery = mapResponsesObjectName.get(true);                    
        } else {
            LOG_LogMessageUtility.logMessage(LOG_LogMessageUtility.LOG_LogLevel.Error,'RE_ClientsHelper','getData','Some Fields doesnt have the required access : '+mapResponsesObjectName.get(false),true);
        }
        Map<String, String> mapInputs= new Map<String,String>();
        if (sQuery != null) {
            lstRecords = RE_SharingByPassCtrl.checkLocationRes(sQuery,locId,recId);
        }
        if(lstRecords.size()>0){
            mapResult.put('isRecordFound',true);
        }else{
            mapResult.put('isRecordFound',false);
        }
         bSuccess=true;
        }catch(Exception e){
            bSuccess = false;
            errorMap.put('error', e.getMessage());
            LOG_LogMessageUtility.logMessage(LOG_LogMessageUtility.LOG_LogLevel.Error, 'RE_ResourceLocation','checkLocationResource',e.getMessage(),true);
        }
        return new RE_CreateLightningServerResponse(bSuccess, errorMap, mapResult); 

    }
    /*********************************************************************************************************************************
* @author       Kojashree Kakariya
* @date         01/28/2020
* @class        wrappper class for saving and updating Location Resource
* @description  Captures the details of Resource Location        
************************************************************************************************************************************/
    
    public class LocationResourceWrapper{
       
        @AuraEnabled  
        public String AccountId;
        @AuraEnabled
        public String sResourceId{get;set;}
        @AuraEnabled 
        public String sLocationResourceId{get;set;}
        @AuraEnabled 
        public String slocationResOffering{get;set;}
        @AuraEnabled 
        public String slocationResStatus{get;set;}
        @AuraEnabled 
        public String slocationResPhone{get;set;}
        @AuraEnabled 
        public String slocationResFax{get;set;}
        @AuraEnabled 
        public String slocationResTollFree{get;set;}
        @AuraEnabled 
        public String slocationResAgesServed{get;set;}
         @AuraEnabled 
        public String slocationResDescription{get;set;}
        @AuraEnabled 
        public String slocationResEligibilty{get;set;}
        @AuraEnabled 
        public String slocationResGeoAgesServed{get;set;}
        @AuraEnabled
        public String slocationResFirstPOCName{get;set;}
        @AuraEnabled
        public String slocationResFirstPOCTitle{get;set;}
        @AuraEnabled
        public String slocationResFirstPOCEmail{get;set;}
        @AuraEnabled
        public String slocationResFirstPOCPhone{get;set;}
        @AuraEnabled
        public String slocationResSecondPOCName{get;set;}
        @AuraEnabled
        public String slocationResSecondPOCTitle{get;set;}
        @AuraEnabled
        public String slocationResSecondPOCEmail{get;set;}
        @AuraEnabled
        public String slocationResSecondPOCPhone{get;set;}
        @AuraEnabled
        public String slocationResTimeZone{get;set;}
        @AuraEnabled
        public String slocationResFees{get;set;}
        @AuraEnabled
        public String slocationResNotes{get;set;}
        @AuraEnabled
        public String slocationResNextSteps{get;set;}
        @AuraEnabled
        public String slocationResWhatToBring{get;set;}
        @AuraEnabled
        public String slocationResEligibilityDesc{get;set;}
        @AuraEnabled
        public Boolean blocationResSNAP{get;set;}
        @AuraEnabled
        public Boolean blocationResCCAP{get;set;}
        @AuraEnabled
        public Boolean blocationResTANF{get;set;}
        @AuraEnabled
        public Boolean blocationResMedicaid{get;set;}
        @AuraEnabled 
        public String tlocationResMondayOpen{get;set;}
        @AuraEnabled 
        public String tlocationResMondayClose{get;set;}
        @AuraEnabled 
        public String tlocationResTuesdayClose{get;set;}
        @AuraEnabled 
        public String tlocationResTuesdayOpen{get;set;}
        @AuraEnabled 
        public String tlocationResWednesdayClose{get;set;}
        @AuraEnabled 
        public String tlocationResWednesdayOpen{get;set;}
        @AuraEnabled 
        public String tlocationResThursdayClose{get;set;}
        @AuraEnabled 
        public String tlocationResThursdayOpen{get;set;}
        @AuraEnabled 
        public String tlocationResFridayClose{get;set;}
        @AuraEnabled 
        public String tlocationResFridayOpen{get;set;}
        @AuraEnabled 
        public String tlocationResSaturdayClose{get;set;}
        @AuraEnabled 
        public String tlocationResSaturdayOpen{get;set;}
        @AuraEnabled 
        public String tlocationResSundayClose{get;set;}
        @AuraEnabled 
        public String tlocationResSundayOpen{get;set;}
        @AuraEnabled
        public Boolean bIsMondayClosed{get;set;}
        @AuraEnabled
        public Boolean bIsTuesdayClosed{get;set;}
        @AuraEnabled
        public Boolean bIsWednesdayClosed{get;set;}
        @AuraEnabled
        public Boolean bIsThursdayClosed{get;set;}
        @AuraEnabled
        public Boolean bIsFridayClosed{get;set;}
        @AuraEnabled
        public Boolean bIsSaturdayClosed{get;set;}
        @AuraEnabled
        public Boolean bIsSundayClosed{get;set;}
        @AuraEnabled
        public String sDaysLocationClosed{get;set;}
        
        public LocationResourceWrapper(LocationResource__c objResLoc){
            this.sResourceId = objResLoc.Resource__c;
            this.sLocationResourceId = objResLoc.Id;
            this.slocationResOffering = objResLoc.Location__c;
            this.slocationResStatus = objResLoc.Status__c;
            this.slocationResPhone = objResLoc.Phone__c;
            this.slocationResFax = objResLoc.Fax__c;
            this.slocationResTollFree = objResLoc.TollFree__c;
            this.slocationResAgesServed = objResLoc.AgesServed__c;
            this.slocationResEligibilty = objResLoc.EligibilityDescription__c;
            this.slocationResDescription = objResLoc.ResourceDescription__c;
            this.slocationResGeoAgesServed = objResLoc.Geography_Served__c;
            this.slocationResFirstPOCName = objResLoc.FirstPointOfContactName__c;
            this.slocationResFirstPOCTitle = objResLoc.FirstPointOfContactTitle__c;
            this.slocationResFirstPOCPhone = objResLoc.FirstPointofContactPhone__c;
            this.slocationResFirstPOCEmail = objResLoc.FirstPointofContactEmail__c;
            this.slocationResSecondPOCName = objResLoc.SecondPointOfContactName__c;
            this.slocationResSecondPOCTitle = objResLoc.SecondPointOfContactTitle__c;
            this.slocationResSecondPOCEmail = objResLoc.SecondPointofContactEmail__c;
            this.slocationResSecondPOCPhone = objResLoc.SecondPointofContactPhone__c;
            this.blocationResSNAP = objResLoc.EligibilitySNAP__c;
            this.blocationResCCAP = objResLoc.EligibilityCCAP__c;
            this.blocationResTANF  = objResLoc.EligibilityTANF__c;
            this.blocationResMedicaid = objResLoc.EligibilityMedicaid__c;
            this.tlocationResMondayOpen  = String.valueOf(objResLoc.MondayOpen__c);
            this.tlocationResMondayClose  = String.ValueOf(objResLoc.MondayClose__c);
            this.tlocationResTuesdayClose  = String.valueOf(objResLoc.TuesdayClose__c);
            this.tlocationResTuesdayOpen  = String.valueOf(objResLoc.TuesdayOpen__c);
            this.tlocationResWednesdayClose  = String.valueOf(objResLoc.WednesdayClose__c);
            this.tlocationResWednesdayOpen  = String.valueOf(objResLoc.WednesdayOpen__c);
            this.tlocationResThursdayClose  = String.valueOf(objResLoc.ThursdayClose__c);
            this.tlocationResThursdayOpen  = String.valueOf(objResLoc.ThursdayOpen__c);
            this.tlocationResFridayClose  = String.valueOf(objResLoc.FridayClose__c);
            this.tlocationResFridayOpen  = String.valueOf(objResLoc.FridayOpen__c);
            this.tlocationResSaturdayClose  = String.valueOf(objResLoc.SaturdayClose__c);
            this.tlocationResSaturdayOpen  = String.valueOf(objResLoc.SaturdayOpen__c);
            this.tlocationResSundayClose  = String.valueOf(objResLoc.SundayClose__c);
            this.tlocationResSundayOpen  = String.valueOf(objResLoc.SundayOpen__c);
            this.slocationResTimeZone  = objResLoc.TimeZone__c;
            this.slocationResFees  = objResLoc.Fees__c;
            this.slocationResNotes  = objResLoc.Notes__c;
            this.slocationResNextSteps  = objResLoc.NextSteps__c;
            this.slocationResWhatToBring  = objResLoc.WhatToBring__c;
            this.sDaysLocationClosed = objResLoc.DaysClosed__c;
            
        }
    }
    
}