force-app/main/default/objects/KOGWebservice__c/KOGWebservice__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>KOGWebservice</label>
</CustomObject>

force-app/main/default/objects/KOGWebservice__c/fields/EndURL__c.field-meta.xml
<CustomField>
    <fullName>EndURL__c</fullName>
    <label>EndURL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/KOGWebservice__c/fields/PageURL__c.field-meta.xml
<CustomField>
    <fullName>PageURL__c</fullName>
    <label>Page URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/SSP_KOGRegistrationTest.cls
@isTest
public class SSP_KOGRegistrationTest {
    
    @isTest static  void kogRegistrationTest(){
        KOGWebservice__c obj = new KOGWebservice__c();
        obj.Name = 'KOG SSP Citizen';
        obj.Certificate__c = 'testcert';
        obj.PageURL__c = 'https://sspdev-benefind-reci.cs32.force.com/benefind/s/dashboard';
        obj.ApplicationName__c = 'DEV4 KHBE Self Service Portal';
        obj.Role__c = 'Citizen';
        obj.EndURL__c = 'https://uat.websrvgw.chfs.ky.gov/DEV/parameterpassingsvc/GatewayRedirectContextService.svc';
        insert obj;
        
        Test.startTest();
        	Test.setMock(WebServiceMock.class, new tempuriOrgGateWayRedirectMock());
        	String strContextId = SSP_KOGRegistration.getKogContextID('Citizen');
        	System.assertEquals('Test1234',strContextId);
        Test.stopTest();
        
    }
	
}