force-app/main/default/objects/SSP_Member__c/SSP_Member__c.object-meta.xml
<CustomObject>
    <description>Stores details about an individual member of a case/application such as gatepost reponse, incarceration, disability, living arrangement, pregnancy, address details. Also repurposed to store information of different individuals in the form of individual alien, alien sponsor, care taker,  care coordinator etc.</description>
    <label>SSP Member</label>
    <nameField>
        
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        
        <label>SSP_Member Name</label>
        
        <type>Text</type>
        
    </nameField>
    <pluralLabel>SSP Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Member__c/fields/HasDifferentMailingAddressToggle__c.field-meta.xml
<CustomField>
    <fullName>HasDifferentMailingAddressToggle__c</fullName>
    <description>This field is used to store if individual has different mailing address than HOH</description>
    <label>Have Different Mailing Address ?</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>YesNo</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/IsFixedAddressToggle__c.field-meta.xml
<CustomField>
    <fullName>IsFixedAddressToggle__c</fullName>
    <description>This field is used to store if individual has physical address</description>
    <label>Has Physical Address ?</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>YesNo</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/MailingAddressLine1__c.field-meta.xml
<CustomField>
    <fullName>MailingAddressLine1__c</fullName>
    <description>This field is used to store Address Line 1 value of Mailing Address</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/MailingAddressLine2__c.field-meta.xml
<CustomField>
    <fullName>MailingAddressLine2__c</fullName>
    <description>This field is used to store Address Line 2 value of Mailing Address</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Address Line 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/MailingAddrValidated__c.field-meta.xml
<CustomField>
    <fullName>MailingAddrValidated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to indicate whether the mailing address of member is validated</description>
    <label>Mailing Address Validated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/MailingCertifiedNoStatIndicator__c.field-meta.xml
<CustomField>
    <fullName>MailingCertifiedNoStatIndicator__c</fullName>
    <description>Used to store the cass_no_stat_ind value in Address Verification Service for Mailing Address</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Mailing Certified Stat Indicator</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/MailingCity__c.field-meta.xml
<CustomField>
    <fullName>MailingCity__c</fullName>
    <description>This field is used to store city for a Mailing address of a member</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/MailingCotVacancyIndicator__c.field-meta.xml
<CustomField>
    <fullName>MailingCotVacancyIndicator__c</fullName>
    <description>Used to store the cass_vac_ind value in Address Verification Service for Mailing Address</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Mailing Vacancy Indicator</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/MailingCountryCode__c.field-meta.xml
<CustomField>
    <fullName>MailingCountryCode__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>SSPCountry</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/MailingCountyCode__c.field-meta.xml
<CustomField>
    <fullName>MailingCountyCode__c</fullName>
    <description>This field is used to store county for a Mailing address of a member</description>
    <label>County</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>SSPCounty</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/MailingMailAddrDeliveryCode__c.field-meta.xml
<CustomField>
    <fullName>MailingMailAddrDeliveryCode__c</fullName>
    <description>Used to store the cot_mail_delivery_code value in Address Verification Service for Mailing Address</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Mailing Mail Delivery Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/MailingResidentialDeliveryIndicator__c.field-meta.xml
<CustomField>
    <fullName>MailingResidentialDeliveryIndicator__c</fullName>
    <description>Used to store the cass_rdi_ind value in Address Verification Service for mailing Address</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Mailing Delivery Indicator</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/MailingStateCode__c.field-meta.xml
<CustomField>
    <fullName>MailingStateCode__c</fullName>
    <description>This field is used to store mailing state code for mailing address on a member</description>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>SSPState</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/MailingZipCode4__c.field-meta.xml
<CustomField>
    <fullName>MailingZipCode4__c</fullName>
    <description>This field is used to store 4 digit Mailing Zip code</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Zip Code(Four Digit)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/MailingZipCode5__c.field-meta.xml
<CustomField>
    <fullName>MailingZipCode5__c</fullName>
    <description>This field is used to store 5 digit Mailing Zip code</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Zip Code(Five Digit)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/PhysicalAddressLine1__c.field-meta.xml
<CustomField>
    <fullName>PhysicalAddressLine1__c</fullName>
    <description>This field is used to store Address Line 1 value of Physical Address</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/PhysicalAddressLine2__c.field-meta.xml
<CustomField>
    <fullName>PhysicalAddressLine2__c</fullName>
    <description>This field is used to store Address Line 2 value of Physical Address</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Address Line 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/PhysicalAddrValidated__c.field-meta.xml
<CustomField>
    <fullName>PhysicalAddrValidated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to indicate whether a member physical address is validated</description>
    <label>Physical Address Validated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/PhysicalCertifiedNoStatIndicator__c.field-meta.xml
<CustomField>
    <fullName>PhysicalCertifiedNoStatIndicator__c</fullName>
    <description>Used to store the cass_no_stat_ind value in Address Verification Service for Physical Address</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Physical Certified Stat Indicator</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/PhysicalCity__c.field-meta.xml
<CustomField>
    <fullName>PhysicalCity__c</fullName>
    <description>This field is used to store city for a Physical address of a member</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/PhysicalCotVacancyIndicator__c.field-meta.xml
<CustomField>
    <fullName>PhysicalCotVacancyIndicator__c</fullName>
    <description>This field is used to store Physical vacancy Indicator</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Physical Vacancy Indicator</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/PhysicalCountryCode__c.field-meta.xml
<CustomField>
    <fullName>PhysicalCountryCode__c</fullName>
    <description>This field is used to store country for a Physical address of a member</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>SSPCountry</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/PhysicalCountyCode__c.field-meta.xml
<CustomField>
    <fullName>PhysicalCountyCode__c</fullName>
    <label>County</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>SSPCounty</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/PhysicalMailAddrDeliveryCode__c.field-meta.xml
<CustomField>
    <fullName>PhysicalMailAddrDeliveryCode__c</fullName>
    <description>Used to store the cot_mail_delivery_code value in Address Verification Service for Physical Address</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Physical Mail Delivery Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/PhysicalResidentialDeliveryIndicator__c.field-meta.xml
<CustomField>
    <fullName>PhysicalResidentialDeliveryIndicator__c</fullName>
    <description>Used to store the cass_rdi_ind value in Address Verification Service for Physical Address</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Physical Delivery Indicator</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/PhysicalStateCode__c.field-meta.xml
<CustomField>
    <fullName>PhysicalStateCode__c</fullName>
    <description>This field is used to store physical state code for physical address on a member</description>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>SSPState</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/PhysicalZipCode4__c.field-meta.xml
<CustomField>
    <fullName>PhysicalZipCode4__c</fullName>
    <description>This field is used to store 4 digit Physical Zip code</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Zip Code (Four Digit)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/PhysicalZipCode5__c.field-meta.xml
<CustomField>
    <fullName>PhysicalZipCode5__c</fullName>
    <description>This field is used to store 5 digit Physical Zip code</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Zip Code (Five Digit)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/SameAddressInfoAsHOHToggle__c.field-meta.xml
<CustomField>
    <fullName>SameAddressInfoAsHOHToggle__c</fullName>
    <description>This field is used to store if individual has same address as that of HOH</description>
    <label>Same Address Information as HOH</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>YesNo</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/SameAddressOfHoh__c.field-meta.xml
<CustomField>
    <fullName>SameAddressOfHoh__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to determine if the non primary applicant will have same address as HOH</description>
    <label>SameAddressOfHoh</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/YesNo.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>Y</fullName>
        
        
        <label>YES</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>N</fullName>
        
        
        <label>NO</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>U</fullName>
        
        
        <label>Unknown</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>NULL</fullName>
        
        
        <label>NULL</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>H</fullName>
        
        
        <label>Historical</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>I don&apos;t know</fullName>
        
        
        <label>I don&apos;t know</label>
        
    </customValue>
    
    <description>Used to store different types of toggle picklist values</description>
    
    <masterLabel>YesNo</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/classes/SSP_ApplicantAddressController.cls
/*
* classname     : SSP_ApplicantAddressController
* @description  : A controller class for handling primary and non-primary address screen component.
* @author       : Ajay Saini
* @date         : DEC-2-2019
* MODIFICATION LOG:
* DEVELOPER             DATE            DESCRIPTION
* ---------------------------------------------------------------------------------------------
* Ajay Saini        DEC-2-2019          Initial Version
*/

public with sharing class SSP_ApplicantAddressController {
    private static final String CLASSNAME = 'SSP_ApplicantAddressController';
    private static List<String> addressFields = new List<String>{
        'IsFixedAddressToggle__c',
        'HasDifferentMailingAddressToggle__c',
        'SameAddressOfHoh__c',
        'SameAddressInfoAsHOHToggle__c',
        'PhysicalAddressLine1__c',
        'PhysicalAddressLine2__c',
        'PhysicalCity__c',
        'PhysicalCountyCode__c',
        'PhysicalStateCode__c',
        'PhysicalCountryCode__c',
        'PhysicalZipCode4__c',
        'PhysicalZipCode5__c',
        'MailingAddressLine1__c',
        'MailingAddressLine2__c',
        'MailingCity__c',
        'MailingCountyCode__c',
        'MailingStateCode__c',
        'MailingCountryCode__c',
        'MailingZipCode4__c',
        'MailingZipCode5__c',
        'PhysicalAddrValidated__c',
        'PhysicalMailAddrDeliveryCode__c',
        'PhysicalCertifiedNoStatIndicator__c',
        'PhysicalResidentialDeliveryIndicator__c',
        'PhysicalCotVacancyIndicator__c',
        'MailingAddrValidated__c',
        'MailingMailAddrDeliveryCode__c',
        'MailingCertifiedNoStatIndicator__c',
        'MailingResidentialDeliveryIndicator__c',
        'MailingCotVacancyIndicator__c',
        'MailingGeolocation__Latitude__s',
        'MailingGeolocation__Longitude__s',
        'PhysicalGeolocation__Latitude__s',
        'PhysicalGeolocation__Longitude__s'
    };

    /***************************************************************************************************
    * @author       Ajay Saini
    * @date         DEC-2-2019
    * @methodname   updateAddress
    * @description  This method is used to fetch for application and member data
    * @return       Status of update operation
    *****************************************************************************************************/
    @AuraEnabled
    public static SSP_LightningResponse updateAddress(SSP_Member__c address, Id applicationId, Boolean bIsAddressChanged) {
        SSP_Utility.isAuthenticatedUser();
        SSP_LightningResponse response = new SSP_LightningResponse();
        List<SSP_ApplicationIndividual__c> lstAppIndividuals;
        List<SSP_Application__c>  lstApps;
        List<String> lstAppFields = new List<String>{'IsPrimaryApplicantAddressModified__c'};
        try {
            List<SSP_Member__c> recordsToUpdate = new List<SSP_Member__c>{address};
                SSP_Member__c objMember;
            Boolean isFixedAddress = address.IsFixedAddressToggle__c == SSP_GlobalConstants.YES;
            Boolean isMailingAddressDifferent = address.HasDifferentMailingAddressToggle__c == SSP_GlobalConstants.YES;
            List<LOG_LogMessage__c> logRecords = SSP_AddressService.validateMemberAddress(recordsToUpdate);
            if(isFixedAddress == true && isMailingAddressDifferent == false) {
                SSP_AddressService.copyMailingFromPhysicalAddress(recordsToUpdate);
            }
            if(address.SameAddressInfoAsHOHToggle__c == SSP_GlobalConstants.YES && applicationId != null) {
                objMember = populateAddressOnHOH(applicationId);
            }
            if(objMember != NULL){
                objMember.SameAddressOfHoh__c = true;
                objMember.IsFixedAddressToggle__c = address.IsFixedAddressToggle__c;
                objMember.HasDifferentMailingAddressToggle__c = address.HasDifferentMailingAddressToggle__c;
                objMember.PhysicalAddressLine1__c = address.PhysicalAddressLine1__c;
                objMember.PhysicalAddressLine2__c = address.PhysicalAddressLine2__c;
                objMember.PhysicalCity__c = address.PhysicalCity__c;
                objMember.PhysicalCountyCode__c = address.PhysicalCountyCode__c;
                objMember.PhysicalStateCode__c = address.PhysicalStateCode__c;
                objMember.PhysicalCountryCode__c = address.PhysicalCountryCode__c;
                objMember.PhysicalZipCode4__c = address.PhysicalZipCode4__c;
                objMember.PhysicalZipCode5__c = address.PhysicalZipCode5__c;
                
                objMember.MailingAddressLine1__c = address.MailingAddressLine1__c;
                objMember.MailingAddressLine2__c = address.MailingAddressLine2__c;
                objMember.MailingCity__c = address.MailingCity__c;
                objMember.MailingCountyCode__c = address.MailingCountyCode__c;
                objMember.MailingStateCode__c = address.MailingStateCode__c;
                objMember.MailingCountryCode__c = address.MailingCountryCode__c;
                objMember.MailingZipCode4__c = address.MailingZipCode4__c;
                objMember.MailingZipCode5__c = address.MailingZipCode5__c;
                
                objMember.PhysicalAddrValidated__c = address.PhysicalAddrValidated__c;
                objMember.PhysicalMailAddrDeliveryCode__c = address.PhysicalMailAddrDeliveryCode__c;
                objMember.PhysicalCertifiedNoStatIndicator__c = address.PhysicalCertifiedNoStatIndicator__c;
                objMember.PhysicalResidentialDeliveryIndicator__c = address.PhysicalResidentialDeliveryIndicator__c;
                objMember.PhysicalCotVacancyIndicator__c = address.PhysicalCotVacancyIndicator__c;
                objMember.PhysicalGeolocation__Latitude__s = address.PhysicalGeolocation__Latitude__s;
                objMember.PhysicalGeolocation__Longitude__s = address.PhysicalGeolocation__Longitude__s;
                
                objMember.MailingAddrValidated__c = address.MailingAddrValidated__c;
                objMember.MailingMailAddrDeliveryCode__c = address.MailingMailAddrDeliveryCode__c;
                objMember.MailingCertifiedNoStatIndicator__c = address.MailingCertifiedNoStatIndicator__c;
                objMember.MailingResidentialDeliveryIndicator__c = address.MailingResidentialDeliveryIndicator__c;
                objMember.MailingCotVacancyIndicator__c = address.MailingCotVacancyIndicator__c;
                objMember.MailingGeolocation__Latitude__s = address.MailingGeolocation__Latitude__s;
                objMember.MailingGeolocation__Longitude__s = address.MailingGeolocation__Longitude__s;
            }
            List<String> fields = new List<String>{'IsHeadOfHousehold__c'};
                for (String addressField: addressFields) {
                    fields.add('SSP_Member__r.' + addressField);
                }
            if(applicationId != NULL){
                lstApps =  SSP_ApplicationSelector.queryApplicationData(new Map<String, String>{'objectName'=>'SSP_Application__c'}, 
                                                                        new Set<String>{'Id','IsPrimaryApplicantAddressModified__c','ProgramsApplied__c'}, 
                                                                        new Map<String, String>{'Id'=> applicationId});
                lstAppIndividuals = SSP_ApplicationIndividualSelector.queryApplicationIndividualData(new Map<String, String>{'objectName'=>'SSP_ApplicationIndividual__c','operator'=>'AND'}, 
                                                                                 new Set<String>{'Id','SSP_Member__c','SSP_Application__c','IsHeadOfHousehold__c'}, 
                                                                                 new Map<String, String>{'limit'=>'1','SSP_Application__c'=> applicationId,'IsHeadOfHousehold__c' =>'#true#'});
                if(lstApps != NULL && lstAppIndividuals != NULL && !lstAppIndividuals.isEmpty() && !lstApps.isEmpty() && lstApps[0].ProgramsApplied__c != NULL && lstApps[0].ProgramsApplied__c.contains('SN') && lstAppIndividuals[0].IsHeadOfHousehold__c && bIsAddressChanged){
                    lstApps[0].IsPrimaryApplicantAddressModified__c = true;
                    ESAPI.accessController().updateAsUser(lstApps[0], lstAppFields);
                }
            }
            if(objMember != NULL ){
                ESAPI.accessController().updateAsUser(objMember, addressFields);
                //update objMember;
            }
            if(address.SameAddressInfoAsHOHToggle__c == SSP_GlobalConstants.YES && applicationId != null) {
                recordsToUpdate.addAll(populateAddressOnAllOtherMembers(applicationId));
            }
            Map<Id, SSP_Member__c> recordsToUpdateMap = new Map<Id, SSP_Member__c>();
            for(SSP_Member__c member: recordsToUpdate) {
                recordsToUpdateMap.put(member.Id, member);
            }
            LOG_LogMessageUtility.logMessage(logRecords);
            // update recordsToUpdate;
            if(recordsToUpdateMap != NULL){
                ESAPI.accessController().updateAsUser(recordsToUpdateMap, SSP_Utility.getFieldsNamesList(recordsToUpdate));
            }
            response.bIsSuccess = true;
            response.put('fields', SSP_Utility.getFieldsNamesList(recordsToUpdate));
            response.put('recordsToUpdateMap', recordsToUpdateMap);
        }
        catch(Exception e) {
            List<LOG_LogMessage__c> lstLogMessages = LOG_LogMessageUtility.logMessage(e, CLASSNAME, 'updateAddress', e.getMessage() , true);
            response.addException(e, lstLogMessages[0].Id);
        }
        return response;
    }

    /***************************************************************************************************
    * @author       Sai Kiran
    * @date         05/02/2020
    * @methodname   populateAddressOnHOH
    * @description  This method is used to fetch for application and member data
    * @return       Status of update operation
    *****************************************************************************************************/
    @AuraEnabled
    public static SSP_Member__c populateAddressOnHOH(Id applicationId) {
        Map<String, String> detailMap = new Map<String, String>{'objectName' => 'SSP_ApplicationIndividual__c', 'operator' => 'AND'};
        List<String> fields = new List<String>{'IsHeadOfHousehold__c'};
        for (String addressField: addressFields) {
            fields.add('SSP_Member__r.' + addressField);
        }
        List<SSP_ApplicationIndividual__c> headOfHousehold = SSP_ApplicationIndividualSelector.queryApplicationIndividualData(detailMap, new Set<String>(fields),
            new Map<String, String>{'SSP_Application__c' => applicationId,  'IsHeadOfHousehold__c'=> '#true#'});
        return headOfHousehold.get(0).SSP_Member__r;
    }
    
    /***************************************************************************************************
    * @author       Ajay Saini
    * @date         DEC-2-2019
    * @methodname   populateAddressOnAllOtherMembers
    * @description  This method is used to fetch for application and member data
    * @return       Status of update operation
    *****************************************************************************************************/
    @AuraEnabled
    public static List<SSP_Member__c> populateAddressOnAllOtherMembers(Id applicationId) {
        Map<String, String> detailMap = new Map<String, String>{'objectName' => 'SSP_ApplicationIndividual__c', 'operator' => 'AND'};
        List<String> fields = new List<String>{'IsHeadOfHousehold__c'};
        for (String addressField: addressFields) {
            fields.add('SSP_Member__r.' + addressField);
        }
        List<SSP_ApplicationIndividual__c> headOfHousehold = SSP_ApplicationIndividualSelector.queryApplicationIndividualData(detailMap, new Set<String>(fields),
            new Map<String, String>{'SSP_Application__c' => applicationId,  'IsHeadOfHousehold__c'=> '#true#'});
        List<SSP_ApplicationIndividual__c> applicationIndividuals = SSP_ApplicationIndividualSelector.queryApplicationIndividualData(detailMap, new Set<String>(fields),
            new Map<String, String>{'SSP_Application__c' => applicationId,  'IsHeadOfHousehold__c'=> '#false#'});
        if(headOfHousehold.isEmpty() || applicationIndividuals.isEmpty()) {
            return new List<SSP_Member__c>();
        }
        return updateNonPrimaryMemberAddress(applicationIndividuals, headOfHousehold.get(0).SSP_Member__r);
    }

    /***************************************************************************************************
    * @author       Ajay Saini
    * @date         DEC-2-2019
    * @methodname   updateNonPrimaryMemberAddress
    * @description  Helper method is used to copyaddress from primary applicants to non-primary applicants.
    * @return       Status of record update.
    *****************************************************************************************************/
    private static List<SSP_Member__c> updateNonPrimaryMemberAddress(List<SSP_ApplicationIndividual__c> applicationIndividuals, SSP_Member__c headOfHousehold) {
        if(headOfHousehold == null) {
            return new List<SSP_Member__c>();
        }
        List<SSP_Member__c> membersToUpdate = new List<SSP_Member__c>();
        for(SSP_ApplicationIndividual__c individual : applicationIndividuals) {
            SSP_Member__c member = (SSP_Member__c)individual.getSObject(SSP_ApplicationIndividual__c.SSP_Member__c.getDescribe().getSObjectField());
            member.SameAddressOfHoh__c = true;
            member.IsFixedAddressToggle__c = headOfHousehold.IsFixedAddressToggle__c;
            member.HasDifferentMailingAddressToggle__c = headOfHousehold.HasDifferentMailingAddressToggle__c;
            member.PhysicalAddressLine1__c = headOfHousehold.PhysicalAddressLine1__c;
            member.PhysicalAddressLine2__c = headOfHousehold.PhysicalAddressLine2__c;
            member.PhysicalCity__c = headOfHousehold.PhysicalCity__c;
            member.PhysicalCountyCode__c = headOfHousehold.PhysicalCountyCode__c;
            member.PhysicalStateCode__c = headOfHousehold.PhysicalStateCode__c;
            member.PhysicalCountryCode__c = headOfHousehold.PhysicalCountryCode__c;
            member.PhysicalZipCode4__c = headOfHousehold.PhysicalZipCode4__c;
            member.PhysicalZipCode5__c = headOfHousehold.PhysicalZipCode5__c;

            member.MailingAddressLine1__c = headOfHousehold.MailingAddressLine1__c;
            member.MailingAddressLine2__c = headOfHousehold.MailingAddressLine2__c;
            member.MailingCity__c = headOfHousehold.MailingCity__c;
            member.MailingCountyCode__c = headOfHousehold.MailingCountyCode__c;
            member.MailingStateCode__c = headOfHousehold.MailingStateCode__c;
            member.MailingCountryCode__c = headOfHousehold.MailingCountryCode__c;
            member.MailingZipCode4__c = headOfHousehold.MailingZipCode4__c;
            member.MailingZipCode5__c = headOfHousehold.MailingZipCode5__c;

            member.PhysicalAddrValidated__c = headOfHousehold.PhysicalAddrValidated__c;
            member.PhysicalMailAddrDeliveryCode__c = headOfHousehold.PhysicalMailAddrDeliveryCode__c;
            member.PhysicalCertifiedNoStatIndicator__c = headOfHousehold.PhysicalCertifiedNoStatIndicator__c;
            member.PhysicalResidentialDeliveryIndicator__c = headOfHousehold.PhysicalResidentialDeliveryIndicator__c;
            member.PhysicalCotVacancyIndicator__c = headOfHousehold.PhysicalCotVacancyIndicator__c;
            member.PhysicalGeolocation__Latitude__s = headOfHousehold.PhysicalGeolocation__Latitude__s;
            member.PhysicalGeolocation__Longitude__s = headOfHousehold.PhysicalGeolocation__Longitude__s;

            member.MailingAddrValidated__c = headOfHousehold.MailingAddrValidated__c;
            member.MailingMailAddrDeliveryCode__c = headOfHousehold.MailingMailAddrDeliveryCode__c;
            member.MailingCertifiedNoStatIndicator__c = headOfHousehold.MailingCertifiedNoStatIndicator__c;
            member.MailingResidentialDeliveryIndicator__c = headOfHousehold.MailingResidentialDeliveryIndicator__c;
            member.MailingCotVacancyIndicator__c = headOfHousehold.MailingCotVacancyIndicator__c;
            member.MailingGeolocation__Latitude__s = headOfHousehold.MailingGeolocation__Latitude__s;
            member.MailingGeolocation__Longitude__s = headOfHousehold.MailingGeolocation__Longitude__s;
            
            membersToUpdate.add(member);
        }
        return membersToUpdate;
    }

    /***************************************************************************************************
    * @author       Ajay Saini
    * @date         DEC-3-2019
    * @methodname   getPrimaryApplicantData
    * @description  This method retreives the primary applicant data from applicationId
    * @return       Primary applicant record
    *****************************************************************************************************/
    @AuraEnabled
    public static SSP_LightningResponse getPrimaryApplicantData(Id applicationId, List<String> fields) {
        SSP_Utility.isAuthenticatedUser();
        SSP_ApplicantAddressController.updateAddressFlags(applicationId);
        
        SSP_LightningResponse response = new SSP_LightningResponse();
        if(fields ==  null) {
            fields = new List<String>();
        }
        for (String addressField: addressFields) {
            fields.add('SSP_Member__r.' + addressField);
        }
        try {
            response.bIsSuccess = false;
            List<SSP_ApplicationIndividual__c> applicationIndividuals = SSP_ApplicationIndividualSelector.queryApplicationPrimaryIndividualData(applicationId, new Set<String>(fields));
            if(applicationIndividuals != null && !applicationIndividuals.isEmpty()) {
                SSP_Member__c member = (SSP_Member__c)applicationIndividuals[0].getSObject(SSP_ApplicationIndividual__c.SSP_Member__c.getDescribe().getSObjectField());
                response.bIsSuccess = true;
                response.put('member', member);
            }
        }
        catch(Exception e) {
            List<LOG_LogMessage__c> lstLogMessages = LOG_LogMessageUtility.logMessage(e, CLASSNAME, 'getPrimaryApplicantData', e.getMessage() , true);
            response.addException(e, lstLogMessages[0].Id);
        }
        return response;
    }
    
    /********************************************************************************************
    * @author       Sanchita Tibrewala
    * @date         03/24/2019
    * @methodname   fetchMemberIdNonPrimary
    * @description  This method fetches Id of Non-Primary in the application for Review Required
    * @param        String
    * @return       SSP_LightningResponse
    ********************************************************************************************/
    @AuraEnabled
    public static SSP_LightningResponse fetchMemberIdNonPrimary(String applicationId){
        SSP_Utility.isAuthenticatedUser();
        List<String> memberIdList = new List<String>();
        SSP_LightningResponse toSend = new SSP_LightningResponse();
        try{
            List<SSP_ApplicationIndividual__c> sspApplicationIndividualList;
            if(String.isNotBlank(applicationId)){
                sspApplicationIndividualList = 
                    SSP_ApplicationIndividualSelector.queryApplicationIndividualData(new Map<String, String>{'objectName'=>'SSP_ApplicationIndividual__c','operator'=>'AND'}, 
                                                                                     new Set<String>{'Id', 'SSP_Member__c', 'IsHeadOfhousehold__c', 'SSP_Application__c'}, 
                                                                                     new Map<String, String>{'limit'=>'10','SSP_Application__c'=> String.escapeSingleQuotes(applicationId), 
                                                                                         'IsHeadOfHousehold__c'=> '#false#'});
            }
            if(!sspApplicationIndividualList.isEmpty()){
                for(SSP_ApplicationIndividual__c appInd : sspApplicationIndividualList){
                        memberIdList.add(appInd.SSP_Member__c);
        		}
            }
 			toSend.bIsSuccess = true;
            toSend.put('memberIdList', memberIdList);
        }
        catch(Exception ex){            
            List<LOG_LogMessage__c> lstLogMessages = LOG_LogMessageUtility.logMessage(ex, 'SSP_ApplicantAddressController', 'fetchMemberIdNonPrimary', ex.getMessage() , true);
            toSend.bIsSuccess = false;
            toSend.addException(ex, lstLogMessages[0].Id);
        }
        return toSend;
    }
    
    @AuraEnabled(cacheable=true)
    public static SSP_lightningResponse getExpenseDetails (String memberId){       
        SSP_Utility.isAuthenticatedUser();
        SSP_lightningResponse response = new SSP_LightningResponse();
        try{
            List<SSP_Asset__c> assetsList = new List<SSP_Asset__c>();
            /*assetsList = SSP_AssetSelector.queryAssetData(new Map<String, String>{'objectName'=>'SSP_Asset__c','operator'=>'AND', 'IN'=>'SSP_Member__c'}, 
                                                        new Set<String>{'Id', 'SSP_Member__c', 'ExpenseTypeCode__c', 'ExpenseSubType__c', 'IsExistingCode__c'}, 
                                                        new Map<String, String>{'SSP_Member__c'=>memberId, 'RecordType.DeveloperName'=>'Expense'});*/
            assetsList = [SELECT Id, SSP_Member__c, ExpenseTypeCode__c,IsExistingData__c, EndDate__c, ExpenseSubType__c FROM SSP_ASSET__c
                        WHERE SSP_Member__c = :memberId
                        AND RecordType.name = 'Expense' 
                        AND (ExpenseTypeCode__c = 'UE' OR ExpenseTypeCode__c = 'SE')
                        AND isDeleted__c = false];
            response.put('assetsList',assetsList);
        }
        catch(exception e){
            LOG_LogMessageUtility.logMessage(e, 'SSP_ApplicantAddressController', 'getExpenseDetails', e.getMessage(), true);
        }
        return response;
    }

    /**
    * @author: Karthik Gulla
    * @method: updateAddressFlags
    * @desc This method is used to get member address details and calculate flags
    * @param {String sApplicationId}
    * @return void
    * */
    public static void updateAddressFlags(Id sApplicationId){
        Set<Id> setApplicationIds = new Set<Id>();
        Set<Id> setMemberIds = new Set<Id>();
        Map<Id,Boolean> mapAppIndividualsHOH = new Map<Id,Boolean>();
        Set<String> setAccessFields = new Set<String>();
        Map<String, SSP_Member__c> mapMembers = new Map<String, SSP_Member__c>();
        SSP_Member__c sspHOHMember = null;
        try{
            setApplicationIds.add(sApplicationId);
            Map<String,String> mapConditions = new Map<String,String>();
            mapConditions.put('SSP_Application__c',String.join(new List<Id>(setApplicationIds), ','));
            List<SSP_ApplicationIndividual__c> lstApplicationIndividuals = SSP_ApplicationIndividualSelector.queryApplicationIndividualData(new Map<String, String>{'objectName'=>'SSP_ApplicationIndividual__c','IN'=>'Id'}, 
                                                                    new Set<String>{'Id','SSP_Member__c' ,'IsHeadOfHousehold__c'}, 
                                                                    mapConditions);
            for(SSP_ApplicationIndividual__c sspAppIndividual:lstApplicationIndividuals){
                setMemberIds.add(sspAppIndividual.SSP_Member__c);
                mapAppIndividualsHOH.put(sspAppIndividual.SSP_Member__c, sspAppIndividual.IsHeadOfHousehold__c);
            }
            
            mapConditions.clear();
            mapConditions.put('Id',String.join(new List<Id>(setMemberIds), ','));
            List<SSP_Member__c> lstApplicationMembers = SSP_MemberSelector.queryMemberData(new Map<String, String>{'objectName'=>'SSP_Member__c','IN'=>'Id'}, 
                                                                new Set<String>{'Id','MailingAddressLine1__c','PhysicalAddressLine1__c','MailingAddressLine2__c','PhysicalAddressLine2__c',
                                                                                'MailingCity__c','PhysicalCity__c','MailingStateCode__c','PhysicalStateCode__c','MailingZipCode4__c',
                                                                                'PhysicalZipCode4__c','MailingZipCode5__c','PhysicalZipCode5__c','MailingCountyCode__c','PhysicalCountyCode__c',
                                                                                'MailingCountryCode__c','PhysicalCountryCode__c','SameAddressInfoAsHOHToggle__c','HasDifferentMailingAddressToggle__c',
                                                                                'DCPhysicalAddressId__c','DCMailingAddressId__c'}, 
                                                                mapConditions);
            
            for(SSP_Member__c sspMember : lstApplicationMembers){
                if(mapAppIndividualsHOH.get(sspMember.Id) != null 
                && mapAppIndividualsHOH.get(sspMember.Id)
                && sspMember.SameAddressInfoAsHOHToggle__c == null){
                    sspHOHMember = sspMember;
                }
            }

            Integer iCount = 0;
            for(SSP_Member__c sspMember : lstApplicationMembers){
                if(sspHOHMember != null && mapAppIndividualsHOH.get(sspMember.Id) != null && !mapAppIndividualsHOH.get(sspMember.Id)){
                    if((sspHOHMember.MailingAddressLine1__c != null && sspMember.MailingAddressLine1__c != null && sspHOHMember.MailingAddressLine1__c.toLowerCase() != sspMember.MailingAddressLine1__c)
                    || (sspHOHMember.PhysicalAddressLine1__c != null && sspMember.PhysicalAddressLine1__c != null && sspHOHMember.PhysicalAddressLine1__c.toLowerCase() != sspMember.PhysicalAddressLine1__c.toLowerCase())
                    || ((sspHOHMember.MailingAddressLine2__c != sspMember.MailingAddressLine2__c)  || ((sspHOHMember.PhysicalAddressLine2__c != null && sspMember.MailingAddressLine2__c != null && sspHOHMember.MailingAddressLine2__c.toLowerCase() != sspMember.MailingAddressLine2__c.toLowerCase())))
                    || ((sspHOHMember.PhysicalAddressLine2__c != sspMember.PhysicalAddressLine2__c) || ((sspHOHMember.PhysicalAddressLine2__c != null && sspMember.PhysicalAddressLine2__c != null && sspHOHMember.PhysicalAddressLine2__c.toLowerCase() != sspMember.PhysicalAddressLine2__c.toLowerCase())))
                    || (sspHOHMember.MailingCity__c != null && sspMember.MailingCity__c != null && sspHOHMember.MailingCity__c.toLowerCase() != sspMember.MailingCity__c.toLowerCase())
                    || (sspHOHMember.PhysicalCity__c != null && sspMember.PhysicalCity__c != null && sspHOHMember.PhysicalCity__c.toLowerCase() != sspMember.PhysicalCity__c.toLowerCase())
                    || (sspHOHMember.MailingStateCode__c != null && sspMember.MailingStateCode__c != null && sspHOHMember.MailingStateCode__c != sspMember.MailingStateCode__c)
                    || (sspHOHMember.PhysicalStateCode__c != null && sspMember.PhysicalStateCode__c != null && sspHOHMember.PhysicalStateCode__c != sspMember.PhysicalStateCode__c)
                    || (sspHOHMember.MailingZipCode4__c != sspMember.MailingZipCode4__c)
                    || (sspHOHMember.PhysicalZipCode4__c != sspMember.PhysicalZipCode4__c)
                    || (sspHOHMember.MailingZipCode5__c != sspMember.MailingZipCode5__c)
                    || (sspHOHMember.PhysicalZipCode5__c != sspMember.PhysicalZipCode5__c)
                    || (sspHOHMember.MailingCountyCode__c != null && sspMember.MailingCountyCode__c != null && sspHOHMember.MailingCountyCode__c != sspMember.MailingCountyCode__c)
                    || (sspHOHMember.PhysicalCountyCode__c != null && sspMember.PhysicalCountyCode__c != null && sspHOHMember.PhysicalCountyCode__c != sspMember.PhysicalCountyCode__c)
                    || (sspHOHMember.MailingCountryCode__c != sspMember.MailingCountryCode__c)
                    || (sspHOHMember.PhysicalCountryCode__c != sspMember.PhysicalCountryCode__c)) {
                        SSP_Member__c sspCurrentMember = new SSP_Member__c();
                        sspCurrentMember.Id = sspHOHMember.Id;
                        sspCurrentMember.SameAddressInfoAsHOHToggle__c = SSP_GlobalConstants.NO;
                        mapMembers.put(sspCurrentMember.Id, sspCurrentMember);
                        break;
                    }
                    iCount++;
                }
            }
           
            if(sspHOHMember != null && iCount == (lstApplicationMembers.size() - 1) && sspHOHMember.SameAddressInfoAsHOHToggle__c == null && (sspHOHMember.DCPhysicalAddressId__c != null || sspHOHMember.DCMailingAddressId__c != null)) {
                SSP_Member__c sspCurrentMember = new SSP_Member__c();
                sspCurrentMember.Id = sspHOHMember.Id;
                sspCurrentMember.SameAddressInfoAsHOHToggle__c = SSP_GlobalConstants.YES;
                mapMembers.put(sspCurrentMember.Id, sspCurrentMember);
            }

            for(SSP_Member__c sspMember : lstApplicationMembers){
                SSP_Member__c sspCurrentMember = new SSP_Member__c();
                if(sspMember.HasDifferentMailingAddressToggle__c == null){
                    if((sspMember.MailingAddressLine1__c != null && sspMember.PhysicalAddressLine1__c != null && sspMember.MailingAddressLine1__c.toLowerCase() == sspMember.PhysicalAddressLine1__c.toLowerCase())
                    && ((sspMember.MailingAddressLine2__c == sspMember.PhysicalAddressLine2__c) || ((sspMember.MailingAddressLine2__c != null && sspMember.PhysicalAddressLine2__c != null && sspMember.MailingAddressLine2__c.toLowerCase() == sspMember.PhysicalAddressLine2__c.toLowerCase())))
                    && (sspMember.MailingCity__c != null && sspMember.PhysicalCity__c != null && sspMember.MailingCity__c.toLowerCase() == sspMember.PhysicalCity__c.toLowerCase())
                    && (sspMember.MailingStateCode__c != null && sspMember.PhysicalStateCode__c != null && sspMember.MailingStateCode__c == sspMember.PhysicalStateCode__c)
                    && (sspMember.MailingZipCode4__c == sspMember.PhysicalZipCode4__c)
                    && (sspMember.MailingZipCode5__c == sspMember.PhysicalZipCode5__c)
                    && (sspMember.MailingCountyCode__c != null && sspMember.PhysicalCountyCode__c != null && sspMember.MailingCountyCode__c == sspMember.PhysicalCountyCode__c)
                    && (sspMember.MailingCountryCode__c == sspMember.PhysicalCountryCode__c)) {
                        if(mapMembers.get(sspMember.Id) != null){
                            sspCurrentMember = mapMembers.get(sspMember.Id);
                        } else {
                            sspCurrentMember.Id = sspMember.Id;
                        }
                        sspCurrentMember.HasDifferentMailingAddressToggle__c = SSP_GlobalConstants.NO; 
                        mapMembers.put(sspCurrentMember.Id, sspCurrentMember);  
                    }
                }
            }

            List<SSP_Member__c> lstTobeUpdatedMembers = mapMembers.values();
            
            if(!lstTobeUpdatedMembers.isEmpty() && Schema.getGlobalDescribe().get(SSP_GlobalConstants.SSPMEMBEROBJECT).getDescribe().isUpdateable()){
                update lstTobeUpdatedMembers;
            }
        }catch(Exception e){
            LOG_LogMessageUtility.logMessage(e, 'SSP_ApplicantAddressController', 'updateAddressFlags', e.getMessage(), true);
        }
    }
}