force-app/main/default/objects/SSP_Member__c/SSP_Member__c.object-meta.xml
<CustomObject>
    <description>Stores details about an individual member of a case/application such as gatepost reponse, incarceration, disability, living arrangement, pregnancy, address details. Also repurposed to store information of different individuals in the form of individual alien, alien sponsor, care taker,  care coordinator etc.</description>
    <label>SSP Member</label>
    <nameField>
        
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        
        <label>SSP_Member Name</label>
        
        <type>Text</type>
        
    </nameField>
    <pluralLabel>SSP Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Member__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>This field is used to indicate the related contact for a member</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>SSP_Member</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/IndianTribeCode__c.field-meta.xml
<CustomField>
    <fullName>IndianTribeCode__c</fullName>
    <description>This field is used to store Indian Tribe code</description>
    <label>Tribe</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>IndianTribeCode</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/IndianTribeState__c.field-meta.xml
<CustomField>
    <fullName>IndianTribeState__c</fullName>
    <description>This field is used to store Indian tribe state code for a member</description>
    <label>IndianTribeState</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>SSPState</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/IsFederalRecognizedIndianTribeToggle__c.field-meta.xml
<CustomField>
    <fullName>IsFederalRecognizedIndianTribeToggle__c</fullName>
    <description>This field is used to indicate whether the member belongs to Federal recognized Indian tribe</description>
    <label>Is federal recognized Indian tribe?</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>YesNo</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/globalValueSets/YesNo.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>Y</fullName>
        
        
        <label>YES</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>N</fullName>
        
        
        <label>NO</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>U</fullName>
        
        
        <label>Unknown</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>NULL</fullName>
        
        
        <label>NULL</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>H</fullName>
        
        
        <label>Historical</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>I don&apos;t know</fullName>
        
        
        <label>I don&apos;t know</label>
        
    </customValue>
    
    <description>Used to store different types of toggle picklist values</description>
    
    <masterLabel>YesNo</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/classes/SSP_AmericanIndianInfoControllerTest.cls
/***************************************************************************************************************************
*   Type         :   Test Class
*   Name         :   SSP_AmericanIndianInfoControllerTest
*   Created By   :   Sanchita Tibrewala
*   Created Date :   01/13/2020
*   Description  :   Test class for SSP_AmericanIndianInformationController
*  
*   Modification Log
*   --------------------------------------------------------------------------------------
*   * Developer                   Date          Description
*   * ------------------------------------------------------------------------------------                 
*     Sanchita                 01/13/2020     Initial Version
*****************************************************************************************************************************/
@isTest
public class SSP_AmericanIndianInfoControllerTest {
    
    /********************************************************************************************
    * @author       Sanchita Tibrewala
    * @date         01/13/2019
    * @methodname   fetchAmericanIndianMemberInformationTest
    * @description  Test method for fetchAmericanIndianMemberInformation
    * @param        none
    * @return       none
    ********************************************************************************************/
	@isTest
    public static void fetchAmericanIndianMemberInformationTest(){
        User u1 = SSP_TestDataFactory.createPortalUser();
        
        System.runAs(u1){
            
            List<SSP_Member__c> memList = SSP_TestDataFactory.createSSPMembers(1, false);
            SSP_Member__c mem = memList.get(0);
            mem.Contact__c = u1.ContactId;
            mem.IndianTribeCode__c = 'CROO';
            mem.IndianTribeState__c = 'KY';
            mem.IsFederalRecognizedIndianTribeToggle__c = 'Y';
            insert mem;
            Id memId = mem.Id;
            
            SSP_LightningResponse lr = SSP_AmericanIndianInformationController.fetchAmericanIndianMemberInformation(memId);
            SSP_Member__c retrievedMem = (SSP_Member__c)lr.mapResponse.get('record'); 
            
            System.assertEquals(retrievedMem.IsFederalRecognizedIndianTribeToggle__c, mem.IsFederalRecognizedIndianTribeToggle__c);
        }
    }
    
    /********************************************************************************************
    * @author       Sanchita Tibrewala
    * @date         01/13/2019
    * @methodname   saveAmericanIndianMemberInformationTest
    * @description  Test method for saveAmericanIndianMemberInformation
    * @param        none
    * @return       none
    ********************************************************************************************/
    @isTest
    public static void saveAmericanIndianMemberInformationTest(){
        User u1 = SSP_TestDataFactory.createPortalUser();
        
        System.runAs(u1){
        
            List<SSP_Member__c> memList = SSP_TestDataFactory.createSSPMembers(1, false);
            SSP_Member__c mem = memList.get(0);
            mem.Contact__c = u1.ContactId;
            insert mem;
            mem.IsFederalRecognizedIndianTribeToggle__c = 'N';
            mem.IndianTribeCode__c = 'CSMO';
            Id memId = mem.Id;
            
            String memString = JSON.serialize(mem);
            SSP_AmericanIndianInformationController.saveAmericanIndianMemberInformation(memId, memString);
            SSP_Member__c retrievedMem;
            if(memId != null){
                retrievedMem = [Select Id, IsFederalRecognizedIndianTribeToggle__c, IndianTribeCode__c From SSP_Member__c Where Id =:memId];
            }
            System.assertEquals(retrievedMem.IsFederalRecognizedIndianTribeToggle__c , mem.IsFederalRecognizedIndianTribeToggle__c);
        }
    }
}