force-app/main/default/objects/GoogleMapsApiConfig__c/GoogleMapsApiConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Google maps api config</description>
    <label>GoogleMapsApiConfig</label>
</CustomObject>

force-app/main/default/objects/GoogleMapsApiConfig__c/fields/API_Key_DCBS__c.field-meta.xml
<CustomField>
    <fullName>API_Key_DCBS__c</fullName>
    <description>API key used for DCBS office</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>API key used for DCBS office</inlineHelpText>
    <label>API Key DCBS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GoogleMapsApiConfig__c/fields/AutoCompleteUrl__c.field-meta.xml
<CustomField>
    <fullName>AutoCompleteUrl__c</fullName>
    <description>Api endpoint for auto complete url</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Api endpoint for auto complete url</inlineHelpText>
    <label>Auto Complete Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/GoogleMapsApiConfig__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Location cordinates</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Comma separated, location coordinates</inlineHelpText>
    <label>Location</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GoogleMapsApiConfig__c/fields/PlaceDetailUrl__c.field-meta.xml
<CustomField>
    <fullName>PlaceDetailUrl__c</fullName>
    <description>Api endpoint for place detail</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Api endpoint for place detail</inlineHelpText>
    <label>Place Detail Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/Geolocation__c.field-meta.xml
<CustomField>
    <fullName>Geolocation__c</fullName>
    <label>Geolocation</label>
    <scale>15</scale>
    <type>Location</type>
</CustomField>

force-app/main/default/objects/Location__c/recordTypes/Location.recordType-meta.xml
<RecordType>
    <fullName>Location</fullName>
    <active>true</active>
    <description>This record type is used for  location object</description>
    <label>Location</label>
</RecordType>

force-app/main/default/objects/LOG_LogMessage__c/LOG_LogMessage__c.object-meta.xml
<CustomObject>
    <description>Container for custom exception/log messages</description>
    <label>Log Message</label>
    <nameField>
        <displayFormat>LOG-{000000}</displayFormat>
        <label>Log Message #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Member__c/SSP_Member__c.object-meta.xml
<CustomObject>
    <description>Stores details about an individual member of a case/application such as gatepost reponse, incarceration, disability, living arrangement, pregnancy, address details. Also repurposed to store information of different individuals in the form of individual alien, alien sponsor, care taker,  care coordinator etc.</description>
    <label>SSP Member</label>
    <nameField>
        
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        
        <label>SSP_Member Name</label>
        
        <type>Text</type>
        
    </nameField>
    <pluralLabel>SSP Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Member__c/fields/PhysicalAddressLine1__c.field-meta.xml
<CustomField>
    <fullName>PhysicalAddressLine1__c</fullName>
    <description>This field is used to store Address Line 1 value of Physical Address</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/PhysicalAddressLine2__c.field-meta.xml
<CustomField>
    <fullName>PhysicalAddressLine2__c</fullName>
    <description>This field is used to store Address Line 2 value of Physical Address</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Address Line 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/PhysicalCity__c.field-meta.xml
<CustomField>
    <fullName>PhysicalCity__c</fullName>
    <description>This field is used to store city for a Physical address of a member</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/PhysicalCountyCode__c.field-meta.xml
<CustomField>
    <fullName>PhysicalCountyCode__c</fullName>
    <label>County</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>SSPCounty</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/PhysicalStateCode__c.field-meta.xml
<CustomField>
    <fullName>PhysicalStateCode__c</fullName>
    <description>This field is used to store physical state code for physical address on a member</description>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>SSPState</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/PhysicalZipCode4__c.field-meta.xml
<CustomField>
    <fullName>PhysicalZipCode4__c</fullName>
    <description>This field is used to store 4 digit Physical Zip code</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Zip Code (Four Digit)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/PhysicalZipCode5__c.field-meta.xml
<CustomField>
    <fullName>PhysicalZipCode5__c</fullName>
    <description>This field is used to store 5 digit Physical Zip code</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Zip Code (Five Digit)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Office__c/SSP_Office__c.object-meta.xml
<CustomObject>
    <description>MOR set for offices for day 0 data for SSP</description>
    <label>SSP Office</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>SSP Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SSP Offices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Office__c/fields/Calculated_Distance__c.field-meta.xml
<CustomField>
    <fullName>Calculated_Distance__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Calculated Distance</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Office__c/fields/Geolocation__c.field-meta.xml
<CustomField>
    <fullName>Geolocation__c</fullName>
    <description>geolocation of office for physical address</description>
    <label>Geolocation</label>
    <scale>6</scale>
    <type>Location</type>
</CustomField>

force-app/main/default/objects/SSP_Office__c/fields/OfficeHoursFrom__c.field-meta.xml
<CustomField>
    <fullName>OfficeHoursFrom__c</fullName>
    <description>Office start time.</description>
    <label>OfficeHoursFrom</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/SSP_Office__c/fields/OfficeHoursFromText__c.field-meta.xml
<CustomField>
    <fullName>OfficeHoursFromText__c</fullName>
    <description>text value for OfficeHoursFrom</description>
    <encryptionScheme>None</encryptionScheme>
    <label>OfficeHoursFromText</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Office__c/fields/OfficeHoursTo__c.field-meta.xml
<CustomField>
    <fullName>OfficeHoursTo__c</fullName>
    <description>Office end time.</description>
    <label>OfficeHoursTo</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/SSP_Office__c/fields/OfficeHoursToText__c.field-meta.xml
<CustomField>
    <fullName>OfficeHoursToText__c</fullName>
    <description>text field for OfficeHoursTo</description>
    <encryptionScheme>None</encryptionScheme>
    <label>OfficeHoursToText</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Office__c/fields/OfficePhone__c.field-meta.xml
<CustomField>
    <fullName>OfficePhone__c</fullName>
    <description>Office phone number.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Office Phone</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Office__c/fields/PhysicalAddressLine1__c.field-meta.xml
<CustomField>
    <fullName>PhysicalAddressLine1__c</fullName>
    <description>Office Address Line1.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Physical AddressLine1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Office__c/fields/PhysicalAddressLine2__c.field-meta.xml
<CustomField>
    <fullName>PhysicalAddressLine2__c</fullName>
    <description>Office Address Line2.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Physical AddressLine2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Office__c/fields/PhysicalCity__c.field-meta.xml
<CustomField>
    <fullName>PhysicalCity__c</fullName>
    <description>Office Address City.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Physical City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Office__c/fields/PhysicalCountyCode__c.field-meta.xml
<CustomField>
    <fullName>PhysicalCountyCode__c</fullName>
    <description>Office Address CountyCode. Use RT &apos;COUNTY&apos; for getting equivalent text value.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Physical County Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Office__c/fields/PhysicalStateCode__c.field-meta.xml
<CustomField>
    <fullName>PhysicalStateCode__c</fullName>
    <description>Office Address StateCode. Use RT &apos;STATE&apos; for getting equivalent text value.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Physical StateCode</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Office__c/fields/PhysicalZipCode4__c.field-meta.xml
<CustomField>
    <fullName>PhysicalZipCode4__c</fullName>
    <description>Office Address ZIpCode4.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Physical ZipCode4</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Office__c/fields/PhysicalZipCode5__c.field-meta.xml
<CustomField>
    <fullName>PhysicalZipCode5__c</fullName>
    <description>Office Address Zipcode5.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Physical ZipCode5</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SSP_FindDCBSOfficeController.cls
/*
* classname         :  SSP_FindDCBSOfficeController
* @description      :  Controller Class for Find DCBS office screen 
* WIHTOUT SHARING   :  The class is running in without sharing mode, since it will fetch office records which are loaded 
                        as a part of day 0 data setup. Also, guest can access this without login to SSP.
* @author           :  Payal Gupta
*/
public without sharing class SSP_FindDCBSOfficeController{
    private static GoogleMapsApiConfig__c config = GoogleMapsApiConfig__c.getInstance();
    private static final String GOOGLE_API_KEY;
    private static final String AUTOCOMPLETE_BASE_URL;
    private static final String PLACE_DETAIL_URL;
    private static final String LOCATION;
    private static final String RADIUS;
    private static final String UTF8 = 'UTF-8';

    public static Map<String, String> countyMap;
    static {
        if(config != null) {
            GOOGLE_API_KEY = config.API_Key_DCBS__c;
            PLACE_DETAIL_URL = config.PlaceDetailUrl__c;
            AUTOCOMPLETE_BASE_URL = config.AutoCompleteUrl__c;
            LOCATION = config.Location__c;
            RADIUS = String.valueOf(config.Radius__c);
        }
        populateCountyMap();
    }

    public class address_componentsListWrapper{
        public List<address_componentsWrapper> address_components;
    }

    public class address_componentsWrapper{
        public String long_name;
        public String short_name;
        public List<String> types;
    }    
    @AuraEnabled
    public static List<SSP_Office__c> getOfficeLocations(decimal lat, decimal lng, String addressCmp){      
        List<SSP_Office__c> sspOfficelist= new List<SSP_Office__c>(); 
        List<address_componentsWrapper> addres_componentList;     
        String postalCode;
        String country;
        String state;
        String county;
        String city;
        Boolean fullAddressPresent= false; //if full address is present then return all offices sorted by distance
        
        if(addressCmp != null){
            addres_componentList = (List<address_componentsWrapper>) JSON.deserialize(addressCmp, List<address_componentsWrapper>.class);
        }
        
        
        if(addres_componentList != null && addres_componentList.size()>0){
            for(address_componentsWrapper component: addres_componentList){
                if(component.types.contains('postal_code')){
                    postalCode = component.long_name;
                    
                }
                if(component.types.contains('country')){
                    country = component.long_name;
                    
                }
                if(component.types.contains('administrative_area_level_1')){
                   state = component.long_name;
                    
                }
                if(component.types.contains('administrative_area_level_2')){
                    String temp;
                    
                    try{
                        temp = component.long_name.trim();
                        if(temp.contains('County')){
                            temp = component.long_name.split('County')[0].trim();
                        }
                        if(countyMap != null && countyMap.containsKey(temp)){
                            county = countyMap.get(temp);
                            if(county.startsWith('0')){
                                county = county.substringAfter('0');
                            }
                            if(county.startsWith('0')){
                                county = county.substringAfter('0');
                            }
                        }
                        

                    }
                    catch(Exception ex){
                        List<LOG_LogMessage__c> lstLogMessages = LOG_LogMessageUtility.logMessage(ex, 'SSP_FindDCBSOfficeController', 'getOfficeLocations', ex.getMessage() , true);
                    }
                    
                }
                if(component.types.contains('locality')){
                    city = component.long_name;
                    
                }
                //different types present on address component that constitutes full address
                if(component.types.contains('route') || component.types.contains('street_number') 
                    || component.types.contains('subpremise')|| component.types.contains('premise')
                    || component.types.contains('sublocality')){
                    fullAddressPresent = true;
                    
                }
            }
            
        }
        if(!fullAddressPresent){
            String soql = 'SELECT Id, Name, Calculated_Distance__c, OfficeHoursTo__c,OfficeHoursFrom__c,OfficePhone__c,Geolocation__latitude__s,Geolocation__longitude__s, PhysicalAddressLine1__c, PhysicalAddressLine2__c,PhysicalCity__c,PhysicalCountyCode__c, PhysicalStateCode__c, PhysicalZipCode4__c,PhysicalZipCode5__c, DISTANCE(Geolocation__c, GEOLOCATION(:lat,:lng), \'mi\') dist, OfficeHoursFromText__c, OfficeHoursToText__c FROM SSP_Office__c  ';
            String filter = ' WHERE ';
            if(postalCode != null){
                filter = filter + ' PhysicalZipCode5__c like \'%'+String.escapeSingleQuotes(postalCode)+ '%\' ';
            }
            if(city != null){
                if(filter.length()>7){
                    filter = filter + ' AND ';
                }
                filter = filter + ' PhysicalCity__c like \'%'+String.escapeSingleQuotes(city) + '%\' ';
            }
            if(county != null){
                if(filter.length()>7){
                    filter = filter + ' AND ';
                }
                filter = filter + ' PhysicalCountyCode__c =:county '; //' PhysicalCountyCode__c like \'%'+county + '%\' '
            }
            if(filter.length()>7){
                soql = soql + filter;
            }

            soql = soql + 'ORDER BY DISTANCE(Geolocation__c, GEOLOCATION('+lat+','+lng+'), \'mi\')';
            
            sspOfficelist=Database.query(soql);
            
            
            
        }
        else{
            
            sspOfficelist = [SELECT Id, Name, Calculated_Distance__c, OfficeHoursTo__c,OfficeHoursFrom__c,OfficePhone__c,Geolocation__latitude__s,Geolocation__longitude__s, 
                            PhysicalAddressLine1__c, PhysicalAddressLine2__c,PhysicalCity__c,PhysicalCountyCode__c, PhysicalStateCode__c, PhysicalZipCode4__c,PhysicalZipCode5__c,
                            DISTANCE(Geolocation__c, GEOLOCATION(:lat,:lng), 'mi') dist, OfficeHoursFromText__c, OfficeHoursToText__c
                            FROM SSP_Office__c ORDER BY DISTANCE(Geolocation__c, GEOLOCATION(:lat,:lng), 'mi')];
        }
        
        for ( SSP_Office__c office : sspOfficelist) { 
                                                         
                                       if(office.get('dist') != null){
                                           office.Calculated_Distance__c = String.valueOf(((Decimal)office.get('dist')).SetScale(2)); 
                                           office.OfficeHoursFromText__c = String.valueOf(office.OfficeHoursFrom__c);
                                           office.OfficeHoursToText__c = String.valueOf(office.OfficeHoursTo__c);
                                                       
                                           //sspOfficelist.add(office); 
                                       }                                  
                                   }
        return sspOfficelist;
        
    }

    public class placeResultWrapper{
        public List<resultsWrapper> results;

    }   
    public class resultsWrapper{
        public string formatted_address;
        public List<address_componentsWrapper> address_components;
    }
    
    @AuraEnabled
    public static SSP_LightningResponse getCurrentAddress(decimal lat, decimal lng){   
        SSP_LightningResponse returnResponse = new SSP_LightningResponse(); 
        String result = '';
            try{
                String autoCompleteUrl = 'https://maps.googleapis.com/maps/api/geocode/json'; 
                if(lat != null && lng != null) {
                    autoCompleteUrl += '?latlng=' + EncodingUtil.urlEncode(String.escapeSingleQuotes(String.valueOf(lat)), UTF8)+','
                                                + EncodingUtil.urlEncode(String.escapeSingleQuotes(String.valueOf(lng)), UTF8);
                }
                
                if(GOOGLE_API_KEY != null) {
                    autoCompleteUrl += '&key=' + EncodingUtil.urlEncode(String.escapeSingleQuotes(GOOGLE_API_KEY), UTF8);
                }
                String response = SSP_SharingBypassFetcher.sendHTTPRequest(autoCompleteUrl);
                
                if(response != null){
                    placeResultWrapper responseWrapperObj = (placeResultWrapper)JSON.deserialize(String.valueof(response),placeResultWrapper.class);
                    
                    if(responseWrapperObj != null && responseWrapperObj.results != null 
                        && responseWrapperObj.results.size()>0 && responseWrapperObj.results[0].formatted_address != null){
                        
                        result = responseWrapperObj.results[0].formatted_address;
                        returnResponse.put('formattedAddress', result);
                        //returnResponse.put('dummy', 'dummry');
                        returnResponse.put('addressComponent', JSON.serialize(responseWrapperObj.results[0].address_components));
                        
                    }
                    
                }
            
            
            } catch(Exception e) {
                LOG_LogMessageUtility.logMessage(e,
                                                'SSP_FindDCBSOfficeController', 'getCurrentAddress', e.getMessage() , true);
                
            }
        return returnResponse;
    }

    public static void populateCountyMap(){
        countyMap = new Map<String, String>();
        Schema.DescribeFieldResult fieldResult = SSP_Member__c.PhysicalCountyCode__c.getDescribe();
       List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
       for( Schema.PicklistEntry entry : ple)
       {
               countyMap.put(entry.getLabel(), entry.getValue());
               
       }     
       
    }
    
}