force-app/main/default/objects/NavFlowDetail__mdt/NavFlowDetail__mdt.object-meta.xml
<CustomObject>
    <description>Contains navigation flow details.</description>
    <label>Navigation Flow Detail</label>
    <pluralLabel>Navigation Flow Details</pluralLabel>
</CustomObject>

force-app/main/default/objects/NavFlowPageConfig__mdt/NavFlowPageConfig__mdt.object-meta.xml
<CustomObject>
    <description>Contains navigation flow page configuration.</description>
    <label>Navigation Flow Page Configuration</label>
    <pluralLabel>Navigation Flow Page Configuration</pluralLabel>
</CustomObject>

force-app/main/default/objects/NavFlowPageConfig__mdt/fields/NavigationFlowDetail__c.field-meta.xml
<CustomField>
    <fullName>NavigationFlowDetail__c</fullName>
    <label>Navigation Flow Detail</label>
    <referenceTo>NavFlowDetail__mdt</referenceTo>
    <relationshipLabel>Navigation Flow Page Configuration</relationshipLabel>
    <relationshipName>Navigation_Flow_Page_Configuration</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/NavFlowPageConfig__mdt/fields/PageInfo__c.field-meta.xml
<CustomField>
    <fullName>PageInfo__c</fullName>
    <description>Page info</description>
    <label>Page Info</label>
    <referenceTo>PageInfo__mdt</referenceTo>
    <relationshipLabel>Navigation Flow Page Configuration</relationshipLabel>
    <relationshipName>Navigation_Flow_Page_Configuration</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/NavFlowStatus__c/NavFlowStatus__c.object-meta.xml
<CustomObject>
    <description>Contains navigation flow status for specific contact, account etc., Primarily used for contact.</description>
    <label>Navigation Flow Status</label>
    <nameField>
        
        <displayFormat>NavFlow-{0000000}</displayFormat>
        
        <label>Navigation Flow Status Name</label>
        
        <type>AutoNumber</type>
        
    </nameField>
    <pluralLabel>Navigation Flow Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NavFlowStatus__c/fields/FlowDupStatus__c.field-meta.xml
<CustomField>
    <fullName>FlowDupStatus__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>FlowDupStatus</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PageInfo__mdt/PageInfo__mdt.object-meta.xml
<CustomObject>
    <description>Contains page information like URL, component name etc.,</description>
    <label>Page Info</label>
    <pluralLabel>Page Info</pluralLabel>
</CustomObject>

force-app/main/default/classes/NavFlowStatJSON.cls
public class NavFlowStatJSON {
	
    public static String createScreenStatusJSON(ContextData ctxData, NavFlowStatus__c navFlowStatus, 
                                                NavFlowDetail__mdt navFlowDetail, 
                                                Map<Integer,Boolean> ReviewRequiredMap, String oldStatus){
        String screenStatus = '';
        Map<Integer,String> intPageMap = new Map<Integer,String>();
        for(Integer i=0; i<navFlowDetail.Navigation_Flow_Page_Configuration__r.size(); i++){
            intPageMap.put(i,navFlowDetail.Navigation_Flow_Page_Configuration__r[i].PageInfo__r.PageName__c);
        }
        
        Map<String,Map<String,Object>> screenStatusMap = new Map<String,Map<String,Object>>();        
        String flowStatus = navFlowStatus.FlowDupStatus__c;
                
        Integer[] flowStatusChars = flowStatus.getChars();
        for(Integer i=0; i<flowStatusChars.size(); i++){
           Map<String,Object> parameterMap = new Map<String,Object>();
           
           String flowStat = String.fromCharArray( new List<Integer> {flowStatus.charAt(i)});
           String oldStat = String.fromCharArray( new List<Integer> {oldStatus.charAt(i)});
           parameterMap.put('Status',flowStat);
           parameterMap.put('isReviewRequired',(ReviewRequiredMap != null ? !ReviewRequiredMap.isEmpty() ? ReviewRequiredMap.containsKey(i) ? ReviewRequiredMap.get(i) : false : false : false)); 
           parameterMap.put('oldStatus',oldStat);
           parameterMap.put('reviewReqScreens',null);
           screenStatusMap.put(intPageMap.get(i),parameterMap);
        }
        
        screenStatus = JSON.serialize(screenStatusMap);
        return screenStatus;
    }
}