force-app/main/default/objects/SSP_Benefits__c/SSP_Benefits__c.object-meta.xml
<CustomObject>
    <description>Stores benefit details such as household, individual, out of state, SSI benefits etc.</description>
    <label>SSP Benefits</label>
    <nameField>
        
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        
        <label>SSP_Benefits Name</label>
        
        <type>Text</type>
        
    </nameField>
    <pluralLabel>SSP Benefits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Benefits__c/fields/BeginDate__c.field-meta.xml
<CustomField>
    <fullName>BeginDate__c</fullName>
    <description>This field is used to begin date for which benefits are available for a member</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Begin Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SSP_Benefits__c/fields/BenefitInfoCounty__c.field-meta.xml
<CustomField>
    <fullName>BenefitInfoCounty__c</fullName>
    <description>This field is used to store county for which benefits are available for a member</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Benefit County</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Benefits__c/fields/BenefitPrograms__c.field-meta.xml
<CustomField>
    <fullName>BenefitPrograms__c</fullName>
    <description>This field is used to store applicable programs for which benefits are available for a member</description>
    <label>Benefit Programs</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>OOSPrograms</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Benefits__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <description>This field is used to store End date for which benefits are removed for a member</description>
    <encryptionScheme>None</encryptionScheme>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SSP_Benefits__c/fields/SSP_Member__c.field-meta.xml
<CustomField>
    <fullName>SSP_Member__c</fullName>
    <description>This field is used to indicate the member for a particular Benefit record</description>
    <label>SSP_Member</label>
    <referenceTo>SSP_Member__c</referenceTo>
    <relationshipName>SSP_Benefits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_Benefits__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>This field is used to store another state for which benefits are available for a member</description>
    <label>Another State for Benefits</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>SSPState</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Member__c/SSP_Member__c.object-meta.xml
<CustomObject>
    <description>Stores details about an individual member of a case/application such as gatepost reponse, incarceration, disability, living arrangement, pregnancy, address details. Also repurposed to store information of different individuals in the form of individual alien, alien sponsor, care taker,  care coordinator etc.</description>
    <label>SSP Member</label>
    <nameField>
        
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        
        <label>SSP_Member Name</label>
        
        <type>Text</type>
        
    </nameField>
    <pluralLabel>SSP Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/OOSPrograms.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>MA</fullName>
        
        
        <label>Medicaid</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SN</fullName>
        
        
        <label>SNAP</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>TN</fullName>
        
        
        <label>TANF</label>
        
    </customValue>
    
    <description>Used to maintain out of state programs</description>
    
    <masterLabel>OOS Programs</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/classes/SSP_AnotherStateBenefitsService.cls
/*
* classname 		: SSP_AnotherStateBenefitsService
* @description 		: This is the service class for Benefits from another state summary and details screen.
* @author 			: Sai Kiran
* @date 			: 11/27/2019
* MODIFICATION LOG	:
* DEVELOPER 			DATE 			DESCRIPTION
* ---------------------------------------------------------------------------------------------
* Nupoor Nimbalkar 		11/27/2019		Initial Version
*/
public class SSP_AnotherStateBenefitsService {
        /*
* method 		: fetchOutOfStateBenefits
* @description  : This method is used to fetch All the details of benefits of Member in the time frame.
* @author 		: Sai Kiran
* @param 		: sMemberId - Member ID in string format
* @return 		: List<SSP_Benefits__c>
* */
    @AuraEnabled
    public static List<SSP_Benefits__c> fetchBenefitRecords(String sBenefitIds){
        Map<String,String> mapConditions = new Map<String,String>();
        List<SSP_Benefits__c> lstBenefits = new List<SSP_Benefits__c>();
        List<String> lstBenefitsFields = new List<String>{'State__c','State__c','BenefitInfoCounty__c','BenefitPrograms__c','BeginDate__c','EndDate__c','SSP_Member__c'};
            List<String> IDs = sBenefitIds.split(',');
        Set<ID> benefitIDs = new Set<ID>();
        try{
            for(String str : IDs){
                benefitIDs.add(String.escapeSingleQuotes(str).replace('"','').trim());
            }
            SSP_Utility.isAuthenticatedUser();
            Boolean bViewBenefitsFields = ESAPI.accessController().isAuthorizedToView(SSP_Benefits__c.getSObjectType(), lstBenefitsFields);
            if(bViewBenefitsFields){
                mapConditions.clear();
                mapConditions.put('ID',String.join(new List<Id>(benefitIDs), ','));
                lstBenefits = SSP_BenefitsSelector.queryBenefitsData(new Map<String, String>{'hasToLabel'=>'true','objectName'=>'SSP_Benefits__c','IN'=>'ID','operator'=>'AND'}, 
                                                        new Set<String>{'ID','BenefitPrograms__c','BeginDate__c','EndDate__c','SSP_Member__c'}, 
                                                        mapConditions);
            }
        }catch(Exception e){
            LOG_LogMessageUtility.logMessage(e, 'SSP_AnotherStateBenefitsService', 'validateBenefits', e.getMessage(), true);
        }
        return lstBenefits;
    }
    /*
* method 		: fetchOutOfStateBenefits
* @description  : This method is used to fetch All the details of benefits from state. 
* @author 		: Sai Kiran
* @param 		: sMemberId - Member ID in string format
* @return 		: List<SSP_Benefits__c>
* */
    @AuraEnabled
    public static List<SSP_Benefits__c> fetchOutOfStateBenefits(String sMemberId){
        Map<String,String> mapConditions = new Map<String,String>();
        List<SSP_Benefits__c> lstBenefits = new List<SSP_Benefits__c>();
        List<String> lstBenefitsFields = new List<String>{'State__c','State__c','BenefitInfoCounty__c','BenefitPrograms__c','BeginDate__c','EndDate__c','SSP_Member__c'};
        Map<String, String> mapQueryParameters = new Map<String, String>();
        Set<String> benefitProgramTypes = new Set<String>();
        benefitProgramTypes.add(SSP_GlobalConstants.SNAP);
        benefitProgramTypes.add(SSP_GlobalConstants.TANF);
        benefitProgramTypes.add(SSP_GlobalConstants.MEDICAID);
        String sQuery;
        String switchCaseKey;
        
        try{
            SSP_Utility.isAuthenticatedUser();
                Boolean bViewBenefitsFields = ESAPI.accessController().isAuthorizedToView(SSP_Benefits__c.getSObjectType(), lstBenefitsFields);
            if(bViewBenefitsFields){
                //Ashwin Changes
                Date dateBeforeMonth = SSP_Utility.today().addMonths(-SSP_GlobalConstants.SIX_MONTH);
                Date dateAfterMonth = SSP_Utility.today().addMonths(SSP_GlobalConstants.SIX_MONTH);
                //Sai Changes
                //Integer currentMonth = SSP_Utility.today().month();
                //Integer nextMonth = SSP_Utility.today().addMonths(SSP_GlobalConstants.ONE_MONTH).month();
                mapQueryParameters.put(SSP_GlobalConstants.sWhereClauseKey, SSP_GlobalConstants.sBenefitFieldsWhereClause);
                sQuery = SSP_Utility.getsQueryonFields('SSP_Benefits__c', SSP_GlobalConstants.sBenefitFields, mapQueryParameters);
                if(sQuery != NULL && !String.isBlank(sQuery)){
                    lstBenefits = Database.query(sQuery);
                }
            }
        }catch(Exception e){
            LOG_LogMessageUtility.logMessage(e, 'SSP_AnotherStateBenefitsService', 'fetchOutOfStateBenefits', e.getMessage(), true);
        }
        return lstBenefits;
    }
    /*
* method 		: generateUniqueID
* @description  : This method is used to generate 10 digit Unique ID to Store in a Benefit Record.
* @author 		: Sai Kiran Velpula
* @return 		: String
* */
    public static String generateUniqueID(){
        String uniqueID;
        Integer len = 10;
        Blob blobKey = crypto.generateAesKey(128);
        String key = EncodingUtil.convertToHex(blobKey);
        uniqueID = key.substring(0,len);
        return uniqueID;
    }
}