force-app/main/default/objects/SSP_Benefits__c/SSP_Benefits__c.object-meta.xml
<CustomObject>
    <description>Stores benefit details such as household, individual, out of state, SSI benefits etc.</description>
    <label>SSP Benefits</label>
    <nameField>
        
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        
        <label>SSP_Benefits Name</label>
        
        <type>Text</type>
        
    </nameField>
    <pluralLabel>SSP Benefits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Benefits__c/fields/BeginDate__c.field-meta.xml
<CustomField>
    <fullName>BeginDate__c</fullName>
    <description>This field is used to begin date for which benefits are available for a member</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Begin Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SSP_Benefits__c/fields/DCId__c.field-meta.xml
<CustomField>
    <fullName>DCId__c</fullName>
    <description>Used to store the generic DC ids from .NET Table</description>
    <externalId>true</externalId>
    <label>DC Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SSP_Benefits__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <description>This field is used to store End date for which benefits are removed for a member</description>
    <encryptionScheme>None</encryptionScheme>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SSP_Benefits__c/fields/HasMedicareCoverageButNoInfo__c.field-meta.xml
<CustomField>
    <fullName>HasMedicareCoverageButNoInfo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to indicate the flag when there is a medical coverage but no information</description>
    <label>Has Medicare Coverage But No Info</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SSP_Benefits__c/fields/MedicareNumber__c.field-meta.xml
<CustomField>
    <fullName>MedicareNumber__c</fullName>
    <description>This field is used to store Medicare number</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Medicare Number</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Benefits__c/fields/MedicareTypeCode__c.field-meta.xml
<CustomField>
    <fullName>MedicareTypeCode__c</fullName>
    <description>This field is used to store Medicare type code</description>
    <label>Medicare Type Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MedicareTypeCode</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Benefits__c/fields/SSP_Member__c.field-meta.xml
<CustomField>
    <fullName>SSP_Member__c</fullName>
    <description>This field is used to indicate the member for a particular Benefit record</description>
    <label>SSP_Member</label>
    <referenceTo>SSP_Member__c</referenceTo>
    <relationshipName>SSP_Benefits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_Benefits__c/recordTypes/MedicareBenefit.recordType-meta.xml
<RecordType>
    <fullName>MedicareBenefit</fullName>
    <active>true</active>
    <description>Record type for Medicare Coverage Summary and details</description>
    <label>MedicareBenefit</label>
</RecordType>

force-app/main/default/objects/SSP_Member__c/SSP_Member__c.object-meta.xml
<CustomObject>
    <description>Stores details about an individual member of a case/application such as gatepost reponse, incarceration, disability, living arrangement, pregnancy, address details. Also repurposed to store information of different individuals in the form of individual alien, alien sponsor, care taker,  care coordinator etc.</description>
    <label>SSP Member</label>
    <nameField>
        
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        
        <label>SSP_Member Name</label>
        
        <type>Text</type>
        
    </nameField>
    <pluralLabel>SSP Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Member__c/fields/DCId__c.field-meta.xml
<CustomField>
    <fullName>DCId__c</fullName>
    <description>This field used to store the unique member DC Id to identify for an external system</description>
    <externalId>true</externalId>
    <label>DCId</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>This field is used to store Firstname on a Member</description>
    <encryptionScheme>None</encryptionScheme>
    <label>FirstName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/IsReceivingMedicareBenefitToggle__c.field-meta.xml
<CustomField>
    <fullName>IsReceivingMedicareBenefitToggle__c</fullName>
    <description>This field is used to determine if an individual has received medicare benefits.</description>
    <label>Is Receiving Medicare Benefits ?</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>YesNo</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <description>This field is used to store Lastname of a member</description>
    <encryptionScheme>None</encryptionScheme>
    <label>LastName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/TBQIndividualVerificationCode__c.field-meta.xml
<CustomField>
    <fullName>TBQIndividualVerificationCode__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to store TBQ Individual Verification code</description>
    <label>TBQIndividualVerificationCode</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/MedicareTypeCode.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>PA</fullName>
        
        
        <label>Medicare Part A</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>PB</fullName>
        
        
        <label>Medicare Part B</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>MD</fullName>
        
        
        <label>CONDITIONAL ENROLLMENT IN MEDICARE PART A</label>
        
    </customValue>
    
    <description>Medicare Types</description>
    
    <masterLabel>Medicare Type Code</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/globalValueSets/YesNo.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>Y</fullName>
        
        
        <label>YES</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>N</fullName>
        
        
        <label>NO</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>U</fullName>
        
        
        <label>Unknown</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>NULL</fullName>
        
        
        <label>NULL</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>H</fullName>
        
        
        <label>Historical</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>I don&apos;t know</fullName>
        
        
        <label>I don&apos;t know</label>
        
    </customValue>
    
    <description>Used to store different types of toggle picklist values</description>
    
    <masterLabel>YesNo</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/classes/SSP_MedicareCoverageService.cls
/*
* classname     :  SSP_MedicareCoverageService
* @description  :  Service class for Medicare Coverage Summary and Details
* @author       :  Varun Kochar   
* @date         :  04/02/2020
* MODIFICATION LOG:
* DEVELOPER                     DATE                               DESCRIPTION
* ---------------------------------------------------------------------------------------------

**/
public class SSP_MedicareCoverageService {
    
    /**
* @author: Varun Kochar
* @method: getBenefit
* @desc This method is used to get details for a SSP Benefit
* @return List<SSP_Benefits__c>
* */
    public static List<SSP_Benefits__c> getBenefit(Set<String> memberId){
        try{
            Map<String, String> benefitDetailMap = new Map<String, String> {'objectName' => 'SSP_Benefits__c', 'operator'=>'AND', 'isDeleted__c'=>'!='  };        
                Set<String> setBenefitFields = new Set<String>{'Id','Name','BeginDate__c','EndDate__c','MedicareNumber__c','DCId__c','SSP_Member__c','SSP_Member__r.Name','SSP_Member__r.TBQIndividualVerificationCode__c','HasMedicareCoverageButNoInfo__c','MedicareTypeCode__c','SSP_Member__r.FirstName__c','SSP_Member__r.LastName__c','isDeleted__c'};
                    Map<String, String> benefitConditionMap = new Map<String, String> {'SSP_Member__c' =>  String.join(new List<String>(memberId), ','), 'Recordtype.DeveloperName' =>'MedicareBenefit' , 'isDeleted__c'=>'true'};
                        return SSP_BenefitsSelector.queryBenefitsData ( benefitDetailMap, setBenefitFields, benefitConditionMap);
            
        }catch(Exception e){
            LOG_LogMessageUtility.logMessage(e, 'SSP_MedicareCoverageService', 'getBenefit', e.getMessage(), true);
        }
        return null;
    }
    /**
* @author: Varun Kochar
* @method: getMember
* @desc This method is used to get details for a SSP Member
* @return List<SSP_Member__c>
* */
    public static List<SSP_Member__c> getMember(Set<String> memberId){
        try{
            Map<String, String> memberDetailMap = new Map<String, String> {'objectName' => 'SSP_Member__c'};        
                Set<String> setMemberFields = new Set<String>{'Id', 'FirstName__c','LastName__c' ,'IsReceivingMedicareBenefitToggle__c'};
                    Map<String, String> memberConditionMap = new Map<String, String> {'Id' =>  String.join(new List<String>(memberId), ',')};
                        return SSP_MemberSelector.queryMemberData ( memberDetailMap, setMemberFields, memberConditionMap);
        }catch(Exception e){
            LOG_LogMessageUtility.logMessage(e, 'SSP_MedicareCoverageService', 'getMember', e.getMessage(), true);
        }
        return null;
    }
    /**
* @author: Varun Kochar
* @method: getMedicareTypeMap
* @desc This method is used to get medicareTypeMap
* @return Map<String, String>
* */
    public static Map<String, String> getMedicareTypeMap(){
        Map<String, String> medicareTypeMap = new Map<String, String>();
        for(Schema.PicklistEntry pickList : SSP_Benefits__c.MedicareTypeCode__c.getDescribe().getPicklistValues()){
            String picklistInTitleCase = '';
            for ( String word : pickList.getLabel().split ( ' ' )) {
                picklistInTitleCase += word.subString ( 0 , 1 ).toUpperCase() + word.SubString ( 1, word.length () ).toLowerCase() + ' ' ;
            }
            medicareTypeMap.put(pickList.getValue(),picklistInTitleCase.trim());
        }
        return medicareTypeMap;                          
    }
}