force-app/main/default/objects/ErrorLog__e/ErrorLog__e.object-meta.xml
<CustomObject>
    <label>ErrorLog</label>
    <pluralLabel>ErrorLogs</pluralLabel>
</CustomObject>

force-app/main/default/objects/ErrorLog__e/fields/DebugLevel__c.field-meta.xml
<CustomField>
    <fullName>DebugLevel__c</fullName>
    <label>Debug Level</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ErrorLog__e/fields/ErroLog__c.field-meta.xml
<CustomField>
    <fullName>ErroLog__c</fullName>
    <label>ErroLog</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ErrorLog__e/fields/Log_Code__c.field-meta.xml
<CustomField>
    <fullName>Log_Code__c</fullName>
    <label>Log Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ErrorLog__e/fields/SourceFunction__c.field-meta.xml
<CustomField>
    <fullName>SourceFunction__c</fullName>
    <label>Source Function</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/ApplicableRoles__c.field-meta.xml
<CustomField>
    <fullName>ApplicableRoles__c</fullName>
    <description>Roles returned from KOG, which this user can play. User needs to select one role to proceed accesing SSP</description>
    <label>Applicable Roles</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assister</fullName>
                <label>kynector</label>
            </value>
            <value>
                <fullName>Citizen_Individual</fullName>
                <label>Citizen</label>
            </value>
            <value>
                <fullName>Agency_Admin</fullName>
                <label>Agency Admin</label>
            </value>
            <value>
                <fullName>CHFS_Prod_Support</fullName>
                <label>CHFS Prod Support</label>
            </value>
            <value>
                <fullName>Contact_Center_View_and_Edit</fullName>
                <label>Contact Center (View and Edit)</label>
            </value>
            <value>
                <fullName>Contact_Center_View_Only</fullName>
                <label>Contact Center (View Only)</label>
            </value>
            <value>
                <fullName>DAIL_Worker</fullName>
                <label>DAIL Worker</label>
            </value>
            <value>
                <fullName>DCBS_View_Only</fullName>
                <label>DCBS - View Only</label>
            </value>
            <value>
                <fullName>DCBS_Central_Office_View_and_Edit</fullName>
                <label>DCBS Central Office - View &amp; Edit</label>
            </value>
            <value>
                <fullName>Department_Of_Education_Representative</fullName>
                <label>Department of Education Representative</label>
            </value>
            <value>
                <fullName>DJJ_Representative</fullName>
                <label>DJJ Representative</label>
            </value>
            <value>
                <fullName>DOC_Representative</fullName>
                <label>DOC Representative</label>
            </value>
            <value>
                <fullName>Eligibility_&amp;_Benefit_Inquiry_User</fullName>
                <label>Eligibility &amp; Benefit Inquiry User</label>
            </value>
            <value>
                <fullName>Individual_Auth_Rep</fullName>
                <label>Individual Authorized Representative</label>
            </value>
            <value>
                <fullName>Insurance_Agent</fullName>
                <label>Agent</label>
            </value>
            <value>
                <fullName>Jailor</fullName>
            </value>
            <value>
                <fullName>Mail_Center_Supervisor</fullName>
                <label>Mail Center Supervisor</label>
            </value>
            <value>
                <fullName>Mail_Center_Worker</fullName>
                <label>Mail Center Worker</label>
            </value>
            <value>
                <fullName>Organization_Auth_Rep</fullName>
                <label>Organization Authorized Representative</label>
            </value>
            <value>
                <fullName>Psychiatric_Facility_Representative</fullName>
                <label>Psychiatric Facility Representative</label>
            </value>
            <value>
                <fullName>QE_Hospital</fullName>
                <label>QEHospital</label>
            </value>
            <value>
                <fullName>QE_Pregnancy</fullName>
                <label>QEPregnancy</label>
            </value>
            <value>
                <fullName>APPLICATION_INITIATOR</fullName>
                <label>Application Initiator</label>
            </value>
            <value>
                <fullName>APPLICATION_REVIEWER</fullName>
                <label>APPLICATION REVIEWER</label>
            </value>
            <value>
                <fullName>CASE_MANAGEMENT_ADMINISTRATOR_INTERNAL</fullName>
                <label>Case Management Administrator (Internal)</label>
            </value>
            <value>
                <fullName>WAIVER_CAPACITY_REVIEWER</fullName>
                <label>Waiver Capacity Reviewer</label>
            </value>
            <value>
                <fullName>CASE_MANAGER</fullName>
                <label>Case Manager</label>
            </value>
            <value>
                <fullName>CASE_SUPERVISOR</fullName>
                <label>Case Supervisor</label>
            </value>
            <value>
                <fullName>CHFS_APPLICATION_INITIATOR</fullName>
                <label>CHFS Application Initiator</label>
            </value>
            <value>
                <fullName>LEVEL_OF_CARE_ASSESSOR</fullName>
                <label>Level of Care Assessor</label>
            </value>
            <value>
                <fullName>RE United Way Staff</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/KOG_Role__c.field-meta.xml
<CustomField>
    <fullName>KOG_Role__c</fullName>
    <label>KOG Role</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/RE_Selected_Role__c.field-meta.xml
<CustomField>
    <fullName>RE_Selected_Role__c</fullName>
    <description>Role selected by user from applicable roles.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Role selected by user from applicable roles.</inlineHelpText>
    <label>RE Selected Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/StaffHandler.cls
/*********************************************************************************************************************************
* Class Name    : StaffHandler 
* Owner         : Deloitte
* Created Date  : 11/05/2019 
* Description   : class is used to Create UW Staff
*
*                            M O D I F I C A T I O N   L O G                                          
*
*  Date         Developer       Description                                                         
*  ----------   -----------     ----------------------------------------------------------------------------------------------------
*  11/08/2019   Sai kiran       Initial Version
*  12/02/2019   Srikanth        Error Handling implementation using platform events
*  04/29/2020   Venkat Korra    Task-339189: Added changes related to New Production Support Profile. 
*                               And modified class name from RE_UWStaffHandler to StaffHandler
*/
public with sharing class StaffHandler {
    
    public class CcAccessException extends Exception{}
    public static staffExceptionCapture createUser(user usr, String federationIdentifier ){
        //below code creates the user with the respective to UW Staff profile
        staffExceptionCapture staffExp = new staffExceptionCapture();
        staffExp.isExceptionFound = false;
        usr.Alias = usr.FirstName.substring(0,2)+String.valueOf(DateTime.now().getTime()).right(6);
        if(usr.LanguageLocaleKey == 'es-US' || usr.LanguageLocaleKey == 'es-MX') {
            usr.LanguageLocaleKey='es_US';
            usr.LocaleSidKey = 'es_US';  
        } else {
            usr.LanguageLocaleKey='en_US';
            usr.LocaleSidKey = 'en_US';  
        }
        usr.TimeZoneSidKey = 'America/New_York';
        usr.EmailEncodingKey = 'UTF-8';
        usr.FederationIdentifier = federationIdentifier;
        List <Profile> prof = new List<Profile>();
        if(Schema.sObjectType.Profile.fields.ID.isAccessible() && Schema.sObjectType.Profile.fields.Name.isAccessible() ){
            // Venkat: 04/29/2020: Task-339189: Added changes related to New Production Support Profile.
            if(usr.KOG_Role__c.contains('UW Staff'))
            {
                prof = getSingleProfileRec('RE United Way Staff');
                usr.RE_Selected_Role__c = 'UW Staff';//[Suresh] set RE selected field
            }
            else if(usr.KOG_Role__c.contains('SF Production Support'))
            {
                prof = getSingleProfileRec('Production Support Profile');
            }
        }
        usr.ProfileId = prof[0].id;
        Database.SaveResult sr = database.insert(usr,false);
        if (!sr.isSuccess()){
            String msg = '';
            for(Database.Error err : sr.getErrors()) {
                msg += err.getStatusCode() + ': ' + err.getMessage() + '\n';
                
            }
            //platform events to capture the Error Log when there is an exception in user creation
            List<ErrorLog__e> publishEvents = new List<ErrorLog__e>();
            publishEvents.add(new ErrorLog__e(DebugLevel__c = 'ERROR',Log_Code__c = 'ERR005',ErroLog__c= 'Error while creating user', Source__c ='StaffHandler', Message__c = msg ,SourceFunction__c = 'createUser'));
            if(publishEvents.size()>0){
                EventBus.publish(publishEvents);
            }
            //below parameters to pass the Error code and message to the JIT handler
            staffExp.ExceptionCode = 'ERR002';
            staffExp.usr = usr;
            //throw new CcAccessException('ERR005');
        }
        return staffExp; 
    }
    
    public static user updateUser(user usrInfo, String federationIdentifier ){
     
        User usr ;
        if(Schema.sObjectType.User.fields.ID.isAccessible() && Schema.sObjectType.User.fields.LanguageLocaleKey.isAccessible() && 
           Schema.sObjectType.User.fields.TimeZoneSidKey.isAccessible() && Schema.sObjectType.User.fields.EmailEncodingKey.isAccessible()
          && Schema.sObjectType.User.fields.ProfileId.isAccessible() && Schema.sObjectType.User.fields.FederationIdentifier.isAccessible() && federationIdentifier!=null){
        usr = [SELECT ID,LanguageLocaleKey, ApplicableRoles__c, TimeZoneSidKey, EmailEncodingKey, ProfileId, KOG_Role__c FROM User Where FederationIdentifier =: federationIdentifier LIMIT 1];
          }
        if(usr.LanguageLocaleKey == 'es-US' || usr.LanguageLocaleKey == 'es-MX') {
            usr.LanguageLocaleKey='es_US';
            usr.LocaleSidKey = 'es_US';  
        } else {
            usr.LanguageLocaleKey='en_US';
            usr.LocaleSidKey = 'en_US';  
        }
        usr.TimeZoneSidKey = 'America/New_York';
        usr.EmailEncodingKey = 'UTF-8';
        List <Profile> prof = new List<Profile>();
        if(Schema.sObjectType.Profile.fields.ID.isAccessible() && Schema.sObjectType.Profile.fields.Name.isAccessible()){
            // Venkat: 04/29/2020: Task-339189: Added changes related to New Production Support Profile.
            if(usr.KOG_Role__c.contains('UW Staff'))
            {
                 usr.ApplicableRoles__c = 'RE United Way Staff';
                prof = getSingleProfileRec('RE United Way Staff');
                usr.RE_Selected_Role__c = 'UW Staff';//[Suresh] set RE selected field
            }
            else if(usr.KOG_Role__c.contains('SF Production Support'))
            {
                
                prof = getSingleProfileRec('Production Support Profile');
            }
        }
        usr.ProfileId = prof[0].id;
        Database.SaveResult sr = database.update(usr,false);
        if (!sr.isSuccess()){
            String msg = '';
            for(Database.Error err : sr.getErrors()) {
                msg += err.getStatusCode() + ': ' + err.getMessage() + '\n';
            }
            //platform events to capture the Error Log when there is an exception in user update
            List<ErrorLog__e> publishEvents = new List<ErrorLog__e>();
            publishEvents.add(new ErrorLog__e(DebugLevel__c = 'ERROR',Log_Code__c = 'ERR003',ErroLog__c= 'Error while creating user', Source__c ='StaffHandler', Message__c = msg ,SourceFunction__c = 'updateUser'));
            if(publishEvents.size()>0){
                EventBus.publish(publishEvents);
            }
            throw new CcAccessException('ERR003');
        }
        return usr; 
         
    }
    
/*********************************************************************************************************************************
* @author       Srikanth
* @date         12/02/2019
* @wrapperClass staffExceptionCapture
* @description  Wrapper class
************************************************************************************************************************************/
    
    public class staffExceptionCapture{
        public boolean isExceptionFound;
        public user usr;
        public string ExceptionCode;
    }
    public static List<profile> getSingleProfileRec(String ProfileName){
        return [Select Id FROM Profile WHERE Name=:ProfileName LIMIT 1];
    }
}