force-app/main/default/objects/SSP_ApplicationIndividual__c/SSP_ApplicationIndividual__c.object-meta.xml
<CustomObject>
    <description>Custom junction object to maintain association between member and application</description>
    <label>SSP ApplicationIndividual</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>SSP_ApplicationIndividual Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SSP ApplicationIndividuals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/MedicaidType__c.field-meta.xml
<CustomField>
    <fullName>MedicaidType__c</fullName>
    <description>Used to store type of Medicaid Program - Magi/Non Magi</description>
    <label>Medicaid Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MAGI</fullName>
            </value>
            <value>
                <fullName>Non-MAGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/ProgramsApplied__c.field-meta.xml
<CustomField>
    <fullName>ProgramsApplied__c</fullName>
    <description>Different types of programs applied on an application for which this member is involved</description>
    <label>Application Programs Applied</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>BenefitPrograms</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/globalValueSets/BenefitPrograms.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>MA</fullName>
        
        
        <label>Medicaid/KCHIP</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>KT</fullName>
        
        
        <label>KTAP (Cash Assistance)</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SN</fullName>
        
        
        <label>SNAP (Food Assistance)</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SS</fullName>
        
        
        <label>State Supplementation</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>DS</fullName>
        
        
        <label>DSNAP</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>CC</fullName>
        
        
        <label>Child Care Assistance</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>KP</fullName>
        
        
        <label>KI-HIPP (Health Insurance Premium Payments)</label>
        
    </customValue>
    
    <description>Different type of Benefit Programs available for a Citizen</description>
    
    <masterLabel>Benefit Programs</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/classes/SSP_OtherResSelectionScreenQueueRule.cls
/*
* classname     :  SSP_OtherResSelectionScreenQueueRule
* @description  :  Class for identifying whether to queue sspOtherResourcesSelection screen for particular individual
* @author       :  Karthik Gulla  
* @date         :  02/29/2020
* MODIFICATION LOG:
* DEVELOPER                     DATE                               DESCRIPTION
* ---------------------------------------------------------------------------------------------
**/
public with sharing class SSP_OtherResSelectionScreenQueueRule extends BasicNavFlowRule {
    
    /**
    * Invoked on workflow "next" action. If true is returned then the page will be marked as "required" in the
    * current flow and so it will be queued to be loaded on its turn. If false is returned then the page
    * will be marked as "not required" and hence will not be loaded in the flow.
    *
    * @param ctx Context object
    * @param ctxData ContextData object
    *
    * @return boolean
    */
    public override boolean isRequired(Context ctx, ContextData ctxData){
        Boolean result = false;
        List<String> lstResourcePrograms = new List<String>();
        lstResourcePrograms.add(SSP_GlobalConstants.STATE);
        lstResourcePrograms.add(SSP_GlobalConstants.NONMAGI);
        try{
            if(ctxData!=null
                && ctxData.ApplicationId != '' && ctxData.ApplicationId != null
                 && ctxData.modeValue != 'RAC'){ 
                Set<Id> setApplicationIds = new Set<Id>();  
                setApplicationIds.add(ctxData.ApplicationId);

		List<SSP_ApplicationIndividual__c> lstAppIndividuals = ctxData.queueObject.applicationIndividualList != null ? ctxData.queueObject.applicationIndividualList : new List<SSP_ApplicationIndividual__c>();
                List<String> lstAppPrograms = new List<String>();
                List<String> lstEmptyAppPrograms = new List<String>();
                for(SSP_ApplicationIndividual__c sspAppIndividual : lstAppIndividuals){
                    lstAppPrograms.clear(); 
                    lstAppPrograms = sspAppIndividual.ProgramsApplied__c != null ? sspAppIndividual.ProgramsApplied__c.split(';') : lstEmptyAppPrograms;

                    if(lstAppPrograms.contains(SSP_GlobalConstants.MEDICAID)
                        && sspAppIndividual.MedicaidType__c == SSP_GlobalConstants.NONMAGI) {
                        lstAppPrograms.add(SSP_GlobalConstants.NONMAGI);
                    }
                        
                    if(SSP_ResourcesService.hasProgramApplicable(lstAppPrograms, lstResourcePrograms)){
                        result = true;
                        break;
                    }
                } 
            }
        }
        catch(Exception ex){            
            LOG_LogMessageUtility.logMessage(ex, 'SSP_OtherResSelectionScreenQueueRule', 'isRequired', ex.getMessage() , true);
        }
        return result;
    }
}