force-app/main/default/objects/SSP_ApplicationIndividual__c/SSP_ApplicationIndividual__c.object-meta.xml
<CustomObject>
    <description>Custom junction object to maintain association between member and application</description>
    <label>SSP ApplicationIndividual</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>SSP_ApplicationIndividual Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SSP ApplicationIndividuals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/MedicaidType__c.field-meta.xml
<CustomField>
    <fullName>MedicaidType__c</fullName>
    <description>Used to store type of Medicaid Program - Magi/Non Magi</description>
    <label>Medicaid Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MAGI</fullName>
            </value>
            <value>
                <fullName>Non-MAGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/MemberStatus__c.field-meta.xml
<CustomField>
    <fullName>MemberStatus__c</fullName>
    <description>This field is used to determine the status of member</description>
    <label>Member Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Edited</fullName>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/ProgramsApplied__c.field-meta.xml
<CustomField>
    <fullName>ProgramsApplied__c</fullName>
    <description>Different types of programs applied on an application for which this member is involved</description>
    <label>Application Programs Applied</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>BenefitPrograms</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/SSP_Member__c.field-meta.xml
<CustomField>
    <fullName>SSP_Member__c</fullName>
    <description>Indicates the member related to an application</description>
    <label>SSP_Member</label>
    <referenceTo>SSP_Member__c</referenceTo>
    <relationshipName>SSP_ApplicationIndividuals</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/SSP_Member__c.object-meta.xml
<CustomObject>
    <description>Stores details about an individual member of a case/application such as gatepost reponse, incarceration, disability, living arrangement, pregnancy, address details. Also repurposed to store information of different individuals in the form of individual alien, alien sponsor, care taker,  care coordinator etc.</description>
    <label>SSP Member</label>
    <nameField>
        
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        
        <label>SSP_Member Name</label>
        
        <type>Text</type>
        
    </nameField>
    <pluralLabel>SSP Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/BenefitPrograms.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>MA</fullName>
        
        
        <label>Medicaid/KCHIP</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>KT</fullName>
        
        
        <label>KTAP (Cash Assistance)</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SN</fullName>
        
        
        <label>SNAP (Food Assistance)</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SS</fullName>
        
        
        <label>State Supplementation</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>DS</fullName>
        
        
        <label>DSNAP</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>CC</fullName>
        
        
        <label>Child Care Assistance</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>KP</fullName>
        
        
        <label>KI-HIPP (Health Insurance Premium Payments)</label>
        
    </customValue>
    
    <description>Different type of Benefit Programs available for a Citizen</description>
    
    <masterLabel>Benefit Programs</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/classes/SSP_ApplicationIndividual_TriggerHandler.cls
/*
* classname     : SSP_ApplicationIndividual_TriggerHandler
* @description  : This class is a Handler class for SSP_ApplicationIndividual_Trigger.
* @author       : Karthik Gulla
* @date         : 04/24/2020
* MODIFICATION LOG:
* DEVELOPER             DATE            DESCRIPTION
* ---------------------------------------------------------------------------------------------
* Karthik Gulla        04/24/2020      Initial Version
*/
public with sharing class SSP_ApplicationIndividual_TriggerHandler implements SSP_ITriggerHandler {
    
    public void beforeInsert(List<SObject> newItems) {}
    
    public void beforeUpdate(Map<Id, SObject> newItems, Map<Id, SObject> oldItems) {
        try {
              for(Id individualId: oldItems.keySet()) {
                SSP_ApplicationIndividual__c oldIndividual = (SSP_ApplicationIndividual__c)oldItems.get(individualId);
                SSP_ApplicationIndividual__c newIndividual = (SSP_ApplicationIndividual__c)newItems.get(individualId);
               
                if(newIndividual!= null && newIndividual.ProgramsApplied__c!= null && !newIndividual.ProgramsApplied__c.contains(SSP_GlobalConstants.MEDICAID) ){
                    newIndividual.MedicaidType__c =null;
                }
              }
            }
        catch(Exception ex) {
            LOG_LogMessageUtility.logMessage(ex, 'SSP_ApplicationIndividual_TriggerHandler', 'beforeUpdate', ex.getMessage() , true);
        }
    }

    public void beforeDelete(Map<Id, SObject> oldItems) {}

    /**
	* method 		: AfterInsert
	* @description 	: Method executes to set MAGI/Non-MAGI application, when new applicationIndividual records are created
	* @author 		: Karthik Gulla
	* @param 		: List<SObject> newItems - Contains new ApplicationIndividual data
	* @return		: void
	* */
    public void afterInsert(Map<Id, SObject> newItems) {
        try {
            Set<String> setMemberIds = new Set<String>();
            String sApplicationId = '';
            for(SSP_ApplicationIndividual__c sspAppIndivRecord : (List<SSP_ApplicationIndividual__c>)newItems.values()){
                if(sspAppIndivRecord.MemberStatus__c != SSP_GlobalConstants.MEMBER_REMOVE_STATUS
                && sspAppIndivRecord.SSP_Member__c != null) {
                    setMemberIds.add(sspAppIndivRecord.SSP_Member__c);
                }
            }
            if(!setMemberIds.isEmpty()){
                SSP_MemberService.checkMembersAgeBlindDisabledInfo(sApplicationId, setMemberIds);
            }
        } catch(Exception ex) {
            LOG_LogMessageUtility.logMessage(ex, 'SSP_ApplicationIndividual_TriggerHandler', 'AfterInsert', ex.getMessage() , true);
        }
    }

    public void afterUpdate(Map<Id, SObject> newItems, Map<Id, SObject> oldItems) {}

    public void afterDelete(Map<Id, SObject> oldItems) {}

    public void afterUndelete(Map<Id, SObject> oldItems) {}

     public Boolean isDisabled() {
        return false;
    }
}