force-app/main/default/objects/SSP_ApplicationIndividual__c/SSP_ApplicationIndividual__c.object-meta.xml
<CustomObject>
    <description>Custom junction object to maintain association between member and application</description>
    <label>SSP ApplicationIndividual</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>SSP_ApplicationIndividual Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SSP ApplicationIndividuals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/SSP_Application__c.field-meta.xml
<CustomField>
    <fullName>SSP_Application__c</fullName>
    <description>Indicates the application related to a member</description>
    <label>SSP_Application</label>
    <referenceTo>SSP_Application__c</referenceTo>
    <relationshipName>SSP_ApplicationIndividuals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/SSP_Member__c.field-meta.xml
<CustomField>
    <fullName>SSP_Member__c</fullName>
    <description>Indicates the member related to an application</description>
    <label>SSP_Member</label>
    <referenceTo>SSP_Member__c</referenceTo>
    <relationshipName>SSP_ApplicationIndividuals</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_Institution__c/SSP_Institution__c.object-meta.xml
<CustomObject>
    <description>Stores details about School, Organisation, Federal Reserve</description>
    <label>SSP Institution</label>
    <nameField>
        
        <displayFormat>IT-{0000000000}</displayFormat>
        
        <label>SSP Institution Name</label>
        
        <type>AutoNumber</type>
        
    </nameField>
    <pluralLabel>SSP Institutions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Institution__c/fields/AddressLine1__c.field-meta.xml
<CustomField>
    <fullName>AddressLine1__c</fullName>
    <description>Used to store Address line 1 details</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Institution__c/fields/AddressLine2__c.field-meta.xml
<CustomField>
    <fullName>AddressLine2__c</fullName>
    <description>Used to store Address line 2 details</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Address Line 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Institution__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Used to store City details</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Institution__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>This field is used to store School/Organization/Bank name</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Institution__c/fields/RoutingNumber__c.field-meta.xml
<CustomField>
    <fullName>RoutingNumber__c</fullName>
    <description>This is used to store Routing Number of Federal Reserve</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>RoutingNumber</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Institution__c/fields/StateCode__c.field-meta.xml
<CustomField>
    <fullName>StateCode__c</fullName>
    <description>Used to store State code details</description>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>SSPState</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_InsuranceCoveredIndiv__c/SSP_InsuranceCoveredIndiv__c.object-meta.xml
<CustomObject>
    <description>Stores details about an individual covered under an insurance policy. It could be an existing member in the system or an external individual covered under policy.</description>
    <label>SSP InsuranceCoveredIndiv</label>
    <nameField>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>SSP_InsuranceCoveredIndiv Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SSP InsuranceCoveredIndiv</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_InsuranceCoveredIndiv__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>This field is used to store Firstname of an Insurance Covered Individual</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_InsuranceCoveredIndiv__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <description>This field is used to store Lastname of an Insurance Covered Individual</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_InsuranceCoveredIndiv__c/fields/MiddleInitial__c.field-meta.xml
<CustomField>
    <fullName>MiddleInitial__c</fullName>
    <description>This field is use to store Middle Initial of Covered Individual</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Middle Initial</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_InsuranceCoveredIndiv__c/fields/SSP_Member__c.field-meta.xml
<CustomField>
    <fullName>SSP_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to indicate the member of an Insurance Covered Individual</description>
    <label>SSP_Member</label>
    <referenceTo>SSP_Member__c</referenceTo>
    <relationshipName>SSP_InsuranceCoveredIndiv</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SSP_InsuranceCoveredIndiv__c/fields/SuffixCode__c.field-meta.xml
<CustomField>
    <fullName>SuffixCode__c</fullName>
    <description>This field is use to store the Covered Individual Member Suffix</description>
    <label>Suffix</label>
    <type>Picklist</type>
    <valueSet>
        
            <valueSetDefinition>
            
            
                <value>
                
                    <fullName>JR</fullName>
                
                
                    <label>JR.</label>
                
                </value>
            
                <value>
                
                    <fullName>SR</fullName>
                
                
                    <label>SR.</label>
                
                </value>
            
                <value>
                
                    <fullName>TW</fullName>
                
                
                    <label>II</label>
                
                </value>
            
                <value>
                
                    <fullName>TH</fullName>
                
                
                    <label>III</label>
                
                </value>
            
                <value>
                
                    <fullName>FO</fullName>
                
                
                    <label>IV</label>
                
                </value>
            
                <value>
                
                    <fullName>FV</fullName>
                
                
                    <label>V</label>
                
                </value>
            
                <value>
                
                    <fullName>SI</fullName>
                
                
                    <label>VI</label>
                
                </value>
            
                <value>
                
                    <fullName>SE</fullName>
                
                
                    <label>VII</label>
                
                </value>
            
            </valueSetDefinition>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Member__c/SSP_Member__c.object-meta.xml
<CustomObject>
    <description>Stores details about an individual member of a case/application such as gatepost reponse, incarceration, disability, living arrangement, pregnancy, address details. Also repurposed to store information of different individuals in the form of individual alien, alien sponsor, care taker,  care coordinator etc.</description>
    <label>SSP Member</label>
    <nameField>
        
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        
        <label>SSP_Member Name</label>
        
        <type>Text</type>
        
    </nameField>
    <pluralLabel>SSP Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Member__c/fields/CheckingAccountNumber__c.field-meta.xml
<CustomField>
    <fullName>CheckingAccountNumber__c</fullName>
    <description>This field is used to store Checking Account Number for Preferred Payment method</description>
    <label>Checking Account Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>This field is used to store Firstname on a Member</description>
    <encryptionScheme>None</encryptionScheme>
    <label>FirstName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <description>This field is used to store Lastname of a member</description>
    <encryptionScheme>None</encryptionScheme>
    <label>LastName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/MailingAddressLine1__c.field-meta.xml
<CustomField>
    <fullName>MailingAddressLine1__c</fullName>
    <description>This field is used to store Address Line 1 value of Mailing Address</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/MailingAddressLine2__c.field-meta.xml
<CustomField>
    <fullName>MailingAddressLine2__c</fullName>
    <description>This field is used to store Address Line 2 value of Mailing Address</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Address Line 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/MailingCity__c.field-meta.xml
<CustomField>
    <fullName>MailingCity__c</fullName>
    <description>This field is used to store city for a Mailing address of a member</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/MailingCountryCode__c.field-meta.xml
<CustomField>
    <fullName>MailingCountryCode__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>SSPCountry</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/MailingCountyCode__c.field-meta.xml
<CustomField>
    <fullName>MailingCountyCode__c</fullName>
    <description>This field is used to store county for a Mailing address of a member</description>
    <label>County</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>SSPCounty</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/MailingStateCode__c.field-meta.xml
<CustomField>
    <fullName>MailingStateCode__c</fullName>
    <description>This field is used to store mailing state code for mailing address on a member</description>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>SSPState</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/MailingZipCode5__c.field-meta.xml
<CustomField>
    <fullName>MailingZipCode5__c</fullName>
    <description>This field is used to store 5 digit Mailing Zip code</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Zip Code(Five Digit)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/MiddleInitial__c.field-meta.xml
<CustomField>
    <fullName>MiddleInitial__c</fullName>
    <description>This field is used to store Middle Initial of a member</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>MiddleInitial</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/OrganizationName__c.field-meta.xml
<CustomField>
    <fullName>OrganizationName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to indicate a related institution of organization type on a member</description>
    <label>Organization/Provider Name</label>
    <referenceTo>SSP_Institution__c</referenceTo>
    <relationshipLabel>SSP Members (Organization/Provider Name)</relationshipLabel>
    <relationshipName>SSP_Member</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/PreferredIssuanceMethod__c.field-meta.xml
<CustomField>
    <fullName>PreferredIssuanceMethod__c</fullName>
    <description>This field is used to store Preferred method of payment</description>
    <label>Preferred Method of Payment</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>PreferredIssuanceMethod</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/RoutingNumber__c.field-meta.xml
<CustomField>
    <fullName>RoutingNumber__c</fullName>
    <description>This field is used to store Routing Number</description>
    <label>Routing Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/SuffixCode__c.field-meta.xml
<CustomField>
    <fullName>SuffixCode__c</fullName>
    <description>This field is used to store Suffix code on a member</description>
    <label>Suffix</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>Suffix</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/globalValueSets/PreferredIssuanceMethod.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>EFT</fullName>
        
        
        <label>Direct Deposit to Checking Account</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>CH</fullName>
        
        
        <label>Check</label>
        
    </customValue>
    
    <description>Methods Preferred for Issuance</description>
    
    <masterLabel>Preferred Issuance Method</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/globalValueSets/Suffix.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>JR</fullName>
        
        
        <label>Jr.</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SR</fullName>
        
        
        <label>Sr.</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>TW</fullName>
        
        
        <label>II</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>TH</fullName>
        
        
        <label>III</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>FO</fullName>
        
        
        <label>IV</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>FV</fullName>
        
        
        <label>V</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SI</fullName>
        
        
        <label>VI</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SE</fullName>
        
        
        <label>VII</label>
        
    </customValue>
    
    <description>Suffix codes used for any user</description>
    
    <masterLabel>Suffix</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/classes/SSP_KHIPPPreferredPaymentMethodService.cls
/*
* classname     :  SSP_KHIPPPreferredPaymentMethodService
* @description  :  Service class for SSP_KHIPPPreferredPaymentMethod
* @author       :  Varun Kochar   
* @date         :  23/01/2020
* MODIFICATION LOG:
* DEVELOPER                     DATE                               DESCRIPTION
* ---------------------------------------------------------------------------------------------

**/
public class SSP_KHIPPPreferredPaymentMethodService {

    /**
    * @author: Varun Kochar
    * @method: getApplicationIndividual
    * @desc This method is used to get details for Application Individual
    * @return  List<SSP_ApplicationIndividual__c>
    * */
    public static List<SSP_ApplicationIndividual__c> getApplicationIndividual(Set<String> applicationId){
        try{
            Map<String, String> applicationIndividualConditionMap = new Map<String, String> {'SSP_Application__c' => String.join(new List<String>(applicationId), ',')};
            Map<String, String> applicationIndividualDetailMap = new Map<String, String> {'objectName' => 'SSP_ApplicationIndividual__c', 'IN'=>'SSP_Application__c'};        
          	Set<String> setapplicationIndividualFields = new Set<String>{'SSP_Member__c','SSP_Member__r.Name','SSP_Member__r.FirstName__c','SSP_Member__r.MiddleInitial__c','SSP_Member__r.SuffixCode__c','SSP_Member__r.LastName__c','SSP_Member__r.PreferredIssuanceMethod__c','SSP_Member__r.RoutingNumber__c',' SSP_Member__r.CheckingAccountNumber__c','SSP_Member__r.MailingAddressLine1__c','SSP_Member__r.MailingAddressLine2__c', 'SSP_Member__r.MailingCity__c', 'toLabel(SSP_Member__r.MailingCountyCode__c)', 'toLabel(SSP_Member__r.MailingStateCode__c)', 'SSP_Member__r.MailingCountryCode__c', 'SSP_Member__r.MailingZipCode5__c'};
            return SSP_ApplicationIndividualSelector.queryApplicationIndividualData ( applicationIndividualDetailMap, setapplicationIndividualFields, applicationIndividualConditionMap);
        }catch(Exception e){
            LOG_LogMessageUtility.logMessage(e, 'SSP_KHIPPPreferredPaymentMethodService', 'getCoveredIndividual', e.getMessage(), true);
        }
        return null;
    }
    /**
    * @author: Varun Kochar
    * @method: getCoveredIndividual
    * @desc This method is used to get details for a particular covered Individual
    * @return List<SSP_InsuranceCoveredIndiv__c>
    * */
    public static List<SSP_InsuranceCoveredIndiv__c> getCoveredIndividual(Set<String> memberId){
        try{
             Map<String, String> insuranceCovIndConditionMap = new Map<String, String> {'SSP_Member__c' => String.join(new List<String>(memberId), ','), 'IsPolicyHolder__c' => 'true','IsEnrolled__c' => 'true'};
            Map<String, String> insuranceCovIndDetailMap = new Map<String, String> {'objectName' => 'SSP_InsuranceCoveredIndiv__c', 'IN'=>'SSP_Member__c', 'operator'=>'AND'};        
                Set<String> setInsuranceCovIndFields = new Set<String>{'Id', 'Name', 'SSP_Member__c'};
                        return SSP_SharingBypassFetcher.fetchRecords(insuranceCovIndDetailMap, setInsuranceCovIndFields, insuranceCovIndConditionMap); // CD1 Security Fixes
                                
        }catch(Exception e){
            LOG_LogMessageUtility.logMessage(e, 'SSP_KHIPPPreferredPaymentMethodService', 'getCoveredIndividual', e.getMessage(), true);
        }
        return null;
    }
    /**
    * @author: Varun Kochar
    * @method: getBankDetails
    * @desc This method is used to get bank details
    * @return List<SSP_Institution__c>
    * */
    public static List<SSP_Institution__c> getBankDetails(Set<String> routingNumber){
        try{
             Map<String, String> institutionConditionMap = new Map<String, String> {'RoutingNumber__c' => String.join(new List<String>(routingNumber), ',')};
            Map<String, String> institutionDetailMap = new Map<String, String> {'objectName' => 'SSP_Institution__c', 'IN'=>'RoutingNumber__c'};        
                Set<String> setinstitutionFields = new Set<String>{'Id','Name__c','AddressLine1__c','AddressLine2__c','City__c','Country__c','County__c','RoutingNumber__c','StateCode__c','ZipCode__c'};
                        return SSP_InstitutionSelector.queryInstitutionData ( institutionDetailMap, setinstitutionFields, institutionConditionMap);
                                
        }catch(Exception e){
            LOG_LogMessageUtility.logMessage(e, 'SSP_KHIPPPreferredPaymentMethodService', 'getBankDetails', e.getMessage(), true);
        }
        return null;
    }
}