force-app/main/default/objects/SSP_Application__c/SSP_Application__c.object-meta.xml
<CustomObject>
    <description>To store SSP Application and Case data</description>
    <label>SSP Application</label>
    <nameField>
        
        <displayFormat>{000000000}</displayFormat>
        
        <label>SSP_Application Name</label>
        
        <type>AutoNumber</type>
        
    </nameField>
    <pluralLabel>SSP Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Application__c/fields/ProgramsApplied__c.field-meta.xml
<CustomField>
    <fullName>ProgramsApplied__c</fullName>
    <description>Used to store the list of programs applied for a household</description>
    <label>Programs Applied</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>BenefitPrograms</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/SSP_ApplicationIndividual__c.object-meta.xml
<CustomObject>
    <description>Custom junction object to maintain association between member and application</description>
    <label>SSP ApplicationIndividual</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>SSP_ApplicationIndividual Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SSP ApplicationIndividuals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/IsHeadOfHousehold__c.field-meta.xml
<CustomField>
    <fullName>IsHeadOfHousehold__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to determine if the member is Head of Household</description>
    <label>Is Head Of Household</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/MemberStatus__c.field-meta.xml
<CustomField>
    <fullName>MemberStatus__c</fullName>
    <description>This field is used to determine the status of member</description>
    <label>Member Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Edited</fullName>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/ProgramsApplied__c.field-meta.xml
<CustomField>
    <fullName>ProgramsApplied__c</fullName>
    <description>Different types of programs applied on an application for which this member is involved</description>
    <label>Application Programs Applied</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>BenefitPrograms</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/SSP_Application__c.field-meta.xml
<CustomField>
    <fullName>SSP_Application__c</fullName>
    <description>Indicates the application related to a member</description>
    <label>SSP_Application</label>
    <referenceTo>SSP_Application__c</referenceTo>
    <relationshipName>SSP_ApplicationIndividuals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/SSP_Member__c.field-meta.xml
<CustomField>
    <fullName>SSP_Member__c</fullName>
    <description>Indicates the member related to an application</description>
    <label>SSP_Member</label>
    <referenceTo>SSP_Member__c</referenceTo>
    <relationshipName>SSP_ApplicationIndividuals</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/SSP_Member__c.object-meta.xml
<CustomObject>
    <description>Stores details about an individual member of a case/application such as gatepost reponse, incarceration, disability, living arrangement, pregnancy, address details. Also repurposed to store information of different individuals in the form of individual alien, alien sponsor, care taker,  care coordinator etc.</description>
    <label>SSP Member</label>
    <nameField>
        
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        
        <label>SSP_Member Name</label>
        
        <type>Text</type>
        
    </nameField>
    <pluralLabel>SSP Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Member__c/fields/IsHeadOfHousehold__c.field-meta.xml
<CustomField>
    <fullName>IsHeadOfHousehold__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Head Of Household</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/SameAddressInfoAsHOHToggle__c.field-meta.xml
<CustomField>
    <fullName>SameAddressInfoAsHOHToggle__c</fullName>
    <description>This field is used to store if individual has same address as that of HOH</description>
    <label>Same Address Information as HOH</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>YesNo</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/globalValueSets/BenefitPrograms.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>MA</fullName>
        
        
        <label>Medicaid/KCHIP</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>KT</fullName>
        
        
        <label>KTAP (Cash Assistance)</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SN</fullName>
        
        
        <label>SNAP (Food Assistance)</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SS</fullName>
        
        
        <label>State Supplementation</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>DS</fullName>
        
        
        <label>DSNAP</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>CC</fullName>
        
        
        <label>Child Care Assistance</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>KP</fullName>
        
        
        <label>KI-HIPP (Health Insurance Premium Payments)</label>
        
    </customValue>
    
    <description>Different type of Benefit Programs available for a Citizen</description>
    
    <masterLabel>Benefit Programs</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/globalValueSets/YesNo.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>Y</fullName>
        
        
        <label>YES</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>N</fullName>
        
        
        <label>NO</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>U</fullName>
        
        
        <label>Unknown</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>NULL</fullName>
        
        
        <label>NULL</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>H</fullName>
        
        
        <label>Historical</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>I don&apos;t know</fullName>
        
        
        <label>I don&apos;t know</label>
        
    </customValue>
    
    <description>Used to store different types of toggle picklist values</description>
    
    <masterLabel>YesNo</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/classes/SSP_ApplicantAddressRule.cls
/***************************************************************************************************************************
*   Type        :   Queueing Rule
*   Name        :   SSP_ApplicantAddressRule
*   Create By   :   Ajay Saini
*   Create Date :   NOV-15-2019
*   Description :   This class is checks id Address screen is required or not.
*   Modification Log:
*   * ------------------------------------------------------------------------------------
*   * Developer                   Date          Description
*   * ------------------------------------------------------------------------------------                 
* 
*****************************************************************************************************************************/
public with sharing class SSP_ApplicantAddressRule extends BasicNavFlowRule {
	/**
     * Invoked on workflow "next" action. If true is returned then the page will be marked as "required" in the
     * current flow and so it will be queued to be loaded on its turn. If false is returned then the page
     * will be marked as "not required" and hence will not be loaded in the flow.
     *
     * @param ctx Context object
     * @param ctxData ContextData object
     *
     * @return boolean
     */
    public override boolean isRequired(Context ctx, ContextData ctxData) {
        Boolean required = false;
        try {
            if(ctxData.queueObject != null){
                List<SSP_ApplicationIndividual__c> applicationIndividualList = ctxData.queueObject.applicationIndividualList != null ?
                    		ctxData.queueObject.applicationIndividualList :  new List<SSP_ApplicationIndividual__c> ();
                SSP_ApplicationIndividual__c headOfHousehold, currentIndividual;
                currentIndividual = ctxData.queueObject.memberAppIndividualMap.get(ctxData.MemberId);
                for(SSP_ApplicationIndividual__c appIndiv : applicationIndividualList){
                    if(appIndiv.IsHeadOfHousehold__c){
                        headOfHousehold = appIndiv;
                        break;
                    }
                }                
                List<String> lstPrograms = !applicationIndividualList.isEmpty() ? applicationIndividualList[0] != null ?
                    						applicationIndividualList[0].ProgramsApplied__c != null ?
                    						applicationIndividualList[0].ProgramsApplied__c.split(';') : new List<String>() :
                							new List<String>() : new List<String>();
                Boolean programCheck = SSP_Utility.checkApplicablePrograms(lstPrograms, SSP_GlobalConstants.ADDRESS_PROGRAMS);
                required = programCheck && (currentIndividual != null && headOfHousehold != null) && (currentIndividual.Id == headOfHousehold.Id) ||
                       (headOfHousehold.SSP_Member__r.SameAddressInfoAsHOHToggle__c  != SSP_GlobalConstants.YES) ||
                       (ctxData.modeValue == SSP_GlobalConstants.RAC_AddMember && currentIndividual.MemberStatus__c == SSP_GlobalConstants.MEMBER_STATUS_New);
                
            }
            /*Map<String, String> detailMap = new Map<String, String>{'objectName'=>'SSP_ApplicationIndividual__c','operator' => 'AND'};
            Set<String> fieldSet = new Set<String>{'Id', 'IsHeadOfHousehold__c', 'SSP_Member__r.SameAddressInfoAsHOHToggle__c', 'SSP_Application__c', 'MemberStatus__c'};
            List<SSP_ApplicationIndividual__c> headOfHousehold = SSP_ApplicationIndividualSelector.queryApplicationIndividualData(detailMap, fieldSet,
                new Map<String, String>{'limit' =>'10', 'SSP_Application__c' => String.escapeSingleQuotes(ctxData.applicationId),  'IsHeadOfHousehold__c'=> '#true#'});
            List<SSP_ApplicationIndividual__c> currentIndividual = SSP_ApplicationIndividualSelector.queryApplicationIndividualData(detailMap, fieldSet,
                new Map<String, String>{'limit' =>'10', 'SSP_Application__c' => String.escapeSingleQuotes(ctxData.applicationId),  'SSP_Member__c'=> String.escapeSingleQuotes(ctxData.memberId)});
            required = currentIndividual.isEmpty() 
            || headOfHousehold.isEmpty() 
            || currentIndividual.get(0).Id == headOfHousehold.get(0).Id
            || headOfHousehold.get(0).SSP_Member__r.SameAddressInfoAsHOHToggle__c != SSP_GlobalConstants.YES
            || ctxData.modeValue == 'addRemoveMember' && currentIndividual.get(0).MemberStatus__c == 'New';*/
        } catch (Exception e) {
            LOG_LogMessageUtility.logMessage(e, 'SSP_ApplicantAddressRule', 'isRequired', e.getMessage() , true);
        }
        return required;
    }
}