force-app/main/default/objects/SSP_Application__c/SSP_Application__c.object-meta.xml
<CustomObject>
    <description>To store SSP Application and Case data</description>
    <label>SSP Application</label>
    <nameField>
        
        <displayFormat>{000000000}</displayFormat>
        
        <label>SSP_Application Name</label>
        
        <type>AutoNumber</type>
        
    </nameField>
    <pluralLabel>SSP Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Application__c/fields/ApplicationCreationInSSP__c.field-meta.xml
<CustomField>
    <fullName>ApplicationCreationInSSP__c</fullName>
    <description>custom date to track application creation. to be used to calculate 8 days of expiry to show as dashboard notification.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Application creation in SSP</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SSP_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Different types of status of an Application</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        
            <valueSetDefinition>
            
            
                <value>
                
                    <fullName>N</fullName>
                
                
                    <label>New</label>
                
                </value>
            
                <value>
                
                    <fullName>P</fullName>
                
                
                    <label>Pending</label>
                
                </value>
            
                <value>
                
                    <fullName>AP</fullName>
                
                
                    <label>Approved</label>
                
                </value>
            
                <value>
                
                    <fullName>UN</fullName>
                
                
                    <label>Unsubmitted</label>
                
                </value>
            
                <value>
                
                    <fullName>Inactive</fullName>
                
                
                    <label>Inactive</label>
                
                </value>
            
                <value>
                
                    <fullName>Blocked</fullName>
                
                
                    <label>Blocked</label>
                
                </value>
            
            </valueSetDefinition>
        
        </valueSet>
</CustomField>

force-app/main/default/classes/SSP_ApplicationStatusChange.cls
global class SSP_ApplicationStatusChange implements Database.Batchable<sObject>,Schedulable{
    date lastSubmissionDate = SSP_Utility.today().addDays(-8);
    String unStatus=SSP_GlobalConstants.BATCH_SSP_APPLICATION_STATUS_UN;
    
    Id recordTypeId = Schema.SObjectType.SSP_Application__c.getRecordTypeInfosByDeveloperName()
        .get(SSP_GlobalConstants.BATCH_RECORDTYPE_DEVNAME_SSPAPPLICATION).getRecordTypeId();
    
    String Query='SELECT Id, ApplicationCreationInSSP__c,RecordTypeId, Status__c FROM SSP_Application__c where ApplicationCreationInSSP__c < : lastSubmissionDate and RecordTypeId=:recordTypeId and Status__c=:unStatus';
    
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(Query);
    }
    
    global void execute(Database.BatchableContext BC, List<SSP_Application__c> scope){
        List<SSP_Application__c> listApplications =new List<SSP_Application__c>();
        if(scope.size()>0) 
        {
            for(SSP_Application__c sspApp : scope){
                sspApp.Status__c=SSP_GlobalConstants.BATCH_SSP_APPLICATION_STATUS_INACTIVE;
                listApplications.add(sspApp);
                
            }
            if (Schema.sObjectType.SSP_Application__c.fields.Status__c.isUpdateable()){
                update scope;
                
            }
        }
    }
    
    global void finish(Database.BatchableContext BC){
    }
    
    global void execute(SchedulableContext sc) {
        SSP_ApplicationStatusChange batchObj = new SSP_ApplicationStatusChange();
        database.executebatch(batchObj);
    }
}