force-app/main/default/objects/SSP_Application__c/SSP_Application__c.object-meta.xml
<CustomObject>
    <description>To store SSP Application and Case data</description>
    <label>SSP Application</label>
    <nameField>
        
        <displayFormat>{000000000}</displayFormat>
        
        <label>SSP_Application Name</label>
        
        <type>AutoNumber</type>
        
    </nameField>
    <pluralLabel>SSP Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Application__c/fields/ProgramsApplied__c.field-meta.xml
<CustomField>
    <fullName>ProgramsApplied__c</fullName>
    <description>Used to store the list of programs applied for a household</description>
    <label>Programs Applied</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>BenefitPrograms</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/SSP_ApplicationIndividual__c.object-meta.xml
<CustomObject>
    <description>Custom junction object to maintain association between member and application</description>
    <label>SSP ApplicationIndividual</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>SSP_ApplicationIndividual Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SSP ApplicationIndividuals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/ProgramsApplied__c.field-meta.xml
<CustomField>
    <fullName>ProgramsApplied__c</fullName>
    <description>Different types of programs applied on an application for which this member is involved</description>
    <label>Application Programs Applied</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>BenefitPrograms</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/SSP_Application__c.field-meta.xml
<CustomField>
    <fullName>SSP_Application__c</fullName>
    <description>Indicates the application related to a member</description>
    <label>SSP_Application</label>
    <referenceTo>SSP_Application__c</referenceTo>
    <relationshipName>SSP_ApplicationIndividuals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/SSP_Member__c.field-meta.xml
<CustomField>
    <fullName>SSP_Member__c</fullName>
    <description>Indicates the member related to an application</description>
    <label>SSP_Member</label>
    <referenceTo>SSP_Member__c</referenceTo>
    <relationshipName>SSP_ApplicationIndividuals</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/SSP_Member__c.object-meta.xml
<CustomObject>
    <description>Stores details about an individual member of a case/application such as gatepost reponse, incarceration, disability, living arrangement, pregnancy, address details. Also repurposed to store information of different individuals in the form of individual alien, alien sponsor, care taker,  care coordinator etc.</description>
    <label>SSP Member</label>
    <nameField>
        
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        
        <label>SSP_Member Name</label>
        
        <type>Text</type>
        
    </nameField>
    <pluralLabel>SSP Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Member__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <description>This field is used to calculate the Age of a member using Date of birth</description>
    <formula>IF( NOT( ISBLANK( BirthDate__c ) ) , IF( DATE( 2000 , MONTH( BirthDate__c ) ,
 DAY( BirthDate__c ) ) &lt;= DATE( 2000 , MONTH( 
IF(ISNULL($Setup.TimeTravelSetting__c.Today__c),TODAY(),$Setup.TimeTravelSetting__c.Today__c ) ) , DAY( 
IF(ISNULL($Setup.TimeTravelSetting__c.Today__c),TODAY(),$Setup.TimeTravelSetting__c.Today__c ) ) ), YEAR (
IF(ISNULL($Setup.TimeTravelSetting__c.Today__c),TODAY(),$Setup.TimeTravelSetting__c.Today__c )) - 
YEAR ( BirthDate__c ), YEAR (
IF(ISNULL($Setup.TimeTravelSetting__c.Today__c),TODAY(),$Setup.TimeTravelSetting__c.Today__c )) - YEAR ( BirthDate__c ) -1 ), null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/IsCurrentlyEnrolledInSchoolToggle__c.field-meta.xml
<CustomField>
    <fullName>IsCurrentlyEnrolledInSchoolToggle__c</fullName>
    <description>This field is used to store if individual is currently enrolled in school</description>
    <label>Is currently enrolled in school?</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>YesNo</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/globalValueSets/BenefitPrograms.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>MA</fullName>
        
        
        <label>Medicaid/KCHIP</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>KT</fullName>
        
        
        <label>KTAP (Cash Assistance)</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SN</fullName>
        
        
        <label>SNAP (Food Assistance)</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SS</fullName>
        
        
        <label>State Supplementation</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>DS</fullName>
        
        
        <label>DSNAP</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>CC</fullName>
        
        
        <label>Child Care Assistance</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>KP</fullName>
        
        
        <label>KI-HIPP (Health Insurance Premium Payments)</label>
        
    </customValue>
    
    <description>Different type of Benefit Programs available for a Citizen</description>
    
    <masterLabel>Benefit Programs</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/globalValueSets/YesNo.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>Y</fullName>
        
        
        <label>YES</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>N</fullName>
        
        
        <label>NO</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>U</fullName>
        
        
        <label>Unknown</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>NULL</fullName>
        
        
        <label>NULL</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>H</fullName>
        
        
        <label>Historical</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>I don&apos;t know</fullName>
        
        
        <label>I don&apos;t know</label>
        
    </customValue>
    
    <description>Used to store different types of toggle picklist values</description>
    
    <masterLabel>YesNo</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/classes/SSP_EducationSummaryQueueingRule.cls
/***************************************************************************************************************************
*   Type        :   Queueing Rule
*   Name        :   SSP_EducationSummaryQueueingRule
*   Create By   :   Ajay Saini
*   Create Date :   DEC-18-2019
*   Description :   This class checks if education summary needs to be queued.
*   Modification Log:
*   --------------------------------------------------------------------------------------
*    Developer                  Date                Description
*   --------------------------------------------------------------------------------------
*    Ajay Saini             DEC-18-2019             Initial Version
*
*****************************************************************************************************************************/
public with sharing class SSP_EducationSummaryQueueingRule extends BasicNavFlowRule {
	/**
     * Invoked on workflow "next" action. If true is returned then the page will be marked as "required" in the
     * current flow and so it will be queued to be loaded on its turn. If false is returned then the page
     * will be marked as "not required" and hence will not be loaded in the flow.
     *
     * @param ctx Context object
     * @param ctxData ContextData object
     *
     * @return boolean
     */
    public override boolean isRequired(Context ctx, ContextData ctxData) {
        Boolean required = false;
        try {
            List<SSP_ApplicationIndividual__c> sspApplicationIndividualList;
            if(String.isNotBlank(ctxData.MemberId) && String.isNotBlank(ctxData.ApplicationId) && ctxData.queueObject != null){
                //required = member.IsCurrentlyEnrolledInSchoolToggle__c == SSP_GlobalConstants.YES;
                String memberId = String.escapeSingleQuotes(ctxData.MemberId);
                
                //update logic as part of defect 361239 : visverma
                SSP_ApplicationIndividual__c sspAppInd = ctxData.queueObject.memberAppIndividualMap != null ?
                    ctxData.queueObject.memberAppIndividualMap.containskey(ctxData.MemberId) ? ctxData.queueObject.memberAppIndividualMap.get(ctxData.MemberId)
                    : new SSP_ApplicationIndividual__c() : new SSP_ApplicationIndividual__c();
                /*sspApplicationIndividualList = 
                    SSP_ApplicationIndividualSelector.queryApplicationIndividualData(new Map<String, String>{'objectName'=>'SSP_ApplicationIndividual__c','operator'=>'AND'}, 
                                                                                     new Set<String>{'Id', 'SSP_Application__c', 'SSP_Member__c', 'ProgramsApplied__c', 'SSP_Member__r.AGE__c'}, 
                                                                                     new Map<String, String>{'limit'=>'100','SSP_Application__c'=> String.escapeSingleQuotes(ctxData.ApplicationId), 
                                                                                         'SSP_Member__c'=> String.escapeSingleQuotes(ctxData.MemberId)});*/
            
            //if (!sspApplicationIndividualList.isEmpty()){
                //SSP_ApplicationIndividual__c sspAppInd = sspApplicationIndividualList.get(0);
                Boolean selectedProgram = false;
                String programs = sspAppInd.ProgramsApplied__c != null ? sspAppInd.ProgramsApplied__c : '';
                List<String> programValues = programs != null && String.isNotBlank(programs) ? programs.split(';') : new list<String>();
                Integer age = sspAppInd.SSP_Member__c != null ? Integer.valueOf(sspAppInd.SSP_Member__r.AGE__c) : 0;
                
                 for(String program : programValues){
                    if(SSP_GlobalConstants.EDUCATION_SUMMARY_PROGRAMS_WITHOUT_AGE_CHECK.contains(program)){
                        required = true;
                        
                        break;                     
                    }
                    else if( SSP_GlobalConstants.EDUCATION_SUMMARY_PROGRAMS_WITH_AGE_CHECK_MA.contains(program) && age>=SSP_GlobalConstants.EDUCATION_SUMMARY_MA_AGE_MIN){
                         required = true;
                        break;
                    }
                    else if(SSP_GlobalConstants.EDUCATION_SUMMARY_PROGRAMS_WITH_AGE_CHECK_SN.contains(program) && age>=SSP_GlobalConstants.EDUCATION_SUMMARY_SN_AGE_MIN && age<SSP_GlobalConstants.EDUCATION_SUMMARY_SN_AGE_MAX){
                         required = true;
                        break;
                    }
                    
                }
                
            }
        }
        catch (Exception e) {
            LOG_LogMessageUtility.logMessage(e, 'SSP_EducationSummaryQueueingRule', 'isRequired', e.getMessage() , true);
        }
        return required;
    }
}