force-app/main/default/objects/SSP_Application__c/SSP_Application__c.object-meta.xml
<CustomObject>
    <description>To store SSP Application and Case data</description>
    <label>SSP Application</label>
    <nameField>
        
        <displayFormat>{000000000}</displayFormat>
        
        <label>SSP_Application Name</label>
        
        <type>AutoNumber</type>
        
    </nameField>
    <pluralLabel>SSP Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Application__c/fields/ProgramsApplied__c.field-meta.xml
<CustomField>
    <fullName>ProgramsApplied__c</fullName>
    <description>Used to store the list of programs applied for a household</description>
    <label>Programs Applied</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>BenefitPrograms</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/SSP_ApplicationIndividual__c.object-meta.xml
<CustomObject>
    <description>Custom junction object to maintain association between member and application</description>
    <label>SSP ApplicationIndividual</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>SSP_ApplicationIndividual Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SSP ApplicationIndividuals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/CareCoordinatorAddressLine1__c.field-meta.xml
<CustomField>
    <fullName>CareCoordinatorAddressLine1__c</fullName>
    <description>Care Coordinator Address Line 1 used in CIS</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Care Coordinator Address Line 1</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/CareCoordinatorAddressLine2__c.field-meta.xml
<CustomField>
    <fullName>CareCoordinatorAddressLine2__c</fullName>
    <description>Care Coordinator Address Line 2 used in CIS</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Care Coordinator Address Line 2</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/CareCoordinatorCity__c.field-meta.xml
<CustomField>
    <fullName>CareCoordinatorCity__c</fullName>
    <description>Care Coordinator City used in CIS</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Care Coordinator City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/CareCoordinatorCountyCode__c.field-meta.xml
<CustomField>
    <fullName>CareCoordinatorCountyCode__c</fullName>
    <description>Care Coordinator County Code used in CIS</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Care Coordinator County Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/CareCoordinatorName__c.field-meta.xml
<CustomField>
    <fullName>CareCoordinatorName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Care Coordinator Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/CareCoordinatorRelationship__c.field-meta.xml
<CustomField>
    <fullName>CareCoordinatorRelationship__c</fullName>
    <description>Used for CIS</description>
    <label>Care Coordinator Relationship</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetDefinition>
            
                <sorted>true</sorted>
            
                <value>
                
                    <fullName>CC</fullName>
                
                
                    <label>Care Coordinator</label>
                
                </value>
            
                <value>
                
                    <fullName>FM</fullName>
                
                
                    <label>Family Member</label>
                
                </value>
            
                <value>
                
                    <fullName>NF</fullName>
                
                
                    <label>Nursing Facility</label>
                
                </value>
            
                <value>
                
                    <fullName>OC</fullName>
                
                
                    <label>Other Caregiver</label>
                
                </value>
            
                <value>
                
                    <fullName>P</fullName>
                
                
                    <label>Provider</label>
                
                </value>
            
                <value>
                
                    <fullName>R</fullName>
                
                
                    <label>Relative</label>
                
                </value>
            
                <value>
                
                    <fullName>SL</fullName>
                
                
                    <label>Self</label>
                
                </value>
            
            </valueSetDefinition>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/CareCoordinatorStateCode__c.field-meta.xml
<CustomField>
    <fullName>CareCoordinatorStateCode__c</fullName>
    <description>Care Coordinator StateCode used in CIS</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Care Coordinator State Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/CareCoordinatorZipcode4__c.field-meta.xml
<CustomField>
    <fullName>CareCoordinatorZipcode4__c</fullName>
    <description>Care Coordinator Zipcode 4 used in CIS</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Care Coordinator Zipcode 4</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/CareCoordinatorZipcode5__c.field-meta.xml
<CustomField>
    <fullName>CareCoordinatorZipcode5__c</fullName>
    <description>Care Coordinator Zipcode 5 used in CIS</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Care Coordinator Zipcode 5</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/CaretakerName__c.field-meta.xml
<CustomField>
    <fullName>CaretakerName__c</fullName>
    <description>Used for Caretake service</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Caretaker Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/CaretakerPhone__c.field-meta.xml
<CustomField>
    <fullName>CaretakerPhone__c</fullName>
    <description>Used for Caretaker services</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Caretaker Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/CaretakerRelation__c.field-meta.xml
<CustomField>
    <fullName>CaretakerRelation__c</fullName>
    <description>Used to denote Caretaker Relationship</description>
    <label>Caretaker Relation</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetDefinition>
            
                <sorted>true</sorted>
            
                <value>
                
                    <fullName>CH</fullName>
                
                
                    <label>Child</label>
                
                </value>
            
                <value>
                
                    <fullName>NR</fullName>
                
                
                    <label>Not Related</label>
                
                </value>
            
                <value>
                
                    <fullName>OR</fullName>
                
                
                    <label>Other Relative</label>
                
                </value>
            
                <value>
                
                    <fullName>PA</fullName>
                
                
                    <label>Parent</label>
                
                </value>
            
                <value>
                
                    <fullName>SP</fullName>
                
                
                    <label>Spouse</label>
                
                </value>
            
            </valueSetDefinition>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/CISEndDate__c.field-meta.xml
<CustomField>
    <fullName>CISEndDate__c</fullName>
    <description>Used for CIS</description>
    <encryptionScheme>None</encryptionScheme>
    <label>CIS End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/CISStartDate__c.field-meta.xml
<CustomField>
    <fullName>CISStartDate__c</fullName>
    <description>Used for CIS</description>
    <encryptionScheme>None</encryptionScheme>
    <label>CIS Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/IsCaretakerLivingTogetherToggle__c.field-meta.xml
<CustomField>
    <fullName>IsCaretakerLivingTogetherToggle__c</fullName>
    <description>Used for Caretaker service</description>
    <label>Is Caretaker Living Together</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>YesNo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/IsHeadOfHousehold__c.field-meta.xml
<CustomField>
    <fullName>IsHeadOfHousehold__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to determine if the member is Head of Household</description>
    <label>Is Head Of Household</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/IsPreventedNursingFacilityToggle__c.field-meta.xml
<CustomField>
    <fullName>IsPreventedNursingFacilityToggle__c</fullName>
    <description>Used for Caretaker service</description>
    <label>Is Prevented Nursing Facility</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>YesNo</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/IsServiceProvidedSafelyToggle__c.field-meta.xml
<CustomField>
    <fullName>IsServiceProvidedSafelyToggle__c</fullName>
    <description>Used for caretaker service</description>
    <label>Is Service Provided Safely</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>YesNo</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/IsServiceReceivedRegularlyToggle__c.field-meta.xml
<CustomField>
    <fullName>IsServiceReceivedRegularlyToggle__c</fullName>
    <description>Is used for Caretaker service</description>
    <label>Is Service Received Regularly</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>YesNo</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/IsServiceStoppingInstitutalizationToggle__c.field-meta.xml
<CustomField>
    <fullName>IsServiceStoppingInstitutalizationToggle__c</fullName>
    <description>Used for CIS</description>
    <label>Is Service Stopping Institutalization</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>YesNo</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/MentalIllnessImpairsFunctioningToggle__c.field-meta.xml
<CustomField>
    <fullName>MentalIllnessImpairsFunctioningToggle__c</fullName>
    <description>Used for CIS</description>
    <label>Mental Illness Impairs Functioning</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>YesNo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/MentalIllnessNeedsTreatmentToggle__c.field-meta.xml
<CustomField>
    <fullName>MentalIllnessNeedsTreatmentToggle__c</fullName>
    <description>Used for CIS</description>
    <label>Mental Illness Needs Treatment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>YesNo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/MentalIllnessWithoutAlzheimersToggle__c.field-meta.xml
<CustomField>
    <fullName>MentalIllnessWithoutAlzheimersToggle__c</fullName>
    <description>Used for CIS</description>
    <label>Mental Illness Without Alzheimers</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>YesNo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/ProgramsApplied__c.field-meta.xml
<CustomField>
    <fullName>ProgramsApplied__c</fullName>
    <description>Different types of programs applied on an application for which this member is involved</description>
    <label>Application Programs Applied</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>BenefitPrograms</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/ServiceEndDate__c.field-meta.xml
<CustomField>
    <fullName>ServiceEndDate__c</fullName>
    <description>This is used as Service End Date for Caretaker Service</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Service End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/ServiceStartDate__c.field-meta.xml
<CustomField>
    <fullName>ServiceStartDate__c</fullName>
    <description>This field is for Service Start Date of Caretaker</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Service Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/SSP_Application__c.field-meta.xml
<CustomField>
    <fullName>SSP_Application__c</fullName>
    <description>Indicates the application related to a member</description>
    <label>SSP_Application</label>
    <referenceTo>SSP_Application__c</referenceTo>
    <relationshipName>SSP_ApplicationIndividuals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/BenefitPrograms.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>MA</fullName>
        
        
        <label>Medicaid/KCHIP</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>KT</fullName>
        
        
        <label>KTAP (Cash Assistance)</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SN</fullName>
        
        
        <label>SNAP (Food Assistance)</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SS</fullName>
        
        
        <label>State Supplementation</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>DS</fullName>
        
        
        <label>DSNAP</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>CC</fullName>
        
        
        <label>Child Care Assistance</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>KP</fullName>
        
        
        <label>KI-HIPP (Health Insurance Premium Payments)</label>
        
    </customValue>
    
    <description>Different type of Benefit Programs available for a Citizen</description>
    
    <masterLabel>Benefit Programs</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/globalValueSets/YesNo.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>Y</fullName>
        
        
        <label>YES</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>N</fullName>
        
        
        <label>NO</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>U</fullName>
        
        
        <label>Unknown</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>NULL</fullName>
        
        
        <label>NULL</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>H</fullName>
        
        
        <label>Historical</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>I don&apos;t know</fullName>
        
        
        <label>I don&apos;t know</label>
        
    </customValue>
    
    <description>Used to store different types of toggle picklist values</description>
    
    <masterLabel>YesNo</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/classes/SSP_CISCareTakerController.cls
/*
* classname     :  SSP_CISCareTakerController
* @description  :  Controller Method for sspCas=reTakerServices
* @author       :  Shrikant Raut   
* @date         :  04/09/2020
* MODIFICATION LOG: 
* DEVELOPER                     DATE                               DESCRIPTION
* ---------------------------------------------------------------------------------------------

**/
public class SSP_CISCareTakerController {
    /***************************************************************************************************
* @author       Shrikant Raut
* @date         04/09/2020
* @methodname   fetchRequiredData
* @description  This methods is used to fetch required Member and Application related data.
* @return       SSP_LightningResponse
*****************************************************************************************************/
    @auraEnabled
    public static SSP_LightningResponse fetchRequiredData(Id sspApplicationId, String sspMemberId, String callingComponent){       
        SSP_Utility.isAuthenticatedUser(); //Iron Dome fix         
        SSP_LightningResponse response = new SSP_LightningResponse();
        String screenId;
        List<SSP_ApplicationIndividual__c> appIndvList = new List<SSP_ApplicationIndividual__c>();  
        Map<String, String> detailMap = new Map<String, String>{SSP_GlobalConstants.SSP_OBJECT_NAME => SSP_GlobalConstants.OBJ_APPLICATION_INDIVIDUAL,
            SSP_GlobalConstants.SSP_OPERATOR => SSP_GlobalConstants.OPERATOR_AND};
                //adding common fields to be queried
                Set<String> fieldSet = new Set<String>{'Id','SSP_Application__r.ProgramsApplied__c','ProgramsApplied__c','IsHeadOfHousehold__c'}; 
                    Map<String, String> conditionMap = new Map<String, String>{SSP_GlobalConstants.KEY_LIMIT=>'100'};
                        try {
                            SSP_Utility.setProgramPermissions();
                            if(sspApplicationId != null && sspMemberId != null){
                                conditionMap.put(SSP_GlobalConstants.OBJ_MEMBER, sspMemberId);
                                conditionMap.put(SSP_GlobalConstants.OBJ_APPLICATION, sspApplicationId);
                                
                                //adding fields to query for sspCareTakerServices lwc cmp
                                if(callingComponent != null && callingComponent.equals(SSP_GlobalConstants.CARE_TAKER_SERVICES)){
                                    screenId = SSP_GlobalConstants.CARETAKER_SERVICES_SCREENID;
                                    fieldSet.addAll(new Set<String>{'ServiceStartDate__c','ServiceEndDate__c','IsServiceProvidedSafelyToggle__c','IsPreventedNursingFacilityToggle__c','IsServiceReceivedRegularlyToggle__c','CaretakerRelation__c','IsCaretakerLivingTogetherToggle__c','CaretakerName__c','CaretakerPhone__c'});
                                    response.put(SSP_GlobalConstants.KEY_CARE_TAKER_RELATIONS,SSP_Utility.getPickListValues(SSP_GlobalConstants.OBJ_APPLICATION_INDIVIDUAL, 'CaretakerRelation__c', null));
                                }
                                
                                //place holder for adding CIS related fields
                                if(callingComponent != null && callingComponent.equals(SSP_GlobalConstants.CIS)){
                                    screenId = SSP_GlobalConstants.CIS_SCREENID;
                                    
                                    fieldSet.addAll(new Set<String>{'CISStartDate__c','CISEndDate__c','MentalIllnessImpairsFunctioningToggle__c','MentalIllnessNeedsTreatmentToggle__c','MentalIllnessWithoutAlzheimersToggle__c','IsServiceStoppingInstitutalizationToggle__c','CareCoordinatorRelationship__c','CareCoordinatorName__c','CareCoordinatorAddressLine1__c','CareCoordinatorCity__c','CareCoordinatorStateCode__c','CareCoordinatorZipcode4__c','CareCoordinatorZipcode5__c','CareCoordinatorCountyCode__c','CareCoordinatorAddressLine2__c','CareCoordinatorPhoneNumber__c'});
                                    response.put(SSP_GlobalConstants.KEY_CIS_RELATIONS,SSP_Utility.getPickListValues(SSP_GlobalConstants.OBJ_APPLICATION_INDIVIDUAL, 'CareCoordinatorRelationship__c', null));
                                }
                                
                                if(fieldSet.contains('')){
                                    fieldSet.remove('');
                                }
                                
                                appIndvList = SSP_ApplicationIndividualSelector.queryApplicationIndividualData(detailMap, fieldSet, conditionMap);  
                                response.put(SSP_GlobalConstants.KEY_APP_INDVS,appIndvList);
                                response.put(SSP_GlobalConstants.KEY_ACCESS_DETAILS,SSP_Utility.getScreenAccessDetails(screenId, null));//DCBS (View Only)
                                response.put(SSP_GlobalConstants.KEY_ACCESSIBLE_PROGRAMS,SSP_Utility.getAvailableProgramsByRole());
                                
                                response.bIsSuccess = true;
                            }
                        }
        catch(Exception ex){
            List<LOG_LogMessage__c> lstLogMessages = LOG_LogMessageUtility.logMessage(ex, 'SSP_CISCareTakerController', 'fetchRequiredData', ex.getMessage(), true);
            response.addException(ex, lstLogMessages[0].Id);            
        }
        return response;
    }
    
    
    /***************************************************************************************************
* @author       Shrikant Raut
* @date         04/14/2019
* @methodname   updateRecord
* @description  This methods is used to update SSP_ApplicationIndividual__c records
* @return       SSP_LightningResponse
*****************************************************************************************************/    
    @auraEnabled
    public static SSP_LightningResponse updateApplicationIndividuals(String serializedJSON){
        SSP_Utility.isAuthenticatedUser(); //Iron Dome fix
        SSP_LightningResponse response = new SSP_LightningResponse();
        try{
            
            if(serializedJSON != null && Schema.sObjectType.SSP_ApplicationIndividual__c.isUpdateable()){
                List<SSP_ApplicationIndividual__c> appIndividualList = (List<SSP_ApplicationIndividual__c>)JSON.deserialize(serializedJSON, List<SSP_ApplicationIndividual__c>.class);
                response.bIsSuccess = ESAPI.accessController().updateAsUser(new Map<ID, SSP_ApplicationIndividual__c>(appIndividualList), SSP_Utility.getFieldsNamesList (appIndividualList)).wasSuccessful();
            }
        }
        catch(Exception ex){
            List<LOG_LogMessage__c> lstLogMessages = LOG_LogMessageUtility.logMessage(ex, 'SSP_CISCareTakerController', 'updateRecord', ex.getMessage(), true);
            response.addException(ex, lstLogMessages[0].Id);            
        }
        return response;
        
    }
}