force-app/main/default/objects/SSP_Application__c/SSP_Application__c.object-meta.xml
<CustomObject>
    <description>To store SSP Application and Case data</description>
    <label>SSP Application</label>
    <nameField>
        
        <displayFormat>{000000000}</displayFormat>
        
        <label>SSP_Application Name</label>
        
        <type>AutoNumber</type>
        
    </nameField>
    <pluralLabel>SSP Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Benefits__c/SSP_Benefits__c.object-meta.xml
<CustomObject>
    <description>Stores benefit details such as household, individual, out of state, SSI benefits etc.</description>
    <label>SSP Benefits</label>
    <nameField>
        
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        
        <label>SSP_Benefits Name</label>
        
        <type>Text</type>
        
    </nameField>
    <pluralLabel>SSP Benefits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Benefits__c/fields/DCId__c.field-meta.xml
<CustomField>
    <fullName>DCId__c</fullName>
    <description>Used to store the generic DC ids from .NET Table</description>
    <externalId>true</externalId>
    <label>DC Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SSP_Benefits__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <description>This field is used to store End date for which benefits are removed for a member</description>
    <encryptionScheme>None</encryptionScheme>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SSP_Benefits__c/fields/HasMedicareCoverageButNoInfo__c.field-meta.xml
<CustomField>
    <fullName>HasMedicareCoverageButNoInfo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to indicate the flag when there is a medical coverage but no information</description>
    <label>Has Medicare Coverage But No Info</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SSP_Benefits__c/fields/MedicareTypeCode__c.field-meta.xml
<CustomField>
    <fullName>MedicareTypeCode__c</fullName>
    <description>This field is used to store Medicare type code</description>
    <label>Medicare Type Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MedicareTypeCode</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Benefits__c/fields/SSP_Member__c.field-meta.xml
<CustomField>
    <fullName>SSP_Member__c</fullName>
    <description>This field is used to indicate the member for a particular Benefit record</description>
    <label>SSP_Member</label>
    <referenceTo>SSP_Member__c</referenceTo>
    <relationshipName>SSP_Benefits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_Benefits__c/recordTypes/MedicareBenefit.recordType-meta.xml
<RecordType>
    <fullName>MedicareBenefit</fullName>
    <active>true</active>
    <description>Record type for Medicare Coverage Summary and details</description>
    <label>MedicareBenefit</label>
</RecordType>

force-app/main/default/objects/SSP_Member__c/SSP_Member__c.object-meta.xml
<CustomObject>
    <description>Stores details about an individual member of a case/application such as gatepost reponse, incarceration, disability, living arrangement, pregnancy, address details. Also repurposed to store information of different individuals in the form of individual alien, alien sponsor, care taker,  care coordinator etc.</description>
    <label>SSP Member</label>
    <nameField>
        
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        
        <label>SSP_Member Name</label>
        
        <type>Text</type>
        
    </nameField>
    <pluralLabel>SSP Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Member__c/fields/DCId__c.field-meta.xml
<CustomField>
    <fullName>DCId__c</fullName>
    <description>This field used to store the unique member DC Id to identify for an external system</description>
    <externalId>true</externalId>
    <label>DCId</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>This field is used to store Firstname on a Member</description>
    <encryptionScheme>None</encryptionScheme>
    <label>FirstName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/IsReceivingMedicareBenefitToggle__c.field-meta.xml
<CustomField>
    <fullName>IsReceivingMedicareBenefitToggle__c</fullName>
    <description>This field is used to determine if an individual has received medicare benefits.</description>
    <label>Is Receiving Medicare Benefits ?</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>YesNo</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <description>This field is used to store Lastname of a member</description>
    <encryptionScheme>None</encryptionScheme>
    <label>LastName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_TrackDeletion__c/SSP_TrackDeletion__c.object-meta.xml
<CustomObject>
    <description>Stores details of entities deleted by an individual on a case</description>
    <label>SSP TrackDeletion</label>
    <nameField>
        
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        
        <label>SSP_TrackDeletion Name</label>
        
        <type>Text</type>
        
    </nameField>
    <pluralLabel>SSP TrackDeletions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_TrackDeletion__c/fields/DCId__c.field-meta.xml
<CustomField>
    <fullName>DCId__c</fullName>
    <description>This field is used to store DC Id of deleted record.</description>
    <externalId>true</externalId>
    <label>DC Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SSP_TrackDeletion__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <description>This field is used to store End Date.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SSP_TrackDeletion__c/fields/EndReason__c.field-meta.xml
<CustomField>
    <fullName>EndReason__c</fullName>
    <description>This field is used to store reason for removal.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>End Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_TrackDeletion__c/fields/OtherReason__c.field-meta.xml
<CustomField>
    <fullName>OtherReason__c</fullName>
    <description>This field is used to capture reason if Other is selected.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Other Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_TrackDeletion__c/fields/ParentDCId__c.field-meta.xml
<CustomField>
    <fullName>ParentDCId__c</fullName>
    <description>If the record deleted is a child record, this field will be used to store DC Id of Parent record.</description>
    <externalId>true</externalId>
    <label>Parent DC Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SSP_TrackDeletion__c/fields/SalesforceId__c.field-meta.xml
<CustomField>
    <fullName>SalesforceId__c</fullName>
    <description>This field is used to capture Salesforce Id of record deleted.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Salesforce Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_TrackDeletion__c/fields/SFObject__c.field-meta.xml
<CustomField>
    <fullName>SFObject__c</fullName>
    <description>object name whose record is being deleted</description>
    <encryptionScheme>None</encryptionScheme>
    <label>SF Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_TrackDeletion__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>This field is used to capture the screen name from where track deletion record was created.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_TrackDeletion__c/fields/SSP_Application__c.field-meta.xml
<CustomField>
    <fullName>SSP_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to indicate the related application for Track deletion record</description>
    <label>SSP_Application</label>
    <referenceTo>SSP_Application__c</referenceTo>
    <relationshipName>SSP_TrackDeletions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SSP_TrackDeletion__c/fields/SSP_Member__c.field-meta.xml
<CustomField>
    <fullName>SSP_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to indicate the related member for Track deletion record</description>
    <label>SSP_Member</label>
    <referenceTo>SSP_Member__c</referenceTo>
    <relationshipName>SSP_TrackDeletions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/MedicareTypeCode.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>PA</fullName>
        
        
        <label>Medicare Part A</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>PB</fullName>
        
        
        <label>Medicare Part B</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>MD</fullName>
        
        
        <label>CONDITIONAL ENROLLMENT IN MEDICARE PART A</label>
        
    </customValue>
    
    <description>Medicare Types</description>
    
    <masterLabel>Medicare Type Code</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/globalValueSets/YesNo.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>Y</fullName>
        
        
        <label>YES</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>N</fullName>
        
        
        <label>NO</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>U</fullName>
        
        
        <label>Unknown</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>NULL</fullName>
        
        
        <label>NULL</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>H</fullName>
        
        
        <label>Historical</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>I don&apos;t know</fullName>
        
        
        <label>I don&apos;t know</label>
        
    </customValue>
    
    <description>Used to store different types of toggle picklist values</description>
    
    <masterLabel>YesNo</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/classes/SSP_MedicareCoverageSummary.cls
/*
* classname     :  SSP_MedicareCoverageSummary
* @description  :  Class to get medical coverage summary
* @author       :  Varun Kochar   
* @date         :  04/02/2020
* MODIFICATION LOG:
* DEVELOPER                     DATE                               DESCRIPTION
* ---------------------------------------------------------------------------------------------

**/
public class SSP_MedicareCoverageSummary {
    
    /***************************************************************************************************
* @author       Varun Kochar
* @date         04/02/2020
* @methodname   getMedicalCoverageSummary
* @description  This methods is used to get medical coverage summary
* @return       
*****************************************************************************************************/
    @auraEnabled
    public static SSP_LightningResponse getMedicalCoverageSummary(Id memberId){
        try{
            SSP_Utility.isAuthenticatedUser();
            SSP_LightningResponse objResponse = new SSP_LightningResponse();
            List<MedicareCoverageSummaryWrapper> wrapper = new List<MedicareCoverageSummaryWrapper>();
            List<SSP_Benefits__c> sspBenefitList = SSP_MedicareCoverageService.getBenefit(new Set<String>{memberId});
            Map<String, String> medicareTypeMap = SSP_MedicareCoverageService.getMedicareTypeMap();
            List<SSP_Member__c> memberList = SSP_MedicareCoverageService.getMember(new Set<String>{memberId});
            String benefitRecordtypeId = Schema.SObjectType.SSP_Benefits__c.getRecordTypeInfosByDeveloperName().get(SSP_GlobalConstants.MEDICAREBENEFIT).getRecordTypeId();
            
            if(!sspBenefitList.isEmpty()){
                for(SSP_Benefits__c benefitObj : sspBenefitList){
                    Boolean displayEdit = String.isNotBlank(benefitObj.MedicareTypeCode__c) || benefitObj.HasMedicareCoverageButNoInfo__c ? true : false;
                    String memberName = benefitObj.SSP_Member__r.FirstName__c + ' ' + benefitObj.SSP_Member__r.LastName__c;
                    String medicareType = String.isNotBlank(benefitObj.MedicareTypeCode__c) ? medicareTypeMap.get(benefitObj.MedicareTypeCode__c) : Label.SSP_MedicareCoverageLabel ;
                    
                    String editButtonAltText = displayEdit ? String.format(Label.SSP_EditCoverageButtonAltText, new List<String>{medicareType}) : Label.SSP_StartCoverageButtonTitle;
                    String removeButtonAltText = String.format(Label.SSP_RemoveCoverageAltText, new List<String>{medicareType});
                    String viewButtonAltText = String.format(Label.SSP_ViewDetails, new List<String>{medicareType});
                    wrapper.add(new MedicareCoverageSummaryWrapper(benefitObj, false, displayEdit, memberName, medicareType, editButtonAltText, removeButtonAltText, '',viewButtonAltText));
                }
            }
            else{
                if(memberList.size()>0 && memberList[0].IsReceivingMedicareBenefitToggle__c== SSP_GlobalConstants.YES){
                SSP_Benefits__c benefitObj = new SSP_Benefits__c(SSP_Member__c = memberList[0].id , RecordtypeId = benefitRecordtypeId);               
                String memberName =memberList[0].FirstName__c + ' ' + memberList[0].LastName__c;
                SSP_MedicareCoverageDetails.saveMedicalCoverageDetail(benefitObj,memberList[0].id);
                String editButtonAltText = Label.SSP_StartCoverageButtonTitle;
                String removeButtonAltText = String.format(Label.SSP_RemoveCoverageAltText, new List<String>{Label.SSP_MedicareCoverageLabel});
                String viewButtonAltText = String.format(Label.SSP_ViewDetails, new List<String>{Label.SSP_MedicareCoverageLabel});
                wrapper.add(new MedicareCoverageSummaryWrapper(benefitObj, false, false, memberName, Label.SSP_MedicareCoverageLabel, editButtonAltText, removeButtonAltText, '',viewButtonAltText));
            	}
            }           
             objResponse.put('wrapper', wrapper);
           
            /** 2.5	Security Role Matrix and Program Access. */
            objResponse.put(SSP_GlobalConstants.SECURITY_MATRIX_SUMMARY, SSP_Utility.getScreenAccessDetails(SSP_GlobalConstants.MEDICARE_COVERAGE_SUMMARY_SCREENID, null));
            objResponse.put(SSP_GlobalConstants.SECURITY_MATRIX_DETAILS, SSP_Utility.getScreenAccessDetails(SSP_GlobalConstants.MEDICARE_COVERAGE_DETAILS_SCREENID, null));
            /** */
            
            return objResponse;
        }catch(Exception e){
            LOG_LogMessageUtility.logMessage(e, 'SSP_MedicareCoverageSummary', 'getMedicalCoverageSummary', e.getMessage(), true);
        }
        return null;
    }
    /***************************************************************************************************
* @author       Varun Kochar
* @date         04/02/2020
* @methodname   removeBenefit
* @description  This methods is used to remove SSP Benefit
* @return       
*****************************************************************************************************/
    @auraEnabled
    public static void removeBenefit(String wrapper ,String memberId , String applicationId){
        try{
            SSP_Utility.isAuthenticatedUser();
            MedicareCoverageSummaryWrapper response = (MedicareCoverageSummaryWrapper)JSON.deserialize(wrapper, MedicareCoverageSummaryWrapper.class);
            List<String> lstTrackDeletionFields = new List<String>{'SSP_Application__c','DCId__c','EndDate__c','EndReason__c','SSP_Member__c','OtherReason__c','ParentDCId__c','SalesforceId__c','Source__c', 'SFObject__c'};
            Boolean bViewTrackDeletionFields = ESAPI.accessController().isAuthorizedToView(SSP_TrackDeletion__c.getSObjectType(), lstTrackDeletionFields);
           // create track deletion record added as part of 372394
             List<SSP_TrackDeletion__c> trackDelRecList = new List<SSP_TrackDeletion__c>();
            SSP_Benefits__c benefitDetails = [select id , DCId__c  from SSP_Benefits__c where id= :response.benefit.id ];
           if(benefitDetails.DCId__c!=null){
               SSP_TrackDeletion__c trackDelRec = new  SSP_TrackDeletion__c();
               trackDelRec.DCId__c= benefitDetails.DCId__c;
               trackDelRec.Source__c='MedicareCoverage';
               trackDelRec.SSP_Application__c=applicationId;
               trackDelRec.SSP_Member__c= response.benefit.SSP_Member__c;
               trackDelRec.SalesforceId__c=  response.benefit.Id;
               trackDelRec.SFObject__c='SSP_Benefits__c';                        
               trackDelRecList.add(trackDelRec);
               if(null!=trackDelRecList && trackDelRecList.size()>0)
                   ESAPI.accessController().insertAsUser(trackDelRecList, lstTrackDeletionFields);            
               response.benefit.IsDeleted__c = true;
               update response.benefit;
           }
            else {
            delete response.benefit;
            }            
            Set<String> membersSet = new  Set<String>{memberId};
            List<SSP_Member__c> members = SSP_MedicareCoverageService.getMember(membersSet);
            List<SSP_Benefits__c> benefitsForMember =SSP_MedicareCoverageService.getBenefit(membersSet);
            if(benefitsForMember.size() == 0){
                if(members!=null && members.size()>0){
                   members[0].IsReceivingMedicareBenefitToggle__c= SSP_GlobalConstants.NO;
                    update members[0];
                }
            }
        }catch(Exception e){
            LOG_LogMessageUtility.logMessage(e, 'SSP_MedicareCoverageSummary', 'removeBenefit', e.getMessage(), true);
        }
    }
    public class MedicareCoverageSummaryWrapper{
        @AuraEnabled public SSP_Benefits__c benefit;
        @AuraEnabled public Boolean removeBenefit;
        @AuraEnabled public Boolean displayEdit;
        @AuraEnabled public String memberName;
        @AuraEnabled public String medicareType;
        @AuraEnabled public String editButtonAltText;
        @AuraEnabled public String removeButtonAltText;
        @AuraEnabled public String formattedBeginDate;
        @AuraEnabled public String viewButtonAltText;
        public MedicareCoverageSummaryWrapper(SSP_Benefits__c benefit, Boolean removeBenefit, Boolean displayEdit, String memberName, String medicareType, String editButtonAltText, String removeButtonAltText, String formattedBeginDate,String viewButtonAltText){
            this.benefit = benefit;
            this.removeBenefit = removeBenefit;
            this.displayEdit = displayEdit;
            this.memberName = memberName;
            this.medicareType = medicareType;
            this.editButtonAltText = editButtonAltText;
            this.removeButtonAltText = removeButtonAltText;
            this.formattedBeginDate = formattedBeginDate;
            this.viewButtonAltText=viewButtonAltText;
        }
    }
}