force-app/main/default/objects/SSP_Application__c/SSP_Application__c.object-meta.xml
<CustomObject>
    <description>To store SSP Application and Case data</description>
    <label>SSP Application</label>
    <nameField>
        
        <displayFormat>{000000000}</displayFormat>
        
        <label>SSP_Application Name</label>
        
        <type>AutoNumber</type>
        
    </nameField>
    <pluralLabel>SSP Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Application__c/fields/HasConvictedCrimeToggle__c.field-meta.xml
<CustomField>
    <fullName>HasConvictedCrimeToggle__c</fullName>
    <description>This field is used to store if anyone in household is convicted to crime?</description>
    <label>Has convicted crime</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>YesNo</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Application__c/fields/ProgramsApplied__c.field-meta.xml
<CustomField>
    <fullName>ProgramsApplied__c</fullName>
    <description>Used to store the list of programs applied for a household</description>
    <label>Programs Applied</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>BenefitPrograms</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/SSP_ApplicationIndividual__c.object-meta.xml
<CustomObject>
    <description>Custom junction object to maintain association between member and application</description>
    <label>SSP ApplicationIndividual</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>SSP_ApplicationIndividual Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SSP ApplicationIndividuals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/IsHeadOfHousehold__c.field-meta.xml
<CustomField>
    <fullName>IsHeadOfHousehold__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to determine if the member is Head of Household</description>
    <label>Is Head Of Household</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/MemberStatus__c.field-meta.xml
<CustomField>
    <fullName>MemberStatus__c</fullName>
    <description>This field is used to determine the status of member</description>
    <label>Member Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Edited</fullName>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/ProgramsApplied__c.field-meta.xml
<CustomField>
    <fullName>ProgramsApplied__c</fullName>
    <description>Different types of programs applied on an application for which this member is involved</description>
    <label>Application Programs Applied</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>BenefitPrograms</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/SSP_Application__c.field-meta.xml
<CustomField>
    <fullName>SSP_Application__c</fullName>
    <description>Indicates the application related to a member</description>
    <label>SSP_Application</label>
    <referenceTo>SSP_Application__c</referenceTo>
    <relationshipName>SSP_ApplicationIndividuals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/SSP_Member__c.field-meta.xml
<CustomField>
    <fullName>SSP_Member__c</fullName>
    <description>Indicates the member related to an application</description>
    <label>SSP_Member</label>
    <referenceTo>SSP_Member__c</referenceTo>
    <relationshipName>SSP_ApplicationIndividuals</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/SSP_Member__c.object-meta.xml
<CustomObject>
    <description>Stores details about an individual member of a case/application such as gatepost reponse, incarceration, disability, living arrangement, pregnancy, address details. Also repurposed to store information of different individuals in the form of individual alien, alien sponsor, care taker,  care coordinator etc.</description>
    <label>SSP Member</label>
    <nameField>
        
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        
        <label>SSP_Member Name</label>
        
        <type>Text</type>
        
    </nameField>
    <pluralLabel>SSP Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Member__c/fields/IsHeadOfHousehold__c.field-meta.xml
<CustomField>
    <fullName>IsHeadOfHousehold__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Head Of Household</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/BenefitPrograms.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>MA</fullName>
        
        
        <label>Medicaid/KCHIP</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>KT</fullName>
        
        
        <label>KTAP (Cash Assistance)</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SN</fullName>
        
        
        <label>SNAP (Food Assistance)</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SS</fullName>
        
        
        <label>State Supplementation</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>DS</fullName>
        
        
        <label>DSNAP</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>CC</fullName>
        
        
        <label>Child Care Assistance</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>KP</fullName>
        
        
        <label>KI-HIPP (Health Insurance Premium Payments)</label>
        
    </customValue>
    
    <description>Different type of Benefit Programs available for a Citizen</description>
    
    <masterLabel>Benefit Programs</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/globalValueSets/YesNo.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>Y</fullName>
        
        
        <label>YES</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>N</fullName>
        
        
        <label>NO</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>U</fullName>
        
        
        <label>Unknown</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>NULL</fullName>
        
        
        <label>NULL</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>H</fullName>
        
        
        <label>Historical</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>I don&apos;t know</fullName>
        
        
        <label>I don&apos;t know</label>
        
    </customValue>
    
    <description>Used to store different types of toggle picklist values</description>
    
    <masterLabel>YesNo</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/classes/SSP_ConvictionQueueingRule.cls
/***************************************************************************************************************************
*   Type        :   Queueing Rule
*   Name        :   SSP_ConvictionQueueingRule
*   Create By   :   Samridh Manucha
*   Create Date :   JAN-21-2020
*   Description :   This class checks conviction Screen needs to be queued.
*   Modification Log:
*   --------------------------------------------------------------------------------------
*    Developer                  Date                    Description
*   --------------------------------------------------------------------------------------
*    Samridh Manucha           JAN-21-2020             Initial Version
*
*****************************************************************************************************************************/
public with sharing class SSP_ConvictionQueueingRule extends BasicNavFlowRule {
    
    /**
     * Invoked on workflow "next" action. If true is returned then the page will be marked as "required" in the
     * current flow and so it will be queued to be loaded on its turn. If false is returned then the page
     * will be marked as "not required" and hence will not be loaded in the flow.
     *
     * @param ctx Context object
     * @param ctxData ContextData object
     *
     * @return boolean
     */
     
    public override boolean isRequired(Context ctx, ContextData ctxData) {
        Boolean hasConvictedCrime = false;
        try {            
            if(ctxData.ApplicationId != null && ctxData.MemberId != null && ctxData.queueObject != null){
                SSP_ApplicationIndividual__c appIndividualRecord = ctxData.queueObject.memberAppIndividualMap.get(ctxData.MemberId);
                List<String> selectedProgramList = appIndividualRecord != null ? appIndividualRecord.ProgramsApplied__c.split(';') : new List<String>();
                Set<String> evaluatingSet = SSP_GlobalConstants.CONVICTION_PROGRAMS;
                Boolean programCheck = SSP_Utility.checkApplicablePrograms(selectedProgramList, evaluatingSet);
                hasConvictedCrime = appIndividualRecord != null && appIndividualRecord.SSP_Application__r.HasConvictedCrimeToggle__c == SSP_GlobalConstants.YES &&
                         appIndividualRecord.IsHeadOfHousehold__c == true && programCheck;                         
            }            
            /*Boolean selectedProgram;
            List<SSP_ApplicationIndividual__c> applicationIndividual = //SSP_ApplicationIndividualSelector.queryApplicationIndividualMemberData(memberId, fields);
                SSP_ApplicationIndividualSelector.queryApplicationIndividualData(new Map<String, String>{'objectName'=>'SSP_ApplicationIndividual__c','operator'=>'AND','MemberStatus__c' => '!='}, 
                                                                                 new Set<String>{'Id', 'SSP_Application__c', 'SSP_Member__c', 'ProgramsApplied__c', 'IsHeadOfHousehold__c', 'SSP_Application__r.HasConvictedCrimeToggle__c'}, 
                                                                                 new Map<String, String>{'limit'=>'100','SSP_Application__c'=> String.escapeSingleQuotes(ctxData.ApplicationId),'SSP_Member__c'=> String.escapeSingleQuotes(ctxData.MemberId),'MemberStatus__c'=> 'Removed'});
            if(!applicationIndividual.isEmpty()){
                String programs = applicationIndividual[0].ProgramsApplied__c;
                List<String> programValues = programs.split(';');
                for(String program : programValues){
                    if(SSP_GlobalConstants.CONVICTION_PROGRAMS.contains(program)){
                        selectedProgram = true;
                        break;                     
                    }
                }
                hasConvictedCrime = (applicationIndividual[0].SSP_Application__r.HasConvictedCrimeToggle__c == SSP_GlobalConstants.YES && applicationIndividual[0].IsHeadOfHousehold__c == true && selectedProgram) ? true : false ;
            }*/
            
        } catch (Exception e) {
            LOG_LogMessageUtility.logMessage(e, 'SSP_ConvictionQueueingRule', 'isRequired', e.getMessage() , true);
        }
        return hasConvictedCrime;
    }
}