force-app/main/default/objects/SSP_Application__c/SSP_Application__c.object-meta.xml
<CustomObject>
    <description>To store SSP Application and Case data</description>
    <label>SSP Application</label>
    <nameField>
        
        <displayFormat>{000000000}</displayFormat>
        
        <label>SSP_Application Name</label>
        
        <type>AutoNumber</type>
        
    </nameField>
    <pluralLabel>SSP Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Application__c/fields/HasConvictedCrimeToggle__c.field-meta.xml
<CustomField>
    <fullName>HasConvictedCrimeToggle__c</fullName>
    <description>This field is used to store if anyone in household is convicted to crime?</description>
    <label>Has convicted crime</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>YesNo</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/SSP_ApplicationIndividual__c.object-meta.xml
<CustomObject>
    <description>Custom junction object to maintain association between member and application</description>
    <label>SSP ApplicationIndividual</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>SSP_ApplicationIndividual Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SSP ApplicationIndividuals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/BlockedCaseNumber__c.field-meta.xml
<CustomField>
    <fullName>BlockedCaseNumber__c</fullName>
    <description>Used to store blocked Case number</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Blocked Case Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/IsActiveIEESCasePresent__c.field-meta.xml
<CustomField>
    <fullName>IsActiveIEESCasePresent__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to indicate Whether an Active IEES case present or not</description>
    <label>IsActiveIEESCasePresent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/isApplicationBlocked__c.field-meta.xml
<CustomField>
    <fullName>isApplicationBlocked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether the Application is blocked</description>
    <label>isApplicationBlocked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/IsHeadOfHousehold__c.field-meta.xml
<CustomField>
    <fullName>IsHeadOfHousehold__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to determine if the member is Head of Household</description>
    <label>Is Head Of Household</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/SSP_Application__c.field-meta.xml
<CustomField>
    <fullName>SSP_Application__c</fullName>
    <description>Indicates the application related to a member</description>
    <label>SSP_Application</label>
    <referenceTo>SSP_Application__c</referenceTo>
    <relationshipName>SSP_ApplicationIndividuals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/SSP_Member__c.field-meta.xml
<CustomField>
    <fullName>SSP_Member__c</fullName>
    <description>Indicates the member related to an application</description>
    <label>SSP_Member</label>
    <referenceTo>SSP_Member__c</referenceTo>
    <relationshipName>SSP_ApplicationIndividuals</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/SSP_Member__c.object-meta.xml
<CustomObject>
    <description>Stores details about an individual member of a case/application such as gatepost reponse, incarceration, disability, living arrangement, pregnancy, address details. Also repurposed to store information of different individuals in the form of individual alien, alien sponsor, care taker,  care coordinator etc.</description>
    <label>SSP Member</label>
    <nameField>
        
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        
        <label>SSP_Member Name</label>
        
        <type>Text</type>
        
    </nameField>
    <pluralLabel>SSP Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Member__c/fields/BirthDate__c.field-meta.xml
<CustomField>
    <fullName>BirthDate__c</fullName>
    <description>This field is used to store Date of birth of a member</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/CitizenShipVerificationCode__c.field-meta.xml
<CustomField>
    <fullName>CitizenShipVerificationCode__c</fullName>
    <description>This field is populated from MCI merged service as part of SSA Call and will need in SSP-DC call.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>CitizenShipVerificationCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/DeathConfirmationCode__c.field-meta.xml
<CustomField>
    <fullName>DeathConfirmationCode__c</fullName>
    <description>This field used to store the death confirmation code</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>DeathConfirmationCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/DeathDate__c.field-meta.xml
<CustomField>
    <fullName>DeathDate__c</fullName>
    <description>This field is used to store Date of Death of a member</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Date of Death</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/EthnicityCode__c.field-meta.xml
<CustomField>
    <fullName>EthnicityCode__c</fullName>
    <description>This field is used to store Ethnicity for a member</description>
    <label>Ethnicity</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>Ethnicity</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>This field is used to store Firstname on a Member</description>
    <encryptionScheme>None</encryptionScheme>
    <label>FirstName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/GenderCode__c.field-meta.xml
<CustomField>
    <fullName>GenderCode__c</fullName>
    <description>This field is used to store Gender on a member</description>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>SSPGender</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/IndividualId__c.field-meta.xml
<CustomField>
    <fullName>IndividualId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>This field is used to store individual Id of a member</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>IndividualId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/InmateStatusIndicator__c.field-meta.xml
<CustomField>
    <fullName>InmateStatusIndicator__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to indicate Inmate Status of a member</description>
    <label>InmateStatusIndicator</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/IsDateOfBirthValidated__c.field-meta.xml
<CustomField>
    <fullName>IsDateOfBirthValidated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is populated from MCI merged service as part of IEES/SSA Call.</description>
    <label>IsDateOfBirthValidated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/IsDateOfDeathValidated__c.field-meta.xml
<CustomField>
    <fullName>IsDateOfDeathValidated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is populated from MCI merged service as part of IEES/SSA Call and will need in SSP-DC call.</description>
    <label>IsDateOfDeathValidated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/IsHeadOfHousehold__c.field-meta.xml
<CustomField>
    <fullName>IsHeadOfHousehold__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Head Of Household</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/IsUSCitizenValidated__c.field-meta.xml
<CustomField>
    <fullName>IsUSCitizenValidated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is populated from MCI merged service as part of IEES/SSA Call and will need in SSP-DC call.</description>
    <label>IsUSCitizenValidated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <description>This field is used to store Lastname of a member</description>
    <encryptionScheme>None</encryptionScheme>
    <label>LastName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/LifeTimeQuarterQuantity__c.field-meta.xml
<CustomField>
    <fullName>LifeTimeQuarterQuantity__c</fullName>
    <description>This field is used to store Lifetime Quarter Quantity</description>
    <label>LifeTimeQuarterQuantity</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/MCIId__c.field-meta.xml
<CustomField>
    <fullName>MCIId__c</fullName>
    <description>This field is used to store MCI id from interface call</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>MCIId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/MiddleInitial__c.field-meta.xml
<CustomField>
    <fullName>MiddleInitial__c</fullName>
    <description>This field is used to store Middle Initial of a member</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>MiddleInitial</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/NationalityCode__c.field-meta.xml
<CustomField>
    <fullName>NationalityCode__c</fullName>
    <description>This field is used to store Nationality code of a member</description>
    <label>Nationality</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>Nationality</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/NoReasonSSNCode__c.field-meta.xml
<CustomField>
    <fullName>NoReasonSSNCode__c</fullName>
    <description>This field is used to store the reason for which member does not have SSN</description>
    <label>Why doesn’t have an SSN ?</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>ReasonForNoSSN</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/PrisonerConfinementDate__c.field-meta.xml
<CustomField>
    <fullName>PrisonerConfinementDate__c</fullName>
    <description>PrisonerConfinementDate detail   in SSN Interface Callout  will store</description>
    <encryptionScheme>None</encryptionScheme>
    <label>PrisonerConfinementDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/PseudoSSN__c.field-meta.xml
<CustomField>
    <fullName>PseudoSSN__c</fullName>
    <description>This field is populated from MCI merged service as part of IEES Call and will need in SSP-DC call.</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>PseudoSSN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/RaceCode__c.field-meta.xml
<CustomField>
    <fullName>RaceCode__c</fullName>
    <description>This field is used to store Race Code for the Member</description>
    <label>Your Race(s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>Race</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/SSN__c.field-meta.xml
<CustomField>
    <fullName>SSN__c</fullName>
    <description>This field is used to store Social Security Number of a member</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Social Security Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/SSNVerificationCode__c.field-meta.xml
<CustomField>
    <fullName>SSNVerificationCode__c</fullName>
    <description>This field is populated from MCI merged service as part of SSA Call and will need in SSP-DC call.</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>SSNVerificationCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/SSNVerified__c.field-meta.xml
<CustomField>
    <fullName>SSNVerified__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to indicate whether the SSN is verified</description>
    <label>SSNVerified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/SuffixCode__c.field-meta.xml
<CustomField>
    <fullName>SuffixCode__c</fullName>
    <description>This field is used to store Suffix code on a member</description>
    <label>Suffix</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>Suffix</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Ethnicity.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>CI</fullName>
        
        
        <label>Chicano/a</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>CU</fullName>
        
        
        <label>Cuban</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>MA</fullName>
        
        
        <label>Mexican American</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>ME</fullName>
        
        
        <label>Mexican</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>OT</fullName>
        
        
        <label>Other</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>PR</fullName>
        
        
        <label>Puerto Rican</label>
        
    </customValue>
    
    <description>Ethnicity Code to which citizen belongs to</description>
    
    <masterLabel>Ethnicity</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/globalValueSets/Nationality.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>AI</fullName>
        
        
        <label>Asian Indian</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>CH</fullName>
        
        
        <label>Chinese</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>FI</fullName>
        
        
        <label>Filipino</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>GU</fullName>
        
        
        <label>Guamanian or Chamorro</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>JP</fullName>
        
        
        <label>Japanese</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>KR</fullName>
        
        
        <label>Korean</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>NH</fullName>
        
        
        <label>Native Hawaiian</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>OA</fullName>
        
        
        <label>Other Asian</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>OPI</fullName>
        
        
        <label>Other Pacific Islander</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SM</fullName>
        
        
        <label>Samoan</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>VT</fullName>
        
        
        <label>Vietnamese</label>
        
    </customValue>
    
    <description>Nationality Code</description>
    
    <masterLabel>Nationality</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/globalValueSets/Race.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>IN</fullName>
        
        
        <label>American Indian or Alaskan Native</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>AS</fullName>
        
        
        <label>Asian</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>B</fullName>
        
        
        <label>Black or African American</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>HPI</fullName>
        
        
        <label>Native Hawaiian/Other Pacific Islander</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>W</fullName>
        
        
        <label>White</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>99</fullName>
        
        
        <label>Unknown</label>
        
    </customValue>
    
    <description>Race values to which citizen belongs to</description>
    
    <masterLabel>Race</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/globalValueSets/ReasonForNoSSN.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>AL</fullName>
        
        
        <label>Not eligible to receive SSN based on alien status</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>AP</fullName>
        
        
        <label>Applied for SSN</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>NB</fullName>
        
        
        <label>Newborn without SSN</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>NO</fullName>
        
        
        <label>Does not have an SSN and may only be issued an SSN for a valid non-work reason</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>RE</fullName>
        
        
        <label>Refuses to provide an SSN</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>RG</fullName>
        
        
        <label>Refuses to obtain an SSN because of a well-established religious objective</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>WS</fullName>
        
        
        <label>Without SSN Card</label>
        
    </customValue>
    
    <description>Different Reasons for which the citizen does not have SSN</description>
    
    <masterLabel>Reason for No SSN</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/globalValueSets/SSPGender.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>M</fullName>
        
        
        <label>Male</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>F</fullName>
        
        
        <label>Female</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>U</fullName>
        
        
        <label>Unknown</label>
        
    </customValue>
    
    <description>Different Gender values</description>
    
    <masterLabel>SSP Gender</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/globalValueSets/Suffix.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>JR</fullName>
        
        
        <label>Jr.</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SR</fullName>
        
        
        <label>Sr.</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>TW</fullName>
        
        
        <label>II</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>TH</fullName>
        
        
        <label>III</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>FO</fullName>
        
        
        <label>IV</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>FV</fullName>
        
        
        <label>V</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SI</fullName>
        
        
        <label>VI</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SE</fullName>
        
        
        <label>VII</label>
        
    </customValue>
    
    <description>Suffix codes used for any user</description>
    
    <masterLabel>Suffix</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/globalValueSets/YesNo.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>Y</fullName>
        
        
        <label>YES</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>N</fullName>
        
        
        <label>NO</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>U</fullName>
        
        
        <label>Unknown</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>NULL</fullName>
        
        
        <label>NULL</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>H</fullName>
        
        
        <label>Historical</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>I don&apos;t know</fullName>
        
        
        <label>I don&apos;t know</label>
        
    </customValue>
    
    <description>Used to store different types of toggle picklist values</description>
    
    <masterLabel>YesNo</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/classes/SSP_MCIMergedServiceMock.cls
/**
* Class Name    : SSP_MCIMergedServiceMock
* Owner         : DELOITTE
* Created Date  : 28/11/2019
* Description   : Mock class for SSP_MCIMergedServiceUtiltiy
*
*                            M O D I F I C A T I O N   L O G                                          
*
*  Date        Developer          			Description                                                         
*  ----------  -------------------------   -------------------------------------------------------------------
*  11/12/2019  Kommana Lova Durga Prasad   Initial Version
*/
@isTest
public class SSP_MCIMergedServiceMock implements HttpCalloutMock{
    
     public static final String stringSuccessRequestBodyforFullMatch = '   {  '  + 
        '     "Mode": "Intake",  '  + 
        '     "IndividualId": "123421123",  '  + 
        '     "Applicationnumber": "1234",  '  + 
        '     "ViewName": "SSP_APP_HHMemberDetails",  '  + 
        '      "CaseNumber": "",    ' +
        '      "IsApplicationBlocked": false,    ' + 
        '	   "BlockedCaseNumber" : "",  '+
        '     "MatchStatus": "Full Match",  '  + 
        '     "Payload": {  '  + 
        '       "SSP_Member__c": [  '  + 
        '         {  '  + 
        '           "NationalityCode__c": "AI",  '  + 
        '           "FirstName__c": "ASDFGHJ",  '  + 
        '           "MiddleInitial__c": "S",  '  + 
        '           "LastName__c": "ASDFGHJ",  '  + 
        '           "SuffixCode__c": "JR.",  '  + 
        '           "BirthDate__c": "1999-11-12",  '  +
        '           "SSN__c": "456345678",  '  + 
        '           "RaceCode__c": "IN",  '  + 
        '           "EthnicityCode__c": "CI",  '  + 
        '           "DeathDate__c": "2019-11-12",  '  + 
        '           "GenderCode__c": null,  '  + 
        '           "NoReasonSSNCode__c": "AL",  '  + 
        '           "IndividualId__c": "123421123",  '  +
        '           "MCIId__c": "MCITEST001",  '  +
        '           "SSNVerified__c": "true",  '  +
        '           "PrisonerConfinementDate__c": "2009-11-19",  '  + 
        '           "DeathConfirmationCode__c": "D123",  '  + 
        '           "HasConvictedCrime__c": "true",  '  + 
        '           "IsUSCitizen__c": "true",  '  + 
        '           "IsDateOfBirthValidated__c": "true",  ' +
        '           "IsUSCitizenValidated__c": "true",  ' +
        '           "IsDateOfDeathValidated__c": "true",  ' +
        '           "IsHeadOfHousehold__c": "true",  ' + 
        '           "PseudoSSN__c": "923923923",  '  +
        '           "CitizenShipVerificationCode__c": "Y",  '  +
        '           "SSNVerificationCode__c": "Y",  '  +
        '           "InmateStatusIndicator__c": "true",  '  + 
        '           "LifeTimeQuarterQuantity__c": "11"  '  + 
        '         }  '  + 
        '       ],  '  + 
        '       "SSP_Application__c": [  '  + 
        '         {  '  +
        '           "HasConvictedCrimeToggle__c": "N" '  +  
        '         }  '  + 
        '       ],  '  +          
        '       "SSP_ApplicationIndividual__c": [  '  + 
        '         {  '  + 
        '           "IsActiveIEESCasePresent__c": "false",  '  + 
        '           "SSP_Member__c": "123421123",  '  + 
        '           "isApplicationBlocked__c": "false",  '  +
        '           "IsHeadOfHousehold__c": "true",  ' + 
        '           "BlockedCaseNumber__c": ""  '  + 
        '         }  '  + 
        '       ]  '  +
        '     },  '  +
        '       "errorData":    {' +
        '           "errorCode": "test",  ' +
        '           "errorDescription": "test"  ' +
        '         }  '  + 
        '  }  ' ;
    
    
    public static final String stringApplicationBlockedforFullMatch = '   {  '  + 
        '     "Mode": "Intake",  '  + 
        '     "IndividualId": "123421123",  '  + 
        '     "Applicationnumber": "1234",  '  + 
        '     "ViewName": "SSP_APP_HHMemberDetails",  '  + 
        '      "CaseNumber": "",    ' +
        '      "IsApplicationBlocked": true,    ' +
        '	   "BlockedCaseNumber" : "C-12339999",  '+		
        '     "MatchStatus": "Full Match",  '  + 
        '     "Payload": {  '  + 
        '       "SSP_Member__c": [  '  + 
        '         {  '  + 
        '           "NationalityCode__c": "AI",  '  + 
        '           "FirstName__c": "ASDFGHJ",  '  + 
        '           "MiddleInitial__c": "S",  '  + 
        '           "LastName__c": "ASDFGHJ",  '  + 
        '           "SuffixCode__c": "JR.",  '  + 
        '           "BirthDate__c": "1999-11-12",  '  +
        '           "SSN__c": "456345601",  '  + 
        '           "RaceCode__c": "IN",  '  + 
        '           "EthnicityCode__c": "CI",  '  + 
        '           "DeathDate__c": "2019-11-12",  '  + 
        '           "GenderCode__c": "M",  '  + 
        '           "NoReasonSSNCode__c": "AL",  '  + 
        '           "IndividualId__c": "123421123",  '  +
        '           "MCIId__c": "MCITEST001",  '  +
        '           "SSNVerified__c": "true",  '  +
        '           "PrisonerConfinementDate__c": "2009-11-19",  '  + 
        '           "DeathConfirmationCode__c": "D123",  '  + 
        '           "HasConvictedCrime__c": "true",  '  + 
        '           "IsUSCitizen__c": "true",  '  +
        '           "IsDateOfBirthValidated__c": "true",  ' +
        '           "IsUSCitizenValidated__c": "true",  ' +
        '           "IsDateOfDeathValidated__c": "true",  ' +
        '           "PseudoSSN__c": "923923923",  '  +
        '           "CitizenShipVerificationCode__c": "Y",  '  +
        '           "SSNVerificationCode__c": "Y",  '  +
        '           "InmateStatusIndicator__c": "true",  '  + 
        '           "IsHeadOfHousehold__c": "true",  ' +
        '           "LifeTimeQuarterQuantity__c": "11"  '  + 
        '         }  '  + 
        '       ],  '  + 
        '       "SSP_ApplicationIndividual__c": [  '  + 
        '         {  '  + 
        '           "IsActiveIEESCasePresent__c": "false",  '  + 
        '           "SSP_Member__c": "123421123",  '  +
        '           "isApplicationBlocked__c": "true",  '  + 
        '           "BlockedCaseNumber__c": "C-12339999"  '  + 
        '         }  '  + 
        '       ]  '  +
        '     },  '  +
        '       "errorData":    {' +
        '           "errorCode": "",  ' +
        '           "errorDescription": ""  ' +
        '         }  '  + 
        '  }  ' ;
    
    
    public static final string StringForHOHwithAdditionalOneIndividual = '   {  '  + 
        '     "Mode": "Intake",  '  + 
        '     "IndividualId": "123421125",  '  + 
        '     "Applicationnumber": "1234",  '  + 
        '     "ViewName": "SSP_APP_HHMemberDetails",  '  + 
        '      "CaseNumber": "",    ' +
        '      "IsApplicationBlocked": false,    ' + 
        '	   "BlockedCaseNumber" : "",  '+
        '     "MatchStatus": "Full Match",  '  + 
        '     "Payload": {  '  + 
        '       "SSP_Member__c": [  '  + 
        '         {  '  + 
        '           "NationalityCode__c": "AI",  '  + 
        '           "FirstName__c": "ASDFGHJ",  '  + 
        '           "MiddleInitial__c": "S",  '  + 
        '           "LastName__c": "ASDFGHJ",  '  + 
        '           "SuffixCode__c": "JR.",  '  + 
        '           "BirthDate__c": "1999-11-12",  '  +
        '           "SSN__c": "456345602",  '  + 
        '           "RaceCode__c": "IN",  '  + 
        '           "EthnicityCode__c": "CI",  '  + 
        '           "DeathDate__c": "2019-11-12",  '  + 
        '           "GenderCode__c": "M",  '  + 
        '           "NoReasonSSNCode__c": "AL",  '  + 
        '           "IndividualId__c": "123421125",  '  +
        '           "MCIId__c": "MCITEST001",  '  +
        '           "SSNVerified__c": "true",  '  +
        '           "PrisonerConfinementDate__c": "2009-11-19",  '  + 
        '           "DeathConfirmationCode__c": "D123",  '  + 
        '           "HasConvictedCrime__c": "true",  '  + 
        '           "IsUSCitizen__c": "true",  '  + 
        '           "IsDateOfBirthValidated__c": "true",  ' +
        '           "IsUSCitizenValidated__c": "true",  ' +
        '           "IsDateOfDeathValidated__c": "true",  ' +
        '           "PseudoSSN__c": "923923923",  '  +
        '           "CitizenShipVerificationCode__c": "Y",  '  +
        '           "SSNVerificationCode__c": "Y",  '  +
        '           "InmateStatusIndicator__c": "true",  '  + 
        '           "IsHeadOfHousehold__c": "true",  ' +
        '           "LifeTimeQuarterQuantity__c": "11"  '  + 
        '         },  '  + 
		'         {  '  + 
        '           "NationalityCode__c": "AI",  '  + 
        '           "FirstName__c": "ASDFGHJ",  '  + 
        '           "MiddleInitial__c": "S",  '  + 
        '           "LastName__c": "ASDFGHJ",  '  + 
        '           "SuffixCode__c": "JR.",  '  + 
        '           "BirthDate__c": "1999-11-12",  '  +
        '           "SSN__c": "456345603",  '  + 
        '           "RaceCode__c": "IN",  '  + 
        '           "EthnicityCode__c": "CI",  '  + 
        '           "DeathDate__c": "2019-11-12",  '  + 
        '           "GenderCode__c": "M",  '  + 
        '           "NoReasonSSNCode__c": "AL",  '  + 
        '           "IndividualId__c": "123421124",  '  +
        '           "MCIId__c": "MCITEST002",  '  +
        '           "SSNVerified__c": "true",  '  +
        '           "PrisonerConfinementDate__c": "2009-11-19",  '  + 
        '           "DeathConfirmationCode__c": "D123",  '  + 
        '           "HasConvictedCrime__c": "true",  '  + 
        '           "IsUSCitizen__c": "true",  '  +
        '           "IsDateOfBirthValidated__c": "true",  ' +
        '           "IsUSCitizenValidated__c": "true",  ' +
        '           "IsDateOfDeathValidated__c": "true",  ' +
        '           "PseudoSSN__c": "923923923",  '  +
        '           "CitizenShipVerificationCode__c": "Y",  '  +
        '           "SSNVerificationCode__c": "Y",  '  +
        '           "InmateStatusIndicator__c": "true",  '  + 
        '           "IsHeadOfHousehold__c": "false",  ' +
        '           "LifeTimeQuarterQuantity__c": "11"  '  + 
        '         }  '  +
        '       ],  '  + 
        '       "SSP_ApplicationIndividual__c": [  '  + 
        '         {  '  + 
        '           "IsActiveIEESCasePresent__c": "false",  '  + 
        '           "SSP_Member__c": "123421125",  '  + 
        '           "isApplicationBlocked__c": "false",  '  + 
        '           "BlockedCaseNumber__c": ""  '  + 
        '         },  '  + 
		'         {  '  + 
        '           "IsActiveIEESCasePresent__c": "false",  '  + 
        '           "SSP_Member__c": "123421124",  '  +
        '           "isApplicationBlocked__c": "false",  '  + 
        '           "BlockedCaseNumber__c": ""  '  + 
        '         }  '  +
        '       ]  '  +
        '     },  '  +
        '       "errorData":    {' +
        '           "errorCode": "",  ' +
        '           "errorDescription": ""  ' +
        '         }  '  + 
        '  }  ' ;
    
    
    public static final string StringSSNFailure = '{'+
        '   "Mode": "Intake",   '+
        '   "IndividualId": "123421134",    '+
        '   "Applicationnumber": "C-123445132", '+
        '   "ViewName": "SSP_APP_HHMemberDetails",  '+
        '   "CaseNumber": "",   ' +
        '    "IsApplicationBlocked": false,    ' + 
        '	   "BlockedCaseNumber" : "",  '+
        '   "MatchStatus": "",  '+
        '   "Payload": "",  '+
        '   "errorData":    {   '+
        '  "errorCode": "ERRSSN001",    '+
        '   "errorDescription": "No match found"    '+
        '   }'+
        '}';
    
    public static string NoMatchGotNewIndividual = '   {  '  + 
        '     "Mode": "Intake",  '  + 
        '     "IndividualId": "12342999",  '  + 
        '     "Applicationnumber": "1234",  '  + 
        '      "CaseNumber": "",    ' +
        '      "IsApplicationBlocked": false,    ' + 
        '	   "BlockedCaseNumber" : "",  '+
        '     "ViewName": "SSP_APP_HHMemberDetails",  '  + 
        '     "MatchStatus": "No Match",  '  + 
        '     "Payload": {  '  + 
        '       "SSP_Member__c": [  '  + 
        '         {  '  + 
        '           "NationalityCode__c": "AI",  '  + 
        '           "FirstName__c": "ASDFGHJ",  '  + 
        '           "MiddleInitial__c": "S",  '  + 
        '           "LastName__c": "ASDFGHJ",  '  + 
        '           "SuffixCode__c": "JR.",  '  + 
        '           "BirthDate__c": "1999-11-12",  '  +
        '           "SSN__c": "456345604",  '  + 
        '           "RaceCode__c": "IN",  '  + 
        '           "EthnicityCode__c": "CI",  '  + 
        '           "DeathDate__c": "2019-11-12",  '  + 
        '           "GenderCode__c": "M",  '  + 
        '           "NoReasonSSNCode__c": "AL",  '  + 
        '           "IndividualId__c": "123429998",  '  +
        '           "MCIId__c": "MCITEST009",  '  +
        '           "SSNVerified__c": "true",  '  +
        '           "PrisonerConfinementDate__c": "2009-11-19",  '  + 
        '           "DeathConfirmationCode__c": "D123",  '  + 
        '           "HasConvictedCrime__c": "true",  '  + 
        '           "IsUSCitizen__c": "true",  '  +
        '           "IsDateOfBirthValidated__c": "true",  ' +
        '           "IsUSCitizenValidated__c": "true",  ' +
        '           "IsDateOfDeathValidated__c": "true",  ' +
        '           "PseudoSSN__c": "923923923",  '  +
        '           "CitizenShipVerificationCode__c": "Y",  '  +
        '           "SSNVerificationCode__c": "Y",  '  +
        '           "IsHeadOfHousehold__c": "false",  ' +
        '           "InmateStatusIndicator__c": "true",  '  + 
        '           "LifeTimeQuarterQuantity__c": "11"  '  + 
        '         }  '  + 
        '       ],  '  + 
        '       "SSP_ApplicationIndividual__c": [  '  + 
        '         {  '  + 
        '           "IsActiveIEESCasePresent__c": "false",  '  + 
        '           "SSP_Member__c": "123429998",  '  + 
        '           "isApplicationBlocked__c": "false",  '  + 
        '           "BlockedCaseNumber__c": ""  '  + 
        '         }  '  + 
        '       ]  '  +
        '     },  '  +
        '       "errorData":    {' +
        '           "errorCode": "",  ' +
        '           "errorDescription": ""  ' +
        '         }  '  + 
        '  }  ' ;
    
    public static string CatchExceptioninProcessResponse = '   {  '  + 
        '     "Mode": "Intake",  '  + 
        '     "IndividualId": "12342999",  '  + 
        '     "Applicationnumber": "1234",  '  + 
        '      "CaseNumber": "",    ' +
        '      "IsApplicationBlocked": false,    ' + 
        '	   "BlockedCaseNumber" : "",  '+
        '     "ViewName": "SSP_APP_HHMemberDetails",  '  + 
        '     "MatchStatus": "No Match",  '  + 
        '     "Payload": {  '  + 
        '       "SSP_Member__c": [  '  + 
        '         {  '  + 
        '           "NationalityCode__c": "AI",  '  + 
        '           "FirstName__c": "ASDFGHJ",  '  + 
        '           "MiddleInitial__c": "S",  '  + 
        '           "LastName__c": "ASDFGHJ",  '  + 
        '           "SuffixCode__c": "JR.",  '  + 
        '           "BirthDate__c": "1999-11-12",  '  +
        '           "SSN__c": "456345604",  '  + 
        '           "RaceCode__c": "IN",  '  + 
        '           "EthnicityCode__c": "CI",  '  + 
        '           "DeathDate__c": "2019-11-12",  '  + 
        '           "GenderCode__c": "M",  '  + 
        '           "NoReasonSSNCode__c": "AL",  '  + 
        '           "IndividualId__c": "123429998",  '  +
        '           "MCIId__c": "MCITEST009",  '  +
        '           "SSNVerified__c": "true",  '  +
        '           "PrisonerConfinementDate__c": "2009-11-19T00:00:00Z",  '  + 
        '           "DeathConfirmationCode__c": "D123",  '  + 
        '           "HasConvictedCrime__c": "true",  '  + 
        '           "IsUSCitizen__c": "true",  '  +
        '           "IsDateOfBirthValidated__c": "true",  ' +
        '           "IsUSCitizenValidated__c": "true",  ' +
        '           "IsDateOfDeathValidated__c": "true",  ' +
        '           "PseudoSSN__c": "923923923",  '  +
        '           "CitizenShipVerificationCode__c": "Y",  '  +
        '           "SSNVerificationCode__c": "Y",  '  +
        '           "IsHeadOfHousehold__c": "false",  ' +
        '           "InmateStatusIndicator__c": "true",  '  + 
        '           "LifeTimeQuarterQuantity__c": "11"  '  + 
        '         }  '  + 
        '       ],  '  + 
        '       "SSP_ApplicationIndividual__c": [  '  + 
        '         {  '  + 
        '           "IsActiveIEESCasePresent__c": "false",  '  + 
        '           "SSP_Member__c": "123429998",  '  + 
        '           "isApplicationBlocked__c": "false",  '  + 
        '           "BlockedCaseNumber__c": ""  '  + 
        '         }  '  + 
        '       ]  '  +
        '     },  '  +
        '       "errorData":    {' +
        '           "errorCode": "",  ' +
        '           "errorDescription": ""  ' +
        '         }  '  + 
        '  }  ' ;
    
    public static final string partialMatchGotNewIndividual = '   {  '  + 
        '     "Mode": "Intake",  '  + 
        '     "IndividualId": "123429588",  '  + 
        '     "Applicationnumber": "1234",  '  + 
        '      "CaseNumber": "",    ' +
        '      "IsApplicationBlocked": false,    ' + 
        '	   "BlockedCaseNumber" : "",  '+
        '     "ViewName": "SSP_APP_HHMemberDetails",  '  + 
        '     "MatchStatus": "Partial Match",  '  + 
        '     "Payload": {  '  + 
        '       "SSP_Member__c": [  '  + 
        '         {  '  + 
        '           "NationalityCode__c": "AI",  '  + 
        '           "FirstName__c": "ASDFGHJ",  '  + 
        '           "MiddleInitial__c": "S",  '  + 
        '           "LastName__c": "ASDFGHJ",  '  + 
        '           "SuffixCode__c": "JR.",  '  + 
        '           "BirthDate__c": "1999-11-12",  '  +
        '           "SSN__c": "456345605",  '  + 
        '           "RaceCode__c": "IN",  '  + 
        '           "EthnicityCode__c": "CI",  '  + 
        '           "DeathDate__c": "2019-11-12",  '  + 
        '           "GenderCode__c": "M",  '  + 
        '           "NoReasonSSNCode__c": "AL",  '  + 
        '           "IndividualId__c": "123429588",  '  +
        '           "MCIId__c": "MCITEST008",  '  +
        '           "SSNVerified__c": "true",  '  +
        '           "PrisonerConfinementDate__c": "2009-11-19",  '  + 
        '           "DeathConfirmationCode__c": "D123",  '  + 
        '           "HasConvictedCrime__c": "true",  '  + 
        '           "IsUSCitizen__c": "true",  '  +
        '           "IsDateOfBirthValidated__c": "true",  ' +
        '           "IsUSCitizenValidated__c": "true",  ' +
        '           "IsDateOfDeathValidated__c": "true",  ' +
        '           "PseudoSSN__c": "923923923",  '  +
        '           "CitizenShipVerificationCode__c": "Y",  '  +
        '           "SSNVerificationCode__c": "Y",  '  +
        '           "IsHeadOfHousehold__c": "false",  ' +
        '           "InmateStatusIndicator__c": "true",  '  + 
        '           "LifeTimeQuarterQuantity__c": "11"  '  + 
        '         }  '  + 
        '       ],  '  + 
        '       "SSP_ApplicationIndividual__c": [  '  + 
        '         {  '  + 
        '           "IsActiveIEESCasePresent__c": "false",  '  + 
        '           "SSP_Member__c": "123429588",  '  + 
        '           "isApplicationBlocked__c": "false",  '  + 
        '           "BlockedCaseNumber__c": ""  '  + 
        '         }  '  + 
        '       ]  '  +
        '     },  '  +
        '       "errorData":    {' +
        '           "errorCode": "",  ' +
        '           "errorDescription": ""  ' +
        '         }  '  + 
        '  }  ' ;
    
    public static final string stringMuleException =  '{'+
        '   "Mode": "Intake",   '+
        '   "IndividualId": "", '+
        '   "Applicationnumber": "C-123445132", '+
        '    "IsApplicationBlocked": false,    ' + 
        '	   "BlockedCaseNumber" : "",  '+
        '   "ViewName": "SSP_APP_HHMemberDetails",  '+
        '   "CaseNumber": "",   ' +
        '   "MatchStatus": "",  '+
        '   "Payload": null,  '+
        '   "errorData":    {   '+
        '  "errorCode": "INT1000",  '+
        '   "errorDescription": "Trusted Data Source System Unavailable/Unreachable"    '+
        '   }'+
        '}';
    public static final string sDocumentDownloadSuccessResponse = 'testblob';
    protected string interfaceName;
    protected Integer code;
    protected boolean isError;
    protected string matchtype;
    public SSP_MCIMergedServiceMock(string interfaceName,Integer code,boolean isError,string matchtype){
        this.interfaceName = interfaceName;
        this.code = code;
        this.isError= isError;
        this.matchtype = matchtype;
    }
    
 public HTTPResponse respond(HTTPRequest request) {
        // Create a fake response
        HttpResponse response = new HttpResponse();
        response.setHeader('Content-Type', 'application/json');
     string body = '';
      if(interfaceName == 'MCIMergedService' && code == 200 && matchtype == 'Full Match'){
         body = stringSuccessRequestBodyforFullMatch;
         response.setStatus('Success');
         response.setStatusCode(200);
     }
     else if(interfaceName == 'MCIMergedService' && code == 200 && matchtype == 'SSN Exception'){
         body = StringSSNFailure;
         response.setStatus('Exception');
         response.setStatusCode(200);
     }	
     else if(interfaceName == 'MCIMergedService' && code == 200 && matchtype == 'Parital Match'){
         body = partialMatchGotNewIndividual;
         response.setStatus('Success');
         response.setStatusCode(200);
     }	
      else if(interfaceName == 'MCIMergedService' && code == 200 && matchtype == 'No Match with New Individual'){
         body = NoMatchGotNewIndividual;
           response.setStatus('Success');
         response.setStatusCode(200);
     }
     else if(interfaceName == 'MCIMergedService' && code == 200 && matchtype == 'Exception in Data'){
         body = CatchExceptioninProcessResponse;
           response.setStatus('Success');
         response.setStatusCode(200);
     }	
      else if(interfaceName == 'MCIMergedService' && code == 500 && matchtype == 'Mule Exception'){
         body = stringMuleException;
           response.setStatus('Exception');
         response.setStatusCode(500);
     }	
     else if(interfaceName == 'MCIMergedService' && code == 200 && matchtype == 'Mule Exception'){
         body = stringMuleException;
           response.setStatus('Exception');
         response.setStatusCode(200);
     }	
     else if(interfaceName == 'MCIMergedService' && code == 200 && matchtype == 'HOH Full Match'){
         body = StringForHOHwithAdditionalOneIndividual;
         response.setStatus('Success');
         response.setStatusCode(200);
     }
     else if(interfaceName == 'MCIMergedService' && code == 200 && matchtype == 'Application Block'){
          body = stringApplicationBlockedforFullMatch;
         response.setStatus('Success');
          response.setStatusCode(200);
     }
     else if(interfaceName == 'DocDownloadService' && code == 200){
          body = sDocumentDownloadSuccessResponse;
         response.setStatus('Success');
          response.setStatusCode(200);
     }
        response.setBody(body);
        
        return response; 
    }
}