force-app/main/default/objects/EncryptionDecryptionSettings__c/EncryptionDecryptionSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>It is used to store Key and IV values for encryption/decryption.</description>
    <label>Encryption and Decryption Settings</label>
</CustomObject>

force-app/main/default/objects/EncryptionDecryptionSettings__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Key</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSPIntegrationEndpoints__c/SSPIntegrationEndpoints__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom setting to store integration endpoints for SSP.</description>
    <label>SSP Integration Endpoints</label>
</CustomObject>

force-app/main/default/objects/SSPIntegrationEndpoints__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <description>Used to store endpoint url.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SSP_ShoppingIntegration.cls
public class SSP_ShoppingIntegration {
    
    static final String cryptoKey = EncryptionDecryptionSettings__c.getInstance('SSPKey').Key__c;
    static Blob cryptoKeyValue = Blob.valueof(cryptoKey);
    @AuraEnabled
    public static SSP_LightningResponse generateEncryptedData(String caseNumber, Boolean isHeadOfHouseHold) {        
        SSP_LightningResponse objResponse = new SSP_LightningResponse();
        String responseData;
        try {
            
            responseData = getRequestBody(caseNumber);
            
            objResponse.bIsSuccess = true;
            objResponse.put('responseData', responseData);
            String portalUrl;
            
            if(isHeadOfHouseHold)
                portalUrl = SSPIntegrationEndpoints__c.getInstance('ShoppingPortal').URL__c + responseData;
            else 
                portalUrl = SSPIntegrationEndpoints__c.getInstance('ShoppingPortalNonPrimary').URL__c + responseData;
            objResponse.put('shoppingPortalUrl', portalUrl);
        } 
        catch (Exception ex) {            
            objResponse.bIsSuccess = false;
            objResponse.put('error', ex.getMessage());
        }
        
        return objResponse;
    }
    
    public static String getRequestBody(String caseNumber) {
        
        Map<String, ShoppingRequest> mapParams = new Map<String, ShoppingRequest>();
        ShoppingRequest reqDetail = new ShoppingRequest();
        reqDetail.CaseNumber = caseNumber;
        reqDetail.TimeStamp = SSP_Utility.now();
        reqDetail.Language = UserInfo.getLanguage() == 'en_US' ? 'EN' : 'ES';        
        mapParams.put('data', reqDetail);        
        Blob data = Blob.valueOf(JSON.serialize(mapParams)); 
        Blob encryptedData = Crypto.encryptWithManagedIV('AES256', cryptoKeyValue, data ); 
        String encryptedValue = EncodingUtil.base64Encode(encryptedData); 
        
        return encryptedValue;
    }
    public class ShoppingRequest {
        public String CaseNumber;
        public DateTime TimeStamp;
        public String Language;
    }
}