force-app/main/default/objects/Account/recordTypes/Application.recordType-meta.xml
<RecordType>
    <fullName>Application</fullName>
    <active>true</active>
    <description>Record type for application account</description>
    <label>Application</label>
</RecordType>

force-app/main/default/objects/SSPIntegrationEndpoints__c/SSPIntegrationEndpoints__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom setting to store integration endpoints for SSP.</description>
    <label>SSP Integration Endpoints</label>
</CustomObject>

force-app/main/default/objects/SSPIntegrationEndpoints__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <description>Used to store endpoint url.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SSP_ProgramSelectionServiceMock.cls
global class SSP_ProgramSelectionServiceMock implements HttpCalloutMock {
    
    global HTTPResponse respond(HTTPRequest req) {
        HttpResponse res = new HttpResponse();
        if(Schema.sObjectType.User.isAccessible()){  //Iron Dome - isAccessible Fix
            User u = [SELECT Id FROM User WHERE Profile.Name = 'System Administrator' AND isActive = true LIMIT 1];
            
            System.runAs(u){
                System.assertEquals(SSPIntegrationEndpoints__c.getInstance('CreateAccountService').URL__c, req.getEndpoint());
                list<account> accList = new Account[]{new Account(name='test1')};
                    Map<String, Object> reqMap = (Map<String, Object>)JSON.deserializeUntyped(req.getBody());
                
                
                
                String resultJSON = SSP_AccountCreationService.doPost((String)reqMap.get('dataString'),
                                                                    (String)reqMap.get('signatureString'),
                                                                    (String)reqMap.get('accountsJSON'),
                                                                    (String)reqMap.get('contactsJSON'),
                                                                    (String)reqMap.get('sCurrentUserContactId')
                                                                    );
                res.setHeader('Content-Type', 'application/json');
                res.setBody(resultJSON);
                res.setStatusCode(200);
            }
        }
        return res;
    }
}