force-app/main/default/objects/Account/recordTypes/Application.recordType-meta.xml
<RecordType>
    <fullName>Application</fullName>
    <active>true</active>
    <description>Record type for application account</description>
    <label>Application</label>
</RecordType>

force-app/main/default/objects/AccountContactRelation/fields/ProgramsApplied__c.field-meta.xml
<CustomField>
    <fullName>ProgramsApplied__c</fullName>
    <label>Programs Applied</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetDefinition>
            
            
                <value>
                
                    <fullName>MA</fullName>
                
                
                    <label>Medicaid/KCHIP</label>
                
                </value>
            
                <value>
                
                    <fullName>KT</fullName>
                
                
                    <label>KTAP (Cash Assistance)</label>
                
                </value>
            
                <value>
                
                    <fullName>SN</fullName>
                
                
                    <label>SNAP (Food Assistance)</label>
                
                </value>
            
                <value>
                
                    <fullName>SS</fullName>
                
                
                    <label>State Supplementation</label>
                
                </value>
            
                <value>
                
                    <fullName>DS</fullName>
                
                
                    <label>DSNAP</label>
                
                </value>
            
                <value>
                
                    <fullName>CC</fullName>
                
                
                    <label>Child Care Assistance</label>
                
                </value>
            
                <value>
                
                    <fullName>KP</fullName>
                
                
                    <label>KI-HIPP (Health Insurance Premium Payments)</label>
                
                </value>
            
            </valueSetDefinition>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Related Account</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SSP_Application__c/SSP_Application__c.object-meta.xml
<CustomObject>
    <description>To store SSP Application and Case data</description>
    <label>SSP Application</label>
    <nameField>
        
        <displayFormat>{000000000}</displayFormat>
        
        <label>SSP_Application Name</label>
        
        <type>AutoNumber</type>
        
    </nameField>
    <pluralLabel>SSP Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Application__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Shows the related Account to an Application</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>SSP_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_Application__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Shows the related Contact to an Application</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>SSP_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SSP_Application__c/fields/ProgramsApplied__c.field-meta.xml
<CustomField>
    <fullName>ProgramsApplied__c</fullName>
    <description>Used to store the list of programs applied for a household</description>
    <label>Programs Applied</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>BenefitPrograms</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/SSP_ApplicationIndividual__c.object-meta.xml
<CustomObject>
    <description>Custom junction object to maintain association between member and application</description>
    <label>SSP ApplicationIndividual</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>SSP_ApplicationIndividual Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SSP ApplicationIndividuals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/ProgramsApplied__c.field-meta.xml
<CustomField>
    <fullName>ProgramsApplied__c</fullName>
    <description>Different types of programs applied on an application for which this member is involved</description>
    <label>Application Programs Applied</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>BenefitPrograms</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/SSP_Application__c.field-meta.xml
<CustomField>
    <fullName>SSP_Application__c</fullName>
    <description>Indicates the application related to a member</description>
    <label>SSP_Application</label>
    <referenceTo>SSP_Application__c</referenceTo>
    <relationshipName>SSP_ApplicationIndividuals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/SSP_Member__c.field-meta.xml
<CustomField>
    <fullName>SSP_Member__c</fullName>
    <description>Indicates the member related to an application</description>
    <label>SSP_Member</label>
    <referenceTo>SSP_Member__c</referenceTo>
    <relationshipName>SSP_ApplicationIndividuals</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/SSP_Member__c.object-meta.xml
<CustomObject>
    <description>Stores details about an individual member of a case/application such as gatepost reponse, incarceration, disability, living arrangement, pregnancy, address details. Also repurposed to store information of different individuals in the form of individual alien, alien sponsor, care taker,  care coordinator etc.</description>
    <label>SSP Member</label>
    <nameField>
        
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        
        <label>SSP_Member Name</label>
        
        <type>Text</type>
        
    </nameField>
    <pluralLabel>SSP Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Member__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>This field is used to indicate the related contact for a member</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>SSP_Member</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/BenefitPrograms.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>MA</fullName>
        
        
        <label>Medicaid/KCHIP</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>KT</fullName>
        
        
        <label>KTAP (Cash Assistance)</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SN</fullName>
        
        
        <label>SNAP (Food Assistance)</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SS</fullName>
        
        
        <label>State Supplementation</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>DS</fullName>
        
        
        <label>DSNAP</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>CC</fullName>
        
        
        <label>Child Care Assistance</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>KP</fullName>
        
        
        <label>KI-HIPP (Health Insurance Premium Payments)</label>
        
    </customValue>
    
    <description>Different type of Benefit Programs available for a Citizen</description>
    
    <masterLabel>Benefit Programs</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/classes/SSP_RelationshipInformationRuleTest.cls
/***************************************************************************************************************************
*   Type         :   Test Class
*   Name         :   SSP_RelationshipInformationRuleTest
*   Created By   :   Sanchita Tibrewala
*   Created Date :   02/03/2019
*   Description  :   Test class for SSP_RelationshipInformationRuleTest
*  
*   Modification Log
*   --------------------------------------------------------------------------------------
*   * Developer                   Date          Description
*   * ------------------------------------------------------------------------------------                 
*     Sanchita                 02/03/2020     Initial Version
*****************************************************************************************************************************/
@isTest
public class SSP_RelationshipInformationRuleTest {
	
    /********************************************************************************************
    * @author       Sanchita Tibrewala
    * @date         02/06/2020
    * @methodname   setup
    * @description  Data creation for test class
    * @param        none
    * @return       none
    ********************************************************************************************/
    @TestSetup 
    public static void setup(){
        List<Account> accList = SSP_TestDataFactory.createAccounts(2, false);
        Account acc = accList.get(0);
        insert acc;
        
        Account accApp = accList.get(1);
        insert accApp;
        
        List<Contact> contList = SSP_TestDataFactory.createContacts(1, false);
        Contact cont = contList.get(0);
        cont.accountId = acc.Id;
        insert cont;
        
        AccountContactRelation acr = new AccountContactRelation(); 
        acr.Accountid = accApp.Id;
        acr.Contactid = cont.Id;
        acr.IsActive = true;
        insert acr;
        
        List<SSP_Member__c> memList = SSP_TestDataFactory.createSSPMembers(2, false);
        SSP_Member__c mem1 = memList.get(0);
        mem1.Contact__c = cont.Id;
        insert mem1;
        
        SSP_Member__c mem2 = memList.get(1);
        mem2.Contact__c = cont.Id;
        insert mem2;
        
        List<SSP_Application__c> appList = SSP_TestDataFactory.createSSPApplications(1, false);
        SSP_Application__c app = appList.get(0);
        app.Account__c = accApp.Id;
        insert app;
        Id appId = app.Id;
        
        List<SSP_ApplicationIndividual__c> appIndvList = SSP_TestDataFactory.createApplicationIndividuals(2, false);
        SSP_ApplicationIndividual__c appIndv1 = appIndvList.get(0);
		appIndv1.SSP_Member__c = mem1.Id;
        appIndv1.SSP_Application__c = appId;
        appIndv1.ProgramsApplied__c = 'MA;DS;KP;CC';
        insert appIndv1;
        
        SSP_ApplicationIndividual__c appIndv2 = appIndvList.get(1);
		appIndv2.SSP_Member__c = mem2.Id;
        appIndv2.SSP_Application__c = appId;
        appIndv2.ProgramsApplied__c = 'MA;DS;KP;CC';
        insert appIndv2;
    }
    
    /********************************************************************************************
    * @author       Sanchita Tibrewala
    * @date         02/03/2020
    * @methodname   isRequiredTest
    * @description  Test method for isRequired
    * @param        none
    * @return       none
    ********************************************************************************************/
    @isTest
    public static void isRequiredTest(){
        SSP_Member__c mem = getMember();
        SSP_Application__c app = getApplication();
        List<SSP_ApplicationIndividual__c> appIndList = queryApplicationIndividual(app.Id);
        
        QueuingWrapper qwrap = new QueuingWrapper ();
        qwrap.applicationIndividualList = appIndList;
        
        Context ctx = new Context();
        ContextData ctxData = new ContextData();
        ctxData.MemberId = mem.Id;
        ctxData.ApplicationId = app.Id;
        ctxData.queueObject = qwrap;
        
        SSP_RelationshipInformationRule cls = new SSP_RelationshipInformationRule();
        Test.startTest();
        boolean result = cls.isRequired(ctx, ctxData);
        Test.stopTest();
        System.assertEquals(result, true);
    }
    
    /********************************************************************************************
    * @author       Sanchita Tibrewala
    * @date         02/03/2020
    * @methodname   isRequiredTest1
    * @description  Test method for isRequired
    * @param        none
    * @return       none
    ********************************************************************************************/
    @isTest
    public static void isRequiredTest1(){        
        SSP_RelationshipInformationRule cls = new SSP_RelationshipInformationRule();
        Test.startTest();
        boolean result2 = cls.isRequired(null, null);
        Test.stopTest();
        System.assertEquals(result2, false);
    }
    
    /********************************************************************************************
    * @author       Sanchita Tibrewala
    * @date         02/05/2020
    * @methodname   getMember
    * @description  retrieves Member
    * @param        void
    * @return       SSP_Member__c
    ********************************************************************************************/
    private static SSP_Member__c getMember(){
        return [Select Id FROM SSP_Member__c LIMIT 1];
    }
    
    /********************************************************************************************
    * @author       Sanchita Tibrewala
    * @date         02/05/2020
    * @methodname   getApplication
    * @description  retrieves Application
    * @param        void
    * @return       SSP_Application__c
    ********************************************************************************************/
    private static SSP_Application__c getApplication(){
        return [SELECT Id FROM SSP_Application__c LIMIT 1];
    }
    
    private static List<SSP_ApplicationIndividual__c> queryApplicationIndividual(String applicationId){
        return ([SELECT Id, ProgramsApplied__c, SSP_Member__c FROM SSP_ApplicationIndividual__c WHERE SSP_Application__c = :applicationId]);
    }
}