force-app/main/default/objects/Account/recordTypes/Citizen.recordType-meta.xml
<RecordType>
    <fullName>Citizen</fullName>
    <active>true</active>
    <label>Citizen</label>
</RecordType>

force-app/main/default/objects/AccountContactRelation/fields/ProgramsApplied__c.field-meta.xml
<CustomField>
    <fullName>ProgramsApplied__c</fullName>
    <label>Programs Applied</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetDefinition>
            
            
                <value>
                
                    <fullName>MA</fullName>
                
                
                    <label>Medicaid/KCHIP</label>
                
                </value>
            
                <value>
                
                    <fullName>KT</fullName>
                
                
                    <label>KTAP (Cash Assistance)</label>
                
                </value>
            
                <value>
                
                    <fullName>SN</fullName>
                
                
                    <label>SNAP (Food Assistance)</label>
                
                </value>
            
                <value>
                
                    <fullName>SS</fullName>
                
                
                    <label>State Supplementation</label>
                
                </value>
            
                <value>
                
                    <fullName>DS</fullName>
                
                
                    <label>DSNAP</label>
                
                </value>
            
                <value>
                
                    <fullName>CC</fullName>
                
                
                    <label>Child Care Assistance</label>
                
                </value>
            
                <value>
                
                    <fullName>KP</fullName>
                
                
                    <label>KI-HIPP (Health Insurance Premium Payments)</label>
                
                </value>
            
            </valueSetDefinition>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Related Account</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PrimaryPhoneExtension__c.field-meta.xml
<CustomField>
    <fullName>PrimaryPhoneExtension__c</fullName>
    <description>Primary Phone Extension of a Contact</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Primary Phone Extension</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Citizen.recordType-meta.xml
<RecordType>
    <fullName>Citizen</fullName>
    <active>true</active>
    <description>This Record type is used for Residents</description>
    <label>Citizen</label>
</RecordType>

force-app/main/default/objects/SSP_Application__c/SSP_Application__c.object-meta.xml
<CustomObject>
    <description>To store SSP Application and Case data</description>
    <label>SSP Application</label>
    <nameField>
        
        <displayFormat>{000000000}</displayFormat>
        
        <label>SSP_Application Name</label>
        
        <type>AutoNumber</type>
        
    </nameField>
    <pluralLabel>SSP Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Application__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Shows the related Account to an Application</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>SSP_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_Application__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Shows the related Contact to an Application</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>SSP_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SSP_Application__c/fields/EnrolledInHealthCareCoverageToggle__c.field-meta.xml
<CustomField>
    <fullName>EnrolledInHealthCareCoverageToggle__c</fullName>
    <description>This field is used to determine if an individual has enrolled in healthcare coverage.</description>
    <label>Enrolled In HealthCare Coverage</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>YesNo</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Application__c/fields/ProgramsApplied__c.field-meta.xml
<CustomField>
    <fullName>ProgramsApplied__c</fullName>
    <description>Used to store the list of programs applied for a household</description>
    <label>Programs Applied</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>BenefitPrograms</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/SSP_ApplicationIndividual__c.object-meta.xml
<CustomObject>
    <description>Custom junction object to maintain association between member and application</description>
    <label>SSP ApplicationIndividual</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>SSP_ApplicationIndividual Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SSP ApplicationIndividuals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/ProgramsApplied__c.field-meta.xml
<CustomField>
    <fullName>ProgramsApplied__c</fullName>
    <description>Different types of programs applied on an application for which this member is involved</description>
    <label>Application Programs Applied</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>BenefitPrograms</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/SSP_Application__c.field-meta.xml
<CustomField>
    <fullName>SSP_Application__c</fullName>
    <description>Indicates the application related to a member</description>
    <label>SSP_Application</label>
    <referenceTo>SSP_Application__c</referenceTo>
    <relationshipName>SSP_ApplicationIndividuals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/SSP_Member__c.field-meta.xml
<CustomField>
    <fullName>SSP_Member__c</fullName>
    <description>Indicates the member related to an application</description>
    <label>SSP_Member</label>
    <referenceTo>SSP_Member__c</referenceTo>
    <relationshipName>SSP_ApplicationIndividuals</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_InsuranceCoveredIndiv__c/SSP_InsuranceCoveredIndiv__c.object-meta.xml
<CustomObject>
    <description>Stores details about an individual covered under an insurance policy. It could be an existing member in the system or an external individual covered under policy.</description>
    <label>SSP InsuranceCoveredIndiv</label>
    <nameField>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>SSP_InsuranceCoveredIndiv Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SSP InsuranceCoveredIndiv</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_InsuranceCoveredIndiv__c/fields/IsPolicyHolder__c.field-meta.xml
<CustomField>
    <fullName>IsPolicyHolder__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This flag is used to identify policy holder</description>
    <label>Is Individual Policy Holder?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SSP_InsuranceCoveredIndiv__c/fields/SSP_InsurancePolicy__c.field-meta.xml
<CustomField>
    <fullName>SSP_InsurancePolicy__c</fullName>
    <description>This field is used to indicate Insurance Policy of an Insurance Covered Individual</description>
    <label>SSP_InsurancePolicy</label>
    <referenceTo>SSP_InsurancePolicy__c</referenceTo>
    <relationshipName>SSP_InsuranceCoveredIndiv</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_InsuranceCoveredIndiv__c/fields/SSP_Member__c.field-meta.xml
<CustomField>
    <fullName>SSP_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to indicate the member of an Insurance Covered Individual</description>
    <label>SSP_Member</label>
    <referenceTo>SSP_Member__c</referenceTo>
    <relationshipName>SSP_InsuranceCoveredIndiv</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SSP_InsuranceCoveredIndiv__c/recordTypes/InsuranceCoveredIndividual.recordType-meta.xml
<RecordType>
    <fullName>InsuranceCoveredIndividual</fullName>
    <active>true</active>
    <description>This is used to store Insurance Covered Individual details.</description>
    <label>Insurance Covered Individual</label>
</RecordType>

force-app/main/default/objects/SSP_InsuranceCoveredIndiv__c/recordTypes/InsuranceExternalCoveredIndividual.recordType-meta.xml
<RecordType>
    <fullName>InsuranceExternalCoveredIndividual</fullName>
    <active>true</active>
    <description>This is used to store external covered individual details</description>
    <label>Insurance External Covered Individual</label>
</RecordType>

force-app/main/default/objects/SSP_InsuranceCoveredIndiv__c/recordTypes/InsuranceExternalPolicyHolder.recordType-meta.xml
<RecordType>
    <fullName>InsuranceExternalPolicyHolder</fullName>
    <active>true</active>
    <description>This is used to store external policy holder details of individual.</description>
    <label>Insurance External Policy Holder</label>
</RecordType>

force-app/main/default/objects/SSP_InsurancePolicy__c/SSP_InsurancePolicy__c.object-meta.xml
<CustomObject>
    <description>Holds details about insurance company, policy and external policy holder.</description>
    <label>SSP InsurancePolicy</label>
    <nameField>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>SSP_InsurancePolicy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SSP InsurancePolicies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_InsurancePolicy__c/fields/InsuranceCompanyName__c.field-meta.xml
<CustomField>
    <fullName>InsuranceCompanyName__c</fullName>
    <description>Health coverage company name</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Insurance Company Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_InsurancePolicy__c/recordTypes/InsurancePolicyDetail.recordType-meta.xml
<RecordType>
    <fullName>InsurancePolicyDetail</fullName>
    <active>true</active>
    <description>This is used to store Insurance Policy details.</description>
    <label>Insurance Policy Detail</label>
</RecordType>

force-app/main/default/objects/SSP_Member__c/SSP_Member__c.object-meta.xml
<CustomObject>
    <description>Stores details about an individual member of a case/application such as gatepost reponse, incarceration, disability, living arrangement, pregnancy, address details. Also repurposed to store information of different individuals in the form of individual alien, alien sponsor, care taker,  care coordinator etc.</description>
    <label>SSP Member</label>
    <nameField>
        
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        
        <label>SSP_Member Name</label>
        
        <type>Text</type>
        
    </nameField>
    <pluralLabel>SSP Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Member__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>This field is used to indicate the related contact for a member</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>SSP_Member</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/PrimaryPhoneExtension__c.field-meta.xml
<CustomField>
    <fullName>PrimaryPhoneExtension__c</fullName>
    <description>This field is used to store primary phone extension of a member</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Primary Phone Extension</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/PrimaryPhoneNumber__c.field-meta.xml
<CustomField>
    <fullName>PrimaryPhoneNumber__c</fullName>
    <description>This field is used to store primary phone number of a member</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Primary Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/globalValueSets/BenefitPrograms.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>MA</fullName>
        
        
        <label>Medicaid/KCHIP</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>KT</fullName>
        
        
        <label>KTAP (Cash Assistance)</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SN</fullName>
        
        
        <label>SNAP (Food Assistance)</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SS</fullName>
        
        
        <label>State Supplementation</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>DS</fullName>
        
        
        <label>DSNAP</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>CC</fullName>
        
        
        <label>Child Care Assistance</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>KP</fullName>
        
        
        <label>KI-HIPP (Health Insurance Premium Payments)</label>
        
    </customValue>
    
    <description>Different type of Benefit Programs available for a Citizen</description>
    
    <masterLabel>Benefit Programs</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/globalValueSets/YesNo.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>Y</fullName>
        
        
        <label>YES</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>N</fullName>
        
        
        <label>NO</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>U</fullName>
        
        
        <label>Unknown</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>NULL</fullName>
        
        
        <label>NULL</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>H</fullName>
        
        
        <label>Historical</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>I don&apos;t know</fullName>
        
        
        <label>I don&apos;t know</label>
        
    </customValue>
    
    <description>Used to store different types of toggle picklist values</description>
    
    <masterLabel>YesNo</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/classes/SSP_EnrollmentDetailsCtrlTest.cls
/*
* classname     : SSP_EnrollmentDetailsCtrlTest
* @description  : This Test class is use to increase coverage of SSP_EnrollmentDetailsCtrl
* @author       : Ashwin Kasture
* @date         : 12/1/2020
* MODIFICATION LOG:
* DEVELOPER             DATE            DESCRIPTION
* ---------------------------------------------------------------------------------------------
* Ashwin Kasture        12/1/2020      Initial Version
*/
@isTest(seeAllData=false)
public class SSP_EnrollmentDetailsCtrlTest {
	/*
	* method        : setup()
	* @description  : This method is use to set up the Test Data.
	* @author       : Ashwin Kasture	
	* @return       : Void
	* */
    @TestSetup static void setup() { 
    	SSP_TestDataFactory.setupTestData();
        
        List<Account> lstAcc = SSP_TestDataFactory.createAccounts(1, false);
        lstAcc[0].Name = 'EnrollmentDetail';
        lstAcc = ESAPI.accessController().insertAsUser(lstAcc, SSP_Utility.getFieldsNamesList (lstAcc)).getInsertedObjects();
        
        List<Contact> lstCon = (List<Contact>)SSP_Utility.fetchRecords(new Map<String, String>{'objectName'=>'Contact','operator'=>'AND'}, new Set<String>{'Id', 'FirstName', 'LastName'}, new Map<String, String>{'FirstName'=>'Citizen','LastName'=>'User'});
        
        AccountContactRelation acr = new AccountContactRelation(); 
        acr.Accountid = lstAcc[0].Id;
        acr.Contactid = lstCon[0].Id;
        acr.IsActive = true;
        acr = (AccountContactRelation)ESAPI.accessController().insertAsUser(new List<AccountContactRelation>{acr}, SSP_Utility.getFieldsNamesList (new List<AccountContactRelation>{acr})).getInsertedObjects()[0];       
        
        List<SSP_Application__c> lstAppln = SSP_TestDataFactory.createSSPApplications(1, false);
        lstAppln[0].Account__c=lstAcc[0].Id;        
        lstAppln[0].Contact__c = lstCon[0].Id;
        lstAppln[0].EnrolledInHealthCareCoverageToggle__c = 'Y';
        lstAppln= ESAPI.accessController().insertAsUser(lstAppln, SSP_Utility.getFieldsNamesList (lstAppln)).getInsertedObjects();
        
        List<SSP_Member__c> lstMem = SSP_TestDataFactory.createSSPMembers(1, false);
        lstMem[0].contact__c=lstCon[0].Id;  
        lstMem[0].PrimaryPhoneExtension__c ='7348789790';
        lstMem[0].PrimaryPhoneNumber__c ='8983838290';
        lstMem = ESAPI.accessController().insertAsUser(lstMem, SSP_Utility.getFieldsNamesList (lstMem)).getInsertedObjects();
        
        List<SSP_ApplicationIndividual__c> lstAppInd = SSP_TestDataFactory.createApplicationIndividuals(1, false); 
        lstAppInd[0].SSP_Application__c=lstAppln[0].Id;
        lstAppInd[0].SSP_Member__c=lstMem[0].Id;
        lstAppInd = ESAPI.accessController().insertAsUser(lstAppInd, SSP_Utility.getFieldsNamesList (lstAppInd)).getInsertedObjects();
        
        System.runAs(fetchCitizenUser()) {
        	List<SSP_InsurancePolicy__c> lstInsurancePolicy = SSP_TestDataFactory.createInsurancePolicyRecords(1, false);            
            String insurancePolicyDetailRecTypeId = SSP_TestDataFactory.getRecordTypeMapping('SSP_InsurancePolicy__c').get('InsurancePolicyDetail');
            lstInsurancePolicy[0].InsuranceCompanyName__c='Company Name';
            lstInsurancePolicy[0].RecordTypeId = insurancePolicyDetailRecTypeId;        
            lstInsurancePolicy = ESAPI.accessController().insertAsUser(lstInsurancePolicy, SSP_Utility.getFieldsNamesList (lstInsurancePolicy)).getInsertedObjects();
            
            List<SSP_InsuranceCoveredIndiv__c> lstInsuranceCovInd = SSP_TestDataFactory.createInsuranceCoveredIndividuals(1, false);            
            String insuranceCovedIndRecTypeId = SSP_TestDataFactory.getRecordTypeMapping('SSP_InsuranceCoveredIndiv__c').get('InsuranceCoveredIndividual');
            lstInsuranceCovInd[0].SSP_InsurancePolicy__c = lstInsurancePolicy[0].Id;
            lstInsuranceCovInd[0].RecordTypeId = insuranceCovedIndRecTypeId;
            lstInsuranceCovInd[0].IsPolicyHolder__c = true;
            lstInsuranceCovInd = ESAPI.accessController().insertAsUser(lstInsuranceCovInd, SSP_Utility.getFieldsNamesList (lstInsuranceCovInd)).getInsertedObjects();
        }
    }
    
    private static User fetchCitizenUser() {
        return ((List<User>)SSP_Utility.fetchRecords(new Map<String, String>{'objectName'=>'User'}, new Set<String>{'Id'}, new Map<String, String>{'UserName'=>'citizen@abc.xyz','limit'=>'1'}))[0];        
    }
    
    /*
    * method        : test_getEnrollmentDetails
    * @description  : This method is use to get cover getEnrollmentDetails() method of SSP_EnrollmentDetailsCtrl class
    * @author       : Ashwin Kasture    
    * @return       : void
    * */
    @isTest
    public static void test_getEnrollmentDetails() {
        System.runAs(fetchCitizenUser()) {
            List<SSP_Application__c> appIndvList = [Select Id From SSP_Application__c];
            List<SSP_InsurancePolicy__c> lstInsurancePolicy = [Select Id From SSP_InsurancePolicy__c];
            List<SSP_InsuranceCoveredIndiv__c> lstInsuranceCovInd = [Select Id,RecordTypeId,IsPolicyHolder__c From SSP_InsuranceCoveredIndiv__c];
            Test.startTest();
            SSP_LightningResponse objResp = new SSP_LightningResponse();
            objResp = SSP_EnrollmentDetailsCtrl.getEnrollmentDetails(appIndvList[0].Id,lstInsurancePolicy[0].Id, true);
            system.assert(objResp.bIsSuccess, true);
            
            SSP_LightningResponse objResp2 = new SSP_LightningResponse();            
            String insuranceExtPolicyHolderRecTypeId = SSP_TestDataFactory.getRecordTypeMapping('SSP_InsuranceCoveredIndiv__c').get('InsuranceExternalPolicyHolder');
            lstInsuranceCovInd[0].RecordTypeId = insuranceExtPolicyHolderRecTypeId;
            lstInsuranceCovInd[0].IsPolicyHolder__c = true;            
            ESAPI.accessController().updateAsUser(new Map<Id, SSP_InsuranceCoveredIndiv__c>(lstInsuranceCovInd), SSP_Utility.getFieldsNamesList(lstInsuranceCovInd));
            objResp2 = SSP_EnrollmentDetailsCtrl.getEnrollmentDetails(appIndvList[0].Id,lstInsurancePolicy[0].Id, true);
                        
            String insuranceCovedIndRecTypeId = SSP_TestDataFactory.getRecordTypeMapping('SSP_InsuranceCoveredIndiv__c').get('InsuranceCoveredIndividual');
            lstInsuranceCovInd[0].RecordTypeId = insuranceCovedIndRecTypeId;
            lstInsuranceCovInd[0].IsPolicyHolder__c = false;
            ESAPI.accessController().updateAsUser(new Map<Id, SSP_InsuranceCoveredIndiv__c>(lstInsuranceCovInd), SSP_Utility.getFieldsNamesList(lstInsuranceCovInd));
            objResp2 = SSP_EnrollmentDetailsCtrl.getEnrollmentDetails(appIndvList[0].Id,lstInsurancePolicy[0].Id, true);
            
            String insuranceExtCoveredIndRecTypeId = SSP_TestDataFactory.getRecordTypeMapping('SSP_InsuranceCoveredIndiv__c').get('InsuranceExternalCoveredIndividual');
            lstInsuranceCovInd[0].RecordTypeId = insuranceExtCoveredIndRecTypeId;
            lstInsuranceCovInd[0].IsPolicyHolder__c = false;
            ESAPI.accessController().updateAsUser(new Map<Id, SSP_InsuranceCoveredIndiv__c>(lstInsuranceCovInd), SSP_Utility.getFieldsNamesList(lstInsuranceCovInd));
            objResp2 = SSP_EnrollmentDetailsCtrl.getEnrollmentDetails(appIndvList[0].Id,lstInsurancePolicy[0].Id, true);
            system.assert(objResp2.bIsSuccess, true);
            
            SSP_LightningResponse objCatchResp = new SSP_LightningResponse();
            objCatchResp = SSP_EnrollmentDetailsCtrl.getEnrollmentDetails(null,null,null);
            system.assertEquals(objCatchResp.bIsSuccess, false);
            Test.stopTest();
        }
    }
    
    /*
    * method        : test_storeEnrollmentDetailsData
    * @description  : This method is use to get cover storeEnrollmentDetailsData() method of SSP_EnrollmentDetailsCtrl class
    * @author       : Ashwin Kasture    
    * @return       : void
    * */
    @isTest
    public static void test_storeEnrollmentDetailsData() {
        System.runAs(fetchCitizenUser()) {			
            {
                List<SSP_InsuranceCoveredIndiv__c> lstInsuranceCovInd = [Select Id From SSP_InsuranceCoveredIndiv__c]; 
                List<SSP_Member__c> lstMem = [Select Id From SSP_Member__c];
                
                String strResp = '{'+
                    '"bDoNotHaveAllInformation" : false,'+
                    '"bIsEnrolledInInsurance" : true,'+
                    '"sPolicyHolderMemberIdDelete": '+'"'+String.valueOf(lstInsuranceCovInd[0].Id)+'",'+
                    '"objPolicyHolder" : {"sMemberId" : '+'"'+String.valueOf(lstMem[0].Id)+'"}'+
                    '}';
                Test.startTest();
                SSP_LightningResponse objResp = new SSP_LightningResponse();
                objResp = SSP_EnrollmentDetailsCtrl.storeEnrollmentDetailsData(strResp);
                system.assert(objResp.bIsSuccess, true);
                
                SSP_LightningResponse objResp1 = new SSP_LightningResponse();
            	String strResp1 = '{'+
                    '"bDoNotHaveAllInformation" : false,'+
                    '"bIsEnrolledInInsurance" : true,'+
                    '"objOutsidePolicyHolder": {"sCoveredIndFirstName":"Test"}'+
                    '}';
            	objResp1 = SSP_EnrollmentDetailsCtrl.storeEnrollmentDetailsData(strResp1);
                system.assert(objResp1.bIsSuccess, true);
                
                SSP_LightningResponse objResp2 = new SSP_LightningResponse();
            	String strResp2 = '{'+
                    '"bDoNotHaveAllInformation" : false,'+
                    '"bIsEnrolledInInsurance" : true'+
                    '}';
            	objResp2 = SSP_EnrollmentDetailsCtrl.storeEnrollmentDetailsData(strResp2);
                system.assert(objResp2.bIsSuccess, true);
                
                SSP_LightningResponse objResp3 = new SSP_LightningResponse();
            	String strResp3 = '{'+
                    '"bDoNotHaveAllInformation" : false,'+
                    '"bIsEnrolledInInsurance" : true,'+
                    '"lstCoveredInd" : [{"sMemberId" :'+'"'+String.valueOf(lstMem[0].Id)+'"}],'+
                    '"lstOutsideCoveredInd" : [{"sCoveredIndFirstName" : "Test"}]'+
                    '}';
            	objResp3 = SSP_EnrollmentDetailsCtrl.storeEnrollmentDetailsData(strResp3);
                system.assert(objResp3.bIsSuccess, true);
                
                SSP_LightningResponse objCatchResp = new SSP_LightningResponse();
                objCatchResp = SSP_EnrollmentDetailsCtrl.storeEnrollmentDetailsData(null);
                system.assertEquals(objCatchResp.bIsSuccess, false);
                Test.stopTest();
            }
        }
    }
    
    /*
    * method        : test_storeEnrollmentDeleteCoverInd
    * @description  : This method is use to get cover storeEnrollmentDetailsData() method of SSP_EnrollmentDetailsCtrl class
    * @author       : Ashwin Kasture    
    * @return       : void
    * */
    @isTest
    public static void test_storeEnrollmentDeleteCoverInd() {
        List<SSP_InsurancePolicy__c> lstInsurancePolicy = [Select Id From SSP_InsurancePolicy__c];
        List<SSP_Member__c> lstMem = [Select Id From SSP_Member__c];        
        System.runAs(fetchCitizenUser()) {
            List<SSP_InsuranceCoveredIndiv__c> lstInsuranceCovInd = SSP_TestDataFactory.createInsuranceCoveredIndividuals(1, false);        
            String insuranceCovedIndRecTypeId = SSP_TestDataFactory.getRecordTypeMapping('SSP_InsuranceCoveredIndiv__c').get('InsuranceCoveredIndividual');
            lstInsuranceCovInd[0].SSP_InsurancePolicy__c = lstInsurancePolicy[0].Id;
            lstInsuranceCovInd[0].SSP_Member__c = lstMem[0].Id;
            lstInsuranceCovInd[0].RecordTypeId = insuranceCovedIndRecTypeId;
            lstInsuranceCovInd[0].IsPolicyHolder__c = false;             
            lstInsuranceCovInd = ESAPI.accessController().insertAsUser(lstInsuranceCovInd, SSP_Utility.getFieldsNamesList (lstInsuranceCovInd)).getInsertedObjects();        
            SSP_LightningResponse objResp = new SSP_LightningResponse();
            String strResp = '{'+
                '"bDoNotHaveAllInformation" : false,'+
                '"bIsEnrolledInInsurance" : true,'+
                '"sInsurancePolicyId" : "'+String.valueOf(lstInsurancePolicy[0].Id)+'",'+                    
                '"lstCoveredIndDelete" : ["'+String.valueOf(lstMem[0].Id)+'"]'+
                '}';
            Test.startTest();
            objResp = SSP_EnrollmentDetailsCtrl.storeEnrollmentDetailsData(strResp);
            system.assert(objResp.bIsSuccess, true); 
            Test.stopTest();
        }
    }
    
    /*
    * method        : test_storeEnrollmentDeleteOutsideCovInd
    * @description  : This method is use to get cover storeEnrollmentDetailsData() method of SSP_EnrollmentDetailsCtrl class
    * @author       : Ashwin Kasture    
    * @return       : void
    * */
    @isTest
    public static void test_storeEnrollmentDeleteOutsideCovInd() {
        List<SSP_InsurancePolicy__c> lstInsurancePolicy = [Select Id From SSP_InsurancePolicy__c];
        List<SSP_InsuranceCoveredIndiv__c> lstInsuranceCovInd = SSP_TestDataFactory.createInsuranceCoveredIndividuals(1, false);        
        System.runAs(fetchCitizenUser()) {
            String insuranceCovedIndRecTypeId = SSP_TestDataFactory.getRecordTypeMapping('SSP_InsuranceCoveredIndiv__c').get('InsuranceCoveredIndividual');
            lstInsuranceCovInd[0].SSP_InsurancePolicy__c = lstInsurancePolicy[0].Id;        
            lstInsuranceCovInd[0].RecordTypeId = insuranceCovedIndRecTypeId;
            lstInsuranceCovInd[0].IsPolicyHolder__c = false;             
            lstInsuranceCovInd = ESAPI.accessController().insertAsUser(lstInsuranceCovInd, SSP_Utility.getFieldsNamesList (lstInsuranceCovInd)).getInsertedObjects();
            
            SSP_LightningResponse objResp = new SSP_LightningResponse();
            String strResp = '{'+
                '"bDoNotHaveAllInformation" : false,'+
                '"bIsEnrolledInInsurance" : true,'+
                '"sInsurancePolicyId" : "'+String.valueOf(lstInsurancePolicy[0].Id)+'",'+
                '"lstOutsideCoveredIndDelete" : ["'+String.valueOf(lstInsuranceCovInd[0].Id)+'"]'+					
                '}';
            Test.startTest();
            objResp = SSP_EnrollmentDetailsCtrl.storeEnrollmentDetailsData(strResp);
            system.assert(objResp.bIsSuccess, true); 
            Test.stopTest();
        }
    }
    
    @isTest
    public static void isRequiredTest(){
        SSP_EnrollmentScreenQueueRule queueRule = new SSP_EnrollmentScreenQueueRule();
        Boolean isRequired = false;
        Map<String,SSP_ApplicationIndividual__c> memberAppIndividualMap = new Map<String,SSP_ApplicationIndividual__c>();
        SSP_Member__c objMember = [SELECT ID FROM SSP_Member__c Limit 1];
        SSP_Application__c objApp = [SELECT ID FROM SSP_Application__c Limit 1];
        Context ctx = new Context();
        ContextData ctxData = new ContextData();
        QueuingWrapper queWrap = new QueuingWrapper();
        ctxData.MemberId = objMember.Id;
        ctxData.ApplicationId = objApp.Id;
        SSP_ApplicationIndividual__c objAppInd = [Select ID, SSP_Member__c, ProgramsApplied__c,SSP_Application__r.EnrolledInHealthCareCoverageToggle__c From SSP_ApplicationIndividual__c LIMIT 1];
        memberAppIndividualMap.put(objAppInd.SSP_Member__c,objAppInd);
        queWrap.memberAppIndividualMap = memberAppIndividualMap;
        ctxData.queueObject = queWrap;
        System.runAs(fetchCitizenUser()) {
            isRequired = queueRule.isRequired(ctx, ctxData);
        }
    }
}