force-app/main/default/objects/Account/recordTypes/Citizen.recordType-meta.xml
<RecordType>
    <fullName>Citizen</fullName>
    <active>true</active>
    <label>Citizen</label>
</RecordType>

force-app/main/default/objects/AccountContactRelation/fields/PermissionLevel_Medicaid__c.field-meta.xml
<CustomField>
    <fullName>PermissionLevel_Medicaid__c</fullName>
    <description>select the applicable permissions for this program</description>
    <label>Level of Permission CCAP</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Permission_Level</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AccountContactRelation/fields/RequestAccessPermission__c.field-meta.xml
<CustomField>
    <fullName>RequestAccessPermission__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Request Access Permission</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Related Account</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Citizen.recordType-meta.xml
<RecordType>
    <fullName>Citizen</fullName>
    <active>true</active>
    <description>This Record type is used for Residents</description>
    <label>Citizen</label>
</RecordType>

force-app/main/default/objects/SSP_Application__c/SSP_Application__c.object-meta.xml
<CustomObject>
    <description>To store SSP Application and Case data</description>
    <label>SSP Application</label>
    <nameField>
        
        <displayFormat>{000000000}</displayFormat>
        
        <label>SSP_Application Name</label>
        
        <type>AutoNumber</type>
        
    </nameField>
    <pluralLabel>SSP Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Application__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Shows the related Account to an Application</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>SSP_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_Application__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Shows the related Contact to an Application</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>SSP_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Permission_Level.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>ST</fullName>
        
        
        <label>Apply, Report Changes , Recertify</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>NT</fullName>
        
        
        <label>Apply, Report Changes , Recertify and receive copy of Notices</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SE</fullName>
        
        
        <label>Apply, Report Changes, Recertify and use EBT Card</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>CC</fullName>
        
        
        <label>Apply, Report Change, Recertify and receive checks made out to client</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>CA</fullName>
        
        
        <label>Apply, Report Change, Recertify and receive checks</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>ET</fullName>
        
        
        <label>Use EBT Card</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>PY</fullName>
        
        
        <label>Statutory Benefit Payee</label>
        
    </customValue>
    
    <description>Level of permissions for Auth Rep</description>
    
    <masterLabel>Permission Level</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/classes/SSP_SSPDCIntegrationServiceTest.cls
/*
* Classname     :  SSP_SSPDCIntegrationServiceTest
* @description  :  This class is the test class of SSP_SSPDCIntegrationService
* @author       :  Ragunathan
* @date         :  04/03/2019
* MODIFICATION LOG:
* DEVELOPER                     DATE                               DESCRIPTION
* ---------------------------------------------------------------------------------------------
* DeveloperName       MM/DD/YYYY          A Brief Description 
                               about the Change
**/
@isTest(seeAllData=false)
public class SSP_SSPDCIntegrationServiceTest {
    @TestSetup
    public static void setupMethod(){
        SSP_TestDataFactory.setupTestData();
        List<Account> lstAcc = SSP_TestDataFactory.createAccounts(1, false);
        lstAcc[0].Name = 'HealthSelectionCtrl';
        lstAcc = ESAPI.accessController().insertAsUser(lstAcc, SSP_Utility.getFieldsNamesList (lstAcc)).getInsertedObjects();
        
        List<Contact> lstCon = (List<Contact>)SSP_Utility.fetchRecords(new Map<String, String>{'objectName'=>'Contact','operator'=>'AND'}, new Set<String>{'Id', 'FirstName', 'LastName'}, new Map<String, String>{'FirstName'=>'Citizen','LastName'=>'User'});
        
        AccountContactRelation acr = new AccountContactRelation(); 
        acr.Accountid = lstAcc[0].Id;
        acr.Contactid = lstCon[0].Id;
        acr.IsActive = true;
        acr.RequestAccessPermission__c = '{   "PermissionLevel_Medicaid__c" : "true" }';
        acr = (AccountContactRelation)ESAPI.accessController().insertAsUser(new List<AccountContactRelation>{acr}, SSP_Utility.getFieldsNamesList (new List<AccountContactRelation>{acr})).getInsertedObjects()[0];       
        
        List<SSP_Application__c> lstAppln = SSP_TestDataFactory.createSSPApplications(1, false);
        lstAppln[0].Account__c=lstAcc[0].Id;        
        lstAppln[0].Contact__c = lstCon[0].Id;
        lstAppln= ESAPI.accessController().insertAsUser(lstAppln, SSP_Utility.getFieldsNamesList (lstAppln)).getInsertedObjects();
    }

    @isTest //SSP_Interface_Security Fixes
    static void shouldGetResponse() { 
        User citizen = getUserDetails();
        System.runAs(citizen){
            Test.setMock(HttpCalloutMock.class, new SSP_SSPDCIntegrationServiceMock(200)); 
            Test.startTest(); 
            Map<String, Object> objResponse = new Map<String, Object>();
            objResponse.put(SSP_InterfaceConstants.SUBMIT_TYPE,'Intake');
            
            List<String> APPLICABLE_SCREEN_LIST = new List<String>{'SSP_APP_Primary_Address','NA'};
            objResponse.put(SSP_InterfaceConstants.SCREEN_LIST,APPLICABLE_SCREEN_LIST);
            SSP_Application__c ssApp = [Select id, Account__c from SSP_Application__c limit 1];
            objResponse.put(SSP_InterfaceConstants.ACCOUNT_ID,ssApp.Account__c);
            objResponse.put(SSP_InterfaceConstants.APPLICATION_ID,ssApp.Id);
            objResponse.put(SSP_InterfaceConstants.IS_DEBUG, true);
            List<Object> lstReturnedData = IntegrationFactory.invokeCallout(
                SSP_InterfaceConstants.SSP_DC, 
                objResponse);
            //System.assertEquals(1, lstReturnedData.Size(),'Correct Output');
            Test.stopTest();   
        }
    }
    @isTest 
    static void shouldGetException() { 
        User citizen = getUserDetails();
        System.runAs(citizen){
            Test.setMock(HttpCalloutMock.class, new SSP_SSPDCIntegrationServiceMock(200)); 
            Test.startTest(); 
            Map<String, Object> objResponse = new Map<String, Object>();
            List<String> APPLICABLE_SCREEN_LIST = new List<String>{'SSP_APP_Primary_Address','NA'};
            objResponse.put(SSP_InterfaceConstants.SCREEN_LIST,APPLICABLE_SCREEN_LIST);
            SSP_Application__c ssApp = [Select id, Account__c from SSP_Application__c limit 1];
            objResponse.put(SSP_InterfaceConstants.ACCOUNT_ID,ssApp.Account__c);
            objResponse.put(SSP_InterfaceConstants.APPLICATION_ID,ssApp.Id);
            objResponse.put(SSP_InterfaceConstants.IS_DEBUG, true);
            List<Object> lstReturnedData = IntegrationFactory.invokeCallout(
                SSP_InterfaceConstants.SSP_DC, 
                objResponse);
            //System.assertEquals(1, lstReturnedData.Size(),'Correct Output');
            Test.stopTest();   
        }
    }
    @isTest 
    static void shouldGetFailureResponse() { 
        User citizen = getUserDetails();
        System.runAs(citizen){
            Test.setMock(HttpCalloutMock.class, new SSP_SSPDCIntegrationServiceErrorMock()); 
            Test.startTest(); 
            Map<String, Object> objResponse = new Map<String, Object>();
            objResponse.put(SSP_InterfaceConstants.SUBMIT_TYPE,'INTAKE');
            SSP_Application__c ssApp = [Select id, Account__c from SSP_Application__c limit 1];
            objResponse.put(SSP_InterfaceConstants.ACCOUNT_ID,ssApp.Account__c);
            objResponse.put(SSP_InterfaceConstants.APPLICATION_ID,ssApp.Id);
            List<String> APPLICABLE_SCREEN_LIST = new List<String>{'SSP_APP_Primary_Address','NA'};
            objResponse.put(SSP_InterfaceConstants.SCREEN_LIST,APPLICABLE_SCREEN_LIST);
            objResponse.put(SSP_InterfaceConstants.IS_DEBUG, true);
            List<Object> lstReturnedData = IntegrationFactory.invokeCallout(
                SSP_InterfaceConstants.SSP_DC, 
                objResponse);
            System.assertEquals(2, lstReturnedData.Size(),'Correct Output');
            Test.stopTest(); 
        }      
    }
    
    
    
    public class SSP_SSPDCIntegrationServiceMock implements HttpCalloutMock{
        public Integer statusCode;
        public SSP_SSPDCIntegrationServiceMock(Integer statusCode){
            this.statusCode = statusCode;
        }
        public HTTPResponse respond(HTTPRequest req) {
            httpResponse response = new HttpResponse();
            response.setStatusCode(this.statusCode);
            response.setBody(responseBody);
            return response;
        }
        
        String responseBody =   '    {    '+
                                '    "SubmitApplicationResponse": {    '+
                                '    "AckResponse": {    '+
                                '    "AckResponseCode": "INT0000",    '+
                                '    "AckResponseDescription": "Success"    '+
                                '    }    '+
                                '    }    '+
                                '    }    ';
    }
    
    static String RACSelectionDetail =  '    [    '+
                                        '    {    '+
                                        '    "memberId": "a0ir0000001wTFfAAM",    '+
                                        '    "selectedScreens": [    '+
                                        '    {    '+
                                        '    "screens": "SSP_APP_Primary_Address,SSP_APP_Primary_Contact",    '+
                                        '    "flowName": "ContactInformation"    '+
                                        '    },    '+
                                        '    {    '+
                                        '    "screens": "SSP_APP_RTF_TaxFiling,SSP_APP_RTF_Relationships",    '+
                                        '    "flowName": "Relationships&TaxFiling"    '+
                                        '    },    '+
                                        '    {    '+
                                        '    "screens": "SSP_APP_Details_MedicareCoverageSummary",    '+
                                        '    "flowName": "MemberHealthInformation"    '+
                                        '    }    '+
                                        '    ]    '+
                                        '    }    '+
                                        '    ]    ';
    
    public class SSP_SSPDCIntegrationServiceErrorMock implements HttpCalloutMock {
        public HttpResponse respond(HttpRequest request) {
            CalloutException e = (CalloutException)CalloutException.class.newInstance();
            e.setMessage('Read Time Out');
            throw e;
        }
    }
    private static User getUserDetails(){
        User citizen  = [SELECT Id, ContactId,Name FROM User WHERE UserName = 'citizen@abc.xyz' LIMIT 1];
        return citizen;
    }
}