force-app/main/default/objects/Account/recordTypes/Citizen.recordType-meta.xml
<RecordType>
    <fullName>Citizen</fullName>
    <active>true</active>
    <label>Citizen</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Related Account</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Citizen.recordType-meta.xml
<RecordType>
    <fullName>Citizen</fullName>
    <active>true</active>
    <description>This Record type is used for Residents</description>
    <label>Citizen</label>
</RecordType>

force-app/main/default/objects/SSP_Application__c/SSP_Application__c.object-meta.xml
<CustomObject>
    <description>To store SSP Application and Case data</description>
    <label>SSP Application</label>
    <nameField>
        
        <displayFormat>{000000000}</displayFormat>
        
        <label>SSP_Application Name</label>
        
        <type>AutoNumber</type>
        
    </nameField>
    <pluralLabel>SSP Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Application__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Shows the related Account to an Application</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>SSP_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_Application__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Shows the related Contact to an Application</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>SSP_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/SSP_ApplicationIndividual__c.object-meta.xml
<CustomObject>
    <description>Custom junction object to maintain association between member and application</description>
    <label>SSP ApplicationIndividual</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>SSP_ApplicationIndividual Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SSP ApplicationIndividuals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/SSP_Application__c.field-meta.xml
<CustomField>
    <fullName>SSP_Application__c</fullName>
    <description>Indicates the application related to a member</description>
    <label>SSP_Application</label>
    <referenceTo>SSP_Application__c</referenceTo>
    <relationshipName>SSP_ApplicationIndividuals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/SSP_Member__c.field-meta.xml
<CustomField>
    <fullName>SSP_Member__c</fullName>
    <description>Indicates the member related to an application</description>
    <label>SSP_Member</label>
    <referenceTo>SSP_Member__c</referenceTo>
    <relationshipName>SSP_ApplicationIndividuals</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_Benefits__c/SSP_Benefits__c.object-meta.xml
<CustomObject>
    <description>Stores benefit details such as household, individual, out of state, SSI benefits etc.</description>
    <label>SSP Benefits</label>
    <nameField>
        
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        
        <label>SSP_Benefits Name</label>
        
        <type>Text</type>
        
    </nameField>
    <pluralLabel>SSP Benefits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Benefits__c/fields/BenefitTypeCode__c.field-meta.xml
<CustomField>
    <fullName>BenefitTypeCode__c</fullName>
    <description>This field is used to store Benefits type for which benefits are available for a member</description>
    <label>Benefit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BenefitTypeCode</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Benefits__c/fields/SSP_Member__c.field-meta.xml
<CustomField>
    <fullName>SSP_Member__c</fullName>
    <description>This field is used to indicate the member for a particular Benefit record</description>
    <label>SSP_Member</label>
    <referenceTo>SSP_Member__c</referenceTo>
    <relationshipName>SSP_Benefits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_Benefits__c/fields/StatusofApplication__c.field-meta.xml
<CustomField>
    <fullName>StatusofApplication__c</fullName>
    <description>This field is used to store status of application for which benefits are available for a member</description>
    <label>Status Of Application</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetDefinition>
            
            
                <value>
                
                    <fullName>AI</fullName>
                
                
                    <label>Pending Application</label>
                
                </value>
            
                <value>
                
                    <fullName>AE</fullName>
                
                
                    <label>Pending Appeal</label>
                
                </value>
            
                <value>
                
                    <fullName>DN</fullName>
                
                
                    <label>Denied</label>
                
                </value>
            
                <value>
                
                    <fullName>TR</fullName>
                
                
                    <label>Discontinued</label>
                
                </value>
            
                <value>
                
                    <fullName>A</fullName>
                
                
                    <label>Applied</label>
                
                </value>
            
                <value>
                
                    <fullName>P</fullName>
                
                
                    <label>Not Applied</label>
                
                </value>
            
            </valueSetDefinition>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Benefits__c/recordTypes/EntitledBenefit.recordType-meta.xml
<RecordType>
    <fullName>EntitledBenefit</fullName>
    <active>true</active>
    <description>This record type is used to store entitled benefits.</description>
    <label>EntitledBenefit</label>
</RecordType>

force-app/main/default/objects/SSP_Member__c/SSP_Member__c.object-meta.xml
<CustomObject>
    <description>Stores details about an individual member of a case/application such as gatepost reponse, incarceration, disability, living arrangement, pregnancy, address details. Also repurposed to store information of different individuals in the form of individual alien, alien sponsor, care taker,  care coordinator etc.</description>
    <label>SSP Member</label>
    <nameField>
        
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        
        <label>SSP_Member Name</label>
        
        <type>Text</type>
        
    </nameField>
    <pluralLabel>SSP Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Member__c/fields/BenefitTypeCode__c.field-meta.xml
<CustomField>
    <fullName>BenefitTypeCode__c</fullName>
    <description>This field is used to store disability benefits type</description>
    <label>Disability Benefits</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>BlindnessDisabilityStatus</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>This field is used to indicate the related contact for a member</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>SSP_Member</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/BenefitTypeCode.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>BL</fullName>
        
        
        <label>Black Lung</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>IR</fullName>
        
        
        <label>IRA at 59 and 1/2 Years</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>RR</fullName>
        
        
        <label>RailRoad Retirement</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>RS</fullName>
        
        
        <label>Social Security Retirement, Survivor&apos;s, and Disability Insurance (RSDI)</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>UMWA</fullName>
        
        
        <label>UMWA</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>UI</fullName>
        
        
        <label>Unemployment Insurance</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>VC</fullName>
        
        
        <label>VA Compensation</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>VP</fullName>
        
        
        <label>VA Pension</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>WC</fullName>
        
        
        <label>Worker&apos;s Compensation</label>
        
    </customValue>
    
    <description>Entitled Benefits</description>
    
    <masterLabel>Benefit Type Code</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/globalValueSets/BlindnessDisabilityStatus.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>SS</fullName>
        
        
        <label>Social Security</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>RR</fullName>
        
        
        <label>Railroad Retirement</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>BL</fullName>
        
        
        <label>Black Lung</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>WC</fullName>
        
        
        <label>Worker&apos;s Compensation</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>LWC</fullName>
        
        
        <label>Lifetime Worker&apos;s Compensation</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>VA</fullName>
        
        
        <label>VA</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>PBD</fullName>
        
        
        <label>Pension based on disability</label>
        
    </customValue>
    
    <description>Used to store Blindness, disability status</description>
    
    <masterLabel>BlindnessDisabilityStatus</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/classes/SSP_EntitledBenefitsControllerTest.cls
/*
* classname     :  SSP_EntitledBenefitsControllerTest
* @description  :  Test class for SSP_EntitledBenefitsController
* @author       :  Shrikant Raut   
* @date         :  12/17/2019
* MODIFICATION LOG:
* DEVELOPER                     DATE                               DESCRIPTION
* ---------------------------------------------------------------------------------------------

**/

@isTest(seeAllData=false)
public class SSP_EntitledBenefitsControllerTest {
 /**
@author : Shrikant Raut
Method to setup test data*/ 
    @testSetup static void setup() { 
        SSP_TestDataFactory.setupTestData();  
        
        List<Account> lstAcc = SSP_TestDataFactory.createAccounts(1, false);
        lstAcc[0].Name = 'BenefitsController';
        insert lstAcc;
        
        List<Contact> lstCon = [SELECT Id, FirstName, LastName FROM Contact WHERE FirstName = 'Citizen' AND LastName = 'User' LIMIT 1];//= SSP_TestDataFactory.createContacts(1, false); 
        
        AccountContactRelation acr = new AccountContactRelation(); 
        acr.Accountid = lstAcc[0].Id;
        acr.Contactid = lstCon[0].Id;
        acr.IsActive = true;
        insert acr;
        
        List<SSP_Application__c> lstAppln = SSP_TestDataFactory.createSSPApplications(1, false);
        lstAppln[0].Account__c=lstAcc[0].Id;        
        lstAppln[0].Contact__c = lstCon[0].Id;
        insert lstAppln;
        
        List<SSP_Member__c> lstMem = SSP_TestDataFactory.createSSPMembers(1, false);
        lstMem[0].contact__c=lstCon[0].Id;  
        insert lstMem;
        
        List<SSP_Benefits__c> lstbenefits = SSP_TestDataFactory.createBenefitRecords(4, 'EntitledBenefit',false);
        lstbenefits[0].SSP_Member__c = lstMem[0].Id;
        lstbenefits[1].SSP_Member__c = lstMem[0].Id;
        lstbenefits[2].SSP_Member__c = lstMem[0].Id;
        lstbenefits[3].SSP_Member__c = lstMem[0].Id;
        insert lstbenefits;
        
        
        List<SSP_ApplicationIndividual__c> lstAppInd = SSP_TestDataFactory.createApplicationIndividuals(1, false); 
        lstAppInd[0].SSP_Application__c=lstAppln[0].Id;
        lstAppInd[0].SSP_Member__c=lstMem[0].Id;
        insert lstAppInd;   
        
    }
    
    /**
    @author : Shrikant Raut
    Test Method to test fetchExistingIncomeDetails method*/
    @isTest
    public static void test_fetchBenefitDetails(){
        User citizen  = [SELECT Id FROM User WHERE UserName = 'citizen@abc.xyz' LIMIT 1][0];
        System.runAs(citizen){
            List<SSP_ApplicationIndividual__c> appIndvList = [SELECT Id, SSP_Member__c, SSP_Application__c FROM SSP_ApplicationIndividual__c WHERE SSP_Application__r.Account__r.Name = 'BenefitsController'];
            List<SSP_Benefits__c> benefitList = [SELECT Id, StatusofApplication__c, BenefitTypeCode__c FROM SSP_Benefits__c WHERE SSP_Member__c = :appIndvList[0].SSP_Member__c];
                        
            test.startTest();            
            SSP_LightningResponse response = SSP_EntitledBenefitsController.fetchBenefitDetails(appIndvList[0].SSP_Member__c, appIndvList[0].SSP_Application__c, 'sspEntitledBenefits');
            system.assertNotEquals(null, response.mapResponse);
            system.assert(response.mapResponse.containsKey('applicationIndividual'));  
            system.assert(response.mapResponse.containsKey('benefitsRecords'));            
            test.stopTest();	
        }
        
    }
    
        /**
@author : Shrikant Raut
Test Method to test fetchExistingIncomeDetails method*/
    @isTest
    public static void test_updateBenefits(){
        User citizen  = [SELECT Id FROM User WHERE UserName = 'citizen@abc.xyz' LIMIT 1][0];
        System.runAs(citizen){
            List<SSP_ApplicationIndividual__c> appIndvList = [SELECT Id, SSP_Member__c, SSP_Application__c FROM SSP_ApplicationIndividual__c WHERE SSP_Application__r.Account__r.Name = 'BenefitsController'];
            List<SSP_Benefits__c> benefitList = [SELECT Id, SSP_Member__c, StatusofApplication__c, BenefitTypeCode__c FROM SSP_Benefits__c WHERE SSP_Member__c = :appIndvList[0].SSP_Member__c];
            Map<String, String>  detailMap = new Map<String, String>{
                'toUpsert'=> JSON.serialize(new List<SSP_Benefits__c>{new SSP_Benefits__c(SSP_Member__c = benefitList[0].SSP_Member__c)}),
                    'toDelete'=> JSON.serialize(benefitList)
            };
            test.startTest();
            system.assertEquals([SELECT COUNT() FROM SSP_Benefits__c WHERE SSP_Member__c = :appIndvList[0].SSP_Member__c], benefitList.size());
            SSP_EntitledBenefitsController.updateBenefits(detailMap);            
            system.assertEquals([SELECT COUNT() FROM SSP_Benefits__c WHERE SSP_Member__c = :appIndvList[0].SSP_Member__c], 1);
            test.stopTest();
        }
    }
    
    
            /**
@author : Shrikant Raut
Test Method to test fetchExistingIncomeDetails method*/
    @isTest
    public static void test_updateBenefits_negative(){
        User citizen  = [SELECT Id FROM User WHERE UserName = 'citizen@abc.xyz' LIMIT 1][0];
        System.runAs(citizen){            
            Map<String, String>  detailMap = new Map<String, String>{
                'toUpsert'=> 'abc',
                    'toDelete'=> null
            };
            test.startTest();            
            SSP_LightningResponse res = SSP_EntitledBenefitsController.updateBenefits(detailMap);    
            system.assertEquals(res.bIsSuccess, false);
            test.stopTest();
        }
    }
}