force-app/main/default/objects/Account/recordTypes/Citizen.recordType-meta.xml
<RecordType>
    <fullName>Citizen</fullName>
    <active>true</active>
    <label>Citizen</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Related Account</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Citizen.recordType-meta.xml
<RecordType>
    <fullName>Citizen</fullName>
    <active>true</active>
    <description>This Record type is used for Residents</description>
    <label>Citizen</label>
</RecordType>

force-app/main/default/objects/SSP_Application__c/SSP_Application__c.object-meta.xml
<CustomObject>
    <description>To store SSP Application and Case data</description>
    <label>SSP Application</label>
    <nameField>
        
        <displayFormat>{000000000}</displayFormat>
        
        <label>SSP_Application Name</label>
        
        <type>AutoNumber</type>
        
    </nameField>
    <pluralLabel>SSP Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Application__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Shows the related Account to an Application</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>SSP_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_Application__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Shows the related Contact to an Application</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>SSP_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/SSP_ApplicationIndividual__c.object-meta.xml
<CustomObject>
    <description>Custom junction object to maintain association between member and application</description>
    <label>SSP ApplicationIndividual</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>SSP_ApplicationIndividual Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SSP ApplicationIndividuals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/SSP_Application__c.field-meta.xml
<CustomField>
    <fullName>SSP_Application__c</fullName>
    <description>Indicates the application related to a member</description>
    <label>SSP_Application</label>
    <referenceTo>SSP_Application__c</referenceTo>
    <relationshipName>SSP_ApplicationIndividuals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/SSP_Member__c.field-meta.xml
<CustomField>
    <fullName>SSP_Member__c</fullName>
    <description>Indicates the member related to an application</description>
    <label>SSP_Member</label>
    <referenceTo>SSP_Member__c</referenceTo>
    <relationshipName>SSP_ApplicationIndividuals</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/SSP_Member__c.object-meta.xml
<CustomObject>
    <description>Stores details about an individual member of a case/application such as gatepost reponse, incarceration, disability, living arrangement, pregnancy, address details. Also repurposed to store information of different individuals in the form of individual alien, alien sponsor, care taker,  care coordinator etc.</description>
    <label>SSP Member</label>
    <nameField>
        
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        
        <label>SSP_Member Name</label>
        
        <type>Text</type>
        
    </nameField>
    <pluralLabel>SSP Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Member__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>This field is used to indicate the related contact for a member</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>SSP_Member</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SSP_MemberDisabilityControllerTest.cls
/*
* classname     : SSP_MemberDisabilityControllerTest
* @description  : A test class for SSP_MemberDisabilityController class.
* @author       : Shivam Tiwari
* @date         : DEC-23-2019
* MODIFICATION LOG:
* DEVELOPER             DATE                DESCRIPTION
* ---------------------------------------------------------------------------------------------
* Shivam Tiwari         DEC-23-2019         Initial Version
*/
@isTest
public class SSP_MemberDisabilityControllerTest {
    
    @testSetup
    public static void setup(){
        SSP_TestDataFactory.setupTestData();
        
        List<Account> lstAcc = SSP_TestDataFactory.createAccounts(1, false);
        lstAcc[0].Name = 'TestAcc';
        insert lstAcc;
        
        List<Contact> lstCon = [SELECT Id, FirstName, LastName FROM Contact WHERE FirstName = 'Citizen' AND LastName = 'User' LIMIT 1];     
        
        AccountContactRelation acr = new AccountContactRelation(); 
        acr.Accountid = lstAcc[0].Id;
        acr.Contactid = lstCon[0].Id;
        acr.IsActive = true;
        insert acr;
        
        List<SSP_Application__c> lstAppln = SSP_TestDataFactory.createSSPApplications(1, false);
        lstAppln[0].Account__c=lstAcc[0].Id;        
        lstAppln[0].Contact__c = lstCon[0].Id;
        insert lstAppln;
        
        List<SSP_Member__c> lstMem = SSP_TestDataFactory.createSSPMembers(1, false);
        lstMem[0].Name='TestMember';
        lstMem[0].contact__c=lstCon[0].Id;        
        insert lstMem;
        
        List<SSP_ApplicationIndividual__c> lstAppInd = SSP_TestDataFactory.createApplicationIndividuals(1, false); 
        lstAppInd[0].Name='TestInd';
        lstAppInd[0].SSP_Application__c=lstAppln[0].Id;
        lstAppInd[0].SSP_Member__c=lstMem[0].Id;
        insert lstAppInd;
    }
    
    @isTest
    public static void fetchDisabilityInformationTest(){
        User citizen  = getCitizenUser();
        System.runAs(citizen){
            List<SSP_Application__c> lstApps = getApplications();
            List<SSP_ApplicationIndividual__c> appIndvList = getApplicationIndividuals(lstApps[0].Id);
            List<SSP_Member__c> lstMembers =  getMembers();
            Id memberId = null;
            for(SSP_Member__c mem : lstMembers){
                if(mem.Name == 'TestMember'){
                    memberId = mem.Id;
                    break;
                }
            }
            test.startTest();
                SSP_MemberDisabilityController.fetchDisabilityInformation(memberId, lstApps[0].Id, false);
            test.stopTest();
        }
    }
    
    @isTest
    public static void fetchBlindnessInformationTest(){
        User citizen  = getCitizenUser();
        System.runAs(citizen){
            List<SSP_Application__c> lstApps = getApplications();
            List<SSP_ApplicationIndividual__c> appIndvList = getApplicationIndividuals(lstApps[0].Id);
            List<SSP_Member__c> lstMembers =  getMembers();
            Id memberId = null;
            for(SSP_Member__c mem : lstMembers){
                if(mem.Name == 'TestMember'){
                    memberId = mem.Id;
                    break;
                }
            }
            test.startTest();
                SSP_MemberDisabilityController.fetchDisabilityInformation(memberId, lstApps[0].Id, true);
            test.stopTest();
        }
    }
    
    @isTest
    public static void saveDisabilityInformationTest(){
        User citizen  = getCitizenUser();
        System.runAs(citizen){
            List<SSP_Application__c> lstApps = getApplications();
            List<SSP_ApplicationIndividual__c> appIndvList = getApplicationIndividuals(lstApps[0].Id);
            List<SSP_Member__c> lstMembers =  getMembers();
            Id memberId = null;
            for(SSP_Member__c mem : lstMembers){
                if(mem.Name == 'TestMember'){
                    memberId = mem.Id;
                    break;
                }
            }
            SSP_MemberDisabilityWrapper wrap = wrapperObject();
            String wrapStr = JSON.serialize(wrap);
            test.startTest();
                SSP_MemberDisabilityController.saveDisabilityInformation(memberId, wrapStr, false);
            test.stopTest();
        }
    }
    
    @isTest
    public static void saveBlindnessInformationTest(){
        User citizen  = getCitizenUser();
        System.runAs(citizen){
            List<SSP_Application__c> lstApps = getApplications();
            List<SSP_ApplicationIndividual__c> appIndvList = getApplicationIndividuals(lstApps[0].Id);
            List<SSP_Member__c> lstMembers =  getMembers();
            Id memberId = null;
            for(SSP_Member__c mem : lstMembers){
                if(mem.Name == 'TestMember'){
                    memberId = mem.Id;
                    break;
                }
            }
            SSP_MemberDisabilityWrapper wrap = wrapperObject();
            String wrapStr = JSON.serialize(wrap);
            test.startTest();
                SSP_MemberDisabilityController.saveDisabilityInformation(memberId, wrapStr, true);
            test.stopTest();
        }
    }
    
    @isTest
    public static void saveDisabilityInformationTest1(){
        User citizen  = getCitizenUser();
        System.runAs(citizen){
            List<SSP_Application__c> lstApps = getApplications();
            List<SSP_ApplicationIndividual__c> appIndvList = getApplicationIndividuals(lstApps[0].Id);
            List<SSP_Member__c> lstMembers =  getMembers();
            Id memberId = null;
            for(SSP_Member__c mem : lstMembers){
                if(mem.Name == 'TestMember'){
                    memberId = mem.Id;
                    break;
                }
            }
            SSP_MemberDisabilityWrapper wrap = wrapperObject();
            wrap.hasEndStageRenalDisease = null;
            wrap.unableToBuyCookForSelf = null;
            wrap.parentUnableToCareForChild = null;
            String wrapStr = JSON.serialize(wrap);
            test.startTest();
                SSP_MemberDisabilityController.saveDisabilityInformation(memberId, wrapStr, false);
            test.stopTest();
        }
    }
    
    @isTest
    public static void saveBlindnessInformationTest1(){
        User citizen  = getCitizenUser();
        System.runAs(citizen){
            List<SSP_Application__c> lstApps = getApplications();
            List<SSP_ApplicationIndividual__c> appIndvList = getApplicationIndividuals(lstApps[0].Id) ;
            List<SSP_Member__c> lstMembers =  getMembers();
            Id memberId = null;
            for(SSP_Member__c mem : lstMembers){
                if(mem.Name == 'TestMember'){
                    memberId = mem.Id;
                    break;
                }
            }
            SSP_MemberDisabilityWrapper wrap = wrapperObject();
            wrap.hasEndStageRenalDisease = null;
            wrap.unableToBuyCookForSelf = null;
            wrap.parentUnableToCareForChild = null;
            String wrapStr = JSON.serialize(wrap);
            test.startTest();
                SSP_MemberDisabilityController.saveDisabilityInformation(memberId, wrapStr, true);
            test.stopTest();
        }
    }
    
    private static SSP_MemberDisabilityWrapper wrapperObject(){
        SSP_MemberDisabilityWrapper wrap = new SSP_MemberDisabilityWrapper();
        wrap.Id = null;
        wrap.memberFullName = 'Test Wrap';
        wrap.age = 50;
        wrap.benefitTypeCode = 'MA, SN, KT';
        wrap.hasEndStageRenalDisease = SSP_GlobalConstants.YES;
        wrap.unableToBuyCookForSelf = SSP_GlobalConstants.YES;
        wrap.parentUnableToCareForChild = SSP_GlobalConstants.YES;
        wrap.disabilityPermanentTemporary = 'Permanent';
        wrap.genderCode = 'F';
        wrap.programsApplied = 'SS';
        wrap.isNonMagi = true;
        return wrap;
    }
    
    private static List<SSP_Application__c> getApplications(){
        return ([SELECT Id  FROM SSP_Application__c LIMIT 1]);
    }
    
    private static User getCitizenUser(){
        return ([SELECT Id FROM User WHERE UserName = 'citizen@abc.xyz' LIMIT 1][0]);
    }
    
    private static List<SSP_ApplicationIndividual__c> getApplicationIndividuals(String appsId){
        return ([SELECT Id, SSP_Member__c, SSP_Application__c FROM SSP_ApplicationIndividual__c WHERE SSP_Application__c =: appsId]);
    }
    
    private static List<SSP_Member__c> getMembers(){
        return ([SELECT Id, Name FROM SSP_Member__c LIMIT 50]);
    }
}