force-app/main/default/objects/Account/recordTypes/Citizen.recordType-meta.xml
<RecordType>
    <fullName>Citizen</fullName>
    <active>true</active>
    <label>Citizen</label>
</RecordType>

force-app/main/default/objects/AccountContactRelation/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>first name in signature of HoH who is adding this auth rep</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountContactRelation/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <description>last name of HoH who is adding this auth rep</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountContactRelation/fields/ProgramsApplied__c.field-meta.xml
<CustomField>
    <fullName>ProgramsApplied__c</fullName>
    <label>Programs Applied</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetDefinition>
            
            
                <value>
                
                    <fullName>MA</fullName>
                
                
                    <label>Medicaid/KCHIP</label>
                
                </value>
            
                <value>
                
                    <fullName>KT</fullName>
                
                
                    <label>KTAP (Cash Assistance)</label>
                
                </value>
            
                <value>
                
                    <fullName>SN</fullName>
                
                
                    <label>SNAP (Food Assistance)</label>
                
                </value>
            
                <value>
                
                    <fullName>SS</fullName>
                
                
                    <label>State Supplementation</label>
                
                </value>
            
                <value>
                
                    <fullName>DS</fullName>
                
                
                    <label>DSNAP</label>
                
                </value>
            
                <value>
                
                    <fullName>CC</fullName>
                
                
                    <label>Child Care Assistance</label>
                
                </value>
            
                <value>
                
                    <fullName>KP</fullName>
                
                
                    <label>KI-HIPP (Health Insurance Premium Payments)</label>
                
                </value>
            
            </valueSetDefinition>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Related Account</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/IndividualId__c.field-meta.xml
<CustomField>
    <fullName>IndividualId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Individual Id of a Contact</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>IndividualId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Citizen.recordType-meta.xml
<RecordType>
    <fullName>Citizen</fullName>
    <active>true</active>
    <description>This Record type is used for Residents</description>
    <label>Citizen</label>
</RecordType>

force-app/main/default/objects/SSP_Application__c/SSP_Application__c.object-meta.xml
<CustomObject>
    <description>To store SSP Application and Case data</description>
    <label>SSP Application</label>
    <nameField>
        
        <displayFormat>{000000000}</displayFormat>
        
        <label>SSP_Application Name</label>
        
        <type>AutoNumber</type>
        
    </nameField>
    <pluralLabel>SSP Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Application__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Shows the related Account to an Application</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>SSP_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_Application__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Shows the related Contact to an Application</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>SSP_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SSP_Application__c/fields/DCCaseNumber__c.field-meta.xml
<CustomField>
    <fullName>DCCaseNumber__c</fullName>
    <description>DC mapping Case number of an Application</description>
    <externalId>true</externalId>
    <label>DCCaseNumber</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SSP_Application__c/fields/ProgramsApplied__c.field-meta.xml
<CustomField>
    <fullName>ProgramsApplied__c</fullName>
    <description>Used to store the list of programs applied for a household</description>
    <label>Programs Applied</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>BenefitPrograms</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Application__c/fields/SSPDCMessage__c.field-meta.xml
<CustomField>
    <fullName>SSPDCMessage__c</fullName>
    <description>Used to store SSP DC message</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>SSP DC Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/SSP_ApplicationIndividual__c.object-meta.xml
<CustomObject>
    <description>Custom junction object to maintain association between member and application</description>
    <label>SSP ApplicationIndividual</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>SSP_ApplicationIndividual Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SSP ApplicationIndividuals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/IsHeadOfHousehold__c.field-meta.xml
<CustomField>
    <fullName>IsHeadOfHousehold__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to determine if the member is Head of Household</description>
    <label>Is Head Of Household</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/MedicaidType__c.field-meta.xml
<CustomField>
    <fullName>MedicaidType__c</fullName>
    <description>Used to store type of Medicaid Program - Magi/Non Magi</description>
    <label>Medicaid Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MAGI</fullName>
            </value>
            <value>
                <fullName>Non-MAGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/ProgramsApplied__c.field-meta.xml
<CustomField>
    <fullName>ProgramsApplied__c</fullName>
    <description>Different types of programs applied on an application for which this member is involved</description>
    <label>Application Programs Applied</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>BenefitPrograms</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/SSP_Application__c.field-meta.xml
<CustomField>
    <fullName>SSP_Application__c</fullName>
    <description>Indicates the application related to a member</description>
    <label>SSP_Application</label>
    <referenceTo>SSP_Application__c</referenceTo>
    <relationshipName>SSP_ApplicationIndividuals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/SSP_Member__c.field-meta.xml
<CustomField>
    <fullName>SSP_Member__c</fullName>
    <description>Indicates the member related to an application</description>
    <label>SSP_Member</label>
    <referenceTo>SSP_Member__c</referenceTo>
    <relationshipName>SSP_ApplicationIndividuals</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/SSP_Member__c.object-meta.xml
<CustomObject>
    <description>Stores details about an individual member of a case/application such as gatepost reponse, incarceration, disability, living arrangement, pregnancy, address details. Also repurposed to store information of different individuals in the form of individual alien, alien sponsor, care taker,  care coordinator etc.</description>
    <label>SSP Member</label>
    <nameField>
        
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        
        <label>SSP_Member Name</label>
        
        <type>Text</type>
        
    </nameField>
    <pluralLabel>SSP Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Member__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>This field is used to indicate the related contact for a member</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>SSP_Member</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>This field is used to store Firstname on a Member</description>
    <encryptionScheme>None</encryptionScheme>
    <label>FirstName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/IndividualId__c.field-meta.xml
<CustomField>
    <fullName>IndividualId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>This field is used to store individual Id of a member</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>IndividualId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/IsHeadOfHousehold__c.field-meta.xml
<CustomField>
    <fullName>IsHeadOfHousehold__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Head Of Household</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <description>This field is used to store Lastname of a member</description>
    <encryptionScheme>None</encryptionScheme>
    <label>LastName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/BenefitPrograms.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>MA</fullName>
        
        
        <label>Medicaid/KCHIP</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>KT</fullName>
        
        
        <label>KTAP (Cash Assistance)</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SN</fullName>
        
        
        <label>SNAP (Food Assistance)</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SS</fullName>
        
        
        <label>State Supplementation</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>DS</fullName>
        
        
        <label>DSNAP</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>CC</fullName>
        
        
        <label>Child Care Assistance</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>KP</fullName>
        
        
        <label>KI-HIPP (Health Insurance Premium Payments)</label>
        
    </customValue>
    
    <description>Different type of Benefit Programs available for a Citizen</description>
    
    <masterLabel>Benefit Programs</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/classes/SSP_EligibilityResultsCtrlTest.cls
/*
* classname 	: SSP_EligibilityResultsCtrlTest
* @description 	: Ctrl class for eligibilty result.
* @author 		: Vishakha verma
* @date 		: Mar-11-2019
* MODIFICATION LOG:
* DEVELOPER 			DATE 			DESCRIPTION
* ---------------------------------------------------------------------------------------------
*  Vishakha   		Mar-11-2019		Initial Version
*/
@isTest(seeAllData=false)
public class SSP_EligibilityResultsCtrlTest {
    
    @testSetup static void setup() { 
        SSP_TestDataFactory.setupTestData();    
        List<Account> lstAcc = SSP_TestDataFactory.createAccounts(1, false);
        lstAcc[0].Name = 'eligibility';
        insert lstAcc;
        
        List<Contact> lstCon = [SELECT Id, FirstName, LastName FROM Contact WHERE FirstName = 'Citizen' AND LastName = 'User' LIMIT 1];//= SSP_TestDataFactory.createContacts(1, false); 
        
        AccountContactRelation acr = new AccountContactRelation(); 
        acr.Accountid = lstAcc[0].Id;
        acr.Contactid = lstCon[0].Id;
        acr.IsActive = true;
        insert acr;
        

        List<SSP_Application__c> lstAppln = SSP_TestDataFactory.createSSPApplications(1, false);
        lstAppln[0].Account__c=lstAcc[0].Id;        
        lstAppln[0].Contact__c = lstCon[0].Id;
        lstAppln[0].DCCaseNumber__c = Decimal.valueOf('123456789');
        lstAppln[0].ProgramsApplied__c = 'MA;KT;SN';
        lstAppln[0].SSPDCMessage__c = SSP_GlobalConstants.SSPDC_P_Message;
        insert lstAppln;
        
             
        List<SSP_Member__c> lstMem = SSP_TestDataFactory.createSSPMembers(1, false);
        lstMem[0].contact__c=lstCon[0].Id; 
        lstMem[0].IndividualId__c = '999033797';
        lstMem[0].FirstName__C ='Test';
        lstMem[0].LastName__C='Last';
        insert lstMem;
        
        List<SSP_Member__c> lstMem2 = SSP_TestDataFactory.createSSPMembers(1, false);
        lstMem2[0].contact__c=lstCon[0].Id; 
        lstMem2[0].IndividualId__c = '999033791';
        lstMem2[0].FirstName__C ='Test';
        lstMem2[0].LastName__C='Last';
        insert lstMem2;
        
        SSP_ApplicationIndividual__c objAppInd = new SSP_ApplicationIndividual__c();            
        objAppInd.ProgramsApplied__c='MA';
        objAppInd.MedicaidType__c='MAGI';
        objAppInd.SSP_Member__c = lstMem2[0].Id;
        objAppInd.SSP_Application__c = lstAppln[0].Id;
        objAppInd.IsHeadOfHousehold__c = true;
        insert objAppInd;
    }
    
    
     @isTest
    public static void getEligibilityDataTest(){
        User citizen  = [SELECT Id FROM User WHERE UserName = 'citizen@abc.xyz' LIMIT 1][0];
        System.runAs(citizen){
            List<SSP_Application__c> lstApps = [SELECT Id , name , DCCaseNumber__c, SSPDCMessage__c FROM SSP_Application__c LIMIT 1];         
            Test.setMock(HttpCalloutMock.class, new SSP_DC_ReverseMockForEligibilty());  
            test.startTest();
            system.assertNotEquals(null, SSP_EligibilityResultsCtrl.getEligibilityData(lstApps[0].id));          
            lstApps[0].SSPDCMessage__c = null;
            upsert lstApps;           
            system.assertNotEquals(null, SSP_EligibilityResultsCtrl.getEligibilityData(lstApps[0].id));          
            lstApps[0].SSPDCMessage__c ='LOG1000';
            upsert lstApps;           
            system.assertNotEquals(null, SSP_EligibilityResultsCtrl.getEligibilityData(lstApps[0].id));
            test.stopTest();           
            
        }
    }
    @isTest
    public static void getEligibilityDataTest2(){
        User citizen  = [SELECT Id FROM User WHERE UserName = 'citizen@abc.xyz' LIMIT 1][0];
        System.runAs(citizen){
            test.startTest(); 
            List<SSP_Application__c> lstApps = [SELECT Id , name , DCCaseNumber__c, SSPDCMessage__c FROM SSP_Application__c LIMIT 1];         
            system.assertNotEquals(null, SSP_EligibilityResultsCtrl.getEligibilityData(lstApps[0].id));          
           test.stopTest();           
            
        }
    }

     @isTest
        public static void buildEligibilityWrapperTest(){     
             List<SSP_Application__c> lstApps = [SELECT Id , name, DCCaseNumber__c FROM SSP_Application__c LIMIT 1];
            User citizen  = SSP_TestDataFactory.createPortalUser();
            string jsonData = '{"SSP_EligibilitySummary": [{"IndividualId": "999033797","ProgramCode": "SS","BenefitStatusCode": "P","BenefitBeginDate": null,"BenefitEndDate": "2020-08-09" ,"EligibleForExpeditedSNAP": "1","EligibleForKIHIPP": "1","IsReferredToFFM": "Y"},{"IndividualId": "999033797","ProgramCode": "MA","BenefitStatusCode": "P","BenefitBeginDate": "2020-08-09","BenefitEndDate": "2020-08-09" ,"EligibleForExpeditedSNAP": "1","EligibleForKIHIPP": "1","IsReferredToFFM": "Y"}, {"IndividualId": "999033791","ProgramCode": "KT","BenefitStatusCode": null,"BenefitBeginDate": null,"BenefitEndDate": null ,"EligibleForExpeditedSNAP": "1","EligibleForKIHIPP": "1","IsReferredToFFM": "Y"}]}';
            SSP_EligibilitySummaryPayloadWrapper payloadWrapper = (SSP_EligibilitySummaryPayloadWrapper)System.JSON.deserialize(jsonData, SSP_EligibilitySummaryPayloadWrapper.class);
            List<SSP_EligibilitySummaryWrapper> lstEligibilitySummary = payloadWrapper.SSP_EligibilitySummary;
			SSP_EligibilityResultsCtrl.buildEligibilityWrapper(lstEligibilitySummary,lstApps);
        }
}