force-app/main/default/objects/DocumentDetail__c/DocumentDetail__c.object-meta.xml
<CustomObject>
    <description>Holds the Document related data</description>
    <label>Document Detail</label>
    <nameField>
        
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        
        <label>Document Name</label>
        
        <type>Text</type>
        
    </nameField>
    <pluralLabel>Document Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DocumentDetail__c/fields/CaseNumber__c.field-meta.xml
<CustomField>
    <fullName>CaseNumber__c</fullName>
    <description>Case Number for which document for RFI to be uploaded</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Case Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocumentDetail__c/fields/ContentDocumentId__c.field-meta.xml
<CustomField>
    <fullName>ContentDocumentId__c</fullName>
    <description>Store the Document Content Id</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Content Document Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocumentDetail__c/fields/DocumentMetadataId__c.field-meta.xml
<CustomField>
    <fullName>DocumentMetadataId__c</fullName>
    <description>Document Id will store in DMS</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Doucment Metadata Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocumentDetail__c/fields/Extension__c.field-meta.xml
<CustomField>
    <fullName>Extension__c</fullName>
    <description>Document Extension</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Extension</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocumentDetail__c/fields/IndividualId__c.field-meta.xml
<CustomField>
    <fullName>IndividualId__c</fullName>
    <description>Store the Individual Id of member</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Individual Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocumentDetail__c/fields/MimeType__c.field-meta.xml
<CustomField>
    <fullName>MimeType__c</fullName>
    <description>Document Mime Type</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Mime Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocumentDetail__c/fields/ReceivedDate__c.field-meta.xml
<CustomField>
    <fullName>ReceivedDate__c</fullName>
    <description>Received Date Time</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Received Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/DocumentDetail__c/fields/UniqueIdentifier__c.field-meta.xml
<CustomField>
    <fullName>UniqueIdentifier__c</fullName>
    <description>Used to store unique identifier for RFI</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Unique Identifier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DocumentDetailSelector.cls
/*
* classname     :  DocumentDetailSelector
* @description  :  Selector class for DocumentDetail__c
* @author       :  Ashwin Kasture 
* @date         :  1/05/2020
* MODIFICATION LOG:
* DEVELOPER                     DATE                               DESCRIPTION
* ---------------------------------------------------------------------------------------------*/
public with sharing class DocumentDetailSelector {
    /*
    * method        : downloadDocumentMethod
    * @description  : This method is use to query data of DocumentDetail__c object.
    * @author       : Ashwin Kasture
    * @param        : String sDocumentData - Contains DocumentMetaDataId Or Content Document Id.
    * @return       : SSP_LightningResponse    * */
    public static List<DocumentDetail__c> queryDocumentDetailData(Set<String> setUniqueIdentifier,String sspDocumentRecTypeId){

        /*  
            lstUniqueIdentifier.addAll(setUniqueIdentifier);
            Map<String, String> mapDocDetailObj = new Map<String, String> {'objectName' => 'DocumentDetail__c'};
            Set<String> setDocDetailFields = new Set<String> {'Id','Name','IndividualId__c','CaseNumber__c','UniqueIdentifier__c','Extension__c','ContentDocumentId__c','ReceivedDate__c','DocumentMetadataId__c','MimeType__c'};
            Map<String, String> mapDocDetailCondition = new Map<String, String> {'RecordTypeId' => sspDocumentRecTypeId,'UniqueIdentifier__c'=>String.join(lstUniqueIdentifier, ',')};
			List<DocumentDetail__c> lstDocumentDetail = new List<DocumentDetail__c>();
            lstDocumentDetail = (List<DocumentDetail__c>)SSP_Utility.fetchRecords(mapDetails, setFields, mapConditions);
            return lstDocumentDetail;
        */
        List<DocumentDetail__c> lstDocDetails = new List<DocumentDetail__c>();
        lstDocDetails = [Select Id,Name,IndividualId__c,CaseNumber__c,UniqueIdentifier__c,Extension__c,ContentDocumentId__c,ReceivedDate__c,DocumentMetadataId__c,MimeType__c
                            FROM DocumentDetail__c 
                            WHERE UniqueIdentifier__c IN: setUniqueIdentifier AND RecordTypeId =:sspDocumentRecTypeId];//Removed UniqueIdentifier__c != null AND  for Perf fix
        return lstDocDetails;
    }
}