force-app/main/default/objects/Account/fields/CaseNumber__c.field-meta.xml
<CustomField>
    <fullName>CaseNumber__c</fullName>
    <description>This field is used to store CaseNumber associated for an authorised representative</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>CaseNumber</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Indicates whether the status of the account is Active-Allow Referrals, Active-Do not allow referrals or Inactive</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active - Allow referrals</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active - Do not allow referrals</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Pending Review</fullName>
                <isActive>false</isActive>
                <label>Pending Review</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <isActive>false</isActive>
                <label>Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Application.recordType-meta.xml
<RecordType>
    <fullName>Application</fullName>
    <active>true</active>
    <description>Record type for application account</description>
    <label>Application</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Related Account</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/IndividualId__c.field-meta.xml
<CustomField>
    <fullName>IndividualId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Individual Id of a Contact</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>IndividualId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of contact-Active or Inactive</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Application__c/SSP_Application__c.object-meta.xml
<CustomObject>
    <description>To store SSP Application and Case data</description>
    <label>SSP Application</label>
    <nameField>
        
        <displayFormat>{000000000}</displayFormat>
        
        <label>SSP_Application Name</label>
        
        <type>AutoNumber</type>
        
    </nameField>
    <pluralLabel>SSP Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Application__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Shows the related Account to an Application</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>SSP_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_Application__c/fields/ApplicationId__c.field-meta.xml
<CustomField>
    <fullName>ApplicationId__c</fullName>
    <description>This field is used to store Case Number generated from the SSP application</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <externalId>true</externalId>
    <label>ApplicationId</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SSP_Application__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Shows the related Contact to an Application</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>SSP_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SSP_Application__c/fields/DCCaseNumber__c.field-meta.xml
<CustomField>
    <fullName>DCCaseNumber__c</fullName>
    <description>DC mapping Case number of an Application</description>
    <externalId>true</externalId>
    <label>DCCaseNumber</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SSP_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Different types of status of an Application</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        
            <valueSetDefinition>
            
            
                <value>
                
                    <fullName>N</fullName>
                
                
                    <label>New</label>
                
                </value>
            
                <value>
                
                    <fullName>P</fullName>
                
                
                    <label>Pending</label>
                
                </value>
            
                <value>
                
                    <fullName>AP</fullName>
                
                
                    <label>Approved</label>
                
                </value>
            
                <value>
                
                    <fullName>UN</fullName>
                
                
                    <label>Unsubmitted</label>
                
                </value>
            
                <value>
                
                    <fullName>Inactive</fullName>
                
                
                    <label>Inactive</label>
                
                </value>
            
                <value>
                
                    <fullName>Blocked</fullName>
                
                
                    <label>Blocked</label>
                
                </value>
            
            </valueSetDefinition>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Application__c/recordTypes/Case.recordType-meta.xml
<RecordType>
    <fullName>Case</fullName>
    <active>true</active>
    <label>Case</label>
</RecordType>

force-app/main/default/objects/SSP_Member__c/SSP_Member__c.object-meta.xml
<CustomObject>
    <description>Stores details about an individual member of a case/application such as gatepost reponse, incarceration, disability, living arrangement, pregnancy, address details. Also repurposed to store information of different individuals in the form of individual alien, alien sponsor, care taker,  care coordinator etc.</description>
    <label>SSP Member</label>
    <nameField>
        
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        
        <label>SSP_Member Name</label>
        
        <type>Text</type>
        
    </nameField>
    <pluralLabel>SSP Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Member__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>This field is used to indicate the related contact for a member</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>SSP_Member</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>This field is used to store Firstname on a Member</description>
    <encryptionScheme>None</encryptionScheme>
    <label>FirstName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/IndividualId__c.field-meta.xml
<CustomField>
    <fullName>IndividualId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>This field is used to store individual Id of a member</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>IndividualId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <description>This field is used to store Lastname of a member</description>
    <encryptionScheme>None</encryptionScheme>
    <label>LastName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Transaction__c/SSP_Transaction__c.object-meta.xml
<CustomObject>
    <description>Object to be used for tracking status of Reverse SSP DC Call outs</description>
    <label>SSP Transaction</label>
    <nameField>
        <displayFormat>TD-{0}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SSP Transaction</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Transaction__c/fields/ApplicationId__c.field-meta.xml
<CustomField>
    <fullName>ApplicationId__c</fullName>
    <description>It will store the Application Id or Application Number details.</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Application Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Transaction__c/fields/CaseNumber__c.field-meta.xml
<CustomField>
    <fullName>CaseNumber__c</fullName>
    <description>It will store the Case Number Details</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>CaseNumber</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Transaction__c/fields/IndividualId__c.field-meta.xml
<CustomField>
    <fullName>IndividualId__c</fullName>
    <description>It will store the Individual Id</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Individual Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Transaction__c/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <description>It will store the Mode of the Transaction</description>
    <label>Mode</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetDefinition>
            
            
                <value>
                
                    <fullName>RAC</fullName>
                
                
                    <label>RAC</label>
                
                </value>
            
                <value>
                
                    <fullName>Recert</fullName>
                
                
                    <label>Recert</label>
                
                </value>
            
                <value>
                
                    <fullName>Intake</fullName>
                
                
                    <label>Intake</label>
                
                </value>
            
                <value>
                
                    <fullName>Other</fullName>
                
                
                    <label>Other</label>
                
                </value>
            
                <value>
                
                    <fullName>Renewal</fullName>
                
                
                    <label>Renewal</label>
                
                </value>
            
            </valueSetDefinition>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>It will store the status of the Transaction</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Timed Out</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Transaction__c/fields/View_Name__c.field-meta.xml
<CustomField>
    <fullName>View_Name__c</fullName>
    <description>It will store the View Name of the Transaction</description>
    <encryptionScheme>None</encryptionScheme>
    <label>View Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SSP_RSSPDC_IntegrationServiceTest.cls
/*
* classname     :  SSP_RSSPDC_IntegrationServiceTest
* @description  :  Test class for SSP_RSSPDC_IntegrationService
* @author       :  Ragunathan 
* @date         :  14/02/2020
* MODIFICATION LOG:
* DEVELOPER                     DATE                               DESCRIPTION
* ---------------------------------------------------------------------------------------------
    Ragunathan                  14/02/2020                      Initial Creation
**/

@isTest(seeAllData=false)
public with sharing class SSP_RSSPDC_IntegrationServiceTest {

    @isTest
    public static void RFIDetails() {
        SSP_DC_ReverseMockImpl mock = new SSP_DC_ReverseMockImpl();        
        Test.setMock(HttpCalloutMock.class, mock);
        Test.startTest();
        RSSP_DC_Wrapper objResponse = invokeRSSPDC(SSP_InterfaceConstants.RFI_DETAILS);
        SSP_RFIInformationPayloadWrapper objWrapper = new SSP_RFIInformationPayloadWrapper();
        objWrapper = objResponse.RFIInformationPayload;
        Test.stopTest();
        System.assertNotEquals(null, objResponse.RFIInformationPayload);
    }
    
    @isTest
    public static void NonCitizenSearchCase() {
        SSP_DC_ReverseMockImpl mock = new SSP_DC_ReverseMockImpl();
        Test.setMock(HttpCalloutMock.class, mock);
        Test.startTest();
        RSSP_DC_Wrapper objResponse = invokeRSSPDC(SSP_InterfaceConstants.NON_CITIZEN_SEARCH_CASE);
        NonCitizenSearchCasePayloadWrapper objWrapper = new NonCitizenSearchCasePayloadWrapper();
        objWrapper = objResponse.nonCitizenSearchCasePayload;
        Test.stopTest();
        System.assertNotEquals(null, objResponse.nonCitizenSearchCasePayload);
    }

    @isTest
    public static void WaiverDetails() {
        SSP_DC_ReverseMockImpl mock = new SSP_DC_ReverseMockImpl();
        Test.setMock(HttpCalloutMock.class, mock);
        Test.startTest();
        RSSP_DC_Wrapper objResponse = invokeRSSPDC(SSP_InterfaceConstants.WAIVER_DETAILS);
        SSP_WaiverDetailsPayloadWrapper objWrapper = new SSP_WaiverDetailsPayloadWrapper();
        objWrapper = objResponse.waiverDetailsPayload;
        Test.stopTest();
        System.assertNotEquals(null, objResponse.waiverDetailsPayload);
    }

    @isTest
    public static void NotificationInformation() {
        SSP_DC_ReverseMockImpl mock = new SSP_DC_ReverseMockImpl();
        Test.setMock(HttpCalloutMock.class, mock);
        Test.startTest();
        RSSP_DC_Wrapper objResponse = invokeRSSPDC(SSP_InterfaceConstants.NOTIFICATION_INFORMATION);
        //SSP_WaiverDetailsPayloadWrapper objWrapper = new SSP_WaiverDetailsPayloadWrapper();
        //objWrapper = objResponse.waiverDetailsPayload;
        Test.stopTest();
        //System.assertNotEquals(null, objResponse.waiverDetailsPayload);
    }

    @isTest
    public static void DashboardCaseInformation() {
        SSP_DC_ReverseMockImpl mock = new SSP_DC_ReverseMockImpl();
        Test.setMock(HttpCalloutMock.class, mock);
        Test.startTest();
        RSSP_DC_Wrapper objResponse = invokeRSSPDC(SSP_InterfaceConstants.DASHBOARD_CASE_INFORMATION);
        SSP_DashboardCaseInformation objWrapper = new SSP_DashboardCaseInformation();
        objWrapper = objResponse.dashboardCaseInfo;
        Test.stopTest();
        System.assertNotEquals(null, objResponse.dashboardCaseInfo);
    }

    @isTest
    public static void TaxForms1095AInformation() {
        SSP_DC_ReverseMockImpl mock = new SSP_DC_ReverseMockImpl();
        Test.setMock(HttpCalloutMock.class, mock);
        Test.startTest();
        RSSP_DC_Wrapper objResponse = invokeRSSPDC(SSP_InterfaceConstants.TAX_FORMS_1095A_INFORMATION);
        SSP_TaxForms1095AInfoPayloadWrapper objWrapper = new SSP_TaxForms1095AInfoPayloadWrapper();
        objWrapper = objResponse.taxForms1095AInfoPayload;
        Test.stopTest();
        System.assertNotEquals(null, objResponse.taxForms1095AInfoPayload);
    }

    @isTest
    public static void RACSelectionDetails() {
        SSP_DC_ReverseMockImpl mock = new SSP_DC_ReverseMockImpl();
        Test.setMock(HttpCalloutMock.class, mock);
        Test.startTest();
        RSSP_DC_Wrapper objResponse = invokeRSSPDC(SSP_InterfaceConstants.RAC_SELECTION_DETAILS);
        SSP_RACSelectionDetailsWrapper objWrapper = new SSP_RACSelectionDetailsWrapper();
        objWrapper = objResponse.racSelectionWrapper;
        Test.stopTest();
        System.assertNotEquals(null, objResponse.racSelectionWrapper);
    }

    @isTest
    public static void DisqualificationDetails() {
        SSP_DC_ReverseMockImpl mock = new SSP_DC_ReverseMockImpl();
        Test.setMock(HttpCalloutMock.class, mock);
        Test.startTest();
        RSSP_DC_Wrapper objResponse = invokeRSSPDC(SSP_InterfaceConstants.RAC_SELECTION_DETAILS);
        SSP_RACSelectionDetailsWrapper objWrapper = new SSP_RACSelectionDetailsWrapper();
        objWrapper = objResponse.racSelectionWrapper;
        Test.stopTest();
        System.assertNotEquals(null, objResponse.racSelectionWrapper);
    }

    @isTest
    public static void BenefitInformation() {
        SSP_DC_ReverseMockImpl mock = new SSP_DC_ReverseMockImpl();
        Test.setMock(HttpCalloutMock.class, mock);
        Test.startTest();
        RSSP_DC_Wrapper objResponse = invokeRSSPDC(SSP_InterfaceConstants.BENEFIT_INFORMATION);
        SSP_BenefitInformationPayloadWrapper objWrapper = new SSP_BenefitInformationPayloadWrapper();
        objWrapper = objResponse.benefitInformations;
        Test.stopTest();
        System.assertNotEquals(null, objResponse.benefitInformations);
    }

    @isTest
    public static void MyInformation() {
        SSP_DC_ReverseMockImpl mock = new SSP_DC_ReverseMockImpl();
        Test.setMock(HttpCalloutMock.class, mock);
        Test.startTest();
        RSSP_DC_Wrapper objResponse = invokeRSSPDC(SSP_InterfaceConstants.MY_INFORMATION);
        //SSP_BenefitInformationPayloadWrapper objWrapper = new SSP_BenefitInformationPayloadWrapper();
        //objWrapper = objResponse.benefitInformations;
        Test.stopTest();
        //System.assertNotEquals(null, objResponse.benefitInformations);
    }

    @isTest
    public static void MedicaidMCOInformation() {
        SSP_DC_ReverseMockImpl mock = new SSP_DC_ReverseMockImpl();
        Test.setMock(HttpCalloutMock.class, mock);
        Test.startTest();
        RSSP_DC_Wrapper objResponse = invokeRSSPDC(SSP_InterfaceConstants.MEDICAID_MCO_INFORMATION);
        SSP_MedicaidMCOInformationWrapper objWrapper = new SSP_MedicaidMCOInformationWrapper();
        objWrapper = objResponse.medicaidMCOInformation;
        Test.stopTest();
        System.assertNotEquals(null, objResponse.medicaidMCOInformation);
    }

    @isTest
    public static void HearingsSummaryInformation() {
        SSP_DC_ReverseMockImpl mock = new SSP_DC_ReverseMockImpl();
        Test.setMock(HttpCalloutMock.class, mock);
        Test.startTest();
        RSSP_DC_Wrapper objResponse = invokeRSSPDC(SSP_InterfaceConstants.HEARINGS_SUMMARY_INFORMATION);
        SSP_HearingsSummaryInfoPayloadWrapper objWrapper = new SSP_HearingsSummaryInfoPayloadWrapper();
        objWrapper = objResponse.hearingsSummaryInfoPayload;
        Test.stopTest();
        System.assertNotEquals(null, objResponse.hearingsSummaryInfoPayload);
    }

    @isTest
    public static void AssisterAuthRepClientDetails() {
        SSP_DC_ReverseMockImpl mock = new SSP_DC_ReverseMockImpl();
        Test.setMock(HttpCalloutMock.class, mock);
        Test.startTest();
        RSSP_DC_Wrapper objResponse = invokeRSSPDC(SSP_InterfaceConstants.ASSISTER_AUTHREP_CLIENT_DETAILS);
        SSP_AssisterAuthRepDetailsPayloadWrapper objWrapper = new SSP_AssisterAuthRepDetailsPayloadWrapper();
        objWrapper = objResponse.assisterAuthRepDetailsPayload;
        Test.stopTest();
        System.assertNotEquals(null, objResponse.assisterAuthRepDetailsPayload);
    }

    @isTest
    public static void AgentAssistAuthRepDetails() {
        SSP_DC_ReverseMockImpl mock = new SSP_DC_ReverseMockImpl();
        Test.setMock(HttpCalloutMock.class, mock);
        Test.startTest();
        RSSP_DC_Wrapper objResponse = invokeRSSPDC(SSP_InterfaceConstants.AUTHREPS_ASSISTERS);
        //SSP_AssisterAuthRepDetailsPayloadWrapper objWrapper = new SSP_AssisterAuthRepDetailsPayloadWrapper();
        //objWrapper = objResponse.assisterAuthRepDetailsPayload;
        Test.stopTest();
        //System.assertNotEquals(null, objResponse.assisterAuthRepDetailsPayload);
    }

    @isTest
    public static void KHIPPPaymentSummary() {
        SSP_DC_ReverseMockImpl mock = new SSP_DC_ReverseMockImpl();
        Test.setMock(HttpCalloutMock.class, mock);
        Test.startTest();
        RSSP_DC_Wrapper objResponse = invokeRSSPDC(SSP_InterfaceConstants.KHIPP_PAYMENT_SUMMARY);
        SSP_KHIPPPaymentSummaryWrapper objWrapper = new SSP_KHIPPPaymentSummaryWrapper();
        objWrapper = objResponse.KHIPPPaymentSummaryPayload;
        Test.stopTest();
        System.assertNotEquals(null, objResponse.KHIPPPaymentSummaryPayload);
    }

    @isTest
    public static void KIHIPPPreferredPayment() {
        SSP_DC_ReverseMockImpl mock = new SSP_DC_ReverseMockImpl();
        Test.setMock(HttpCalloutMock.class, mock);
        Test.startTest();
        RSSP_DC_Wrapper objResponse = invokeRSSPDC(SSP_InterfaceConstants.KIHIPP_PREFERRED_PAYMENT);
        SSP_KIHIPPPreferredPaymentPayloadWrapper objWrapper = new SSP_KIHIPPPreferredPaymentPayloadWrapper();
        objWrapper = objResponse.KIHIPPPreferredPaymentPayload;
        Test.stopTest();
        System.assertNotEquals(null, objResponse.KIHIPPPreferredPaymentPayload);
    }

    @isTest
    public static void NonCitizenSearchExport() {
        SSP_DC_ReverseMockImpl mock = new SSP_DC_ReverseMockImpl();
        Test.setMock(HttpCalloutMock.class, mock);
        Test.startTest();
        RSSP_DC_Wrapper objResponse = invokeRSSPDC(SSP_InterfaceConstants.NON_CITIZEN_SEARCH_EXPORT);
        SSP_NonCitizenSearchExportPayloadWrapper objWrapper = new SSP_NonCitizenSearchExportPayloadWrapper();
        objWrapper = objResponse.nonCitizenSearchExportPayload;
        Test.stopTest();
        System.assertNotEquals(null, objResponse.nonCitizenSearchExportPayload);
    }

    @isTest
    public static void EligibilitySummary() {
        SSP_DC_ReverseMockImpl mock = new SSP_DC_ReverseMockImpl();
        Test.setMock(HttpCalloutMock.class, mock);
        Test.startTest();
        RSSP_DC_Wrapper objResponse = invokeRSSPDC(SSP_InterfaceConstants.ELIGIBILITY_SUMMARY);
        SSP_EligibilitySummaryPayloadWrapper objWrapper = new SSP_EligibilitySummaryPayloadWrapper();
        objWrapper = objResponse.EligibilitySummaryPayload;
        Test.stopTest();
        System.assertNotEquals(null, objResponse.EligibilitySummaryPayload);
    }

    @isTest
    public static void PastApplications() {
        SSP_DC_ReverseMockImpl mock = new SSP_DC_ReverseMockImpl();
        Test.setMock(HttpCalloutMock.class, mock);
        Test.startTest();
        RSSP_DC_Wrapper objResponse = invokeRSSPDC(SSP_InterfaceConstants.PAST_APPLICATIONS);
        SSP_PastApplicationsPayloadWrapper objWrapper = new SSP_PastApplicationsPayloadWrapper();
        objWrapper = objResponse.PastApplicationsPayload;
        Test.stopTest();
        System.assertNotEquals(null, objResponse.PastApplicationsPayload);
    }

    @isTest
    public static void NonCitizenClientInformation() {
        SSP_DC_ReverseMockImpl mock = new SSP_DC_ReverseMockImpl();
        Test.setMock(HttpCalloutMock.class, mock);
        Test.startTest();
        RSSP_DC_Wrapper objResponse = invokeRSSPDC(SSP_InterfaceConstants.NON_CITIZEN_CLIENT_INFORMATION);
        SSP_NonCitizenClientInfoPayloadWrapper objWrapper = new SSP_NonCitizenClientInfoPayloadWrapper();
        objWrapper = objResponse.nonCitizenClientInfoPayload;
        Test.stopTest();
        System.assertNotEquals(null, objResponse.nonCitizenClientInfoPayload);
    }
    
    @isTest 
    public static void SSP_RSSPDCWrapper() {
        Test.startTest();
        SSP_RSSPDCWrapper objWrapper = new SSP_RSSPDCWrapper();
        objWrapper.boolIsDebug = true;
        objWrapper.sInterfaceName = '';
        objWrapper.sScreenNames = '';
        objWrapper.lstAllViews = null;
        objWrapper.log = null;
        objWrapper.mapsObjectList = null;
        objWrapper.retry = null;
        objWrapper.objRequest = null;
        objWrapper.sFlowType = '';
        objWrapper.objUser = null;
        Test.stopTest();
        System.assertNotEquals(false, objWrapper.boolIsDebug);
    }
    
    @isTest 
    public static void shouldGetResponseForPendingViews() {
        SSP_DC_ReverseMockImpl mock = new SSP_DC_ReverseMockImpl();         
        Test.setMock(HttpCalloutMock.class, mock);
        //Create Test Data
        Id applicationId = createApplication(700000043).Id;
        //Test data for SSP Member
        createMember('999034247');
        //Test data for Transaction
        createTransactionWithStatus('Pending_Views', applicationId, '999034247');
        Map<String, String> mapprograms = new Map<String, String>();
        Map<String, Object> mapParams = new Map<String, Object>{
            'jsonbody' => prepareRequestWrapper('Pending_Views', applicationId, '999034247')
        };

        //SSP_RSSPDC_IntegrationService.boolIsChainJob = false;
        
        Test.startTest();   
        //When
        //SSP_RSSPDC_IntegrationService sspdcreverse = new SSP_RSSPDC_IntegrationService();  
        List<Object> response = SSP_RSSPDC_IntegrationService.invokeCallout(SSP_InterfaceConstants.REVERSE_SSP_DC, mapParams);
        Test.stopTest();
        System.assertNotEquals(null, response);
    }
    
    @isTest 
    public static void shouldGetResponseForQualifiedIndividual() {
        SSP_DC_ReverseMockImpl mock = new SSP_DC_ReverseMockImpl();        
        Test.setMock(HttpCalloutMock.class, mock);
        Id applicationId = createApplication(700000043).Id;
        Map<String, String> mapprograms = new Map<String, String>();
        Map<String, Object> mapParams = new Map<String, Object>{
            'jsonbody' => prepareRequestWrapper('ResourceInformation', applicationId, '999018553')
        };
        //SSP_RSSPDC_IntegrationService.boolIsChainJob = false;
        //Test data for Transaction
        createTransactionWithStatus('ResourceInformation', applicationId, '999018553');
        Test.startTest();    
        //When
        //SSP_RSSPDC_IntegrationService sspdcreverse = new SSP_RSSPDC_IntegrationService();  
        List<Object> response = SSP_RSSPDC_IntegrationService.invokeCallout(SSP_InterfaceConstants.REVERSE_SSP_DC, mapParams);
        Test.stopTest();
        System.assertNotEquals(null, response);
    }

    @isTest 
    public static void shouldGetResponseForIncomeInformation() {
        SSP_DC_ReverseMockImpl mock = new SSP_DC_ReverseMockImpl();        
        Test.setMock(HttpCalloutMock.class, mock);
        Id applicationId = createApplication(700000043).Id;
        createMember('999034247');        
        
        Map<String, String> mapprograms = new Map<String, String>();
        Map<String, Object> mapParams = new Map<String, Object> {
            'jsonbody' => prepareRequestWrapper('All_Views', applicationId, '999034247')
        };
        createTransactionWithStatus('IncomeInformation', applicationId, '999034247');
        Test.startTest();
        //When
        //SSP_RSSPDC_IntegrationService response = new SSP_RSSPDC_IntegrationService();
        List<Object> responses = SSP_RSSPDC_IntegrationService.invokeCallout(SSP_InterfaceConstants.REVERSE_SSP_DC, mapParams);
        Test.stopTest();
        System.assertNotEquals(null, responses);
    }

    @isTest
    public static void getAllViews() {
        SSP_DC_ReverseMockImpl mock = new SSP_DC_ReverseMockImpl();        
        Test.setMock(HttpCalloutMock.class, mock);
        Id applicationId = createApplication(700000043).Id;
        createMember('999034247');        
        Test.startTest();
        Map<String, Object> mapParams = new Map<String, Object>();
        SSP_RSSPDC_RequestWrapper reqWrapper = new SSP_RSSPDC_RequestWrapper();
        reqWrapper.viewName = SSP_InterfaceConstants.ALL_VIEWS;
        reqWrapper.mode = SSP_InterfaceConstants.MODE_INTAKE;
        reqWrapper.applicationID = applicationId;
        mapParams.put(SSP_InterfaceConstants.JSON_BODY,reqWrapper);
        mapParams.put(SSP_InterfaceConstants.IS_DEBUG,true);
        List<Object> objList = IntegrationFactory.invokeCallout(SSP_InterfaceConstants.REVERSE_SSP_DC, mapParams);
        Test.stopTest();

    }

    @isTest 
    public static void AllViews() {
        SSP_DC_ReverseMockImpl mock = new SSP_DC_ReverseMockImpl();        
        Test.setMock(HttpCalloutMock.class, mock);
        Id applicationId = createApplication(700000043).Id;
        createMember('999034247');        
        
        Map<String, String> mapprograms = new Map<String, String>();
        
        //SSP_RSSPDC_IntegrationService.boolIsChainJob = false;
        //Test data for Transaction
        List<String> views = new List<String> {
                'QualifiedIndividual', 
                'MemberInformation', 
                'RelationshipInformation', 
                'HealthInformation',
                'HouseHoldOtherInformation',
                'ResourceInformation', 
                'IncomeInformation', 
                'ExpenseInformation', 
                'AbsentParentInformation',
                'HealthCoverageInformation'
                };
        for(String view: views){
           createTransactionWithStatus(view, applicationId, '999034247');
           Map<String, Object> mapParams = new Map<String, Object> {
            'jsonbody' => prepareRequestWrapper(view, applicationId, '999034247')
            };

            //SSP_RSSPDC_IntegrationService response = new SSP_RSSPDC_IntegrationService();
            List<Object> responses = SSP_RSSPDC_IntegrationService.invokeCallout(SSP_InterfaceConstants.REVERSE_SSP_DC, mapParams);
            System.assertNotEquals(null, responses);
        }
        
    }

    private static SSP_Transaction__c createTransactionWithStatus(String viewName, Id applicationId, String individualId) {
        
        SSP_Transaction__c transactionData = new SSP_Transaction__c(
            View_Name__c = viewName,
            IndividualId__c = individualId,
            ApplicationId__c = applicationId,
            CaseNumber__c = '123456',
            Mode__c = 'Intake',
            Status__c ='Failed'
        );
        
        insert transactionData;
        return transactionData;
    }
    
    private static SSP_Application__c createApplication(Integer caseNumber){
        
        Account acc = new Account(Name='TestName');
        insert acc;
        Id recordTypeId = Schema.SObjectType.SSP_Application__c.getRecordTypeInfosByDeveloperName().get('Case').getRecordTypeId();
        SSP_Application__c application = new SSP_Application__c(
                                                RecordTypeId = recordTypeId,
                                                DCCaseNumber__c =caseNumber,
                                                Account__c = acc.Id);
        
        insert application;
        return application;
    } 
    
    private static SSP_Member__c createMember(String individualId) {
        
        Contact con = new Contact(FirstName='FirstName', LastName='Test Name', IndividualId__c= individualId);
        insert con;
        SSP_Member__c member = new SSP_Member__c(
            Name = 'TestMember',
            FirstName__c = 'FirstName',
            LastName__c = 'FirstName',
            Contact__c = con.Id,
            IndividualId__c = individualId);
        
        insert member;
        
        return member;
    }
    
    private static SSP_RSSPDC_RequestWrapper prepareRequestWrapper(String viewName, Id applicationId, String primAppIndivId) {
        SSP_RSSPDC_RequestWrapper requestWrapper = new SSP_RSSPDC_RequestWrapper();
        requestWrapper.caseNumber                     = 123456;
        requestWrapper.mode                           = 'Intake';
        requestWrapper.miscelleanousParameter         = '';
        requestWrapper.primaryApplicationIndividualId = primAppIndivId;
        requestWrapper.individualIds                  = '999018553;1234567;2345678;3456789';
        requestWrapper.viewName                       = viewName;
        requestWrapper.applicationID                  = applicationId;
        
        return requestWrapper;
    }
    
    public class SSP_RSSPDC_IntegrationServiceErrorMock implements HttpCalloutMock {
        public HttpResponse respond(HttpRequest request) {
            CalloutException e = (CalloutException)CalloutException.class.newInstance();
            e.setMessage('Read Time Out');
            throw e;
        }
    }

    public static void handleException() {
        SSP_DC_ReverseMockImpl mock = new SSP_DC_ReverseMockImpl(true);
        Test.setMock(HttpCalloutMock.class, mock);
        Test.startTest();
        RSSP_DC_Wrapper objResponse = invokeRSSPDC(SSP_InterfaceConstants.KHIPP_PAYMENT_SUMMARY);
        SSP_KHIPPPaymentSummaryWrapper objWrapper = new SSP_KHIPPPaymentSummaryWrapper();
        objWrapper = objResponse.KHIPPPaymentSummaryPayload;
        Test.stopTest();
        System.assertEquals(null, objResponse.KHIPPPaymentSummaryPayload);
    }

    public static RSSP_DC_Wrapper invokeRSSPDC(String sViewName) {
        Map<String, Object> mapParams = new Map<String, Object>();
        SSP_RSSPDC_RequestWrapper reqWrapper = new SSP_RSSPDC_RequestWrapper();
        reqWrapper.viewName = sViewName;
        mapParams.put(SSP_InterfaceConstants.JSON_BODY,reqWrapper);
        mapParams.put(SSP_InterfaceConstants.IS_DEBUG,true);
        List<Object> objList = IntegrationFactory.invokeCallout(SSP_InterfaceConstants.REVERSE_SSP_DC, mapParams);
        return (RSSP_DC_Wrapper)objList[0];
    }
}