force-app/main/default/objects/Account/fields/DCDataId__c.field-meta.xml
<CustomField>
    <fullName>DCDataId__c</fullName>
    <description>Mapped to Application.AgentAssisterAssociation.AgencyId field in SSP-DC. Field is used as lookup id on DCAgencyEmployee table.</description>
    <label>DC Data Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/AuthRep.recordType-meta.xml
<RecordType>
    <fullName>AuthRep</fullName>
    <active>true</active>
    <description>Authorized representative account</description>
    <label>AuthRep</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Resource_Engine.recordType-meta.xml
<RecordType>
    <fullName>Resource_Engine</fullName>
    <active>true</active>
    <label>Organization</label>
</RecordType>

force-app/main/default/objects/AccountContactRelation/fields/AddressLine2__c.field-meta.xml
<CustomField>
    <fullName>AddressLine2__c</fullName>
    <description>This field is used to store address of AuthRep/Assiter/Agent.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>AddressLine2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountContactRelation/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>This  field is used to store address of AuthRep/Assiter/Agent</description>
    <encryptionScheme>None</encryptionScheme>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountContactRelation/fields/CountyCode__c.field-meta.xml
<CustomField>
    <fullName>CountyCode__c</fullName>
    <description>This  field is used to store address of AuthRep/Assiter/Agent</description>
    <label>CountyCode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SSPCounty</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AccountContactRelation/fields/RepresentativeRelationshipCode__c.field-meta.xml
<CustomField>
    <fullName>RepresentativeRelationshipCode__c</fullName>
    <description>Relationship of auth rep with application HoH</description>
    <label>How is this person related to you?</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>RepresentativeRelationship</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/AccountContactRelation/fields/SSP_State__c.field-meta.xml
<CustomField>
    <fullName>SSP_State__c</fullName>
    <description>This  field is used to store address of AuthRep/Assiter/Agent</description>
    <label>SSP State</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>SSPState</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/AccountContactRelation/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <description>This  field is used to store address of AuthRep/Assiter/Agent</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountContactRelation/fields/SuffixCode__c.field-meta.xml
<CustomField>
    <fullName>SuffixCode__c</fullName>
    <description>suffix code in signature to add this auth rep</description>
    <label>Suffix Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Suffix</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AccountContactRelation/fields/Zipcode4__c.field-meta.xml
<CustomField>
    <fullName>Zipcode4__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Zip Code (Four Digit)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountContactRelation/fields/Zipcode5__c.field-meta.xml
<CustomField>
    <fullName>Zipcode5__c</fullName>
    <description>This  field is used to store address of AuthRep/Assiter/Agent</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Zip Code (Five Digit)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Related Account</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/AddressLine2__c.field-meta.xml
<CustomField>
    <fullName>AddressLine2__c</fullName>
    <description>Address Line 2</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Address Line 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>City</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CountyCode__c.field-meta.xml
<CustomField>
    <fullName>CountyCode__c</fullName>
    <description>County</description>
    <label>County</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SSPCounty</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/DoesAuthRepHasOrg__c.field-meta.xml
<CustomField>
    <fullName>DoesAuthRepHasOrg__c</fullName>
    <description>toggle question to ask for further details for organization for auth rep</description>
    <label>Does Auth Rep work for organization?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>YesNo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/GenderCode__c.field-meta.xml
<CustomField>
    <fullName>GenderCode__c</fullName>
    <description>Gender of a Contact</description>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SSPGender</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/IsManualAuthRep__c.field-meta.xml
<CustomField>
    <fullName>IsManualAuthRep__c</fullName>
    <defaultValue>false</defaultValue>
    <description>flag set to true for auth reps added manually in SSP. This will be false for auth reps added via day 0 data load.</description>
    <label>Is Manual Auth Rep</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/OrganizationName__c.field-meta.xml
<CustomField>
    <fullName>OrganizationName__c</fullName>
    <description>Organization Name of a Contact</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Organization Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/OrgranizationIdentificationNumber__c.field-meta.xml
<CustomField>
    <fullName>OrgranizationIdentificationNumber__c</fullName>
    <description>Organization Identification Number</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Organization ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PreferredLanguageCode__c.field-meta.xml
<CustomField>
    <fullName>PreferredLanguageCode__c</fullName>
    <description>Shows the list of preferred languages</description>
    <label>Preferred Language</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>SpokenLanguage</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/PrimaryPhoneExtension__c.field-meta.xml
<CustomField>
    <fullName>PrimaryPhoneExtension__c</fullName>
    <description>Primary Phone Extension of a Contact</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Primary Phone Extension</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/RepresentativeRelationshipCode__c.field-meta.xml
<CustomField>
    <fullName>RepresentativeRelationshipCode__c</fullName>
    <description>How is this person related to you ?</description>
    <label>How is this person related to you?</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>RepresentativeRelationship</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/SSN__c.field-meta.xml
<CustomField>
    <fullName>SSN__c</fullName>
    <description>Social Security Number</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Social Security Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SSP_State__c.field-meta.xml
<CustomField>
    <fullName>SSP_State__c</fullName>
    <description>State code of Contact</description>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>SSPState</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <description>Street of a contact address</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SuffixCode__c.field-meta.xml
<CustomField>
    <fullName>SuffixCode__c</fullName>
    <description>Suffix Code</description>
    <label>Suffix</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Suffix</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Zipcode4__c.field-meta.xml
<CustomField>
    <fullName>Zipcode4__c</fullName>
    <description>Four digit Zip Code</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Zip Code (Four Digit)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Zipcode5__c.field-meta.xml
<CustomField>
    <fullName>Zipcode5__c</fullName>
    <description>Five digit Zip Code</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Zip Code (Five Digit)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Non_Citizen.recordType-meta.xml
<RecordType>
    <fullName>Non_Citizen</fullName>
    <active>true</active>
    <description>Common recordtype to be used for all non citizen roles</description>
    <label>Non Citizen</label>
</RecordType>

force-app/main/default/objects/SSP_Application__c/SSP_Application__c.object-meta.xml
<CustomObject>
    <description>To store SSP Application and Case data</description>
    <label>SSP Application</label>
    <nameField>
        
        <displayFormat>{000000000}</displayFormat>
        
        <label>SSP_Application Name</label>
        
        <type>AutoNumber</type>
        
    </nameField>
    <pluralLabel>SSP Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Application__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Shows the related Account to an Application</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>SSP_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/SSP_ApplicationIndividual__c.object-meta.xml
<CustomObject>
    <description>Custom junction object to maintain association between member and application</description>
    <label>SSP ApplicationIndividual</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>SSP_ApplicationIndividual Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SSP ApplicationIndividuals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/SSP_Application__c.field-meta.xml
<CustomField>
    <fullName>SSP_Application__c</fullName>
    <description>Indicates the application related to a member</description>
    <label>SSP_Application</label>
    <referenceTo>SSP_Application__c</referenceTo>
    <relationshipName>SSP_ApplicationIndividuals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/SSP_Member__c.object-meta.xml
<CustomObject>
    <description>Stores details about an individual member of a case/application such as gatepost reponse, incarceration, disability, living arrangement, pregnancy, address details. Also repurposed to store information of different individuals in the form of individual alien, alien sponsor, care taker,  care coordinator etc.</description>
    <label>SSP Member</label>
    <nameField>
        
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        
        <label>SSP_Member Name</label>
        
        <type>Text</type>
        
    </nameField>
    <pluralLabel>SSP Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Member__c/fields/GenderCode__c.field-meta.xml
<CustomField>
    <fullName>GenderCode__c</fullName>
    <description>This field is used to store Gender on a member</description>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>SSPGender</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/OrganizationName__c.field-meta.xml
<CustomField>
    <fullName>OrganizationName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to indicate a related institution of organization type on a member</description>
    <label>Organization/Provider Name</label>
    <referenceTo>SSP_Institution__c</referenceTo>
    <relationshipLabel>SSP Members (Organization/Provider Name)</relationshipLabel>
    <relationshipName>SSP_Member</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/PrimaryPhoneExtension__c.field-meta.xml
<CustomField>
    <fullName>PrimaryPhoneExtension__c</fullName>
    <description>This field is used to store primary phone extension of a member</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Primary Phone Extension</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/SSN__c.field-meta.xml
<CustomField>
    <fullName>SSN__c</fullName>
    <description>This field is used to store Social Security Number of a member</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Social Security Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/SuffixCode__c.field-meta.xml
<CustomField>
    <fullName>SuffixCode__c</fullName>
    <description>This field is used to store Suffix code on a member</description>
    <label>Suffix</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>Suffix</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/globalValueSets/RepresentativeRelationship.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>EX</fullName>
        
        
        <label>Executor</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>FM</fullName>
        
        
        <label>Family member (not spouse)</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>FR</fullName>
        
        
        <label>Friend</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>LG</fullName>
        
        
        <label>Legal Guardian</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>NF</fullName>
        
        
        <label>Nursing Facility Representative</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>OT</fullName>
        
        
        <label>Other</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>OE</fullName>
        
        
        <label>Outside entity</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>MN</fullName>
        
        
        <label>Parent of a minor child</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>PA</fullName>
        
        
        <label>Power of Attorney</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SP</fullName>
        
        
        <label>Spouse</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>PY</fullName>
        
        
        <label>Statutory Benefit Payee</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>TCE</fullName>
        
        
        <label>Treatment Center Employee</label>
        
    </customValue>
    
    <description>Used to store relationship types for Representatives</description>
    
    <masterLabel>Representative Relationship</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/globalValueSets/SSPGender.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>M</fullName>
        
        
        <label>Male</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>F</fullName>
        
        
        <label>Female</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>U</fullName>
        
        
        <label>Unknown</label>
        
    </customValue>
    
    <description>Different Gender values</description>
    
    <masterLabel>SSP Gender</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/globalValueSets/Suffix.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>JR</fullName>
        
        
        <label>Jr.</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SR</fullName>
        
        
        <label>Sr.</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>TW</fullName>
        
        
        <label>II</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>TH</fullName>
        
        
        <label>III</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>FO</fullName>
        
        
        <label>IV</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>FV</fullName>
        
        
        <label>V</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SI</fullName>
        
        
        <label>VI</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SE</fullName>
        
        
        <label>VII</label>
        
    </customValue>
    
    <description>Suffix codes used for any user</description>
    
    <masterLabel>Suffix</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/globalValueSets/YesNo.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>Y</fullName>
        
        
        <label>YES</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>N</fullName>
        
        
        <label>NO</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>U</fullName>
        
        
        <label>Unknown</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>NULL</fullName>
        
        
        <label>NULL</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>H</fullName>
        
        
        <label>Historical</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>I don&apos;t know</fullName>
        
        
        <label>I don&apos;t know</label>
        
    </customValue>
    
    <description>Used to store different types of toggle picklist values</description>
    
    <masterLabel>YesNo</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/classes/SSP_AddAuthRepController.cls
/*
* classname     :  SSP_AddAuthRepController
* @description  :  Controller class for Add Auth Rep FLow (Class is refering to day 0 data, where we need to access and operate on day0 data which the member doesnt have access, hence is without sharing)
* @author       :  Shrikant Raut   
* @date         :  01/06/2020
* MODIFICATION LOG:
* DEVELOPER                     DATE                               DESCRIPTION
* ---------------------------------------------------------------------------------------------

**/
public without sharing class SSP_AddAuthRepController {
    /*
* @author       Shrikant Raut 
* @date         01/20/2019 
* @methodname   fetchContactInformation
* @description  This methods is used to fetch  contact information
* @return       SSP_LightningResponse
**/
    @auraEnabled(cacheable=true) 
    public static SSP_LightningResponse fetchContactInformation(Id sspContactId, Id sspApplicationId, String callingComponent ){
        SSP_Utility.isAuthenticatedUser(); //Iron Dome fix
        SSP_LightningResponse response = new SSP_LightningResponse();
        Set<String> fieldSet = new Set<String>{'Id','IsManualAuthRep__c','DoesAuthRepHasOrg__c','FirstName','MiddleName','LastName','SuffixCode__c','Email','SSN__c','GenderCode__c','BirthDate','Phone','PrimaryPhoneExtension__c','PreferredLanguageCode__c','OrganizationName__c','OrgranizationIdentificationNumber__c'};
            List<Contact> contactList = new List<Contact>();
        List<AccountContactRelation> acrList = new List<AccountContactRelation>();      
        List<AccountContactRelation> acrOrgList = new List<AccountContactRelation>();      
        SSP_Application__c sspApp;
        try{
            if(sspApplicationId != null ){
                SSP_LightningResponse objResponse = new SSP_LightningResponse();           
                objResponse = SSP_AuthRepAccessRequestService.getRequestAccessPermission(sspApplicationId);
                if(objResponse != null && objResponse.mapResponse != null && (!objResponse.mapResponse.containsKey('hasAccess'))){
                    response.put('hasNoAccess',true);
                    response.bIsSuccess = true;
                    return response;    
                }
            }
            if(sspApplicationId != null){
                sspApp = SSP_ApplicationSelector.queryApplicationDataById(sspApplicationId, new List<String>{'Account__c'});
                response.put('applicationAccount',sspApp.Account__c);   
            }
            if(sspContactId != null && sspApp != null){                
                
                Map<String, String> conditionMap = new Map<String, String>{'limit'=>'1','Id'=> sspContactId};                    
                    contactList = SSP_ContactSelector.queryContactData(new Map<String, String>{'objectName'=>'Contact','operator'=>'AND'}, 
                                                                       fieldSet, 
                                                                       conditionMap);                    
                acrList = SSP_AccountContactRelationSelector.queryACRData(new Map<String, String>{'objectName'=>'AccountContactRelation','operator'=>'AND','hasToLabel'=>'true'}, 
                                                                          new Set<String>{'Id','contactId','RepresentativeRelationshipCode__c','toLabel(CountyCode__c)','Zipcode5__c','Zipcode4__c','AddressLine2__c','Street__c','City__c','toLabel(SSP_State__c)'}, 
                                                                          new Map<String, String>{'limit'=>'1','ContactId'=> sspContactId, 'AccountId' => sspApp.Account__c});  
                
                acrOrgList = SSP_AccountContactRelationSelector.queryACRData(new Map<String, String>{'objectName'=>'AccountContactRelation','operator'=>'AND'}, 
                                                                             new Set<String>{'Id','account.Name','account.DCdataId__c'}, 
                                                                             new Map<String, String>{'limit'=>'1000','contactId'=> sspContactId,'account.recordtype.developerName '=>'Resource_Engine'});
                
                if((!acrOrgList.isEmpty()) && acrOrgList[0].account != null && acrOrgList[0].account.DCdataId__c != null){
                    response.put('organizationName', acrOrgList[0].account.Name );
                    response.put('organizationId', acrOrgList[0].account.DCdataId__c);    
                }
                                                 
                response.put('contactRecord',(contactList != null && !contactList.isEmpty()) ? contactList[0] : null);
                response.put('accountContactRelationRecord',(acrList != null && !acrList.isEmpty()) ? acrList[0] : null);                                             
            }    
            response.put('relationshipCodes',SSP_Utility.getPickListValues('AccountContactRelation','RepresentativeRelationshipCode__c',null));                  
            response.bIsSuccess = true;
        }catch(Exception ex){                                
            List<LOG_LogMessage__c> lstLogMessages = LOG_LogMessageUtility.logMessage(ex, 'SSP_AddAuthRepController', 'fetchContactInformation', ex.getMessage() , true);            
            response.addException(ex, lstLogMessages[0].Id);            
        }
        
        
        return response;
    }
    
    /*
* @author       Shrikant Raut
* @date         01/20/2019
* @methodname   upsertContactInformation and create ACR if required
* @description  This methods is used to insert/update contact record for AuthReps.
* @return       SSP_LightningResponse
**/
    @auraEnabled
    public static SSP_LightningResponse upsertContactInformation(String contactJSON, String relationJSON, String detailJSON ){                    
        SSP_LightningResponse response = new SSP_LightningResponse();
        Map<String, String> resultMap = new Map<String, String>();
        try{
            if(contactJSON != null && detailJSON != null){
                List<Contact> contactList = (List<Contact>)JSON.deserialize(contactJSON, List<Contact>.class);
                List<AccountContactRelation> acrList;
                if(relationJSON != null){
                    acrList = (List<AccountContactRelation>)JSON.deserialize(relationJSON, List<AccountContactRelation>.class);
                }
                
                Map<String, String> detailMap =  (Map<String, String>)JSON.deserialize(detailJSON, Map<String, String>.class);
                Id sspApplicationId = (detailMap != null && detailMap.containsKey('sspApplicationId')) ? detailMap.get('sspApplicationId') : null;
                Id sspApplicationAccount = (detailMap != null && detailMap.containsKey('sspApplicationAccount')) ? detailMap.get('sspApplicationAccount') : null;
                Boolean isSelectedViaSearch = (detailMap != null && detailMap.containsKey('isSelectedViaSearch')) ? (detailMap.get('isSelectedViaSearch').equalsIgnoreCase('true') ? true : false ) : false;
                Boolean isAddFlow =  (detailMap != null && detailMap.containsKey('flowName')) ? (detailMap.get('flowName').equalsIgnoreCase('addAuthRep') ? true : false ) : false;
                Boolean updateResult = true;
                if(sspApplicationAccount != null ){    
                    List<AccountContactRelation> lstCurrentUserACR =  new List<AccountContactRelation>();                   
                    if(sspApplicationAccount != null){
                        lstCurrentUserACR = SSP_SharingBypassFetcher.fetchRecords (
                            new Map<String, String>{'objectName'=>'AccountContactRelation','operator'=>'AND'}, 
                            new Set<String>{'Id'}, 
                            new Map<String, String>{'ContactId'=> SSP_Utility.getCurrentUserDetails()[0].ContactId, 'AccountId'=>sspApplicationAccount});
                    }
                    if(lstCurrentUserACR.isEmpty()){
                        response.put('hasNoAccess',true);
                        response.bIsSuccess = true;
                        return response;    
                    }
                }
                
                //Update contact only if the authrep is not selected using search and an existing authrep is been edited (For Edit Flow)
                if(contactList != null && !contactList.isEmpty() && contactList[0] != null && contactList[0].Id != null && !isSelectedViaSearch && !isAddFlow){ 
                    ESAPI.accessController().setSharingMode(SFDCAccessController.SharingMode.WITHOUT);
                   // validateAddress(contactList[0]);   
                    updateResult = ESAPI.accessController().updateAsUser(new Map<ID,Contact>(contactList), SSP_Utility.getFieldsNamesList (contactList)).wasSuccessful();    
                    response.bIsSuccess = true;
                    
                }
                
                //Upsert acr based on the action performed(authrep edited - update acr)               
                if(contactList != null && !contactList.isEmpty() && contactList[0].Id != null && updateResult && !isAddFlow && acrList != null){
                    acrList = upsertACR(acrList, sspApplicationAccount, null);
                    Boolean result = (acrList != null && !acrList.isEmpty());
                    response.bIsSuccess = result;
                    response.put(result ? 'SUCCESS' : 'ERROR', result ? acrList[0].id : 'ACR creation failed' );
                    response.put(result ? 'ACR' : 'ERROR', result ? acrList[0].id : 'ACR creation failed' );
                    response.put('contactId', contactList[0].Id);
                }
                
                //For manual data entry of a new authrep, insert contact and corresponding acr record                
                else if(contactList != null && !contactList.isEmpty() &&  contactList[0] != null && contactList[0].Id == null && acrList == null && isAddFlow){
                    resultMap = createNewAuthRep(contactList);                    
                    response.bIsSuccess = !(resultMap != null && resultMap.containsKey('ERROR'));
                }
                
                //else copy contact Id into response map
                else if(contactList != null && !contactList.isEmpty() && contactList[0].Id != null){
                    response.put('contactId', contactList[0].Id);
                }
                
                if(resultMap != null && !resultMap.isEmpty()){
                    for(String key : resultMap.keySet()){
                        response.put(key, resultMap.get(key));
                    }
                }
            }
        }
        catch(Exception ex){
            List<LOG_LogMessage__c> lstLogMessages = LOG_LogMessageUtility.logMessage(ex, 'SSP_AddAuthRepController', 'upsertContactInformation', ex.getMessage() , true);            
            response.addException(ex, lstLogMessages[0].Id);
        }
        return response;
    }
    
    /*
    * @author       Shrikant Raut
    * @date         01/22/2019
    * @methodname   createNewAuthRep
    * @description  Method to contact for Authorized representative
    * @return       SSP_LightningResponse
    **/
    private static Map<String, String> createNewAuthRep(List<Contact> contactList){
        Map<String, String> resultMap = new Map<String, String>();                 
        contactList[0].recordTypeId = SSP_Utility.getRecrodTypeIdBySobjectAndDevName('Contact','Non_Citizen');
        contactList[0].IsManualAuthRep__c = true;
        Map<String,object> mapRestResult =  createContact(contactList);            
        contactList = (List<Contact>)mapRestResult.get('lstContacts');         
        if(contactList != null && !contactList.isEmpty() && contactList[0].AccountId != null){                            
            resultMap.put('contactId', contactList[0].Id);
            resultMap.put('SUCCESS',JSON.serialize(new Map<String, String>{ 'contactId'=>contactList[0].Id}));             
        }else{
            resultMap.put('ERROR', 'Contact insertion failed');
        }
        return resultMap;
    }

    /*
    * @author       Shrikant Raut
    * @date         01/28/2019
    * @methodname   createACR
    * @description  Method to create account contact relation. 
    * @return       SSP_LightningResponse
    **/
    private static List<AccountContactRelation> upsertACR(List<AccountContactRelation> acrList, Id sspApplicationAccount, Id sspContactId){
        if(acrList != null && sspApplicationAccount !=null && acrList[0] != null && acrList[0].Id != null){      
            ESAPI.accessController().setSharingMode(SFDCAccessController.SharingMode.WITHOUT);
            acrList = ESAPI.accessController().updateAsUser(new Map<ID,AccountContactRelation>(acrList), SSP_Utility.getFieldsNamesList (acrList)).wasSuccessful() ? acrList : null ;        
        }
        return acrList;
    }


    /*
    * @author       Shrikant Raut
    * @date         01/22/2019
    * @methodname   createNewAuthRep
    * @description  Method to create account using API
    * @return       SSP_LightningResponse
    **/
    private static Map<String,object> createContact(List<Contact> contactList){
        List<Account> lstAccountToInsert = new List<Account>();
        Account objAcc = new Account(); 
        objAcc.Name =  contactList[0].FirstName +' '+ contactList[0].LastName;
        lstAccountToInsert.add(objAcc);                
        Map<String,Object> accCreation = SSP_ProgramSelectionService.invokeAccountCreationService(lstAccountToInsert, contactList, SSP_Utility.getCurrentUserDetails()[0].ContactId); //ForceReviewer Fix
        //List<LOG_LogMessage__c> physicalAddressLogs = validateAddress(contactList[0]);
        
        if(!contactList.isEmpty() && !accCreation.isEmpty()){
            
            
            List<Contact> sObjContactList = (List<Contact>)accCreation.get('lstContacts');   
            contactList[0].Id = sObjContactList[0].Id;
            //contactList[0].Id = (Id)accCreation.get('lstContacts').Id;
            if(!contactList.isEmpty()){
                
             	validateAddress(contactList[0]);   
            }            
        }
        return accCreation;
    }

            /*
    * @author       Shrikant Raut 
    * @date         01/20/2019 
    * @methodname   fetchContactInformation
    * @description  This methods is used to fetch  contact information
    * @return       SSP_LightningResponse
    **/
    @auraEnabled(cacheable=true) 
    public static SSP_LightningResponse fetchDetailsForConsent(Id sspAccountId, String callingComponent){
        SSP_Utility.isAuthenticatedUser(); //Iron Dome fix
        SSP_LightningResponse response = new SSP_LightningResponse();        
        List<Contact> contactList = new List<Contact>();    
        List<SSP_ApplicationIndividual__c> memberList = new List<SSP_ApplicationIndividual__c>();    
        List<AccountContactRelation> acrList = new List<AccountContactRelation>();                    
        try{
            memberList = SSP_ApplicationIndividualSelector.queryApplicationIndividualData(new Map<String, String>{'objectName'=>'SSP_ApplicationIndividual__c','operator'=>'AND'}, 
                                                            new Set<String>{'SSP_Member__r.FirstName__c', 'SSP_Application__c', 'SSP_Member__r.MiddleInitial__c', 'SSP_Member__r.LastName__c', 'SSP_Member__r.SuffixCode__c'}, 
                                                            new Map<String, String>{'limit'=>'1','IsHeadOfHousehold__c'=> '#true#', 'SSP_Application__r.Account__c'=>sspAccountId});                                                     
            response.put('appIndividualRecord',(memberList != null && !memberList.isEmpty()) ? memberList[0] : null);   
            response.put('dateToday',SSP_Utility.today());                                                   
            response.put('suffixCodeValues',SSP_Utility.getPickListValues('AccountContactRelation','SuffixCode__c',null));                          
            response.bIsSuccess = true;
        }catch(Exception ex){                                       
            List<LOG_LogMessage__c> lstLogMessages = LOG_LogMessageUtility.logMessage(ex, 'SSP_AddAuthRepController', 'fetchContactInformation', ex.getMessage() , true);                        
            response.addException(ex, lstLogMessages[0].Id);
        }
        return response;
    }
    
    
    /*    
* @date         01/24/2020
* @methodname   checkForDupicateAuthRep
* @description  Method to create account using API
* @return       SSP_LightningResponse
**/
    @AuraEnabled
    public static SSP_LightningResponse checkForDupicateAuthRep(string sContactJSON){
        SSP_LightningResponse response = new SSP_LightningResponse();
        try{   
            Contact objContact = (Contact)JSON.deserialize(sContactJSON, Contact.class); 
            Set<String> fieldSet = new Set<String>{'Id','DoesAuthRepHasOrg__c','Name','FirstName','MiddleName','LastName','SuffixCode__c','Email','GenderCode__c','Phone','PrimaryPhoneExtension__c','PreferredLanguageCode__c','RepresentativeRelationshipCode__c','OrganizationName__c','OrgranizationIdentificationNumber__c'};
                List<Contact> contactList = new List<Contact>();  
            List<AccountContactRelation> acrList = new List<AccountContactRelation>();  
            if(objContact != null ){
                Map<String, String> conditionMap = new Map<String, String>{'limit'=>'1','FirstName'=> objContact.FirstName,'LastName' => objContact.LastName,'Email' => objContact.Email,'IsManualAuthRep__c'=>'false'};                    
                    contactList = SSP_ContactSelector.queryContactData(new Map<String, String>{'objectName'=>'Contact','operator'=>'AND'}, 
                                                                       fieldSet, 
                                                                       conditionMap);     
                if(!contactList.isEmpty()){
                    acrList = SSP_AccountContactRelationSelector.queryACRData(new Map<String, String>{'objectName'=>'AccountContactRelation','operator'=>'AND'}, 
                                                                              new Set<String>{'Id','account.Name','account.DCdataId__c','Roles','dcAgencyId__c','dcContactId__c'}, 
                                                                              new Map<String, String>{'limit'=>'1000','contactId'=> contactList[0].Id,'account.recordtype.name'=>'Organization'});
                }
                
                // if((!acrList.isEmpty()) && acrList[0].Roles.contains('Authorized Representative')){  
                if((!acrList.isEmpty()) && acrList[0].Roles != null && (acrList[0].Roles.contains(SSP_GlobalConstants.INDIVDIUDAL_AUTH_REP_ROLE_STRING) || acrList[0].Roles.contains( SSP_GlobalConstants.ORGANISATION_AUTH_REP) ||
                                                                        acrList[0].Roles.contains('Authorized Representative')  )) { 
                                                                            if(acrList[0].account.DCdataId__c != null){
                                                                                response.put('organizationName', acrList[0].account.Name );    
                                                                                response.put('organizationId',((!acrList.isEmpty()) && acrList[0].account.DCdataId__c != null) ? acrList[0].account.DCdataId__c : null);
                                                                            }
                                                                            response.put('organizationContactId',((!acrList.isEmpty()) && acrList[0].dcContactId__c != null) ? acrList[0].dcContactId__c : null);
                                                                            if(!contactList.isEmpty()){
                                                                            response.put('contactDuplicateRecord',contactList[0]); 
                                                                            }

                                                                            /** #390707 */
                                                                            if(acrList[0].Roles.contains( SSP_GlobalConstants.ORGANISATION_AUTH_REP)){
                                                                                response.put('isOrgAuthRep', 'Y' ); 
                                                                                if(((String.isNotBlank(contactList[0].DoesAuthRepHasOrg__c) && contactList[0].DoesAuthRepHasOrg__c != 'Y') || String.isBlank(contactList[0].DoesAuthRepHasOrg__c)) && acrList[0].account.DCdataId__c != null){
                                                                                    Contact conToUpdate = new Contact(Id = contactList[0].Id);
                                                                                    conToUpdate.DoesAuthRepHasOrg__c = 'Y';
                                                                                    conToUpdate.OrganizationName__c = acrList[0].account.Name;
                                                                                    conToUpdate.OrgranizationIdentificationNumber__c = String.valueOf(acrList[0].account.DCdataId__c);
                                                                                    ESAPI.accessController().setSharingMode(SFDCAccessController.SharingMode.WITHOUT);                    
                                                                                    ESAPI.accessController().updateAsUser(new Map<ID,Contact>(new List<Contact>{conToUpdate}), SSP_Utility.getFieldsNamesList (new List<Contact>{conToUpdate}));
                                                                                    
                                                                                }
                                                                            }                                                                            
                                                                            /** */
                                                                        }else {
                                                                            if(!contactList.isEmpty()){
                                                                            contactList[0].DoesAuthRepHasOrg__c = 'N'; 
                                                                        }
                                                                            response.put('contactDuplicateRecord',NULL); 
                                                                        }
                
                
                
            }
            
        }  catch(Exception ex) {
            response.put('EXCEPTION',ex.getStackTraceString());
            LOG_LogMessageUtility.logMessage(LOG_LogMessageUtility.LOG_LogLevel.Error, 'SSP_AddAuthRepController', 'checkForDupicateAuthRep', ex.getMessage(), true);
        }
        return response;
    }
    
    public static void validateAddress(Contact objContact){
        List<LOG_LogMessage__c> logMessageList = new List<LOG_LogMessage__c>();
        SSP_AddressVerificationWSDLService.COT_USAC_County_op1 request = new SSP_AddressVerificationWSDLService.COT_USAC_County_op1();
        request.record_id = '';
        request.line1 = objContact.Street__c;
        request.line2 = objContact.AddressLine2__c;
        request.city = objContact.City__c;
        request.state = objContact.SSP_State__c; 
        request.zip = objContact.Zipcode5__c;
        
        List<Object> responseRecords = IntegrationFactory.invokeCallout('SSP_AddressVerification', new Map<String, Object>{'body' => JSON.serialize(request)});
        if(responseRecords != null && !responseRecords.isEmpty() && responseRecords[0] != null) {
            SSP_AddressResponseWrapper responseContainer = (SSP_AddressResponseWrapper)responseRecords[0];
            SSP_AddressVerificationWSDLService.COT_USAC_County_svcOutVar1 response = (SSP_AddressVerificationWSDLService.COT_USAC_County_svcOutVar1)responseContainer.responseDetail;            
            if(response != null) {   
                objContact.IsAddressValidated__c = true;             
                if(response.cot_mail_delivery_code == 'G') {
                    objContact.Street__c = response.cass_line1;
                    objContact.AddressLine2__c = response.cass_line2;
                    objContact.City__c = response.cass_city;
                    objContact.SSP_State__c = response.cass_state;
                    objContact.Zipcode4__c = response.cass_zip4;
                    objContact.Zipcode5__c = response.cass_zip5;
                    objContact.CountyCode__c = getCountyCode(response.usps_county_name);
                }
                else if(response.cot_mail_delivery_code == 'R') {
                    objContact.Street__c = response.cass_line1;
                    objContact.AddressLine2__c = response.cass_line2;
                    objContact.City__c = response.cass_city;
                    objContact.SSP_State__c = response.cass_state;
                    objContact.CountyCode__c = getCountyCode(response.usps_county_name);
                }
            }            
        }
        
        if(objContact.SSP_State__c == 'KY' && objContact.CountyCode__c == '200') {
            objContact.CountyCode__c = null;
		}
        if(objContact != null){            
            //ESAPI.accessController().updateAsUser(objContact, SSP_Utility.getFieldsNamesList(new List<Contact> {objContact}));
           // update objContact;
            
        }
        //return null;
    }
    
    public static String getCountyCode(String countyName) {
        countyName = countyName.toLowerCase();
        
        Map<String, String> values = SSP_Utility.getPickListValues('Contact', 'CountyCode__c', null);
        
        for(String countyCode: values.keySet()) {
            if(countyName == values.get(countyCode).toLowerCase()) {
                
                return countyCode;
            }
        }
        //return OUT OF COUNTY code, if not found
        return '200';
    }

}