force-app/main/default/objects/Account/fields/POC_Email__c.field-meta.xml
<CustomField>
    <fullName>POC_Email__c</fullName>
    <description>The email address of the Point of Contact of the account</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>POC_Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/POC_Name__c.field-meta.xml
<CustomField>
    <fullName>POC_Name__c</fullName>
    <description>The name of the point of contact for the account</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>POC Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Resource_Engine.recordType-meta.xml
<RecordType>
    <fullName>Resource_Engine</fullName>
    <active>true</active>
    <label>Organization</label>
</RecordType>

force-app/main/default/objects/CommunicationLog__c/CommunicationLog__c.object-meta.xml
<CustomObject>
    <description>Central object to send communications</description>
    <label>Communication Nub</label>
    <nameField>
        <displayFormat>CL-{0000}</displayFormat>
        <label>Communication Nub Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Communication Nub</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Community_URL_Settings__c/Community_URL_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Contains community URLs specific to org</description>
    <label>Community URL Settings</label>
</CustomObject>

force-app/main/default/objects/Contact/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Related Account</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Account to which the location record is related to</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/PointofContactEmail__c.field-meta.xml
<CustomField>
    <fullName>PointofContactEmail__c</fullName>
    <description>Contact info for POC at this location</description>
    <label>Point of Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/PointOfContactName__c.field-meta.xml
<CustomField>
    <fullName>PointOfContactName__c</fullName>
    <description>Contact info for POC at this location</description>
    <label>Point Of Contact Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/LocationResource__c.object-meta.xml
<CustomObject>
    <label>Location Resource</label>
    <nameField>
        <label>Location Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Location Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LocationResource__c/fields/AccountName__c.field-meta.xml
<CustomField>
    <fullName>AccountName__c</fullName>
    <formula>Location__r.AccountName__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AccountName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>The location record to which the location resource is related to</description>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Location Resources</relationshipLabel>
    <relationshipName>Location_Resources</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <description>The resource record to which the location resource is related to</description>
    <label>Resource</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Location Resources</relationshipLabel>
    <relationshipName>Location_Resources</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Referral__c/Referral__c.object-meta.xml
<CustomObject>
    <label>Referral</label>
    <nameField>
        <displayFormat>REF-{0000}</displayFormat>
        <label>Referral Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Referral__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Location of the resource for which the referral is created</description>
    <label>Location Requested</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Referrals</relationshipLabel>
    <relationshipName>Referrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referral__c/fields/ReferredAccountID__c.field-meta.xml
<CustomField>
    <fullName>ReferredAccountID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Organization who receives the referral (to whom the referral is made)</description>
    <label>Organization Referred To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Referrals</relationshipLabel>
    <relationshipName>Referrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referral__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Resource record for which the referral is created</description>
    <label>Resource</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Referrals</relationshipLabel>
    <relationshipName>Referrals</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/ReferralTriggerHandlerTest.cls
@isTest
public class ReferralTriggerHandlerTest {
    
    static  Id citizenRecordTypeIdAccount = Schema.SObjectType.Account.getRecordTypeInfosByName().get(RE_GlobalConstants.strCitizenRecordTypeName).getRecordTypeId();
    static Id contactCitizenRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get(RE_GlobalConstants.strCitizenRecordTypeName).getRecordTypeId();
    @testSetup static void setup() {
        TestDataFactory.testDataSetup();
        List<Account> lstCitizenAccounts = [SELECT Id,POC_Name__c,Name,POC_Email__c FROM Account where recordTypeId=:citizenRecordTypeIdAccount AND recordTypeId != null LIMIT 1];
        Contact citizenContact = TestDataFactory.createContactRecord(RE_GlobalConstants.strCitizenFirstName,RE_GlobalConstants.strCitizenLastName,RE_GlobalConstants.strCitizenEmail,contactCitizenRecordTypeId,false);
        citizenContact.AccountId=lstCitizenAccounts[0].Id;
        citizenContact.MailingPostalCode='43223';
        insert citizenContact;
        Id locationRecordTypeId = Schema.SObjectType.Location__c.getRecordTypeInfosByName().get(RE_GlobalConstants.strLocationRecordTypeName).getRecordTypeId();
        List<Location__c> lstLocation = TestDataFactory.createLocations(2, true, locationRecordTypeId, new List<Id>{lstCitizenAccounts[0].Id});
        Id resourceRecordTypeId = Schema.SObjectType.Resource__c.getRecordTypeInfosByName().get(RE_GlobalConstants.strResourceRecordTypeName).getRecordTypeId();
        List<Resource__c> lstResource = TestDataFactory.createResources(10, true, resourceRecordTypeId, new List<Id>{lstCitizenAccounts[0].Id});
        List<Referral__c> lstRreferral=TestDataFactory.createReferral(10,true,GeneralUtility.fetchRecordType(RE_GlobalConstants.strReferralRecordTypeDeveloperName,RE_GlobalConstants.strReferralObjectName).Id,citizenContact.Id,lstCitizenAccounts,lstResource);
        List<LocationResource__c> lstLocRes = TestDataFactory.createLocationResource(2, true, null, lstLocation, lstResource);
    }
    
    @isTest
    public static void getOrgRefCount(){
        Map<Id,Integer> orgIdCountMap = new Map<Id,Integer>();
        Id sREAccRecTypeId = GeneralUtility.getRecrodTypeIdBySobjectAndDevName('Account','Resource_Engine');
        List<Account> accountList = TestDataFactory.createAccounts(10,true,sREAccRecTypeId);
        Set<Id> orgSet = new Set<Id>();
        for(Account a : accountList){
            orgSet.add(a.Id);
        }
        List<AggregateResult> results = [SELECT COUNT(Id) cnt, ReferredAccountID__c rid FROM Referral__c WHERE ReferredAccountID__c IN:orgSet GROUP BY ReferredAccountID__c];
        for(AggregateResult result : results){
            Id orgId = (Id)result.get('rid');
            Integer orgCount = (Integer)result.get('cnt');
            orgIdCountMap.put(orgId, orgCount);
        }
        System.assert(true, orgIdCountMap != null);
    }
    
    @isTest
    public static void testcreateCommunicationRecord(){
        List<CommunicationLog__c> lstCommunicationNubInsert = new List<CommunicationLog__c>();
        Id sREAccRecTypeId = GeneralUtility.getRecrodTypeIdBySobjectAndDevName('Account','Resource_Engine');
        List<Account> lstAccounts = TestDataFactory.createAccounts(1,true,sREAccRecTypeId);
        List<Location__c> lstLocations = [SELECT Id,PointOfContactName__c,AccountName__c,Account__c,PointofContactEmail__c FROM Location__c LIMIT 1];
        
        List<Id> lstAccountIds = new List<Id>();
        lstAccountIds.add(lstAccounts[0].Id);
        List<Resource__c> resourceLst = TestDataFactory.createResources(2, true, null, lstAccountIds);
        List<Location__c> locationLst = TestDataFactory.createLocations(2, true, null, lstAccountIds);
        List<LocationResource__c> lstLocRes = TestDataFactory.createLocationResource(2, true, null, locationLst, resourceLst);
        Test.startTest();
        Boolean isFirstEmail = true;
        String orgId = lstAccounts[0].Id;
        String resourceURL= Community_URL_Settings__c.getOrgDefaults().URL__c+'/s/searchorganization?isOpenClaimRequest='+true+'&orgId=';
        
        ReferralTriggerHandler.createCommunicationRecord(lstAccounts, isFirstEmail, resourceURL);
        ReferralTriggerHandler.createCommunicationRecord(lstLocations, isFirstEmail, resourceURL);
        ReferralTriggerHandler.createCommunicationRecord(lstLocRes, isFirstEmail, resourceURL);
        ReferralTriggerHandler.getOrgData(null);
        ReferralTriggerHandler.getLocationResources(null, null);
        ReferralTriggerHandler.getOrgRefCount(null);
        ReferralTriggerHandler.getLocations(null);
        ReferralTriggerHandler.sendEmail(null, false, 'resourceurl');
        ReferralTriggerHandler.createCommunicationRecord(null, true, 'resourceurl');
        System.assert(lstAccounts.size() > 0, true);
        System.assert(lstLocations.size() > 0, true);
        System.assert(lstLocRes.size() > 0, true);
        Test.stopTest();
    }
    
    
}