force-app/main/default/objects/Account/fields/Rating_Count__c.field-meta.xml
<CustomField>
    <fullName>Rating_Count__c</fullName>
    <description>The count of ratings for the account</description>
    <label>Rating Count</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Rating_Sum__c.field-meta.xml
<CustomField>
    <fullName>Rating_Sum__c</fullName>
    <description>The sum of ratings submitted for the account</description>
    <label>Rating Sum</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Indicates whether the status of the account is Active-Allow Referrals, Active-Do not allow referrals or Inactive</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active - Allow referrals</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active - Do not allow referrals</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Pending Review</fullName>
                <isActive>false</isActive>
                <label>Pending Review</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <isActive>false</isActive>
                <label>Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of contact-Active or Inactive</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/CPUserContact.recordType-meta.xml
<RecordType>
    <fullName>CPUserContact</fullName>
    <active>true</active>
    <description>This record type used for CP user</description>
    <label>CP User Contact</label>
</RecordType>

force-app/main/default/objects/Referral__c/Referral__c.object-meta.xml
<CustomObject>
    <label>Referral</label>
    <nameField>
        <displayFormat>REF-{0000}</displayFormat>
        <label>Referral Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Referral__c/fields/DateClosed__c.field-meta.xml
<CustomField>
    <fullName>DateClosed__c</fullName>
    <description>Date that the referral is completed and marked as closed</description>
    <label>Date Closed</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Referral__c/fields/DateOfReferral__c.field-meta.xml
<CustomField>
    <fullName>DateOfReferral__c</fullName>
    <description>Date the referral is made</description>
    <label>Date Of Referral</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Referral__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Resource record for which the referral is created</description>
    <label>Resource</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Referrals</relationshipLabel>
    <relationshipName>Referrals</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referral__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Indicates whether the status of the referral is New, In Progress-Org in System, In Progress-Org not in system, Closed or Draft</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress - Org in System</fullName>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>In Progress - Org Not in System</fullName>
                <label>Org Not in System</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/RE_ReferralDashboardCtrlTest.cls
/*
* Component Name    : RE_ReferralDashboardCtrlTest
* Owner             : Sai Kiran Velpula
* Created Date      : 09/24/2019
* Description       : Referral Dashboard Controller Test Class
*/
@isTest
public class RE_ReferralDashboardCtrlTest {   
    /*
    *Method Name: getStatisticsDataTest
    *Description: Method to cover functionality of method - getStatisticsData.
    *Returns: none
    */
    @isTest static void getStatisticsDataTest() {
        TestDataFactory.testDataSetup();
        List<Resource__c> resourceList = [SELECT id FROM Resource__c LIMIT 2];
        List<Account> accountList = [SELECT id,Rating_Sum__c,Rating_Count__c FROM Account LIMIT 1];
        accountList[0].Rating_Sum__c = 8;
        accountList[0].Rating_Count__c = 2;
        update accountList;
        RecordType objRecordType = [SELECT ID from RecordType where DeveloperName = 'CPUserContact' AND sObjectType = 'Contact'];
        Contact objContact = TestDataFactory.createContactRecord('FirstName', 'LastName', 'test@email.com', objRecordType.Id, true);
        User cpUser = [SELECT Id,Name, ContactId FROM User WHERE Email='communityusr@deloitte.com' LIMIT 1];
        List<Referral__c> lstReferrals = TestDataFactory.createReferral(1, false, objRecordType.Id , cpUser.ContactId, accountList, resourceList);
        lstReferrals[0].Status__c = 'Closed';
        lstReferrals[0].DateOfReferral__c = System.today();
        lstReferrals[0].DateClosed__c = System.today();
        insert lstReferrals;
        Test.startTest();
        RE_CreateLightningServerResponse result1;
        RE_CreateLightningServerResponse result2;
        System.runAs(cpUser){
            result1 = RE_ReferralDashboardCtrl.getStatisticsData();
            
        }
        System.assert(result1.isSuccessful == true,'Success');
        Test.stopTest(); 
    }
    
    /*
    *Method Name: getStatisticsDataTest
    *Description: Method to cover functionality of method - getStatisticsData.
    *Returns: none
    */
    @isTest static void getStatisticsDataUpdateTest() {
        TestDataFactory.testDataSetup();
        List<Resource__c> resourceList = [SELECT id FROM Resource__c LIMIT 2];
        List<Account> accountList = [SELECT id,Rating_Sum__c,Rating_Count__c FROM Account LIMIT 1];
        accountList[0].Rating_Sum__c = 8;
        accountList[0].Rating_Count__c = 2;
        update accountList;
        RecordType objRecordType = [SELECT ID from RecordType where DeveloperName = 'CPUserContact' AND sObjectType = 'Contact'];
        Contact objContact = TestDataFactory.createContactRecord('FirstName', 'LastName', 'test@email.com', objRecordType.Id, true);
        User cpUser = [SELECT Id,Name, ContactId FROM User WHERE Email='communityusr@deloitte.com' LIMIT 1];
        List<Referral__c> lstReferrals = TestDataFactory.createReferral(1, false, objRecordType.Id , cpUser.ContactId, accountList, resourceList);
        lstReferrals[0].Status__c = 'Closed';
        lstReferrals[0].DateOfReferral__c = System.today();
        lstReferrals[0].DateClosed__c = System.today();
        insert lstReferrals;
        Test.startTest();
        RE_CreateLightningServerResponse result1;
        RE_CreateLightningServerResponse result2;
       
        accountList[0].Rating_Count__c = 0;
        update accountList;
        System.runAs(cpUser){
            result2 = RE_ReferralDashboardCtrl.getStatisticsData();
            
        }
        System.assert(result2.isSuccessful == true,'Success');
        Test.stopTest(); 
    }
}