force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Indicates whether the status of the account is Active-Allow Referrals, Active-Do not allow referrals or Inactive</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active - Allow referrals</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active - Do not allow referrals</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Pending Review</fullName>
                <isActive>false</isActive>
                <label>Pending Review</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <isActive>false</isActive>
                <label>Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Assister.recordType-meta.xml
<RecordType>
    <fullName>Assister</fullName>
    <active>true</active>
    <label>Assister</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Citizen.recordType-meta.xml
<RecordType>
    <fullName>Citizen</fullName>
    <active>true</active>
    <label>Citizen</label>
</RecordType>

force-app/main/default/objects/AccountContactRelation/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>first name in signature of HoH who is adding this auth rep</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Related Account</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CaseOwnership__c.field-meta.xml
<CustomField>
    <fullName>CaseOwnership__c</fullName>
    <description>This field is used to store Case Owner Role.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>CaseOwnership</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/IndividualId__c.field-meta.xml
<CustomField>
    <fullName>IndividualId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Individual Id of a Contact</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>IndividualId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of contact-Active or Inactive</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Assister.recordType-meta.xml
<RecordType>
    <fullName>Assister</fullName>
    <active>true</active>
    <description>assistor contact record</description>
    <label>Assister</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Citizen.recordType-meta.xml
<RecordType>
    <fullName>Citizen</fullName>
    <active>true</active>
    <description>This Record type is used for Residents</description>
    <label>Citizen</label>
</RecordType>

force-app/main/default/objects/SSP_Application__c/SSP_Application__c.object-meta.xml
<CustomObject>
    <description>To store SSP Application and Case data</description>
    <label>SSP Application</label>
    <nameField>
        
        <displayFormat>{000000000}</displayFormat>
        
        <label>SSP_Application Name</label>
        
        <type>AutoNumber</type>
        
    </nameField>
    <pluralLabel>SSP Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Application__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Shows the related Account to an Application</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>SSP_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_Application__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Shows the related Contact to an Application</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>SSP_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SSP_Application__c/fields/DCCaseNumber__c.field-meta.xml
<CustomField>
    <fullName>DCCaseNumber__c</fullName>
    <description>DC mapping Case number of an Application</description>
    <externalId>true</externalId>
    <label>DCCaseNumber</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SSP_Application__c/fields/LocalDCBSOffice__c.field-meta.xml
<CustomField>
    <fullName>LocalDCBSOffice__c</fullName>
    <description>This Field is used to store local dcbs office</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Local DCBS Office</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Different types of status of an Application</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        
            <valueSetDefinition>
            
            
                <value>
                
                    <fullName>N</fullName>
                
                
                    <label>New</label>
                
                </value>
            
                <value>
                
                    <fullName>P</fullName>
                
                
                    <label>Pending</label>
                
                </value>
            
                <value>
                
                    <fullName>AP</fullName>
                
                
                    <label>Approved</label>
                
                </value>
            
                <value>
                
                    <fullName>UN</fullName>
                
                
                    <label>Unsubmitted</label>
                
                </value>
            
                <value>
                
                    <fullName>Inactive</fullName>
                
                
                    <label>Inactive</label>
                
                </value>
            
                <value>
                
                    <fullName>Blocked</fullName>
                
                
                    <label>Blocked</label>
                
                </value>
            
            </valueSetDefinition>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/SSP_ApplicationIndividual__c.object-meta.xml
<CustomObject>
    <description>Custom junction object to maintain association between member and application</description>
    <label>SSP ApplicationIndividual</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>SSP_ApplicationIndividual Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SSP ApplicationIndividuals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/SSP_Application__c.field-meta.xml
<CustomField>
    <fullName>SSP_Application__c</fullName>
    <description>Indicates the application related to a member</description>
    <label>SSP_Application</label>
    <referenceTo>SSP_Application__c</referenceTo>
    <relationshipName>SSP_ApplicationIndividuals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/SSP_Member__c.field-meta.xml
<CustomField>
    <fullName>SSP_Member__c</fullName>
    <description>Indicates the member related to an application</description>
    <label>SSP_Member</label>
    <referenceTo>SSP_Member__c</referenceTo>
    <relationshipName>SSP_ApplicationIndividuals</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/SSP_Member__c.object-meta.xml
<CustomObject>
    <description>Stores details about an individual member of a case/application such as gatepost reponse, incarceration, disability, living arrangement, pregnancy, address details. Also repurposed to store information of different individuals in the form of individual alien, alien sponsor, care taker,  care coordinator etc.</description>
    <label>SSP Member</label>
    <nameField>
        
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        
        <label>SSP_Member Name</label>
        
        <type>Text</type>
        
    </nameField>
    <pluralLabel>SSP Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Member__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>This field is used to indicate the related contact for a member</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>SSP_Member</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/DCId__c.field-meta.xml
<CustomField>
    <fullName>DCId__c</fullName>
    <description>This field used to store the unique member DC Id to identify for an external system</description>
    <externalId>true</externalId>
    <label>DCId</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>This field is used to store Firstname on a Member</description>
    <encryptionScheme>None</encryptionScheme>
    <label>FirstName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/IndividualId__c.field-meta.xml
<CustomField>
    <fullName>IndividualId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>This field is used to store individual Id of a member</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>IndividualId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/MailingAddressLine1__c.field-meta.xml
<CustomField>
    <fullName>MailingAddressLine1__c</fullName>
    <description>This field is used to store Address Line 1 value of Mailing Address</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/MailingAddressLine2__c.field-meta.xml
<CustomField>
    <fullName>MailingAddressLine2__c</fullName>
    <description>This field is used to store Address Line 2 value of Mailing Address</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Address Line 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/MailingCountyCode__c.field-meta.xml
<CustomField>
    <fullName>MailingCountyCode__c</fullName>
    <description>This field is used to store county for a Mailing address of a member</description>
    <label>County</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>SSPCounty</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/MailingStateCode__c.field-meta.xml
<CustomField>
    <fullName>MailingStateCode__c</fullName>
    <description>This field is used to store mailing state code for mailing address on a member</description>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>SSPState</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/MailingZipCode5__c.field-meta.xml
<CustomField>
    <fullName>MailingZipCode5__c</fullName>
    <description>This field is used to store 5 digit Mailing Zip code</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Zip Code(Five Digit)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/PhysicalAddressLine1__c.field-meta.xml
<CustomField>
    <fullName>PhysicalAddressLine1__c</fullName>
    <description>This field is used to store Address Line 1 value of Physical Address</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/PhysicalAddressLine2__c.field-meta.xml
<CustomField>
    <fullName>PhysicalAddressLine2__c</fullName>
    <description>This field is used to store Address Line 2 value of Physical Address</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Address Line 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/PhysicalCountyCode__c.field-meta.xml
<CustomField>
    <fullName>PhysicalCountyCode__c</fullName>
    <label>County</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>SSPCounty</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/PhysicalStateCode__c.field-meta.xml
<CustomField>
    <fullName>PhysicalStateCode__c</fullName>
    <description>This field is used to store physical state code for physical address on a member</description>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>SSPState</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/PhysicalZipCode5__c.field-meta.xml
<CustomField>
    <fullName>PhysicalZipCode5__c</fullName>
    <description>This field is used to store 5 digit Physical Zip code</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Zip Code (Five Digit)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/PreferredDCBSOffice__c.field-meta.xml
<CustomField>
    <fullName>PreferredDCBSOffice__c</fullName>
    <description>Field to capture DCBSPOffice</description>
    <encryptionScheme>None</encryptionScheme>
    <label>PreferredDCBSOffice</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/PreferredNotificationMethodCode__c.field-meta.xml
<CustomField>
    <fullName>PreferredNotificationMethodCode__c</fullName>
    <description>This field is used to store Preferred Notification method for communication</description>
    <label>Preferred Contact Method</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>PreferredNotification</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/globalValueSets/PreferredNotification.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>EE</fullName>
        
        
        <label>Electronic - Email only</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>ES</fullName>
        
        
        <label>Electronic - Email and Text Message</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>P</fullName>
        
        
        <label>Mail</label>
        
    </customValue>
    
    <description>Preferred method for contact to receive any Notification - Changed values as per DDD drop v4</description>
    
    <masterLabel>Preferred Notification</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/classes/SSP_MyInformationControllerTest.cls
/*
* classname     :  SSP_MyInformationControllerTest
* @description  :  Test class for SSP_MyInformationController
* @author       :  Kireeti Gora  
* @date         :  01/03/2020
* MODIFICATION LOG:
* DEVELOPER                     DATE                               DESCRIPTION
* ---------------------------------------------------------------------------------------------

**/
/**
@author : Kireeti Gora
Method to setup test data*/ 
@isTest(seeAllData=false)
public class SSP_MyInformationControllerTest {
    
    @testSetup static void setup() { 
        SSP_TestDataFactory.setupTestData();  
        Id contactRecordTypeId = SSP_Utility.getRecrodTypeIdBySobjectAndDevName('Contact','Citizen');
        List<Account> lstAcc = SSP_TestDataFactory.createAccounts(1, false);
        lstAcc[0].Name = 'myInformationController';
        insert lstAcc;
        
        List<Contact> lstCon = [SELECT Id, FirstName, LastName FROM Contact WHERE FirstName = 'Citizen' AND LastName = 'User' LIMIT 1]; 
        
        List<Contact> lstContacts = new List<Contact>();
        lstContacts.add(SSP_TestDataFactory.createContactRecord('CitizenOne', 'User', 'citizenone@abc.xyz', contactRecordTypeId, false));
        lstContacts[0].CaseOwnership__c ='test';
        lstContacts[0].Id =lstCon[0].id;
        lstContacts[0].individualId__c ='678688';
        update lstContacts;
        
        AccountContactRelation acr = new AccountContactRelation(); 
        acr.Accountid = lstAcc[0].Id;
        acr.Contactid = lstCon[0].Id;
        acr.IsActive = true;
        insert acr;
        
        List<SSP_Application__c> lstAppln = SSP_TestDataFactory.createSSPApplications(1, false);
        lstAppln[0].Account__c=lstAcc[0].Id;        
        lstAppln[0].Contact__c = lstCon[0].Id;
        lstAppln[0].status__c = 'Approved';
        lstAppln[0].LocalDCBSOffice__c = 'Kentucky';
        insert lstAppln;
        
        List<SSP_Member__c> lstMem = SSP_TestDataFactory.createSSPMembers(1, false);
        lstMem[0].contact__c=lstCon[0].Id;  
        lstMem[0].PhysicalAddressLine1__c='test';
        lstMem[0].PhysicalAddressLine2__c='test';
       // lstMem[0].PhysicalCountyCode__c='1';
        lstMem[0].PhysicalStateCode__c='AL';
        lstMem[0].PhysicalZipCode5__c='40014';
        lstMem[0].MailingAddressLine1__c='test';
        lstMem[0].MailingAddressLine2__c='test';
//        lstMem[0].MailingCountyCode__c='1';
        lstMem[0].MailingStateCode__c='AL';
        lstMem[0].MailingZipCode5__c='40014';
        lstMem[0].PreferredNotificationMethodCode__c='P';
        lstMem[0].PreferredDCBSOffice__c='sample';
        lstMem[0].DcId__c=7896;
        insert lstMem;
        
        
        
        List<SSP_ApplicationIndividual__c> lstAppInd = SSP_TestDataFactory.createApplicationIndividuals(1, false); 
        lstAppInd[0].SSP_Application__c=lstAppln[0].Id;
        lstAppInd[0].SSP_Member__c=lstMem[0].Id;
        insert lstAppInd;   
        
    }
    /**
@author : Kireeti Gora
Test Method to test getMyInformationDetails method*/
    @isTest
    public static void test_getMyInformationDetails(){
        Test.setMock(HttpCalloutMock.class, new SSP_DC_ReverseMockImpl());
        User citizen  = [SELECT Id FROM User WHERE UserName = 'citizen@abc.xyz' LIMIT 1][0];
        System.runAs(citizen){
            test.startTest();
            
            SSP_LightningResponse response = SSP_MyInformationController.getMyInformationDetails('page');
            system.assertNotEquals(null, response.mapResponse);
            system.assert(response.mapResponse.containsKey('memberDetail'));  
            
            
            
            test.stopTest();
        }
        
    } 
    /**
@author : Kireeti Gora
Test Method to test test_getMyInformationDetails_Negative method*/
    @isTest
    public static void test_getMyInformationDetails_Negative(){
        List<SSP_Member__c> lstMember =  new List<SSP_Member__c>();
        lstMember = [SELECT Id from SSP_Member__c];
        delete lstMember;
        User citizen  = [SELECT Id FROM User WHERE UserName = 'citizen@abc.xyz' LIMIT 1][0];
        System.runAs(citizen){
            test.startTest();
            
            SSP_LightningResponse response = SSP_MyInformationController.getMyInformationDetails('page');
            
            SSP_MyInformationController.getCaseOwnershipFlag();
             Cache.SessionPartition sessionPart = Cache.Session.getPartition(SSP_GlobalConstants.CACHE_PARTITION_NAME);  
        	sessionPart.put(SSP_GlobalConstants.INDIVIDUAL_ID,'678688');
            sessionPart.put(SSP_GlobalConstants.SELECTED_ROLE,'Assister');
            SSP_MyInformationController.getCaseOwnershipFlag(); 
            system.assertNotEquals(null, response.mapResponse);
        
            
            
            test.stopTest();
        }
        
    } 
        /**
@author : Kireeti Gora
Test Method to test test_getMyInformationDetails_2 method*/
    @isTest
    public static void test_getMyInformationDetails_2(){
        Test.setMock(HttpCalloutMock.class, new SSP_DC_ReverseMockImpl());
        List<SSP_Application__c> lstApp =  new List<SSP_Application__c>();
        lstApp = [SELECT Id,DCCaseNumber__c from SSP_Application__c];
        lstApp[0].DCCaseNumber__c =null;
        update lstApp;
        User citizen  = [SELECT Id FROM User WHERE UserName = 'citizen@abc.xyz' LIMIT 1][0];
        System.runAs(citizen){
            test.startTest();
             Cache.SessionPartition sessionPart = Cache.Session.getPartition(SSP_GlobalConstants.CACHE_PARTITION_NAME);  
        sessionPart.put(SSP_GlobalConstants.INDIVIDUAL_ID,'678688');
            SSP_LightningResponse response = SSP_MyInformationController.getMyInformationDetails('page');
             SSP_LightningResponse response1 = SSP_MyInformationController.getMyInformationDetails(SSP_GlobalConstants.HAMBURGER);
            sessionPart.put(SSP_GlobalConstants.INDIVIDUAL_ID,'abghhh');
            SSP_LightningResponse response2 = SSP_MyInformationController.getMyInformationDetails('page');
            SSP_Member__c currentMem = [Select Id, firstName__c, PreferredDCBSOffice__c, MailingZipCode5__c from SSP_Member__c where firstName__c='TRQSDCVIUH' LIMIT 1];
            currentMem.firstName__c = null;
            currentMem.PreferredDCBSOffice__c = '';
            update currentMem;
            SSP_MyInformationController.LocalDCBSOffice = '';
            SSP_LightningResponse response3 = SSP_MyInformationController.getMyInformationDetails('page');
            system.assertNotEquals(null, response.mapResponse);
           
            
            
            test.stopTest();
        }
        
    } 
    
    /**
@author : Kireeti Gora
Test Method to test test_getMyInformationDetails_3 method*/
    @isTest
    public static void test_getMyInformationDetails_3(){
        List<SSP_Application__c> lstApp =  new List<SSP_Application__c>();
        lstApp = [SELECT Id,DCCaseNumber__c from SSP_Application__c];
        lstApp[0].DCCaseNumber__c =null;
        update lstApp;
        User citizen  = [SELECT Id FROM User WHERE UserName = 'citizen@abc.xyz' LIMIT 1][0];
        System.runAs(citizen){
            test.startTest();
            SSP_Member__c currentMem = [Select Id, firstName__c, PreferredDCBSOffice__c, MailingZipCode5__c from SSP_Member__c where MailingZipCode5__c='40014' LIMIT 1];
            currentMem.firstName__c = null;
            currentMem.PreferredDCBSOffice__c = '';
            update currentMem;
            SSP_MyInformationController.LocalDCBSOffice = '';
            SSP_LightningResponse response3 = SSP_MyInformationController.getMyInformationDetails('page');
            test.stopTest();
        }
        
    } 
    
        
    private static User fetchCitizenUser(){
        return ((List<User>)SSP_Utility.fetchRecords(new Map<String, String>{'objectName'=>'User'}, new Set<String>{'Id'}, new Map<String, String>{'UserName'=>'citizen@abc.xyz','limit'=>'1'}))[0];        
    }
    
        /**
    @author : Shrikant Raut
    Test Method to test fetchContactMethodDetails method
	*/
    @isTest
    public static void test_fetchContactMethodDetails(){    
        User citizen = fetchCitizenUser();
        System.runAs(citizen){
            test.startTest();
            SSP_Member__c member = [SELECT Id FROM SSP_Member__c LIMIT 1][0];
            member.PreferredNotificationMethodCode__c = 'P';
            update member;
            
            SSP_LightningResponse response = new SSP_LightningResponse();
            response = SSP_MyInformationController.fetchContactMethodDetails(citizen.Id);
            response = SSP_MyInformationController.fetchContactMethodDetails(member.Id);
            system.assertNotEquals(null, response.mapResponse, 'failed in fetching mapResponse');
            system.assertEquals(true, response.mapResponse.containsKey('dataWrapper'), 'failed in fetching mapResponse');
            test.stopTest();
        }
    }
     @isTest
    public static void test1(){
        SSP_Member__c member = [SELECT Id FROM SSP_Member__c LIMIT 1][0];
        String individualId = SSP_MyInformationControllerTest.getIndividualId();
        User citizen  = [SELECT Id FROM User WHERE UserName = 'citizen@abc.xyz' LIMIT 1][0];
        System.runAs(citizen){
        SSP_LightningResponse response2 = SSP_MyInformationController.triggerMyInfoCallout(individualId);
       
    }
    }
    @isTest
    public static void test2(){
        String line1='testline1';
        String line2='testline2'; 
        String city='testline3'; 
        String county='testline4';
        String state='testline5';
        String zip4='testline6'; 
        String zip5='testline7';
        String country='testline8';
        SSP_MyInformationController.formatAddress(line1,line2,city,county,state,zip4,zip5,country);
    }
    @isTest
        public static String getIndividualId(){
        //added by nupoor
        String individualId;
        if(UserInfo.getSessionId() != null){
        Cache.SessionPartition sessionPart = Cache.Session.getPartition(SSP_GlobalConstants.CACHE_PARTITION_NAME);  
        individualId = sessionPart != null ? ((sessionPart.get(SSP_GlobalConstants.INDIVIDUAL_ID) != null && String.isNotBlank(String.valueOf(sessionPart.get(SSP_GlobalConstants.INDIVIDUAL_ID)))) ? String.valueOf(sessionPart.get(SSP_GlobalConstants.INDIVIDUAL_ID)) : String.valueOf(sessionPart.get(SSP_CacheBuilderImplementation.class, SSP_GlobalConstants.INDIVIDUAL_ID))) : null;            
        
        }
        return (individualId != null && !String.isBlank(individualId)) ? individualId : null;
    }
    @isTest
    public static void getIndividualId1(){
    List<Account> lstAcc1 = SSP_TestDataFactory.createAccounts(1, false);
        lstAcc1[0].Name = 'myInformationController';
        insert lstAcc1;
        
        List<Contact> lstCon1 = [SELECT Id, FirstName, LastName,CaseOwnership__c FROM Contact WHERE CaseOwnership__c!=null  LIMIT 1];
        //insert lstCon1;
        
        AccountContactRelation acr1 = new AccountContactRelation(); 
        acr1.Accountid = lstAcc1[0].Id;
        acr1.Contactid = lstCon1[0].Id;
        acr1.IsActive = true;
        insert acr1;
    }
      @isTest
    public static void testupsertMemberInformation(){
    Boolean test = SSP_MyInformationController.upsertMemberInformation(null,null);
    }
    
}