force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Indicates whether the status of the account is Active-Allow Referrals, Active-Do not allow referrals or Inactive</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active - Allow referrals</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active - Do not allow referrals</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Pending Review</fullName>
                <isActive>false</isActive>
                <label>Pending Review</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <isActive>false</isActive>
                <label>Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Assister.recordType-meta.xml
<RecordType>
    <fullName>Assister</fullName>
    <active>true</active>
    <label>Assister</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Citizen.recordType-meta.xml
<RecordType>
    <fullName>Citizen</fullName>
    <active>true</active>
    <label>Citizen</label>
</RecordType>

force-app/main/default/objects/AccountContactRelation/fields/ProgramsApplied__c.field-meta.xml
<CustomField>
    <fullName>ProgramsApplied__c</fullName>
    <label>Programs Applied</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetDefinition>
            
            
                <value>
                
                    <fullName>MA</fullName>
                
                
                    <label>Medicaid/KCHIP</label>
                
                </value>
            
                <value>
                
                    <fullName>KT</fullName>
                
                
                    <label>KTAP (Cash Assistance)</label>
                
                </value>
            
                <value>
                
                    <fullName>SN</fullName>
                
                
                    <label>SNAP (Food Assistance)</label>
                
                </value>
            
                <value>
                
                    <fullName>SS</fullName>
                
                
                    <label>State Supplementation</label>
                
                </value>
            
                <value>
                
                    <fullName>DS</fullName>
                
                
                    <label>DSNAP</label>
                
                </value>
            
                <value>
                
                    <fullName>CC</fullName>
                
                
                    <label>Child Care Assistance</label>
                
                </value>
            
                <value>
                
                    <fullName>KP</fullName>
                
                
                    <label>KI-HIPP (Health Insurance Premium Payments)</label>
                
                </value>
            
            </valueSetDefinition>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Application__c/SSP_Application__c.object-meta.xml
<CustomObject>
    <description>To store SSP Application and Case data</description>
    <label>SSP Application</label>
    <nameField>
        
        <displayFormat>{000000000}</displayFormat>
        
        <label>SSP_Application Name</label>
        
        <type>AutoNumber</type>
        
    </nameField>
    <pluralLabel>SSP Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Application__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Shows the related Account to an Application</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>SSP_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_Application__c/fields/ApplicationCreationInSSP__c.field-meta.xml
<CustomField>
    <fullName>ApplicationCreationInSSP__c</fullName>
    <description>custom date to track application creation. to be used to calculate 8 days of expiry to show as dashboard notification.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Application creation in SSP</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SSP_Application__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Shows the related Contact to an Application</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>SSP_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SSP_Application__c/fields/DCCaseNumber__c.field-meta.xml
<CustomField>
    <fullName>DCCaseNumber__c</fullName>
    <description>DC mapping Case number of an Application</description>
    <externalId>true</externalId>
    <label>DCCaseNumber</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SSP_Application__c/fields/ProgramsApplied__c.field-meta.xml
<CustomField>
    <fullName>ProgramsApplied__c</fullName>
    <description>Used to store the list of programs applied for a household</description>
    <label>Programs Applied</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>BenefitPrograms</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Different types of status of an Application</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        
            <valueSetDefinition>
            
            
                <value>
                
                    <fullName>N</fullName>
                
                
                    <label>New</label>
                
                </value>
            
                <value>
                
                    <fullName>P</fullName>
                
                
                    <label>Pending</label>
                
                </value>
            
                <value>
                
                    <fullName>AP</fullName>
                
                
                    <label>Approved</label>
                
                </value>
            
                <value>
                
                    <fullName>UN</fullName>
                
                
                    <label>Unsubmitted</label>
                
                </value>
            
                <value>
                
                    <fullName>Inactive</fullName>
                
                
                    <label>Inactive</label>
                
                </value>
            
                <value>
                
                    <fullName>Blocked</fullName>
                
                
                    <label>Blocked</label>
                
                </value>
            
            </valueSetDefinition>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Application__c/recordTypes/Case.recordType-meta.xml
<RecordType>
    <fullName>Case</fullName>
    <active>true</active>
    <label>Case</label>
</RecordType>

force-app/main/default/objects/SSP_ApplicationIndividual__c/SSP_ApplicationIndividual__c.object-meta.xml
<CustomObject>
    <description>Custom junction object to maintain association between member and application</description>
    <label>SSP ApplicationIndividual</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>SSP_ApplicationIndividual Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SSP ApplicationIndividuals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/IsHeadOfHousehold__c.field-meta.xml
<CustomField>
    <fullName>IsHeadOfHousehold__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to determine if the member is Head of Household</description>
    <label>Is Head Of Household</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/ProgramsApplied__c.field-meta.xml
<CustomField>
    <fullName>ProgramsApplied__c</fullName>
    <description>Different types of programs applied on an application for which this member is involved</description>
    <label>Application Programs Applied</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>BenefitPrograms</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/SSP_Application__c.field-meta.xml
<CustomField>
    <fullName>SSP_Application__c</fullName>
    <description>Indicates the application related to a member</description>
    <label>SSP_Application</label>
    <referenceTo>SSP_Application__c</referenceTo>
    <relationshipName>SSP_ApplicationIndividuals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/SSP_Member__c.field-meta.xml
<CustomField>
    <fullName>SSP_Member__c</fullName>
    <description>Indicates the member related to an application</description>
    <label>SSP_Member</label>
    <referenceTo>SSP_Member__c</referenceTo>
    <relationshipName>SSP_ApplicationIndividuals</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/SSP_Member__c.object-meta.xml
<CustomObject>
    <description>Stores details about an individual member of a case/application such as gatepost reponse, incarceration, disability, living arrangement, pregnancy, address details. Also repurposed to store information of different individuals in the form of individual alien, alien sponsor, care taker,  care coordinator etc.</description>
    <label>SSP Member</label>
    <nameField>
        
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        
        <label>SSP_Member Name</label>
        
        <type>Text</type>
        
    </nameField>
    <pluralLabel>SSP Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Member__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>This field is used to indicate the related contact for a member</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>SSP_Member</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/IsHeadOfHousehold__c.field-meta.xml
<CustomField>
    <fullName>IsHeadOfHousehold__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Head Of Household</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/BenefitPrograms.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>MA</fullName>
        
        
        <label>Medicaid/KCHIP</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>KT</fullName>
        
        
        <label>KTAP (Cash Assistance)</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SN</fullName>
        
        
        <label>SNAP (Food Assistance)</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SS</fullName>
        
        
        <label>State Supplementation</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>DS</fullName>
        
        
        <label>DSNAP</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>CC</fullName>
        
        
        <label>Child Care Assistance</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>KP</fullName>
        
        
        <label>KI-HIPP (Health Insurance Premium Payments)</label>
        
    </customValue>
    
    <description>Different type of Benefit Programs available for a Citizen</description>
    
    <masterLabel>Benefit Programs</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/classes/SSP_ApplicationController_test.cls
/*
* classname     :  sspApplicationController_test
* @description  :  This class contains the test methods for sspApplicationController.
* @author       :  Yathansh Sharma   
* @date         :  12/23/2019
* MODIFICATION LOG:
* DEVELOPER                     DATE                                DESCRIPTION
* ---------------------------------------------------------------------------------------------
  Yathansh Sharma               12/23/2019                          Created.
**/
@isTest
public class SSP_ApplicationController_test {

    public static String caseApplicationRecordTypeId = Schema.describeSObjects(New String[]{'SSP_Application__c'}).get(0).getRecordTypeInfosByDeveloperName().get('Case').getRecordTypeId();
    /***************************************************************************************************
     * @author       Yathansh Sharma
     * @date         12/23/2019
     * @methodname   testFetchApplicationRecords
     * @description  This method is used to test the method fetchApplicationList.
     * @return       void
     *****************************************************************************************************/
    @isTest
    public static void testFetchApplicationRecords(){
        SSP_TestDataFactory.setupTestData();  
        test.startTest();
        account acc = new account(name='test');
        insert acc;
        ssp_application__c app = new ssp_application__c(Account__c = acc.id,Status__c='AP',RecordTypeId=caseApplicationRecordTypeId);
        insert app;
        User citizen  = [SELECT Id FROM User WHERE UserName = 'citizen@abc.xyz' LIMIT 1];
        SSP_Member__c mem = new SSP_Member__c();
        mem.name = 'test';
        mem.contact__c = SSP_UserSelector.queryUserData(new Map<String, String>{'objectName'=>'User','operator'=>'AND'}, 
                                                        new Set<String>{'Id', 'ContactId'}, 
                                                        new Map<String, String>{'limit'=>'1','Id'=> citizen.id})[0].contactId;
        insert mem;
        AccountContactRelation acr = new AccountContactRelation();
        acr.contactId = mem.contact__c;
        acr.accountId = app.Account__c;
        acr.roles = 'Authorized Representative';
        insert acr;
        SSP_ApplicationIndividual__c ai = new SSP_ApplicationIndividual__c();
        ai.SSP_Member__c = mem.id;
        ai.SSP_Application__c = app.id;
        insert ai;
        System.runAs(citizen){
            SSP_ApplicationController.fetchApplicationList(null, null,null,null);
        
        	system.assertEquals(1, [select count() from ssp_application__c]);
        }
        test.stopTest();
    }

    /***************************************************************************************************
     * @author       Yathansh Sharma
     * @date         2/24/2020
     * @methodname   testGetRenewalWrapperData
     * @description  This method is used to test the method getRenewalWrapperData.
     * @return       void
     *****************************************************************************************************/
    @isTest
    public static void testGetRenewalWrapperData(){
        SSP_TestDataFactory.setupTestData();  
        test.startTest();
        account acc = new account(name='test');
        insert acc;
        ssp_application__c app = new ssp_application__c(Account__c = acc.id);
        app.RecordTypeId = Schema.describeSObjects(New String[]{'SSP_Application__c'}).get(0).getRecordTypeInfosByDeveloperName().get('Case').getRecordTypeId();
        app.ProgramsApplied__c = 'MA';
        insert app;
        User citizen  = [SELECT Id FROM User WHERE UserName = 'citizen@abc.xyz' LIMIT 1];
        SSP_Member__c mem = new SSP_Member__c();
        mem.name = 'test';
        mem.contact__c = SSP_UserSelector.queryUserData(new Map<String, String>{'objectName'=>'User','operator'=>'AND'}, 
                                                        new Set<String>{'Id', 'ContactId'}, 
                                                        new Map<String, String>{'limit'=>'1','Id'=> citizen.id})[0].contactId;
        insert mem;
        AccountContactRelation acr = new AccountContactRelation();
        acr.contactId = mem.contact__c;
        acr.accountId = app.Account__c;
        acr.roles = 'Authorized Representative';
        insert acr;
        SSP_DashboardCaseInformation.Renewal renewal= new  SSP_DashboardCaseInformation.Renewal();
        renewal.CaseNumber='76590';
        renewal.RenewalProgramCode=SSP_GlobalConstants.PROGRAM_TYPE_MA;
        renewal.RenewalDueDate=String.valueof(5);
        Map<String, String> mapCaseVsIndividualId = new Map<String, String>();
        mapCaseVsIndividualId.put('76590','76459');
       
        List<SSP_DashboardCaseInformation.Renewal> lstRenewal= new List<SSP_DashboardCaseInformation.Renewal>();
        lstRenewal.add(renewal);
        Cache.SessionPartition sessionPart = Cache.Session.getPartition(SSP_GlobalConstants.CACHE_PARTITION_NAME);  
        sessionpart.put('hasMedicaidRenewals',JSON.serialize(lstRenewal),3600,Cache.Visibility.ALL,false);
        sessionpart.put('caseVsIndividualId',JSON.serialize(mapCaseVsIndividualId),3600,Cache.Visibility.ALL,false);
        System.runAs(citizen){
            SSP_ApplicationController.getRenewalWrapperData(app.id);
        }
        test.stopTest();
    }
    
    //To cover Else block in above function
   	@isTest
    public static void testGetRenewalWrapperDataElse(){
        SSP_TestDataFactory.setupTestData();  
        test.startTest();
        account acc = new account(name='test');
        insert acc;
        ssp_application__c app = new ssp_application__c(Account__c = acc.id);
        app.RecordTypeId = Schema.describeSObjects(New String[]{'SSP_Application__c'}).get(0).getRecordTypeInfosByDeveloperName().get('Case').getRecordTypeId();
        app.ProgramsApplied__c = 'KT';
        insert app;
        User citizen  = [SELECT Id FROM User WHERE UserName = 'citizen@abc.xyz' LIMIT 1];
        SSP_Member__c mem = new SSP_Member__c();
        mem.name = 'test';
        mem.contact__c = SSP_UserSelector.queryUserData(new Map<String, String>{'objectName'=>'User','operator'=>'AND'}, 
                                                        new Set<String>{'Id', 'ContactId'}, 
                                                        new Map<String, String>{'limit'=>'1','Id'=> citizen.id})[0].contactId;
        insert mem;
        AccountContactRelation acr = new AccountContactRelation();
        acr.contactId = mem.contact__c;
        acr.accountId = app.Account__c;
        acr.roles = 'Authorized Representative';
        insert acr;
        SSP_DashboardCaseInformation.Renewal renewal= new  SSP_DashboardCaseInformation.Renewal();
        renewal.CaseNumber='76590';
        renewal.RenewalProgramCode=SSP_GlobalConstants.PROGRAM_TYPE_MA;
        renewal.RenewalDueDate=String.valueof(5);
        Map<String, String> mapCaseVsIndividualId = new Map<String, String>();
        mapCaseVsIndividualId.put('76590','76459');
        List<SSP_DashboardCaseInformation.Renewal> lstRenewal= new List<SSP_DashboardCaseInformation.Renewal>();
        Cache.SessionPartition sessionPart = Cache.Session.getPartition(SSP_GlobalConstants.CACHE_PARTITION_NAME);  
        sessionpart.put('hasMedicaidRenewals',JSON.serialize(lstRenewal),3600,Cache.Visibility.ALL,false);
        sessionpart.put('caseVsIndividualId',JSON.serialize(mapCaseVsIndividualId),3600,Cache.Visibility.ALL,false);
        System.runAs(citizen){
            SSP_ApplicationController.getRenewalWrapperData(app.id);
        }
        test.stopTest();
    }
    
    //to cover If{} in fetchApplicationRecords() 
       @isTest
    public static void testFetchApplicationRecordsIf(){
        SSP_TestDataFactory.setupTestData();  
        test.startTest();
        account acc = new account(name='test');
        insert acc;
        ssp_application__c app = new ssp_application__c(Account__c = acc.id,Status__c='UN',ProgramsApplied__c='MA',RecordTypeId=caseApplicationRecordTypeId,DCCaseNumber__c=12345,ApplicationCreationInSSP__c=DATE.today().addDays(8));
        insert app;
        User citizen  = [SELECT Id FROM User WHERE UserName = 'citizen@abc.xyz' LIMIT 1];
        SSP_Member__c mem = new SSP_Member__c();
        mem.name = 'test';
        mem.contact__c = SSP_UserSelector.queryUserData(new Map<String, String>{'objectName'=>'User','operator'=>'AND'}, 
                                                        new Set<String>{'Id', 'ContactId'}, 
                                                        new Map<String, String>{'limit'=>'1','Id'=> citizen.id})[0].contactId;
        insert mem;
        AccountContactRelation acr = new AccountContactRelation();
        acr.contactId = mem.contact__c;
        acr.accountId = app.Account__c;
        acr.roles = 'Authorized Representative';
        insert acr;
        SSP_ApplicationIndividual__c ai = new SSP_ApplicationIndividual__c();
        ai.SSP_Member__c = mem.id;
        ai.SSP_Application__c = app.id;
        ai.IsHeadOfHousehold__c=true;
        insert ai;
        System.runAs(citizen){
            SSP_ApplicationController.fetchApplicationList(null, 'sspAssisterOrAgentModal',app.id,'Assister');
        
        	system.assertEquals(1, [select count() from ssp_application__c]);
        }
        test.stopTest();
    }
    
    @isTest
    public static void testgetProgramFromCache(){
        SSP_BenefitInformationWrapper objWrapper = new SSP_BenefitInformationWrapper();
        objWrapper.ProgramCode = system.label.SSP_KTAP;
        objWrapper.CaseNumber='123456';
        objWrapper.EdgNumber='123456';

        List<SSP_BenefitInformationWrapper> lstbenefits= new List<SSP_BenefitInformationWrapper>();
        lstbenefits.add(objWrapper);

        Map<String,List<SSP_BenefitInformationWrapper>> mapcasevswrapper= new Map<String,List<SSP_BenefitInformationWrapper>>();
        mapcasevswrapper.put('123456',lstbenefits);
        Cache.SessionPartition sessionPart = Cache.Session.getPartition(SSP_GlobalConstants.CACHE_PARTITION_NAME);  
        sessionpart.put('AllBenefits',JSON.serialize(mapcasevswrapper));

        Test.startTest();
        ssp_LightningResponse response=SSP_ApplicationController.getProgramFromCache();
        System.assertEquals(response.mapResponse.get('cacheResponse')!=null,true);
        Test.stopTest();

    }
    @isTest
    public static void testhandleMedicaidRenewal(){
        Test.startTest();
        ssp_LightningResponse response=SSP_ApplicationController.handleMedicaidRenewal('123456');
        ssp_LightningResponse response1=SSP_ApplicationController.handleMedicaidRenewal(null);
        Test.stopTest();
    }
    //renewalNextAction
    /*   @isTest
    public static void renewalNextActionTest(){
        SSP_TestDataFactory.setupTestData();  
        test.startTest();
        account acc = new account(name='test');
        insert acc;
        ssp_application__c app = new ssp_application__c(Account__c = acc.id);
        insert app;
        User citizen  = [SELECT Id FROM User WHERE UserName = 'citizen@abc.xyz' LIMIT 1];
        SSP_Member__c mem = new SSP_Member__c();
        mem.name = 'test';
        mem.contact__c = SSP_UserSelector.queryUserData(new Map<String, String>{'objectName'=>'User','operator'=>'AND'}, 
                                                        new Set<String>{'Id', 'ContactId'}, 
                                                        new Map<String, String>{'limit'=>'1','Id'=> citizen.id})[0].contactId;
        insert mem;
        AccountContactRelation acr = new AccountContactRelation();
        acr.contactId = mem.contact__c;
        acr.accountId = app.Account__c;
        acr.roles = 'Authorized Representative';
        insert acr;
        SSP_ApplicationIndividual__c ai = new SSP_ApplicationIndividual__c();
        ai.SSP_Member__c = mem.id;
        ai.SSP_Application__c = app.id;
        insert ai;
        System.runAs(citizen){
            SSP_ApplicationController.renewalNextAction(app.Id);
        
       // 	system.assertEquals(1, [select count() from ssp_application__c]);
        }
        test.stopTest();
        
    } */
        
        
        
    
}