force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Indicates whether the status of the account is Active-Allow Referrals, Active-Do not allow referrals or Inactive</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active - Allow referrals</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active - Do not allow referrals</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Pending Review</fullName>
                <isActive>false</isActive>
                <label>Pending Review</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <isActive>false</isActive>
                <label>Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Application.recordType-meta.xml
<RecordType>
    <fullName>Application</fullName>
    <active>true</active>
    <description>Record type for application account</description>
    <label>Application</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Citizen.recordType-meta.xml
<RecordType>
    <fullName>Citizen</fullName>
    <active>true</active>
    <label>Citizen</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Related Account</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CacheBenefitMedicaidEBTData__c.field-meta.xml
<CustomField>
    <fullName>CacheBenefitMedicaidEBTData__c</fullName>
    <description>MedicaidEBT information from Benefits call out will store here</description>
    <encryptionScheme>None</encryptionScheme>
    <label>CacheBenefitMedicaidEBTData</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/IndividualId__c.field-meta.xml
<CustomField>
    <fullName>IndividualId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Individual Id of a Contact</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>IndividualId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/MemberType__c.field-meta.xml
<CustomField>
    <fullName>MemberType__c</fullName>
    <description>This field is used to check if logged in user is HOH or Dependent.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>MemberType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of contact-Active or Inactive</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Citizen.recordType-meta.xml
<RecordType>
    <fullName>Citizen</fullName>
    <active>true</active>
    <description>This Record type is used for Residents</description>
    <label>Citizen</label>
</RecordType>

force-app/main/default/objects/SSP_Application__c/SSP_Application__c.object-meta.xml
<CustomObject>
    <description>To store SSP Application and Case data</description>
    <label>SSP Application</label>
    <nameField>
        
        <displayFormat>{000000000}</displayFormat>
        
        <label>SSP_Application Name</label>
        
        <type>AutoNumber</type>
        
    </nameField>
    <pluralLabel>SSP Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Application__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Shows the related Account to an Application</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>SSP_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_Application__c/fields/ApplicationCreationInSSP__c.field-meta.xml
<CustomField>
    <fullName>ApplicationCreationInSSP__c</fullName>
    <description>custom date to track application creation. to be used to calculate 8 days of expiry to show as dashboard notification.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Application creation in SSP</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SSP_Application__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Shows the related Contact to an Application</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>SSP_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SSP_Application__c/fields/DCCaseNumber__c.field-meta.xml
<CustomField>
    <fullName>DCCaseNumber__c</fullName>
    <description>DC mapping Case number of an Application</description>
    <externalId>true</externalId>
    <label>DCCaseNumber</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SSP_Application__c/fields/LocalDCBSOffice__c.field-meta.xml
<CustomField>
    <fullName>LocalDCBSOffice__c</fullName>
    <description>This Field is used to store local dcbs office</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Local DCBS Office</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Application__c/fields/ProgramsApplied__c.field-meta.xml
<CustomField>
    <fullName>ProgramsApplied__c</fullName>
    <description>Used to store the list of programs applied for a household</description>
    <label>Programs Applied</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>BenefitPrograms</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Application__c/fields/RAC_Selections__c.field-meta.xml
<CustomField>
    <fullName>RAC_Selections__c</fullName>
    <description>This is used to store the json of screens selected on RAC selection screen,</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>RAC Selections</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SSP_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Different types of status of an Application</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        
            <valueSetDefinition>
            
            
                <value>
                
                    <fullName>N</fullName>
                
                
                    <label>New</label>
                
                </value>
            
                <value>
                
                    <fullName>P</fullName>
                
                
                    <label>Pending</label>
                
                </value>
            
                <value>
                
                    <fullName>AP</fullName>
                
                
                    <label>Approved</label>
                
                </value>
            
                <value>
                
                    <fullName>UN</fullName>
                
                
                    <label>Unsubmitted</label>
                
                </value>
            
                <value>
                
                    <fullName>Inactive</fullName>
                
                
                    <label>Inactive</label>
                
                </value>
            
                <value>
                
                    <fullName>Blocked</fullName>
                
                
                    <label>Blocked</label>
                
                </value>
            
            </valueSetDefinition>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Application__c/recordTypes/Case.recordType-meta.xml
<RecordType>
    <fullName>Case</fullName>
    <active>true</active>
    <label>Case</label>
</RecordType>

force-app/main/default/objects/SSP_ApplicationIndividual__c/SSP_ApplicationIndividual__c.object-meta.xml
<CustomObject>
    <description>Custom junction object to maintain association between member and application</description>
    <label>SSP ApplicationIndividual</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>SSP_ApplicationIndividual Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SSP ApplicationIndividuals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/IsHeadOfHousehold__c.field-meta.xml
<CustomField>
    <fullName>IsHeadOfHousehold__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to determine if the member is Head of Household</description>
    <label>Is Head Of Household</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/ProgramsApplied__c.field-meta.xml
<CustomField>
    <fullName>ProgramsApplied__c</fullName>
    <description>Different types of programs applied on an application for which this member is involved</description>
    <label>Application Programs Applied</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>BenefitPrograms</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/SSP_Application__c.field-meta.xml
<CustomField>
    <fullName>SSP_Application__c</fullName>
    <description>Indicates the application related to a member</description>
    <label>SSP_Application</label>
    <referenceTo>SSP_Application__c</referenceTo>
    <relationshipName>SSP_ApplicationIndividuals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/SSP_Member__c.field-meta.xml
<CustomField>
    <fullName>SSP_Member__c</fullName>
    <description>Indicates the member related to an application</description>
    <label>SSP_Member</label>
    <referenceTo>SSP_Member__c</referenceTo>
    <relationshipName>SSP_ApplicationIndividuals</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/SSP_Member__c.object-meta.xml
<CustomObject>
    <description>Stores details about an individual member of a case/application such as gatepost reponse, incarceration, disability, living arrangement, pregnancy, address details. Also repurposed to store information of different individuals in the form of individual alien, alien sponsor, care taker,  care coordinator etc.</description>
    <label>SSP Member</label>
    <nameField>
        
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        
        <label>SSP_Member Name</label>
        
        <type>Text</type>
        
    </nameField>
    <pluralLabel>SSP Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Member__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>This field is used to indicate the related contact for a member</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>SSP_Member</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>This field is used to store Firstname on a Member</description>
    <encryptionScheme>None</encryptionScheme>
    <label>FirstName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/IndividualId__c.field-meta.xml
<CustomField>
    <fullName>IndividualId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>This field is used to store individual Id of a member</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>IndividualId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/IsHeadOfHousehold__c.field-meta.xml
<CustomField>
    <fullName>IsHeadOfHousehold__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Head Of Household</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <description>This field is used to store Lastname of a member</description>
    <encryptionScheme>None</encryptionScheme>
    <label>LastName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/PhysicalAddressLine1__c.field-meta.xml
<CustomField>
    <fullName>PhysicalAddressLine1__c</fullName>
    <description>This field is used to store Address Line 1 value of Physical Address</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/PhysicalCity__c.field-meta.xml
<CustomField>
    <fullName>PhysicalCity__c</fullName>
    <description>This field is used to store city for a Physical address of a member</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Office__c/SSP_Office__c.object-meta.xml
<CustomObject>
    <description>MOR set for offices for day 0 data for SSP</description>
    <label>SSP Office</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>SSP Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SSP Offices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Office__c/fields/DCOfficeId__c.field-meta.xml
<CustomField>
    <fullName>DCOfficeId__c</fullName>
    <description>OfficeId from Office table.</description>
    <externalId>true</externalId>
    <label>DC OfficeId</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SSP_Office__c/fields/PhysicalAddressLine1__c.field-meta.xml
<CustomField>
    <fullName>PhysicalAddressLine1__c</fullName>
    <description>Office Address Line1.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Physical AddressLine1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Office__c/fields/PhysicalCity__c.field-meta.xml
<CustomField>
    <fullName>PhysicalCity__c</fullName>
    <description>Office Address City.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Physical City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/BenefitPrograms.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>MA</fullName>
        
        
        <label>Medicaid/KCHIP</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>KT</fullName>
        
        
        <label>KTAP (Cash Assistance)</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SN</fullName>
        
        
        <label>SNAP (Food Assistance)</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SS</fullName>
        
        
        <label>State Supplementation</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>DS</fullName>
        
        
        <label>DSNAP</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>CC</fullName>
        
        
        <label>Child Care Assistance</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>KP</fullName>
        
        
        <label>KI-HIPP (Health Insurance Premium Payments)</label>
        
    </customValue>
    
    <description>Different type of Benefit Programs available for a Citizen</description>
    
    <masterLabel>Benefit Programs</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/classes/SSP_RequestAMedicaidCardTest.cls
@isTest(seeAllData=false)
public with sharing class SSP_RequestAMedicaidCardTest {
    @TestSetup
    static void setup(){
         UserRole portalRole = [Select Id From UserRole Where PortalType = 'None' Limit 1];
    system.debug('portalRole is ' + portalRole);
    
    Profile profile = [Select Id from Profile where name = 'System Administrator'];
    User portalUserCreator = new User(
        UserRoleId 			=	portalRole.Id,
        ProfileId 			=	profile.Id,
        Username			=	System.now().millisecond() + Math.random() + 'test2@test.com',
        Alias 				=	'batman',
        Email				=	'ronald.stewart@mailinators.com',
        EmailEncodingKey	=	'UTF-8',
        Firstname			=	'Bruce',
        Lastname			=	'Wayne',
        LanguageLocaleKey	=	'en_US',
        LocaleSidKey		=	'en_US',
        TimeZoneSidKey		=	'America/Chicago'
    );
    Database.insert(portalUserCreator);
    
    System.runAs ( portalUserCreator ) {
        //Create account
        Account portalUserAccount = new Account(
            Name = 'Portal Account',
            OwnerId = portalUserCreator.Id
        );
        Database.insert(portalUserAccount);
        //String individualId=SSP_Utility.getIndividualId();
        //Create contact
        Contact contactForPortalUser = new Contact(
            FirstName = 'Test',
            Lastname = 'McTesty',
            AccountId = portalUserAccount.Id,
            Email = System.now().millisecond() + 'test@test.com',
            IndividualId__c = '1250002321',//'1250002321',
            MemberType__c='HOH',
            CacheBenefitMedicaidEBTData__c='[{"ShowMedicard":true,"ShowEBT":true,"IndividualName":"GLOT TEST","IndividualId":"1250002321","CaseNumber":"100011699"}]'
        );
        Database.insert(contactForPortalUser);
        //Create SSP Member
        SSP_Member__c objMem = new SSP_Member__c(
            Contact__c = contactForPortalUser.Id,
            FirstName__c='Test',
            LastName__c = 'McTesty'
            
                    );
        Database.insert(objMem);
//Create SSP Application 
        SSP_Application__c SSPApp = new SSP_Application__c(
            Contact__c = contactForPortalUser.Id,
            Account__c = portalUserAccount.Id,
            Status__c = 'P',
            ProgramsApplied__c ='MA;KT;CC;SN;SS;KP'
        );
        Database.insert(SSPApp);
        
            SSP_Application__c SSPAppUn = new SSP_Application__c(
            Contact__c = contactForPortalUser.Id,
            Account__c = portalUserAccount.Id,
            Status__c = 'UN',
            RecordTypeId=SSP_Utility.getRecrodTypeIdBySobjectAndDevName('SSP_Application__c','Case'),
            LocalDCBSOffice__c = 'Kentucky',
            ProgramsApplied__c ='MA;KT;CC;SN;SS;KP',
            //DCCaseNumber__c = 890,
            RAC_Selections__c='CIS_CareTaker',
            ApplicationCreationInSSP__c = system.today()
        );
        Database.insert(SSPAppUn);
        
        SSP_Application__c SSPAppNcase = new SSP_Application__c(
            Contact__c = contactForPortalUser.Id,
            Account__c = portalUserAccount.Id,
            Status__c = 'UN'
        );
        Database.insert(SSPAppNcase);
        
            SSP_Application__c SSPAppNull = new SSP_Application__c(
            Contact__c = contactForPortalUser.Id,
            Account__c = portalUserAccount.Id
        );
        Database.insert(SSPAppNull);
        
        SSP_ApplicationIndividual__c SSPAppInd = new SSP_ApplicationIndividual__c(
            SSP_Application__c = SSPApp.Id,
            SSP_Member__c= ObjMem.Id,
            IsHeadOfHousehold__c = false
        );
        Database.insert(SSPAppInd);
                    
        SSP_ApplicationIndividual__c SSPAppIndUn = new SSP_ApplicationIndividual__c(
        SSP_Application__c = SSPAppUn.Id,
        SSP_Member__c= ObjMem.Id,
        IsHeadOfHousehold__c = true
        );
        Database.insert(SSPAppIndUn);
        
        SSP_ApplicationIndividual__c SSPAppNcaseIn = new SSP_ApplicationIndividual__c(
        SSP_Application__c = SSPAppNcase.Id,
        SSP_Member__c= ObjMem.Id,
        IsHeadOfHousehold__c = true
        );
        Database.insert(SSPAppNcaseIn);

        
        //Create Portal user
        Profile portalProfile = [SELECT Id FROM Profile WHERE Name=:'RE Citizen Profile' Limit 1];
        User portalUser = new User(
            Username = System.now().millisecond() + 'test12345@test.com',
            ContactId = contactForPortalUser.Id,
            ProfileId = portalProfile.Id,
            Alias = 'test123',
            Email = 'test12345@test.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'McTesty',
            CommunityNickname = 'batman905',
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            LanguageLocaleKey = 'en_US'
        );
        Database.insert(portalUser);
        
        SSP_Office__c sspo=new SSP_Office__c();
    sspo.Name='Testing address';
    sspo.DCOfficeId__c=1001;
    sspo.PhysicalAddressLine1__c='1 street';
    sspo.PhysicalCity__c='Frankfort';
    Database.insert(sspo);
    }

    

}
    @isTest 
    static void testmedicaidCardRequestCallOut() {
        Test.setMock(WebServiceMock.class, new SSP_SOAPIntegrationServiceMock(true, SSP_InterfaceConstants.MEDICAID_CARD_REQUEST));
        
        Map<String,String> mapParams = new Map<String,String>();
          SSP_Office__c sspo=new SSP_Office__c();
    sspo.Name='Testing address';
    sspo.DCOfficeId__c=1002;
    sspo.PhysicalAddressLine1__c='1 street';
    sspo.PhysicalCity__c='Frankfort';
    Database.insert(sspo);
        
        mapParams.put('memberCaseNumber','100053289');
        mapParams.put('addInfo','Replacing Card 8');
        mapParams.put('IsRequestedInOffice','Y');
        mapParams.put('whyReplace','Requesting another one');
        mapParams.put('memberIndividualId','999018951');
        mapParams.put('recordId',sspo.Id);
        mapParams.put('officeId','');
        Test.startTest();
        SSP_LightningResponse objresp= SSP_RequestAMedicaidCard.medicaidCardRequestCallOut(mapParams);
        Test.stopTest();
        String jsonstring=String.ValueOf(objresp.mapResponse.get('response'));
        
        //"Status":true
        system.assert(jsonstring.contains('"Status":true'), 'Success');
        
        // system.assertNotEquals(null,objresp);
        
    }

     @isTest 
    static void testEBTRequestCallOut() {
        Test.setMock(WebServiceMock.class, new SSP_SOAPIntegrationServiceMock(true, SSP_InterfaceConstants.EBT_CARD_REQUEST));
        
        Map<String,String> mapParams = new Map<String,String>();
        
        
        mapParams.put('memberCaseNumber','100053289');
        mapParams.put('addInfo','Replacing Card 8');
        mapParams.put('IsRequestedInOffice','N');
        mapParams.put('whyReplace','Requesting another one');
        mapParams.put('memberIndividualId','999018951');
        mapParams.put('officeId','');
        Test.startTest();
        SSP_LightningResponse objresp= SSP_RequestAMedicaidCard.ebtCardRequestCallOut(mapParams);
         Test.stopTest();
        String jsonstring=String.ValueOf(objresp.mapResponse.get('response'));
        
        //"Status":true
        system.assert(jsonstring.contains('"Status":true'), 'Success');
        
   
       
    }

     @isTest 
    static void testGetMailingAddress() {
       
        Test.setMock(HttpCalloutMock.class, new SSP_DC_ReverseMockImpl());
        
     
        Test.startTest();
        SSP_LightningResponse objresp= SSP_RequestAMedicaidCard.getMailingAddress('999018553','1234567');
        Test.stopTest();
        String jsonstring=String.ValueOf(objresp.mapResponse.get('response'));
       
        //"Status":true
       system.assert(jsonstring!=null);
	
        
           
    }

    @istest
    static void testGetReasonPickListValues()
    {
        Map<String,String> mapofoptions = SSP_RequestAMedicaidCard.getReasonPickListValues();

        system.assert(mapofoptions.size()>=3);
    }
    
    @istest
    static void testmedicaidEBTData()
    {
            User fetchedPortalUser = [SELECT id ,ContactId FROM User WHERE LastName=:'McTesty'];
       
        system.runAs(fetchedPortalUser){
            Test.startTest();
            SSP_LightningResponse resp=SSP_RequestAMedicaidCard.medicaidEBTData();
            Test.stopTest();
            system.assert(resp.bIsSuccess);

        }
    }

    @istest
    static void testGetDCBSAddress()
    {
        Test.startTest();
        SSP_LightningResponse response = SSP_RequestAMedicaidCard.getDCBSAddress('1001');
        Test.stopTest();
        System.assert(response.bIsSuccess);


    }
    
    @istest
    static void testupdateDashboardRefresh()
    {
        User fetchedPortalUser = [SELECT id ,ContactId FROM User WHERE LastName=:'McTesty'];
       
        system.runAs(fetchedPortalUser){
        Test.startTest();
        SSP_LightningResponse resp=SSP_RequestAMedicaidCard.updateDashboardRefresh();
            Test.stopTest();
            System.assert(resp.bIsSuccess);
            
            
        }
        
    }
   
    
     @isTest 
    static void testmedicaidEBTDataNonHohCase() {
     
           Contact con= [Select Id,MemberType__c from Contact where IndividualId__c = '1250002321' Limit 1];
        con.MemberType__c='';
        Database.update(con);
        
            User fetchedPortalUser = [SELECT id ,ContactId FROM User WHERE LastName=:'McTesty'];
       
        system.runAs(fetchedPortalUser){
            Test.startTest();
            SSP_LightningResponse resp=SSP_RequestAMedicaidCard.medicaidEBTData();
            Test.stopTest();
            system.assert(resp.bIsSuccess);

        }
        
       
        
        
    }
    
     @isTest 
    static void testmedicaidCardRequestCallOutDCBSID() {
        Test.setMock(WebServiceMock.class, new SSP_SOAPIntegrationServiceMock(true, SSP_InterfaceConstants.MEDICAID_CARD_REQUEST));
        
        Map<String,String> mapParams = new Map<String,String>();
          SSP_Office__c sspo=new SSP_Office__c();
    sspo.Name='Testing address';
    sspo.DCOfficeId__c=1002;
    sspo.PhysicalAddressLine1__c='1 street';
    sspo.PhysicalCity__c='Frankfort';
    Database.insert(sspo);
        
        mapParams.put('memberCaseNumber','100053289');
        mapParams.put('addInfo','Replacing Card 8');
        mapParams.put('IsRequestedInOffice','Y');
        mapParams.put('whyReplace','Requesting another one');
        mapParams.put('memberIndividualId','999018951');
        mapParams.put('recordId','');
        mapParams.put('officeId','1002');
        Test.startTest();
        SSP_LightningResponse objresp= SSP_RequestAMedicaidCard.medicaidCardRequestCallOut(mapParams);
       Test.stopTest();
        String jsonstring=String.ValueOf(objresp.mapResponse.get('response'));
        
        //"Status":true
        system.assert(jsonstring.contains('"Status":true'), 'Success');
        
    }
    
     @isTest 
    static void testGetMailingAddressNegativeScenario() {
       
        //Test.setMock(HttpCalloutMock.class, new SSP_DC_ReverseMockImpl());
        
     
        Test.startTest();
        SSP_LightningResponse objresp= SSP_RequestAMedicaidCard.getMedicaidLinkVisibility('abc');
        Test.stopTest();
        String jsonstring=String.ValueOf(objresp.mapResponse.get('response'));
        system.assert(!objresp.bIsSuccess);
        
        
           
    }
    
     @isTest 
    static void testmedicaidCardRequestCallOutNegative() {
        //Test.setMock(WebServiceMock.class, new SSP_SOAPIntegrationServiceMock(true, SSP_InterfaceConstants.MEDICAID_CARD_REQUEST));
        
        Map<String,String> mapParams = new Map<String,String>();
          SSP_Office__c sspo=new SSP_Office__c();
    sspo.Name='Testing address';
    sspo.DCOfficeId__c=1002;
    sspo.PhysicalAddressLine1__c='1 street';
    sspo.PhysicalCity__c='Frankfort';
    Database.insert(sspo);

        Test.startTest();
        SSP_LightningResponse objresp= SSP_RequestAMedicaidCard.medicaidCardRequestCallOut(mapParams);
       Test.stopTest();
        String jsonstring=String.ValueOf(objresp.mapResponse.get('response'));
         system.assert(!objresp.bIsSuccess);
   
        
    }
}