force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Indicates whether the status of the account is Active-Allow Referrals, Active-Do not allow referrals or Inactive</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active - Allow referrals</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active - Do not allow referrals</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Pending Review</fullName>
                <isActive>false</isActive>
                <label>Pending Review</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <isActive>false</isActive>
                <label>Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Citizen.recordType-meta.xml
<RecordType>
    <fullName>Citizen</fullName>
    <active>true</active>
    <label>Citizen</label>
</RecordType>

force-app/main/default/objects/AppConfig__c/AppConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom setting to store app configuration data for SSP.</description>
    <label>App Config</label>
</CustomObject>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of contact-Active or Inactive</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Citizen.recordType-meta.xml
<RecordType>
    <fullName>Citizen</fullName>
    <active>true</active>
    <description>This Record type is used for Residents</description>
    <label>Citizen</label>
</RecordType>

force-app/main/default/objects/SSP_Message_Center_Configuration__mdt/SSP_Message_Center_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>SSP Message Center Configuration</label>
    <pluralLabel>SSP Message Center Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/SSP_Message_Center_Configuration__mdt/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SSP_Message_Center_Configuration__mdt/fields/Body_Spanish__c.field-meta.xml
<CustomField>
    <fullName>Body_Spanish__c</fullName>
    <label>Body Spanish</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SSP_Message_Center_Configuration__mdt/fields/Communication_Body__c.field-meta.xml
<CustomField>
    <fullName>Communication_Body__c</fullName>
    <label>Communication Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SSP_Message_Center_Configuration__mdt/fields/Communication_Body_Spanish__c.field-meta.xml
<CustomField>
    <fullName>Communication_Body_Spanish__c</fullName>
    <label>Communication Body Spanish</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SSP_Message_Center_Configuration__mdt/fields/Due_Date_criterion__c.field-meta.xml
<CustomField>
    <fullName>Due_Date_criterion__c</fullName>
    <label>Due Date criterion</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Message_Center_Configuration__mdt/fields/Expiry_Date_Criterion__c.field-meta.xml
<CustomField>
    <fullName>Expiry_Date_Criterion__c</fullName>
    <label>Expiry Date Criterion</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Message_Center_Configuration__mdt/fields/Send_Reminder_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Send_Reminder_Criteria__c</fullName>
    <label>Send Reminder Criteria</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Message_Center_Configuration__mdt/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <label>Severity</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetDefinition>
            
            
                <value>
                
                    <fullName>Critical</fullName>
                
                    <default>true</default>
                
                    <label>Critical</label>
                
                </value>
            
                <value>
                
                    <fullName>Normal</fullName>
                
                
                    <label>Normal</label>
                
                </value>
            
            </valueSetDefinition>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Message_Center_Configuration__mdt/fields/Title_Spanish__c.field-meta.xml
<CustomField>
    <fullName>Title_Spanish__c</fullName>
    <label>Title Spanish</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Notifications__c/SSP_Notifications__c.object-meta.xml
<CustomObject>
    <description>Object to store system notifications, To Dos, Notices/Messages, Announcements</description>
    <label>SSP Notifications</label>
    <nameField>
        
        <displayFormat>Msg-{0000000000}</displayFormat>
        
        <label>SSP_Notifications Name</label>
        
        <type>AutoNumber</type>
        
    </nameField>
    <pluralLabel>SSP Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Notifications__c/fields/dueDate__c.field-meta.xml
<CustomField>
    <fullName>dueDate__c</fullName>
    <description>due date to be considered for archiving this notification.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>due date to be considered for archiving this notification.</inlineHelpText>
    <label>DueDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SSP_Notifications__c/fields/Linked_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Linked_Record_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Linked Record Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Notifications__c/fields/MessageCreateDate__c.field-meta.xml
<CustomField>
    <fullName>MessageCreateDate__c</fullName>
    <description>created date for this notice</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>created date for this notice</inlineHelpText>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SSP_Notifications__c/fields/messageSubject__c.field-meta.xml
<CustomField>
    <fullName>messageSubject__c</fullName>
    <description>title to show for each notice on UI</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>title to show for each notice on UI</inlineHelpText>
    <label>MessageSubject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Notifications__c/fields/messageSubjectES__c.field-meta.xml
<CustomField>
    <fullName>messageSubjectES__c</fullName>
    <description>title to show for each notice on UI</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>title to show for each notice on UI</inlineHelpText>
    <label>MessageSubjectES</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Notifications__c/fields/Notification_Body__c.field-meta.xml
<CustomField>
    <fullName>Notification_Body__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Notification Body</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SSP_Notifications__c/fields/Notification_Body_Es__c.field-meta.xml
<CustomField>
    <fullName>Notification_Body_Es__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Notification Body Es</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SSP_Notifications__c/fields/notificationCode__c.field-meta.xml
<CustomField>
    <fullName>notificationCode__c</fullName>
    <description>unique id for each notification. Ex. NOT-001. If it’s a reminder then RNOT-001. For a reminder separate notification will be sent.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>unique id for each notification. Ex. NOT-001. If it’s a reminder then RNOT-001. For a reminder separate notification will be sent.</inlineHelpText>
    <label>NotificationCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Notifications__c/fields/recipientId__c.field-meta.xml
<CustomField>
    <fullName>recipientId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>RecipientId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Notifications__c/fields/recipientType__c.field-meta.xml
<CustomField>
    <fullName>recipientType__c</fullName>
    <description>user to which notice is generated. Audience of this notice.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>user to which notice is generated. Audience of this notice.</inlineHelpText>
    <label>RecipientType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Notifications__c/fields/Reminder_Date__c.field-meta.xml
<CustomField>
    <fullName>Reminder_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Reminder Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SSP_Notifications__c/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Severity</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Notifications__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetDefinition>
            
            
                <value>
                
                    <fullName>Active</fullName>
                
                
                    <label>Active</label>
                
                </value>
            
                <value>
                
                    <fullName>Expired</fullName>
                
                
                    <label>Expired</label>
                
                </value>
            
            </valueSetDefinition>
        
        </valueSet>
</CustomField>

force-app/main/default/classes/SSP_InsertSurveyInvitationCtrlTest.cls
@isTest
public class SSP_InsertSurveyInvitationCtrlTest {
    @testSetup static void testData(){
        
        map<string,object> mapInputData = new map<string,object>();
        String identifier = SSP_GlobalConstants.SF_TOD_003;
        mapInputData.put('recipientId', '919221392');
        mapInputData.put('recipientType', 'Citizen_Individual');
        //  mapInputData.put('acrId', '07kr000000BdPqk');
        mapInputData.put('preferredCommunication', 'ES');
        mapInputData.put('preferredWrittenLanguageCode', '1');
        mapInputData.put('phone', '(272) 207-2369');
        mapInputData.put('email', 'test@gmail.com');
        mapInputData.put('citizenFirstName', 'Harry');
        mapInputData.put('nameCitizen', 'Potter'); 
        mapInputData.put('nameNonCitizen', 'Harry Potter');
        mapInputData.put('programs', 'Medicaid/KCHIP');
        mapInputData.put('permissions', 'Apply , Report Changes , Recertify');
        
        SSP_Notifications__c msgRecord = new SSP_Notifications__c();
        //  List<SSP_Message_Center_Configuration__mdt> msgCenterMdt = new list<SSP_Message_Center_Configuration__mdt>();
        String locale;
        SSP_Message_Center_Configuration__mdt msgCenterMdt = [select Id, Code__c, Body__c, Body_Spanish__c, Title__c, 
                                                              Title_Spanish__c, Due_Date_criterion__c, Expiry_Date_Criterion__c,
                                                              Send_Reminder_Criteria__c, Communication_Body__c, Communication_Body_Spanish__c, Severity__c
                                                              from SSP_Message_Center_Configuration__mdt 
                                                              where DeveloperName =:identifier];
        
        msgRecord.recipientId__c = (String)mapInputData.get('recipientId');
        // msgRecord.Linked_Record_Id__c = ((String)inputData.get('acrId'));
        msgRecord.messageSubject__c = msgCenterMdt.Title__c;
        msgRecord.messageSubjectES__c = msgCenterMdt.Title_Spanish__c;
        msgRecord.notificationCode__c = msgCenterMdt.Code__c;
        msgRecord.MessageCreateDate__c = SSP_Utility.today();
        msgRecord.Severity__c = msgCenterMdt.Severity__c;
        msgRecord.Status__c = SSP_GlobalConstants.NOTIFICATION_ACTIVE;
        msgRecord.Notification_Body__c = String.format(msgCenterMdt.Body__c,new list<string>{(String)mapInputData.get('nameNonCitizen'),(String)mapInputData.get('programs')});
        msgRecord.Notification_Body_Es__c = String.format(msgCenterMdt.Body_Spanish__c,new list<string>{(String)mapInputData.get('nameNonCitizen'),(String)mapInputData.get('programs')});
        msgRecord.RecordTypeId = Schema.SObjectType.SSP_Notifications__c.getRecordTypeInfosByName().get('To Do').getRecordTypeId();
        msgRecord.recipientType__c = SSP_GlobalConstants.NOTIFICATION_CITIZEN;
        msgRecord.dueDate__c = msgRecord.MessageCreateDate__c.addDays(Integer.valueOf(msgCenterMdt.Due_Date_criterion__c));
        msgRecord.Reminder_Date__c = (Date.valueOf(msgRecord.dueDate__c)).addDays(Integer.valueOf(msgCenterMdt.Send_Reminder_Criteria__c));
        insert msgRecord;
        
        AppConfig__c timerValue = new AppConfig__c();
        List <AppConfig__c> delaytimer = new List<AppConfig__c>();
        timerValue.Name = 'AssisterTimerConfig';
        timerValue.Value__c = '3';
        delaytimer.add(timerValue);
        insert delaytimer;
        
        List<Account> accList = SSP_TestDataFactory.createAccounts(1, false);
        Account acc = accList.get(0);
        insert acc;
        
        Id contactRecordTypeId = SSP_Utility.getRecrodTypeIdBySobjectAndDevName('Contact','Citizen');
        Contact objCitizenContact = SSP_TestDataFactory.createContactRecord('Citizen', 'User', 'citizen@abc.xyz1', contactRecordTypeId, false);
        objCitizenContact.accountId = acc.Id;
        insert objCitizenContact;
        User objCitizenUser = SSP_TestDataFactory.createCommunityUser('sspC', objCitizenContact.Id,'citizen@abc.xyz1', 'RE Citizen Profile', true);
        
    }
    @isTest static void saveSurveyInvitationTest(){
        User citizen  = [SELECT Id FROM User WHERE UserName = 'citizen@abc.xyz1' LIMIT 1][0]; 
        Map<String , object>mapInputData = new Map<String , Object>();
        mapInputData.put('preferredCommunication','ES');
        ID notificID = [select id from ssp_notifications__c where recipientId__c = '919221392' LIMIT 1].id;
        ssp_notifications__c notificRec = [select Id , recipientId__c , messageSubject__c , messageSubjectES__c ,  Notification_Body__c , Notification_Body_Es__c from ssp_notifications__c where id=:notificID LIMIT 1];
        system.runAs(citizen){   
            test.startTest();
            SSP_InsertSurveyInvitationCtrl.saveSurveyInvitation('Kynector Access Request', notificID,'SSP_Notifications__c',true, false,'Benefind');
            string surveyLink = SSP_InsertSurveyInvitationCtrl.saveSurveyInvitation('Kynector Access Request', notificID,'SSP_Notifications__c',true, false,'Benefind');
            SSP_messageUtility.sendCommunnication(surveyLink , (String)mapInputData.get('preferredCommunication') , null,(String)mapInputData.get('phone') , (String)mapInputData.get('email'),notificRec.Notification_Body__c,
                                                  notificRec.Notification_Body_Es__c,null,null,notificID,(String)mapInputData.get('citizenFirstName'));/*String title, String titleSpanish*/
            test.stopTest();
        }
    }
}