force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Indicates whether the status of the account is Active-Allow Referrals, Active-Do not allow referrals or Inactive</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active - Allow referrals</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active - Do not allow referrals</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Pending Review</fullName>
                <isActive>false</isActive>
                <label>Pending Review</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <isActive>false</isActive>
                <label>Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of contact-Active or Inactive</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/MondayClose__c.field-meta.xml
<CustomField>
    <fullName>MondayClose__c</fullName>
    <description>Indicates the closing time on Monday for the location</description>
    <label>MondayClose</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/MondayOpen__c.field-meta.xml
<CustomField>
    <fullName>MondayOpen__c</fullName>
    <description>Indicates the opening time on Monday for the location</description>
    <label>MondayOpen</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <inlineHelpText>Notes</inlineHelpText>
    <label>Notes</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Address Information</description>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Indicates whether the status of location is active or inactive</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location__c/fields/TimeZone__c.field-meta.xml
<CustomField>
    <fullName>TimeZone__c</fullName>
    <description>Time zone in which the hours open/close for the location is recorded</description>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>USTimeZones</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location__c/fields/TuesdayClose__c.field-meta.xml
<CustomField>
    <fullName>TuesdayClose__c</fullName>
    <description>Indicates the closing time on Tuesday for the location</description>
    <label>TuesdayClose</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/TuesdayOpen__c.field-meta.xml
<CustomField>
    <fullName>TuesdayOpen__c</fullName>
    <description>Indicates the opening time on Tuesday for the location</description>
    <label>TuesdayOpen</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/WednesdayOpen__c.field-meta.xml
<CustomField>
    <fullName>WednesdayOpen__c</fullName>
    <description>Indicates the opening time on Wednesday for the location</description>
    <label>WednesdayOpen</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/LocationResource__c.object-meta.xml
<CustomObject>
    <label>Location Resource</label>
    <nameField>
        <label>Location Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Location Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LocationResource__c/fields/AgesServed__c.field-meta.xml
<CustomField>
    <fullName>AgesServed__c</fullName>
    <label>Ages Served</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Infants (0-1)</fullName>
            </value>
            <value>
                <fullName>Pre-K (1-5)</fullName>
            </value>
            <value>
                <fullName>Children (6-12)</fullName>
            </value>
            <value>
                <fullName>Teenagers (13-19)</fullName>
            </value>
            <value>
                <fullName>Adults (20-55)</fullName>
            </value>
            <value>
                <fullName>Seniors (55+)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/EligibilityCCAP__c.field-meta.xml
<CustomField>
    <fullName>EligibilityCCAP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Eligibility CCAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/EligibilityDescription__c.field-meta.xml
<CustomField>
    <fullName>EligibilityDescription__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Eligibility Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/EligibilityMedicaid__c.field-meta.xml
<CustomField>
    <fullName>EligibilityMedicaid__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Eligibility Medicaid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/EligibilitySNAP__c.field-meta.xml
<CustomField>
    <fullName>EligibilitySNAP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Eligibility SNAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/EligibilityTANF__c.field-meta.xml
<CustomField>
    <fullName>EligibilityTANF__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Eligibility TANF</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/Fees__c.field-meta.xml
<CustomField>
    <fullName>Fees__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Fees</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/FirstPointofContactEmail__c.field-meta.xml
<CustomField>
    <fullName>FirstPointofContactEmail__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>First Point of Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/FirstPointOfContactName__c.field-meta.xml
<CustomField>
    <fullName>FirstPointOfContactName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>First Point Of Contact Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/FirstPointofContactPhone__c.field-meta.xml
<CustomField>
    <fullName>FirstPointofContactPhone__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>First Point of Contact Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/FirstPointOfContactTitle__c.field-meta.xml
<CustomField>
    <fullName>FirstPointOfContactTitle__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>First Point Of Contact Title</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/Geography_Served__c.field-meta.xml
<CustomField>
    <fullName>Geography_Served__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Geography Served</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>The location record to which the location resource is related to</description>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Location Resources</relationshipLabel>
    <relationshipName>Location_Resources</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/MondayClose__c.field-meta.xml
<CustomField>
    <fullName>MondayClose__c</fullName>
    <label>MondayClose</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/MondayOpen__c.field-meta.xml
<CustomField>
    <fullName>MondayOpen__c</fullName>
    <label>MondayOpen</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/NextSteps__c.field-meta.xml
<CustomField>
    <fullName>NextSteps__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Next Steps</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>TimeOpen Notes</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <description>The resource record to which the location resource is related to</description>
    <label>Resource</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Location Resources</relationshipLabel>
    <relationshipName>Location_Resources</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/ResourceDescription__c.field-meta.xml
<CustomField>
    <fullName>ResourceDescription__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Resource Description</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/SecondPointofContactEmail__c.field-meta.xml
<CustomField>
    <fullName>SecondPointofContactEmail__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Second Point of Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/SecondPointOfContactName__c.field-meta.xml
<CustomField>
    <fullName>SecondPointOfContactName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Second Point Of Contact Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/SecondPointofContactPhone__c.field-meta.xml
<CustomField>
    <fullName>SecondPointofContactPhone__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Second Point of Contact Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/SecondPointOfContactTitle__c.field-meta.xml
<CustomField>
    <fullName>SecondPointOfContactTitle__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Second Point Of Contact Title</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Not Used</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/TimeZone__c.field-meta.xml
<CustomField>
    <fullName>TimeZone__c</fullName>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EST</fullName>
            </value>
            <value>
                <fullName>CST</fullName>
            </value>
            <value>
                <fullName>MST</fullName>
            </value>
            <value>
                <fullName>PST</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/TollFree__c.field-meta.xml
<CustomField>
    <fullName>TollFree__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>TollFree</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/TuesdayClose__c.field-meta.xml
<CustomField>
    <fullName>TuesdayClose__c</fullName>
    <label>TuesdayClose</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/TuesdayOpen__c.field-meta.xml
<CustomField>
    <fullName>TuesdayOpen__c</fullName>
    <label>TuesdayOpen</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/LocationResource__c/fields/WhatToBring__c.field-meta.xml
<CustomField>
    <fullName>WhatToBring__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>What to bring</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/globalValueSets/USTimeZones.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>EST</fullName>
        
        
        <label>EST</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>CST</fullName>
        
        
        <label>CST</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>MST</fullName>
        
        
        <label>MST</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>PST</fullName>
        
        
        <label>PST</label>
        
    </customValue>
    
    <masterLabel>US Time Zones</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/classes/RE_ResourceLocationCtrlTest.cls
@isTest
public class RE_ResourceLocationCtrlTest {
    static  Id citizenRecordTypeIdAccount = Schema.SObjectType.Account.getRecordTypeInfosByName().get(RE_GlobalConstants.strCitizenRecordTypeName).getRecordTypeId();
    static Id contactCitizenRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get(RE_GlobalConstants.strCitizenRecordTypeName).getRecordTypeId();
    static Id locationRecordTypeId = Schema.SObjectType.Location__c.getRecordTypeInfosByName().get(RE_GlobalConstants.strLocationRecordTypeName).getRecordTypeId();
    
    
    /********************************************************************************************
* @author      Kojashree Kakariya
* @date         02/07/2019
* @methodname   setupTestData
* @description  This method is used to create test records for all test methods
* @param        none
* @return       none
********************************************************************************************/
    @testSetup static void setupTestData(){        
        TestDataFactory.testDataSetup();
        Profile objProfile = [SELECT Id FROM Profile WHERE Name =: RE_GlobalConstants.STANDARD_USER_PROFILE_TEST];
        Id idAccount = [SELECT id FROM Account LIMIT 1].id;
        List<Id> accountIdList = new List<Id>();
        accountIdList.add(idAccount);
        Id sContactId = [SELECT Id FROM Contact WHERE Email =: RE_GlobalConstants.CPADMIN_USER1_EMAIL_TEST LIMIT 1].Id;
        User objReUser = TestDataFactory.createSpecificCommunityUser('reusr', null, 'REUser', RE_GlobalConstants.SAMPLE_USER_NAME_TEST, RE_GlobalConstants.SAMPLE_USER_EMAIL_TEST, RE_GlobalConstants.SAMPLE_USER_EMAIL_TEST, objProfile.Id, true);                
        List<Location__c> locationList = [SELECT id FROM Location__c LIMIT 2];
        List<Resource__c> resourceList = [SELECT id FROM Resource__c LIMIT 2];
        List<LocationResource__c> locationRsrcList = TestDataFactory.createLocationResource(2,true,null,locationList,resourceList);
        
    }
    
    /********************************************************************************************
* @author       Kojashree Kakariya
* @date          02/07/2019
* @methodname   testGetLocationResourceDetails
* @description  This method is used to test the functionality of method - getResourceLocationDetails.
* @param        none
* @return       none
********************************************************************************************/
    @isTest static void testGetLocationResourceDetails() {        
        User communityUser = [SELECT Id,ContactId FROM USER WHERE Email =:RE_GlobalConstants.COMMUNITY_USER_EMAIL_TEST LIMIT 1];
        List<LocationResource__c> locationResList = [SELECT Id FROM LocationResource__c LIMIT 1];
        RE_CreateLightningServerResponse result;
        Test.startTest();
        System.runAs(communityUser) {
            if(!locationResList.isEmpty())
                result = RE_ResourceLocationCtrl.getResourceLocationDetails(String.valueOf(locationResList[0].Id));
        }
        Test.stopTest();
        System.assert(result.isSuccessful == true,'Success');
    }
    
    /********************************************************************************************
* @author      Kojashree Kakariya
* @date          02/07/2019
* @methodname   testGetLocationResourceDetailsExcptn
* @description  This method is used to test the functionality of catch block of method - getResourceLocationDetails.
* @param        none
* @return       none
********************************************************************************************/
    @isTest static void testGetLocationResourceDetailsExcptn() {
        User communityUser = [SELECT Id,ContactId FROM USER WHERE Email =:RE_GlobalConstants.COMMUNITY_USER_EMAIL_TEST LIMIT 1];
        List<LocationResource__c> locationResList = [SELECT Id FROM LocationResource__c LIMIT 1];
        RE_CreateLightningServerResponse result;
        Test.startTest();
        System.runAs(communityUser) {
            result = RE_ResourceLocationCtrl.getResourceLocationDetails('null');
        }
        Test.stopTest();
        System.assert(result.isSuccessful == false,'Success');
    }
    
    /********************************************************************************************
* @author       Kojashree Kakariya
* @date          02/07/2019
*Method Name:   testGetPickListValues
*Description:   Method to cover functionality of method - getPickListValues.
*Returns:       none
*********************************************************************************************/
    @isTest static void testGetPickListValues() {
        Test.startTest();
        RE_CreateLightningServerResponse responseResult = RE_ResourceLocationCtrl.getPickListValues('LocationResource__c','Status__c');
        RE_CreateLightningServerResponse rest2 = RE_ResourceLocationCtrl.updateResourceLocation('{}', '');
        System.assert(rest2.isSuccessful == false,'Success');
        Test.stopTest();
        System.assertEquals(responseResult.isSuccessful,true,'Success');
    }
    
    /********************************************************************************************
* @author       Kojashree Kakariya
* @date          02/07/2019
*Method Name:   updateResourceLocation
*Description:   Method to cover functionality of method - updateResourceLocationDetails.
*Returns:       none
*********************************************************************************************/
    
    @isTest static void updateResourceLocation(){
        User communityUser = [SELECT Id,ContactId FROM USER WHERE Email =:RE_GlobalConstants.COMMUNITY_USER_EMAIL_TEST LIMIT 1];
        LocationResource__c locRes = [SELECT Id,Name,AgesServed__c,Location__c,Status__c,Phone__c,TollFree__c,Fax__c,ResourceDescription__c,
                                      Geography_Served__c,EligibilityCCAP__c,EligibilityDescription__c,EligibilityMedicaid__c,EligibilitySNAP__c,EligibilityTANF__c,
                                      FirstPointofContactEmail__c,FirstPointOfContactName__c,FirstPointofContactPhone__c,FirstPointOfContactTitle__c,
                                      SecondPointofContactEmail__c,SecondPointOfContactName__c,SecondPointofContactPhone__c,SecondPointOfContactTitle__c,
                                      TimeZone__c,Fees__c,Notes__c,WhatToBring__c,NextSteps__c,MondayOpen__c,MondayClose__c,TuesdayOpen__c,TuesdayClose__c,WednesdayOpen__c,WednesdayClose__c,
                                      ThursdayOpen__c,ThursdayClose__c,FridayOpen__c,FridayClose__c,SaturdayOpen__c,SaturdayClose__c,SundayOpen__c,SundayClose__c,Resource__c,DaysClosed__c FROM LocationResource__c LIMIT 1 ];
        
        RE_ResourceLocationCtrl.LocationResourceWrapper wrapper = new RE_ResourceLocationCtrl.LocationResourceWrapper(locRes);
        List<Location__c> locationList = [SELECT id FROM Location__c LIMIT 2];
        List<Resource__c> resourceList = [SELECT id FROM Resource__c LIMIT 2];
        
        wrapper.bIsMondayClosed = false;
        wrapper.bIsTuesdayClosed = false;
        wrapper.bIsWednesdayClosed = false;
        wrapper.bIsThursdayClosed = false;
        wrapper.bIsFridayClosed = false;
        wrapper.bIsSaturdayClosed = false;
        wrapper.bIsSundayClosed = false;
        wrapper.slocationResDescription = 'Update Test Description'; 
        String locResString = JSON.serialize(wrapper);
        String resID = locRes.Resource__c;
        RE_CreateLightningServerResponse result;
        Test.startTest();
        System.runAs(communityUser) {
            RE_ResourceLocationCtrl.convertToLocalTime(wrapper.tlocationResThursdayClose);
            result = RE_ResourceLocationCtrl.updateResourceLocation(locResString, locRes.Id);
            RE_CreateLightningServerResponse rest2 = RE_ResourceLocationCtrl.checkResourceLocation(locationList[0].Id, resourceList[0].Id);
             System.assert(rest2.isSuccessful == true,'Success');
        }
        Test.stopTest();
        System.assert(result.isSuccessful == true,'Success');
        
    }
            
/********************************************************************************************
* @author       Kojashree Kakariya
* @date          02/07/2019
*Method Name:   updateResourceLocation
*Description:   Method to cover functionality of method - updateResourceLocationDetails.
*Returns:       none
*********************************************************************************************/
    
    @isTest static void updateResourceLocationElse(){
        User communityUser = [SELECT Id,ContactId FROM USER WHERE Email =:RE_GlobalConstants.COMMUNITY_USER_EMAIL_TEST LIMIT 1];
        LocationResource__c locRes = [SELECT Id,Name,AgesServed__c,Location__c,Status__c,Phone__c,TollFree__c,Fax__c,ResourceDescription__c,
                                      Geography_Served__c,EligibilityCCAP__c,EligibilityDescription__c,EligibilityMedicaid__c,EligibilitySNAP__c,EligibilityTANF__c,
                                      FirstPointofContactEmail__c,FirstPointOfContactName__c,FirstPointofContactPhone__c,FirstPointOfContactTitle__c,
                                      SecondPointofContactEmail__c,SecondPointOfContactName__c,SecondPointofContactPhone__c,SecondPointOfContactTitle__c,
                                      TimeZone__c,Fees__c,Notes__c,WhatToBring__c,NextSteps__c,MondayOpen__c,MondayClose__c,TuesdayOpen__c,TuesdayClose__c,WednesdayOpen__c,WednesdayClose__c,
                                      ThursdayOpen__c,ThursdayClose__c,FridayOpen__c,FridayClose__c,SaturdayOpen__c,SaturdayClose__c,SundayOpen__c,SundayClose__c,Resource__c,DaysClosed__c FROM LocationResource__c LIMIT 1 ];
        
        RE_ResourceLocationCtrl.LocationResourceWrapper wrapper = new RE_ResourceLocationCtrl.LocationResourceWrapper(locRes);
        List<Location__c> locationList = [SELECT id FROM Location__c LIMIT 2];
        List<Resource__c> resourceList = [SELECT id FROM Resource__c LIMIT 2];
        
        wrapper.bIsMondayClosed = false;
        wrapper.bIsTuesdayClosed = false;
        wrapper.bIsWednesdayClosed = false;
        wrapper.bIsThursdayClosed = false;
        wrapper.bIsFridayClosed = false;
        wrapper.bIsSaturdayClosed = false;
        wrapper.bIsSundayClosed = false;
        wrapper.tlocationResMondayOpen = null;
        wrapper.tlocationResMondayClose = null;
        wrapper.tlocationResTuesdayOpen = null;
        wrapper.tlocationResTuesdayClose = null;
        wrapper.tlocationResWednesdayOpen = null;
        wrapper.tlocationResWednesdayClose = null;
        wrapper.tlocationResThursdayOpen = null;
        wrapper.tlocationResThursdayClose = null;
        wrapper.slocationResDescription = 'Update Test Description'; 
        String locResString = JSON.serialize(wrapper);
        String resID = locRes.Resource__c;
        RE_CreateLightningServerResponse result;
        Test.startTest();
        System.runAs(communityUser) {
            //RE_ResourceLocationCtrl.convertToLocalTime(wrapper.tlocationResThursdayClose);
            result = RE_ResourceLocationCtrl.updateResourceLocation(locResString, locRes.Id);
            RE_CreateLightningServerResponse rest2 = RE_ResourceLocationCtrl.checkResourceLocation(locationList[0].Id, resourceList[0].Id);
             System.assert(rest2.isSuccessful == true,'Success');
        }
        Test.stopTest();
        System.assert(result.isSuccessful == true,'Success');
        
    }
}