force-app/main/default/objects/LOG_LogMessage__c/LOG_LogMessage__c.object-meta.xml
<CustomObject>
    <description>Container for custom exception/log messages</description>
    <label>Log Message</label>
    <nameField>
        <displayFormat>LOG-{000000}</displayFormat>
        <label>Log Message #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Application__c/SSP_Application__c.object-meta.xml
<CustomObject>
    <description>To store SSP Application and Case data</description>
    <label>SSP Application</label>
    <nameField>
        
        <displayFormat>{000000000}</displayFormat>
        
        <label>SSP_Application Name</label>
        
        <type>AutoNumber</type>
        
    </nameField>
    <pluralLabel>SSP Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Application__c/fields/ProgramsApplied__c.field-meta.xml
<CustomField>
    <fullName>ProgramsApplied__c</fullName>
    <description>Used to store the list of programs applied for a household</description>
    <label>Programs Applied</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>BenefitPrograms</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/SSP_ApplicationIndividual__c.object-meta.xml
<CustomObject>
    <description>Custom junction object to maintain association between member and application</description>
    <label>SSP ApplicationIndividual</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>SSP_ApplicationIndividual Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SSP ApplicationIndividuals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/MedicaidType__c.field-meta.xml
<CustomField>
    <fullName>MedicaidType__c</fullName>
    <description>Used to store type of Medicaid Program - Magi/Non Magi</description>
    <label>Medicaid Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MAGI</fullName>
            </value>
            <value>
                <fullName>Non-MAGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/MemberStatus__c.field-meta.xml
<CustomField>
    <fullName>MemberStatus__c</fullName>
    <description>This field is used to determine the status of member</description>
    <label>Member Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Edited</fullName>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/ProgramsApplied__c.field-meta.xml
<CustomField>
    <fullName>ProgramsApplied__c</fullName>
    <description>Different types of programs applied on an application for which this member is involved</description>
    <label>Application Programs Applied</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>BenefitPrograms</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/SSP_Application__c.field-meta.xml
<CustomField>
    <fullName>SSP_Application__c</fullName>
    <description>Indicates the application related to a member</description>
    <label>SSP_Application</label>
    <referenceTo>SSP_Application__c</referenceTo>
    <relationshipName>SSP_ApplicationIndividuals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/SSP_Member__c.field-meta.xml
<CustomField>
    <fullName>SSP_Member__c</fullName>
    <description>Indicates the member related to an application</description>
    <label>SSP_Member</label>
    <referenceTo>SSP_Member__c</referenceTo>
    <relationshipName>SSP_ApplicationIndividuals</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_Benefits__c/SSP_Benefits__c.object-meta.xml
<CustomObject>
    <description>Stores benefit details such as household, individual, out of state, SSI benefits etc.</description>
    <label>SSP Benefits</label>
    <nameField>
        
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        
        <label>SSP_Benefits Name</label>
        
        <type>Text</type>
        
    </nameField>
    <pluralLabel>SSP Benefits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Benefits__c/fields/DCId__c.field-meta.xml
<CustomField>
    <fullName>DCId__c</fullName>
    <description>Used to store the generic DC ids from .NET Table</description>
    <externalId>true</externalId>
    <label>DC Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SSP_Benefits__c/fields/SSP_Member__c.field-meta.xml
<CustomField>
    <fullName>SSP_Member__c</fullName>
    <description>This field is used to indicate the member for a particular Benefit record</description>
    <label>SSP_Member</label>
    <referenceTo>SSP_Member__c</referenceTo>
    <relationshipName>SSP_Benefits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_Benefits__c/recordTypes/EntitledBenefit.recordType-meta.xml
<RecordType>
    <fullName>EntitledBenefit</fullName>
    <active>true</active>
    <description>This record type is used to store entitled benefits.</description>
    <label>EntitledBenefit</label>
</RecordType>

force-app/main/default/objects/SSP_Member__c/SSP_Member__c.object-meta.xml
<CustomObject>
    <description>Stores details about an individual member of a case/application such as gatepost reponse, incarceration, disability, living arrangement, pregnancy, address details. Also repurposed to store information of different individuals in the form of individual alien, alien sponsor, care taker,  care coordinator etc.</description>
    <label>SSP Member</label>
    <nameField>
        
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        
        <label>SSP_Member Name</label>
        
        <type>Text</type>
        
    </nameField>
    <pluralLabel>SSP Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Member__c/fields/DCId__c.field-meta.xml
<CustomField>
    <fullName>DCId__c</fullName>
    <description>This field used to store the unique member DC Id to identify for an external system</description>
    <externalId>true</externalId>
    <label>DCId</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/IndividualId__c.field-meta.xml
<CustomField>
    <fullName>IndividualId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>This field is used to store individual Id of a member</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>IndividualId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/IsTMember__c.field-meta.xml
<CustomField>
    <fullName>IsTMember__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to indicate whether the Member is T member</description>
    <label>IsTMember</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SSP_TrackDeletion__c/SSP_TrackDeletion__c.object-meta.xml
<CustomObject>
    <description>Stores details of entities deleted by an individual on a case</description>
    <label>SSP TrackDeletion</label>
    <nameField>
        
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        
        <label>SSP_TrackDeletion Name</label>
        
        <type>Text</type>
        
    </nameField>
    <pluralLabel>SSP TrackDeletions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_TrackDeletion__c/fields/DCId__c.field-meta.xml
<CustomField>
    <fullName>DCId__c</fullName>
    <description>This field is used to store DC Id of deleted record.</description>
    <externalId>true</externalId>
    <label>DC Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SSP_TrackDeletion__c/fields/SalesforceId__c.field-meta.xml
<CustomField>
    <fullName>SalesforceId__c</fullName>
    <description>This field is used to capture Salesforce Id of record deleted.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Salesforce Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_TrackDeletion__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>This field is used to capture the screen name from where track deletion record was created.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_TrackDeletion__c/fields/SSP_Application__c.field-meta.xml
<CustomField>
    <fullName>SSP_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to indicate the related application for Track deletion record</description>
    <label>SSP_Application</label>
    <referenceTo>SSP_Application__c</referenceTo>
    <relationshipName>SSP_TrackDeletions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SSP_TrackDeletion__c/fields/SSP_Member__c.field-meta.xml
<CustomField>
    <fullName>SSP_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to indicate the related member for Track deletion record</description>
    <label>SSP_Member</label>
    <referenceTo>SSP_Member__c</referenceTo>
    <relationshipName>SSP_TrackDeletions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/BenefitPrograms.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>MA</fullName>
        
        
        <label>Medicaid/KCHIP</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>KT</fullName>
        
        
        <label>KTAP (Cash Assistance)</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SN</fullName>
        
        
        <label>SNAP (Food Assistance)</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SS</fullName>
        
        
        <label>State Supplementation</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>DS</fullName>
        
        
        <label>DSNAP</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>CC</fullName>
        
        
        <label>Child Care Assistance</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>KP</fullName>
        
        
        <label>KI-HIPP (Health Insurance Premium Payments)</label>
        
    </customValue>
    
    <description>Different type of Benefit Programs available for a Citizen</description>
    
    <masterLabel>Benefit Programs</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/classes/SSP_HouseholdCircumstancesController.cls
/*
* classname 	: SSP_HouseholdCircumstancesController
* @description 	: A controller class for household circumstances screen component.
* @author 		: Ajay Saini
* @date 		: DEC-1-2019
* MODIFICATION LOG:
* DEVELOPER 			DATE 			DESCRIPTION
* ---------------------------------------------------------------------------------------------
* Ajay Saini 		DEC-1-2019			Initial Version
*/
public with sharing class SSP_HouseholdCircumstancesController {
    private static final String CLASSNAME = 'SSP_HouseholdCircumstancesController';

	/***************************************************************************************************
    * @author       Ajay Saini
    * @date         DEC-1-2019
    * @methodname   fetchApplicationMembers
    * @description  This methods is used to fetch for data application and member data
    * @return       application and list of applicants
    *****************************************************************************************************/
    @AuraEnabled(cacheable=true)
    public static SSP_LightningResponse fetchApplicationMembers(Id applicationId, List<String> memberFields, String applicationMode) {
        SSP_LightningResponse response = new SSP_LightningResponse();
        try {
		SSP_Utility.isAuthenticatedUser();
            for(Integer i = 0; i < memberFields.size(); ++i) {
                memberFields[i] = 'SSP_Member__r.' + memberFields[i];
            }
            memberFields.add('MemberStatus__c');
            memberFields.add('MedicaidType__c');
            List<SSP_Member__c> members = new List<SSP_Member__c>();
            Map<Id, String> memberProgramsMap = new Map<Id, String>();
            List<SSP_ApplicationIndividual__c> applicationIndividuals = SSP_ApplicationIndividualSelector.queryApplicationIndividualData(null, applicationId, new Set<String>(memberFields));
            if(applicationIndividuals == null) {
                applicationIndividuals = new List<SSP_ApplicationIndividual__c>();
            }
            for(SSP_ApplicationIndividual__c individual: applicationIndividuals) {
                SSP_Member__c member = (SSP_Member__c)individual.getSObject(SSP_ApplicationIndividual__c.SSP_Member__c.getDescribe().getSObjectField());
                individual.ProgramsApplied__c = individual.ProgramsApplied__c != null? individual.ProgramsApplied__c : '';
                if(individual.ProgramsApplied__c.contains('MA') && individual.MedicaidType__c != null) {
                    individual.ProgramsApplied__c += ';' + individual.MedicaidType__c;
                }
                memberProgramsMap.put(individual.SSP_Member__c, individual.ProgramsApplied__c);
                if('addRemoveMember' == applicationMode) {
                    if('New' == individual.MemberStatus__c && !individual.IsTMember__c) {
                        members.add(member);
                    }
                }
                else if (applicationMode == SSP_GlobalConstants.SSP_RAC_FLOW){
                    if(!individual.IsTMember__c && SSP_Utility.getRACSelectedMembers(String.valueOf(applicationId)).contains(member.IndividualId__c)){
                    	members.add(member);    
                    }                     
                }
                else if('addRemoveMember' != applicationMode && !individual.IsTMember__c) {
                    members.add(member);
                }
            }
            response.put('applicationMode', applicationMode);
            response.put('members', members);
            response.put('memberProgramsMap', memberProgramsMap);
	        response.put('screenPermission', SSP_Utility.getScreenAccessDetails('SSP_APP_Select_HouseholdCircumstance', null).screenPermission);//CD2 2.5 Security Role Matrix and Program Access.
            response.bIsSuccess = true;
        }
        catch(Exception e) {
            List<LOG_LogMessage__c> lstLogMessages = LOG_LogMessageUtility.logMessage(e, CLASSNAME, 'fetchApplicationMembers', e.getMessage() , true);
            response.addException(e, lstLogMessages[0].Id);
        }
        return response;
    }
    
    /***************************************************************************************************
    * @author       Sai Velpula
    * @date         05/05/2020
    * @methodname   deleteMemberData
    * @description  This methods is used to Delete for member data
    * @return       boolean
    *****************************************************************************************************/
    @AuraEnabled
    public static SSP_LightningResponse deleteMemberData(List<String> sMemberIds, String sApplicationId) {
        SSP_LightningResponse response = new SSP_LightningResponse();
        Set<String> setMemberIds = new Set<String>(sMemberIds);
        Map<String,String> mapConditions = new Map<String,String>();
        List<SSP_TrackDeletion__c> lstTrackDeletion = new List<SSP_TrackDeletion__c>();
        List<SSP_Benefits__c> lstDeleteBenefits = new List<SSP_Benefits__c>();
        List<SSP_Benefits__c> lstAddToTrackDeletion = new List<SSP_Benefits__c>();
        List<SSP_Benefits__c> lstBenefits;
        try{
            SSP_Utility.isAuthenticatedUser();
            Id objRecordTypeId = SSP_Utility.getRecrodTypeIdBySobjectAndDevName('SSP_Benefits__c','EntitledBenefit');
            mapConditions.clear();
            mapConditions.put('SSP_Member__c',String.join(new List<String>(setMemberIds), ','));
            mapConditions.put('RecordTypeId',objRecordTypeId);
            lstBenefits = SSP_BenefitsSelector.queryBenefitsData(new Map<String, String>{'objectName'=>'SSP_Benefits__c','IN'=>'SSP_Member__c','operator'=>'AND'}, 
                                                                 new Set<String>{'ID','DCId__c'}, 
                                                                 mapConditions);
            if(lstBenefits != NULL && !lstBenefits.IsEmpty()){
                for(SSP_Benefits__c objBenefit : lstBenefits){
                    if(objBenefit.DCId__c != NULL){
                        lstAddToTrackDeletion.add(objBenefit);
                    }else{
                        lstDeleteBenefits.add(objBenefit);
                    }
                }
            }
            if(lstDeleteBenefits != NULL && !lstDeleteBenefits.IsEmpty()){
                ESAPI.accessController().deleteAsUser(lstDeleteBenefits);
                //delete lstDeleteBenefits;
            }
            if(lstAddToTrackDeletion != NULL && !lstAddToTrackDeletion.IsEmpty() && sApplicationId != NULL && String.isNotBlank(sApplicationId)){
                for(SSP_Benefits__c objBenefit : lstAddToTrackDeletion){
                    SSP_TrackDeletion__c objTrackDeletion = new SSP_TrackDeletion__c();
                    objTrackDeletion.SSP_Application__c = sApplicationId;
                    objTrackDeletion.SalesforceId__c = objBenefit.Id;
                    objTrackDeletion.SSP_Member__c = objBenefit.SSP_Member__c;
                    objTrackDeletion.Source__c = 'SSP_APP_Select_HouseholdCircumstance';
                    objTrackDeletion.DCId__c = objBenefit.DCId__c;
                    lstTrackDeletion.add(objTrackDeletion);
                }
            }
            if(lstTrackDeletion != NULL && !lstTrackDeletion.IsEmpty()){
                ESAPI.accessController().insertAsUser(lstBenefits, SSP_Utility.getFieldsNamesList(lstTrackDeletion));
            }
        }catch(Exception e) {
            List<LOG_LogMessage__c> lstLogMessages = LOG_LogMessageUtility.logMessage(e, CLASSNAME, 'deleteMemberData', e.getMessage() , true);
            response.addException(e, lstLogMessages[0].Id);
        }
        return response;
    }
}