force-app/main/default/objects/LOG_LogMessage__c/LOG_LogMessage__c.object-meta.xml
<CustomObject>
    <description>Container for custom exception/log messages</description>
    <label>Log Message</label>
    <nameField>
        <displayFormat>LOG-{000000}</displayFormat>
        <label>Log Message #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Application__c/SSP_Application__c.object-meta.xml
<CustomObject>
    <description>To store SSP Application and Case data</description>
    <label>SSP Application</label>
    <nameField>
        
        <displayFormat>{000000000}</displayFormat>
        
        <label>SSP_Application Name</label>
        
        <type>AutoNumber</type>
        
    </nameField>
    <pluralLabel>SSP Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Application__c/fields/HasShelterExpExceedIncomeResourcesToggle__c.field-meta.xml
<CustomField>
    <fullName>HasShelterExpExceedIncomeResourcesToggle__c</fullName>
    <description>This field is used to identify if shelter expenses exceed monthly gross income for SNAP.</description>
    <label>HasShelterExpExceedIncomeResourcesToggle</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>YesNo</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Application__c/fields/HouseholdTotalMonthlyCashSavingAmount__c.field-meta.xml
<CustomField>
    <fullName>HouseholdTotalMonthlyCashSavingAmount__c</fullName>
    <description>Used to store household Total Monthly Cash Savings Amount</description>
    <label>HouseholdTotalMonthlyCashSavingAmount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SSP_Application__c/fields/HouseholdTotalMonthlyGrossIncAmount__c.field-meta.xml
<CustomField>
    <fullName>HouseholdTotalMonthlyGrossIncAmount__c</fullName>
    <label>HouseholdTotalMonthlyGrossIncAmount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SSP_Application__c/fields/IsDestituteFarmOrMigrantHouseholdToggle__c.field-meta.xml
<CustomField>
    <fullName>IsDestituteFarmOrMigrantHouseholdToggle__c</fullName>
    <description>This field is used to identify if anyone in household is migrant or seasonal farmworker for SNAP.</description>
    <label>IsDestituteFarmOrMigrantHousehold?</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>YesNo</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/globalValueSets/YesNo.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>Y</fullName>
        
        
        <label>YES</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>N</fullName>
        
        
        <label>NO</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>U</fullName>
        
        
        <label>Unknown</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>NULL</fullName>
        
        
        <label>NULL</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>H</fullName>
        
        
        <label>Historical</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>I don&apos;t know</fullName>
        
        
        <label>I don&apos;t know</label>
        
    </customValue>
    
    <description>Used to store different types of toggle picklist values</description>
    
    <masterLabel>YesNo</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/classes/SSP_ExpeditedSnapBenefitCtrl.cls
/*
* classname 		: SSP_ExpeditedSnapBenefitCtrl
* @description 		: This is the Controller class for Expedited SNAP Benefits.
* @author 			: Sai Kiran
* @date 			: 01/24/2019
* MODIFICATION LOG	:
* DEVELOPER 			DATE 			DESCRIPTION
* ---------------------------------------------------------------------------------------------
*/
public class SSP_ExpeditedSnapBenefitCtrl {
    
    
    /*
* method 		: fetchApplicationData
* @description  : This method is used to fetch Application Obj with Expedited Snap Benefits.
* @author 		: Sai Kiran Velpula
* @param 		: sApplicationID - String
* @return 		: SSP_LightningResponse
* */
    @AuraEnabled
    public static SSP_LightningResponse fetchApplicationData(String sApplicationID){
        SSP_LightningResponse objResponse = new SSP_LightningResponse();
        SSP_ExpeditedSnapBenefitWrapper objAppWrap;
        SSP_Application__c objApplication;      
        try{
            SSP_Utility.isAuthenticatedUser();
            if(sApplicationID != NULL && String.isNotBlank(sApplicationID)){
                sApplicationID = String.escapeSingleQuotes(sApplicationID);
                objApplication = SSP_ExpeditedSnapBenefitService.fetchApplicationData(sApplicationID);
            }
            if(objApplication != NULL){
                objAppWrap = new SSP_ExpeditedSnapBenefitWrapper();
                objAppWrap.sGrossIncAmount = objApplication.HouseholdTotalMonthlyGrossIncAmount__c;
                objAppWrap.sCashSavingAmount = objApplication.HouseholdTotalMonthlyCashSavingAmount__c;
                objAppWrap.bDestituteFarmOrMigrantHouseholdToggle = objApplication.IsDestituteFarmOrMigrantHouseholdToggle__c;
                objAppWrap.bShelterExpExceedIncomeResourcesToggle = objApplication.HasShelterExpExceedIncomeResourcesToggle__c;
            }
            objResponse.put('objApplicationWrap',objAppWrap);
            objResponse.bIsSuccess = true;
        }catch(Exception ex){
            List<LOG_LogMessage__c> lstLogMessages = LOG_LogMessageUtility.logMessage(ex, 'SSP_ExpeditedSnapBenefitService', 'fetchApplicationData', ex.getMessage() , true);
            objResponse.bIsSuccess = false;
        }
        
        return objResponse;
    }
    /*
* method 		: updateApplication
* @description  : This method is used to update Application Obj with Expedited Snap Benefits.
* @author 		: Sai Kiran Velpula
* @param 		: sApplicationWrapper
* @return 		: SSP_LightningResponse
* */
    @AuraEnabled
    public static SSP_LightningResponse updateApplication(String sApplicationWrapper){
        SSP_LightningResponse objResponse = new SSP_LightningResponse();
        SSP_Application__c objApplication;
        List<String> lstApplicationFields = new List<String>{'HouseholdTotalMonthlyGrossIncAmount__c','HouseholdTotalMonthlyCashSavingAmount__c','HasShelterExpExceedIncomeResourcesToggle__c','IsDestituteFarmOrMigrantHouseholdToggle__c'};
            try{
                objApplication = SSP_ExpeditedSnapBenefitService.updateApplication(sApplicationWrapper);
                if(objApplication != NULL ){
                    ESAPI.accessController().updateAsUser(objApplication, lstApplicationFields);
                }
                objResponse.bIsSuccess = true;
            }catch(Exception ex){
                List<LOG_LogMessage__c> lstLogMessages = LOG_LogMessageUtility.logMessage(ex, 'SSP_ExpeditedSnapBenefitService', 'updateApplication', ex.getMessage() , true);
                objResponse.bIsSuccess = false;
            }
        
        return objResponse;
    }
    
    
}