force-app/main/default/objects/LOG_LogMessage__c/LOG_LogMessage__c.object-meta.xml
<CustomObject>
    <description>Container for custom exception/log messages</description>
    <label>Log Message</label>
    <nameField>
        <displayFormat>LOG-{000000}</displayFormat>
        <label>Log Message #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Application__c/SSP_Application__c.object-meta.xml
<CustomObject>
    <description>To store SSP Application and Case data</description>
    <label>SSP Application</label>
    <nameField>
        
        <displayFormat>{000000000}</displayFormat>
        
        <label>SSP_Application Name</label>
        
        <type>AutoNumber</type>
        
    </nameField>
    <pluralLabel>SSP Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Application__c/fields/ProgramsApplied__c.field-meta.xml
<CustomField>
    <fullName>ProgramsApplied__c</fullName>
    <description>Used to store the list of programs applied for a household</description>
    <label>Programs Applied</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>BenefitPrograms</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/SSP_ApplicationIndividual__c.object-meta.xml
<CustomObject>
    <description>Custom junction object to maintain association between member and application</description>
    <label>SSP ApplicationIndividual</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>SSP_ApplicationIndividual Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SSP ApplicationIndividuals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/ProgramsApplied__c.field-meta.xml
<CustomField>
    <fullName>ProgramsApplied__c</fullName>
    <description>Different types of programs applied on an application for which this member is involved</description>
    <label>Application Programs Applied</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>BenefitPrograms</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/SSP_Application__c.field-meta.xml
<CustomField>
    <fullName>SSP_Application__c</fullName>
    <description>Indicates the application related to a member</description>
    <label>SSP_Application</label>
    <referenceTo>SSP_Application__c</referenceTo>
    <relationshipName>SSP_ApplicationIndividuals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/SSP_Member__c.field-meta.xml
<CustomField>
    <fullName>SSP_Member__c</fullName>
    <description>Indicates the member related to an application</description>
    <label>SSP_Member</label>
    <referenceTo>SSP_Member__c</referenceTo>
    <relationshipName>SSP_ApplicationIndividuals</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/SSP_Member__c.object-meta.xml
<CustomObject>
    <description>Stores details about an individual member of a case/application such as gatepost reponse, incarceration, disability, living arrangement, pregnancy, address details. Also repurposed to store information of different individuals in the form of individual alien, alien sponsor, care taker,  care coordinator etc.</description>
    <label>SSP Member</label>
    <nameField>
        
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        
        <label>SSP_Member Name</label>
        
        <type>Text</type>
        
    </nameField>
    <pluralLabel>SSP Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Member__c/fields/IsFosterCareToggle__c.field-meta.xml
<CustomField>
    <fullName>IsFosterCareToggle__c</fullName>
    <description>This field is used to determine if an individual was in foster care.</description>
    <label>Is Foster Care ?</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>YesNo</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/globalValueSets/BenefitPrograms.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>MA</fullName>
        
        
        <label>Medicaid/KCHIP</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>KT</fullName>
        
        
        <label>KTAP (Cash Assistance)</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SN</fullName>
        
        
        <label>SNAP (Food Assistance)</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SS</fullName>
        
        
        <label>State Supplementation</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>DS</fullName>
        
        
        <label>DSNAP</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>CC</fullName>
        
        
        <label>Child Care Assistance</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>KP</fullName>
        
        
        <label>KI-HIPP (Health Insurance Premium Payments)</label>
        
    </customValue>
    
    <description>Different type of Benefit Programs available for a Citizen</description>
    
    <masterLabel>Benefit Programs</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/globalValueSets/YesNo.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>Y</fullName>
        
        
        <label>YES</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>N</fullName>
        
        
        <label>NO</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>U</fullName>
        
        
        <label>Unknown</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>NULL</fullName>
        
        
        <label>NULL</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>H</fullName>
        
        
        <label>Historical</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>I don&apos;t know</fullName>
        
        
        <label>I don&apos;t know</label>
        
    </customValue>
    
    <description>Used to store different types of toggle picklist values</description>
    
    <masterLabel>YesNo</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/classes/SSP_FormerFosterCareInformationRule.cls
/***************************************************************************************************************************
*   Type         :   Queueing Logic
*   Name         :   SSP_FormerFosterCareInformationRule
*   Created By   :   Sanchita Tibrewala
*   Created Date :   02/11/2020
*   Description  :   To decide whether the Former Foster Care screen is queued in the flow or not
*  
*   Modification Log
*   ----------------------------------------------------------------------------------------------
*   * Developer                   Date          Description
*   * --------------------------------------------------------------------------------------------               
*     Sanchita                 02/11/2020     Initial Version
*****************************************************************************************************************************/
public with sharing class SSP_FormerFosterCareInformationRule extends BasicNavFlowRule {
	
    /********************************************************************************************
    * @author       Sanchita Tibrewala
    * @date         02/11/2020
    * @methodname   isRequired
    * @description  To decide whether the Former Foster Care screen is queued in the flow or not
    * @param        Context, ContextData
    * @return       Boolean
    ********************************************************************************************/
    public override boolean isRequired(Context ctx, ContextData ctxData){
        Boolean result = false;
        try{
            if(ctxData.ApplicationId != null && ctxData.MemberId != null && ctxData.queueObject != null){
                SSP_ApplicationIndividual__c appIndividualRecord = ctxData.queueObject.memberAppIndividualMap.get(ctxData.MemberId);
                List<String> selectedProgramList = appIndividualRecord != null ? appIndividualRecord.ProgramsApplied__c.split(';') : new list<String>();
                Set<String> evaluatingSet = new Set<String> {SSP_GlobalConstants.MEDICAID};
                Boolean programCheck = SSP_Utility.checkApplicablePrograms(selectedProgramList, evaluatingSet);
                result = appIndividualRecord != null && (appIndividualRecord.SSP_Member__r.IsFosterCareToggle__c == SSP_GlobalConstants.YES) && programCheck;                         
            }
             /*List<SSP_Member__c> sspMemberList;
             List<SSP_ApplicationIndividual__c> sspApplicationIndividualList;
             if(String.isNotBlank(ctxData.MemberId) && String.isNotBlank(ctxData.ApplicationId)){
                 sspMemberList = 
                    SSP_MemberSelector.queryMemberData(new Map<String, String>{'objectName'=>'SSP_Member__c'}, 
                                                       new Set<String>{'Id', 'IsFosterCareToggle__c'}, 
                                                       new Map<String, String>{'limit'=>'10','Id'=> String.escapeSingleQuotes(ctxData.MemberId)});
                 sspApplicationIndividualList = 
                    SSP_ApplicationIndividualSelector.queryApplicationIndividualData(new Map<String, String>{'objectName'=>'SSP_ApplicationIndividual__c','operator'=>'AND'}, 
                                                                                     new Set<String>{'Id', 'SSP_Application__c', 'SSP_Member__c', 'ProgramsApplied__c'}, 
                                                                                     new Map<String, String>{'limit'=>'100','SSP_Application__c'=> String.escapeSingleQuotes(ctxData.ApplicationId), 
                                                                                         'SSP_Member__c'=> String.escapeSingleQuotes(ctxData.MemberId)});
             }
             if (!sspMemberList.isEmpty() && !sspApplicationIndividualList.isEmpty()){
                 SSP_Member__c sspMember = sspMemberList.get(0);
                 SSP_ApplicationIndividual__c sspAppInd = sspApplicationIndividualList.get(0);
                 String programs = sspAppInd.ProgramsApplied__c;
                 List<String> programValues = programs.split(';');
                 if(sspMember.IsFosterCareToggle__c == SSP_GlobalConstants.YES && !programValues.isEmpty() && programValues.contains(SSP_GlobalConstants.MEDICAID)){
                     result = true;
                 }
             }*/
        }
		catch(Exception ex){            
            List<LOG_LogMessage__c> lstLogMessages = LOG_LogMessageUtility.logMessage(ex, 'SSP_FormerFosterCareInformationRule', 'isRequired', ex.getMessage() , true);
        }
		return result;
    }
}