force-app/main/default/objects/LOG_LogMessage__c/LOG_LogMessage__c.object-meta.xml
<CustomObject>
    <description>Container for custom exception/log messages</description>
    <label>Log Message</label>
    <nameField>
        <displayFormat>LOG-{000000}</displayFormat>
        <label>Log Message #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Application__c/SSP_Application__c.object-meta.xml
<CustomObject>
    <description>To store SSP Application and Case data</description>
    <label>SSP Application</label>
    <nameField>
        
        <displayFormat>{000000000}</displayFormat>
        
        <label>SSP_Application Name</label>
        
        <type>AutoNumber</type>
        
    </nameField>
    <pluralLabel>SSP Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Application__c/fields/HasShelterExpExceedIncomeResourcesToggle__c.field-meta.xml
<CustomField>
    <fullName>HasShelterExpExceedIncomeResourcesToggle__c</fullName>
    <description>This field is used to identify if shelter expenses exceed monthly gross income for SNAP.</description>
    <label>HasShelterExpExceedIncomeResourcesToggle</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>YesNo</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Application__c/fields/HouseholdTotalMonthlyCashSavingAmount__c.field-meta.xml
<CustomField>
    <fullName>HouseholdTotalMonthlyCashSavingAmount__c</fullName>
    <description>Used to store household Total Monthly Cash Savings Amount</description>
    <label>HouseholdTotalMonthlyCashSavingAmount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SSP_Application__c/fields/HouseholdTotalMonthlyGrossIncAmount__c.field-meta.xml
<CustomField>
    <fullName>HouseholdTotalMonthlyGrossIncAmount__c</fullName>
    <label>HouseholdTotalMonthlyGrossIncAmount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SSP_Application__c/fields/IsDestituteFarmOrMigrantHouseholdToggle__c.field-meta.xml
<CustomField>
    <fullName>IsDestituteFarmOrMigrantHouseholdToggle__c</fullName>
    <description>This field is used to identify if anyone in household is migrant or seasonal farmworker for SNAP.</description>
    <label>IsDestituteFarmOrMigrantHousehold?</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>YesNo</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Application__c/fields/ProgramsApplied__c.field-meta.xml
<CustomField>
    <fullName>ProgramsApplied__c</fullName>
    <description>Used to store the list of programs applied for a household</description>
    <label>Programs Applied</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>BenefitPrograms</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/globalValueSets/BenefitPrograms.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>MA</fullName>
        
        
        <label>Medicaid/KCHIP</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>KT</fullName>
        
        
        <label>KTAP (Cash Assistance)</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SN</fullName>
        
        
        <label>SNAP (Food Assistance)</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SS</fullName>
        
        
        <label>State Supplementation</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>DS</fullName>
        
        
        <label>DSNAP</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>CC</fullName>
        
        
        <label>Child Care Assistance</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>KP</fullName>
        
        
        <label>KI-HIPP (Health Insurance Premium Payments)</label>
        
    </customValue>
    
    <description>Different type of Benefit Programs available for a Citizen</description>
    
    <masterLabel>Benefit Programs</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/globalValueSets/YesNo.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>Y</fullName>
        
        
        <label>YES</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>N</fullName>
        
        
        <label>NO</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>U</fullName>
        
        
        <label>Unknown</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>NULL</fullName>
        
        
        <label>NULL</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>H</fullName>
        
        
        <label>Historical</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>I don&apos;t know</fullName>
        
        
        <label>I don&apos;t know</label>
        
    </customValue>
    
    <description>Used to store different types of toggle picklist values</description>
    
    <masterLabel>YesNo</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/classes/SSP_ExpeditedSnapBenefitService.cls
/*
* classname 		: SSP_ExpeditedSnapBenefitService
* @description 		: This is the Service class for Expedite SNAP Benefits.
* @author 			: Sai Kiran
* @date 			: 01/24/2019
* MODIFICATION LOG	:
* DEVELOPER 			DATE 			DESCRIPTION
* ---------------------------------------------------------------------------------------------
*/
public class SSP_ExpeditedSnapBenefitService {
    
    /*
* method 		: fetchApplicationData
* @description  : This method is used to fetch Application Obj to display Expedited Snap Benefits.
* @author 		: Sai Kiran Velpula
* @param 		: sApplicationID - String
* @return 		: SSP_Application__c Object
* */
    @AuraEnabled
    public static SSP_Application__c fetchApplicationData(String sApplicationID){
        Map<String,String> mapConditions = new Map<String,String>();
        SSP_Application__c objApplication;
        List<SSP_Application__c> lstApplications = new List<SSP_Application__c>();
        List<String> lstApplicationFields = new List<String>{'ProgramsApplied__c','HouseholdTotalMonthlyGrossIncAmount__c','HouseholdTotalMonthlyCashSavingAmount__c','HasShelterExpExceedIncomeResourcesToggle__c','IsDestituteFarmOrMigrantHouseholdToggle__c'};
            try{
                SSP_Utility.isAuthenticatedUser();
                Boolean bViewApplicationFields = ESAPI.accessController().isAuthorizedToView(SSP_Application__c.getSObjectType(), lstApplicationFields);
                if(bViewApplicationFields){ 
                    mapConditions.put('ID',sApplicationID);
                    mapConditions.put('limit','1');
                    lstApplications = SSP_ApplicationSelector.queryApplicationData(new Map<String, String>{'objectName'=>'SSP_Application__c','operator'=>'AND'}, 
                                                                                   new Set<String>{'ID','ProgramsApplied__c','HouseholdTotalMonthlyGrossIncAmount__c','HouseholdTotalMonthlyCashSavingAmount__c','HasShelterExpExceedIncomeResourcesToggle__c','IsDestituteFarmOrMigrantHouseholdToggle__c'}, 
                                                                                   mapConditions);
                }
                if(lstApplications.size()>0){
                    objApplication = lstApplications[0];
                }
            }catch(Exception ex){
                List<LOG_LogMessage__c> lstLogMessages = LOG_LogMessageUtility.logMessage(ex, 'SSP_ExpeditedSnapBenefitService', 'fetchApplicationData', ex.getMessage() , true);
            }
        return objApplication;
    }
    
    /*
* method 		: updateApplication
* @description  : This method is used to update Application Obj with Expedited Snap Benefits.
* @author 		: Sai Kiran Velpula
* @param 		: sApplicationWrapper
* @return 		: SSP_Application__c Object
* */
    @AuraEnabled
    public static SSP_Application__c updateApplication(String sApplicationWrapper){
        SSP_ExpeditedSnapBenefitWrapper objApplicationWrap;
        SSP_Application__c objApplication;
        try{
            if(sApplicationWrapper != NULL && !String.isBlank(sApplicationWrapper)){
                objApplicationWrap = (SSP_ExpeditedSnapBenefitWrapper)JSON.deserialize(sApplicationWrapper, SSP_ExpeditedSnapBenefitWrapper.class);
                objApplication = new SSP_Application__c(ID = objApplicationWrap.sApplicationId);
                objApplication.HouseholdTotalMonthlyGrossIncAmount__c = objApplicationWrap.sGrossIncAmount;
                objApplication.HouseholdTotalMonthlyCashSavingAmount__c = objApplicationWrap.sCashSavingAmount;
                objApplication.HasShelterExpExceedIncomeResourcesToggle__c = objApplicationWrap.bShelterExpExceedIncomeResourcesToggle;
                objApplication.IsDestituteFarmOrMigrantHouseholdToggle__c = objApplicationWrap.bDestituteFarmOrMigrantHouseholdToggle;
            }
        }catch(Exception ex){
            List<LOG_LogMessage__c> lstLogMessages = LOG_LogMessageUtility.logMessage(ex, 'SSP_ExpeditedSnapBenefitService', 'updateApplication', ex.getMessage() , true);
        }
        return objApplication;
    }
    
}