force-app/main/default/objects/LOG_LogMessage__c/LOG_LogMessage__c.object-meta.xml
<CustomObject>
    <description>Container for custom exception/log messages</description>
    <label>Log Message</label>
    <nameField>
        <displayFormat>LOG-{000000}</displayFormat>
        <label>Log Message #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_ApplicationIndividual__c/SSP_ApplicationIndividual__c.object-meta.xml
<CustomObject>
    <description>Custom junction object to maintain association between member and application</description>
    <label>SSP ApplicationIndividual</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>SSP_ApplicationIndividual Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SSP ApplicationIndividuals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/ProgramsApplied__c.field-meta.xml
<CustomField>
    <fullName>ProgramsApplied__c</fullName>
    <description>Different types of programs applied on an application for which this member is involved</description>
    <label>Application Programs Applied</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>BenefitPrograms</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/SSP_Member__c.field-meta.xml
<CustomField>
    <fullName>SSP_Member__c</fullName>
    <description>Indicates the member related to an application</description>
    <label>SSP_Member</label>
    <referenceTo>SSP_Member__c</referenceTo>
    <relationshipName>SSP_ApplicationIndividuals</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/SSP_Member__c.object-meta.xml
<CustomObject>
    <description>Stores details about an individual member of a case/application such as gatepost reponse, incarceration, disability, living arrangement, pregnancy, address details. Also repurposed to store information of different individuals in the form of individual alien, alien sponsor, care taker,  care coordinator etc.</description>
    <label>SSP Member</label>
    <nameField>
        
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        
        <label>SSP_Member Name</label>
        
        <type>Text</type>
        
    </nameField>
    <pluralLabel>SSP Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Member__c/fields/HasReceivedBenefitsFromOtherStateToggle__c.field-meta.xml
<CustomField>
    <fullName>HasReceivedBenefitsFromOtherStateToggle__c</fullName>
    <description>This field is used to indicate whether the member has received benefits from other state</description>
    <label>Has received benefits from other state?</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>YesNo</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/globalValueSets/BenefitPrograms.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>MA</fullName>
        
        
        <label>Medicaid/KCHIP</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>KT</fullName>
        
        
        <label>KTAP (Cash Assistance)</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SN</fullName>
        
        
        <label>SNAP (Food Assistance)</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SS</fullName>
        
        
        <label>State Supplementation</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>DS</fullName>
        
        
        <label>DSNAP</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>CC</fullName>
        
        
        <label>Child Care Assistance</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>KP</fullName>
        
        
        <label>KI-HIPP (Health Insurance Premium Payments)</label>
        
    </customValue>
    
    <description>Different type of Benefit Programs available for a Citizen</description>
    
    <masterLabel>Benefit Programs</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/globalValueSets/YesNo.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>Y</fullName>
        
        
        <label>YES</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>N</fullName>
        
        
        <label>NO</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>U</fullName>
        
        
        <label>Unknown</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>NULL</fullName>
        
        
        <label>NULL</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>H</fullName>
        
        
        <label>Historical</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>I don&apos;t know</fullName>
        
        
        <label>I don&apos;t know</label>
        
    </customValue>
    
    <description>Used to store different types of toggle picklist values</description>
    
    <masterLabel>YesNo</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/classes/SSP_AnotherStateBenefitsQueueRule.cls
/*
* classname     :  SSP_AnotherStateBenefitsQueueRule
* @description  :  Class for identifying whether to queue sspOutOfStateBenefit screen for particular individual
* @author       :  Sai Kiran   
* @date         :  02/08/2019
* MODIFICATION LOG:
* DEVELOPER                     DATE                               DESCRIPTION
* ---------------------------------------------------------------------------------------------

**/
public class SSP_AnotherStateBenefitsQueueRule extends BasicNavFlowRule {
    
    /**
* Invoked on workflow "next" action. If true is returned then the page will be marked as "required" in the
* current flow and so it will be queued to be loaded on its turn. If false is returned then the page
* will be marked as "not required" and hence will not be loaded in the flow.
*
* @param ctx Context object
* @param ctxData ContextData object
*
* @return boolean
*/
    public override boolean isRequired(Context ctx, ContextData ctxData){
        Boolean result = false;
        try{
            if(ctxData!=null && ctxData.MemberId != '' && ctxData.MemberId != null && ctxData.queueObject != null){
                SSP_ApplicationIndividual__c appIndividualRecord = ctxData.queueObject.memberAppIndividualMap != null ? 
                    			  				ctxData.queueObject.memberAppIndividualMap.containskey(ctxData.MemberId) ? 
                    							ctxData.queueObject.memberAppIndividualMap.get(ctxData.MemberId) : new SSP_ApplicationIndividual__c() : new SSP_ApplicationIndividual__c();
                if(appIndividualRecord != NULL && appIndividualRecord.ProgramsApplied__c != NULL){
                    Boolean programCheck = SSP_Utility.checkApplicablePrograms(appIndividualRecord.ProgramsApplied__c.split(';'), SSP_GlobalConstants.BENEFITS_STATE_PROGRAMS);
                    if(appIndividualRecord != null && appIndividualRecord.SSP_Member__r.HasReceivedBenefitsFromOtherStateToggle__c == SSP_GlobalConstants.YES
                       && programCheck){
                           result = true;
                       }
                    
                }
            }
        }
        catch(Exception ex){            
            List<LOG_LogMessage__c> lstLogMessages = LOG_LogMessageUtility.logMessage(ex, 'SSP_SSIBenefitQueueRule', 'isRequired', ex.getMessage() , true);
        }
        return result;
    }
    
}