force-app/main/default/objects/LOG_LogMessage__c/LOG_LogMessage__c.object-meta.xml
<CustomObject>
    <description>Container for custom exception/log messages</description>
    <label>Log Message</label>
    <nameField>
        <displayFormat>LOG-{000000}</displayFormat>
        <label>Log Message #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Application__c/SSP_Application__c.object-meta.xml
<CustomObject>
    <description>To store SSP Application and Case data</description>
    <label>SSP Application</label>
    <nameField>
        
        <displayFormat>{000000000}</displayFormat>
        
        <label>SSP_Application Name</label>
        
        <type>AutoNumber</type>
        
    </nameField>
    <pluralLabel>SSP Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_ApplicationIndividual__c/SSP_ApplicationIndividual__c.object-meta.xml
<CustomObject>
    <description>Custom junction object to maintain association between member and application</description>
    <label>SSP ApplicationIndividual</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>SSP_ApplicationIndividual Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SSP ApplicationIndividuals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/IsHeadOfHousehold__c.field-meta.xml
<CustomField>
    <fullName>IsHeadOfHousehold__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to determine if the member is Head of Household</description>
    <label>Is Head Of Household</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/MemberStatus__c.field-meta.xml
<CustomField>
    <fullName>MemberStatus__c</fullName>
    <description>This field is used to determine the status of member</description>
    <label>Member Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Edited</fullName>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/SSP_Application__c.field-meta.xml
<CustomField>
    <fullName>SSP_Application__c</fullName>
    <description>Indicates the application related to a member</description>
    <label>SSP_Application</label>
    <referenceTo>SSP_Application__c</referenceTo>
    <relationshipName>SSP_ApplicationIndividuals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/SSP_Member__c.field-meta.xml
<CustomField>
    <fullName>SSP_Member__c</fullName>
    <description>Indicates the member related to an application</description>
    <label>SSP_Member</label>
    <referenceTo>SSP_Member__c</referenceTo>
    <relationshipName>SSP_ApplicationIndividuals</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/SSP_Member__c.object-meta.xml
<CustomObject>
    <description>Stores details about an individual member of a case/application such as gatepost reponse, incarceration, disability, living arrangement, pregnancy, address details. Also repurposed to store information of different individuals in the form of individual alien, alien sponsor, care taker,  care coordinator etc.</description>
    <label>SSP Member</label>
    <nameField>
        
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        
        <label>SSP_Member Name</label>
        
        <type>Text</type>
        
    </nameField>
    <pluralLabel>SSP Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Member__c/fields/BirthDate__c.field-meta.xml
<CustomField>
    <fullName>BirthDate__c</fullName>
    <description>This field is used to store Date of birth of a member</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/CanBuyCookWithHOH__c.field-meta.xml
<CustomField>
    <fullName>CanBuyCookWithHOH__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to indicate whether member can buy and cook meals with head of household</description>
    <label>Buy and Cook Meals with HOH ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/ExternalAlienSponsor__c.field-meta.xml
<CustomField>
    <fullName>ExternalAlienSponsor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to store external Alien Sponsor for member</description>
    <label>External Alien Sponsor</label>
    <referenceTo>SSP_AlienSponsor__c</referenceTo>
    <relationshipLabel>SSP Members (External Alien Sponsor)</relationshipLabel>
    <relationshipName>SSP_Members1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>This field is used to store Firstname on a Member</description>
    <encryptionScheme>None</encryptionScheme>
    <label>FirstName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/InternalAlienSponsor__c.field-meta.xml
<CustomField>
    <fullName>InternalAlienSponsor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to store if Alien Sponsor is from Household</description>
    <label>Internal Alien Sponsor</label>
    <referenceTo>SSP_Member__c</referenceTo>
    <relationshipLabel>SSP Members (Internal Alien Sponsor)</relationshipLabel>
    <relationshipName>SSP_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/IsHeadOfHousehold__c.field-meta.xml
<CustomField>
    <fullName>IsHeadOfHousehold__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Head Of Household</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <description>This field is used to store Lastname of a member</description>
    <encryptionScheme>None</encryptionScheme>
    <label>LastName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/SponsoredIndividual__c.field-meta.xml
<CustomField>
    <fullName>SponsoredIndividual__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to store the related member for an Alien Sponsor within household</description>
    <label>Alien Sponsor</label>
    <referenceTo>SSP_Member__c</referenceTo>
    <relationshipName>SSP_Member1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SSP_HouseHoldMealsService.cls
/***************************************************************************************************************************
*   Type         :   Service Class
*   Name         :   SSP_HouseHoldMealsService
*   Created By   :   Suyash Singhal
*   Created Date :   11/13/2019
*   Description  : 
*  
*   Modification Log
*   --------------------------------------------------------------------------------------
*   * Developer                   Date          Description
*   * ------------------------------------------------------------------------------------                 
*     Suyash                    11/13/2019        Initial Version
*****************************************************************************************************************************/

public with sharing class SSP_HouseHoldMealsService {
    

     /********************************************************************************************
    * @author       Suyash Singhal
    * @date         11/13/2019
    * @description  This method gets all the Household details as an init method
    * @param        sApplicationId
    * @return       SSP_LightningResponse
    ********************************************************************************************/
    public static map<String,Object> fetchHouseHoldData(List<String> lstApplications , String mode){

        List<SSP_Member__c> lstMembers = new List<SSP_Member__c>();
        map<String,Object> objResponse = new map<String,Object>();
        Set<Id> setMemIds = new set<Id>();
        Map<id,SSP_ApplicationIndividual__c> indivVsmemberMap = new Map<id , SSP_ApplicationIndividual__c>();
        List<SSP_HouseHoldMeals.WrapperHHMeals> lstWrapper = new List<SSP_HouseHoldMeals.WrapperHHMeals>();
        String sLabelValue ='';
        String sApplicationId = lstApplications[0]; 

        
        try{
           List<SSP_ApplicationIndividual__c> lstAppIndividuals = new List<SSP_ApplicationIndividual__c> ();  
         if(String.IsNotBlank(sApplicationId)){
             
           lstAppIndividuals =  SSP_ApplicationIndividualSelector.queryApplicationIndividualData(new Map<String, String>{'objectName'=>'SSP_ApplicationIndividual__c','operator'=>'AND','MemberStatus__c' => '!='}, 
                                                                                                                         new Set<String>{'Id','SSP_Member__c', 'SSP_Application__c', 'IsHeadOfHousehold__c','MemberStatus__c'},
                                                                                                                         new Map<String, String>{'limit'=>'100','SSP_Application__c'=> sApplicationId, 'MemberStatus__c'=> 'Removed'});
             


            for(SSP_ApplicationIndividual__c objAppIndiv : lstAppIndividuals){
                if(objAppIndiv.IsHeadOfHousehold__c || !mode.endsWithIgnoreCase('addRemoveMember') || (mode.endsWithIgnoreCase('addRemoveMember') && objAppIndiv.MemberStatus__c=='New' )){
                setMemIds.add(objAppIndiv.SSP_Member__c);
                indivVsmemberMap.put(objAppIndiv.SSP_Member__c ,objAppIndiv);
                }
            }     
         }

         if(!setMemIds.isEmpty()){
            
             lstMembers =  SSP_MemberSelector.queryMemberData(new Map<String, String>{'objectName'=>'SSP_Member__c','IN'=>'Id'}, 
                                                                              new Set<String>{'Id','Name', 'FirstName__c','LastName__c','BirthDate__c', 'CanBuyCookWithHOH__c','SponsoredIndividual__c', 'InternalAlienSponsor__c','ExternalAlienSponsor__c'}, 
                                                                              new Map<String, String>{'Id'=> String.join(new List<Id>(setMemIds), ',')}); 


          //   lstMembers = [select Id,Name,BirthDate__c,CanBuyCookWithHOH__c,SponsoredIndividual__c, InternalAlienSponsor__c,ExternalAlienSponsor__c from SSP_Member__c where id =:setMemIds];
             for(SSP_Member__c objMem : lstMembers){ SSP_HouseHoldMeals.WrapperHHMeals objWrapper = new SSP_HouseHoldMeals.WrapperHHMeals();
                objWrapper.sMemberName = objMem.FirstName__c+' '+objMem.LastName__c; 
                objWrapper.sMemberId = objMem.Id;
                objWrapper.bCanBuyCookWithHOH = objMem.CanBuyCookWithHOH__c;
                objWrapper.sMemberStatus = (indivVsmemberMap != null && indivVsmemberMap.containsKey(objMem.id)) ? indivVsmemberMap.get(objMem.id).MemberStatus__c : null;
               if(null!=indivVsmemberMap.get(objMem.id) && indivVsmemberMap.get(objMem.id).IsHeadOfHousehold__c){
                   objWrapper.bHOH = indivVsmemberMap.get(objMem.id).IsHeadOfHousehold__c;
                    objResponse.put('headOfHousehold',String.valueOf(JSON.serialize(objWrapper)));
                    sLabelValue = system.Label.sspMemberWhoBuysAndCooks + ' ' +  objMem.FirstName__c+' '+objMem.LastName__c ;
                    objResponse.put('sLabel',sLabelValue + ' ?');
                }
               lstWrapper.add(objWrapper);
            }
            

         }

        

       
         objResponse.put('bIsSuccess',true) ; 
         objResponse.put('Result',String.valueOf(JSON.serialize(lstWrapper)));
         objResponse.put('lstMembers',lstMembers);
        }
        catch(Exception ex) {
             objResponse.put('bIsSuccess',false) ;
            List<LOG_LogMessage__c> lstLogMessages = LOG_LogMessageUtility.logMessage(ex, 'SSP_HouseHoldMealsService', 'fetchHouseHoldData', ex.getMessage() , true);
        }        

        return objResponse;
        
    }

    
     /********************************************************************************************
    * @author       Suyash Singhal
    * @date         11/13/2019
    * @description  This method save the member data from component
    * @param        String sMemberIds,String sAppId
    * @return       SSP_LightningResponse
    ********************************************************************************************/
    public static map<String,Object> saveData(String sMemberIds,String sAppId , String mode){

        map<String,Object> objResponse = new map<String,Object>();

        try{
            List<String> lstMemberIds = new List<String>();
            if(String.isNotBlank(sMemberIds)){
                if(sMemberIds.contains(',')){
                lstMemberIds = sMemberIds.split(',');
                }
                else{
                    lstMemberIds.add(sMemberIds);

                }

            }
            
           
            List<SSP_Member__c> lstMembers = (List<SSP_Member__c> )fetchHouseHoldData(new List<String>{sAppId} , mode ).get('lstMembers');
            List<SSP_Member__c> lstMembersToUpdate = new List<SSP_Member__c>();

         
            for(SSP_Member__c objMember : lstMembers){
                if(lstMemberIds.contains(objMember.id)){
               
                    objMember.CanBuyCookWithHOH__c = true;
                }
                else{
                    objMember.CanBuyCookWithHOH__c = false;
                }
                lstMembersToUpdate.add(objMember);
            }
         
            objResponse.put('bIsSuccess',true) ; 
           
            
            ESAPI.accessController().updateAsUser(new Map<ID,SSP_Member__c>(lstMembersToUpdate), new List<String>(SSP_Utility.getFieldsNamesList(lstMembersToUpdate)));
            

        }catch(Exception ex) {
            objResponse.put('bIsSuccess',false) ; 
            List<LOG_LogMessage__c> lstLogMessages = LOG_LogMessageUtility.logMessage(ex, 'SSP_HouseHoldMealsService', 'saveData', ex.getMessage() , true);
        }        

        return objResponse;
    }

}