force-app/main/default/objects/LOG_LogMessage__c/LOG_LogMessage__c.object-meta.xml
<CustomObject>
    <description>Container for custom exception/log messages</description>
    <label>Log Message</label>
    <nameField>
        <displayFormat>LOG-{000000}</displayFormat>
        <label>Log Message #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LOG_LogMessage__c/fields/LOG_Age__c.field-meta.xml
<CustomField>
    <fullName>LOG_Age__c</fullName>
    <description>Age in Days</description>
    <formula>TODAY() - DATEVALUE(CreatedDate)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Age in Days</inlineHelpText>
    <label>Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LOG_LogMessage__c/fields/LOG_Debug_Level__c.field-meta.xml
<CustomField>
    <fullName>LOG_Debug_Level__c</fullName>
    <description>Debug Level</description>
    <label>Debug Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Debug</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LOG_LogMessage__c/fields/LOG_Integration_Payload__c.field-meta.xml
<CustomField>
    <fullName>LOG_Integration_Payload__c</fullName>
    <description>If log is integration related show xml payload</description>
    <inlineHelpText>If log is integration related show xml payload</inlineHelpText>
    <label>Integration Payload/Request Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/LOG_LogMessage__c/fields/LOG_Log_Code__c.field-meta.xml
<CustomField>
    <fullName>LOG_Log_Code__c</fullName>
    <description>LOG LogMessage: the exception error code of custom org code for record</description>
    <inlineHelpText>LOG LogMessage: the exception error code of custom org code for record</inlineHelpText>
    <label>Log Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LOG_LogMessage__c/fields/LOG_Message__c.field-meta.xml
<CustomField>
    <fullName>LOG_Message__c</fullName>
    <description>Message to log</description>
    <inlineHelpText>Message to log</inlineHelpText>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/LOG_LogMessage__c/fields/LOG_Reference_Id__c.field-meta.xml
<CustomField>
    <fullName>LOG_Reference_Id__c</fullName>
    <description>The related record Id</description>
    <inlineHelpText>The related record Id</inlineHelpText>
    <label>Reference Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LOG_LogMessage__c/fields/LOG_Reference_Info__c.field-meta.xml
<CustomField>
    <fullName>LOG_Reference_Info__c</fullName>
    <description>The related record info (e.g. Apex Batch Job Id, Contact etc)</description>
    <inlineHelpText>The related record info (e.g. Apex Batch Job Id, Contact etc)</inlineHelpText>
    <label>Reference Info</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/LOG_LogMessage__c/fields/LOG_Source__c.field-meta.xml
<CustomField>
    <fullName>LOG_Source__c</fullName>
    <description>The originating class/component of log message</description>
    <inlineHelpText>The originating component of log message</inlineHelpText>
    <label>Source</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LOG_LogMessage__c/fields/LOG_Source_Function__c.field-meta.xml
<CustomField>
    <fullName>LOG_Source_Function__c</fullName>
    <description>The originating function in the class/component</description>
    <inlineHelpText>The originating function in the class/component</inlineHelpText>
    <label>Source Function</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LOG_LogMessage__c/fields/LOG_Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>LOG_Stack_Trace__c</fullName>
    <description>Raw exception stack trace for unhandled errors</description>
    <inlineHelpText>Raw exception stack trace for unhandled errors</inlineHelpText>
    <label>Stack Trace</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/LOG_LogMessage__c/fields/LOG_Timer__c.field-meta.xml
<CustomField>
    <fullName>LOG_Timer__c</fullName>
    <description>The time in milliseconds for the transaction (e.g. For integration/batch apex messages it might be the time taken to process)</description>
    <inlineHelpText>The time in milliseconds for the transaction (e.g. For integration/batch apex messages it might be the time taken to process)</inlineHelpText>
    <label>ExecutionTime (Milliseconds)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LOG_LogMessageSettings__c/LOG_LogMessageSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>LOG_LogMessageSettings</description>
    <label>LOG_LogMessageSettings</label>
</CustomObject>

force-app/main/default/objects/LOG_LogMessageSettings__c/fields/LOG_Debug__c.field-meta.xml
<CustomField>
    <fullName>LOG_Debug__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If True – log debug messages in this org 
Otherwise - False</description>
    <inlineHelpText>If True – log debug messages in this org 
Otherwise - False</inlineHelpText>
    <label>Debug</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LOG_LogMessageSettings__c/fields/LOG_Error__c.field-meta.xml
<CustomField>
    <fullName>LOG_Error__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If True – log errors in this org 
Otherwise - False</description>
    <inlineHelpText>If True – log errors in this org 
Otherwise - False</inlineHelpText>
    <label>Error</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LOG_LogMessageSettings__c/fields/LOG_Info__c.field-meta.xml
<CustomField>
    <fullName>LOG_Info__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If True – log info messages in this org 
Otherwise - False</description>
    <inlineHelpText>If True – log info messages in this org 
Otherwise - False</inlineHelpText>
    <label>Info</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LOG_LogMessageSettings__c/fields/LOG_Log_Purge__c.field-meta.xml
<CustomField>
    <fullName>LOG_Log_Purge__c</fullName>
    <defaultValue>360</defaultValue>
    <description>Log Purge (Days) - The number of days of logs to keep</description>
    <inlineHelpText>Log Purge (Days) - The number of days of logs to keep</inlineHelpText>
    <label>Log Purge</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LOG_LogMessageSettings__c/fields/LOG_Warning__c.field-meta.xml
<CustomField>
    <fullName>LOG_Warning__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If True – log Warning messages in this org 
Otherwise - False</description>
    <inlineHelpText>If True – log Warning-level messages in this org 
Otherwise - False</inlineHelpText>
    <label>Warning</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/LOG_TestDataUtility.cls
/********************************************************************************************************
* @author       Deloitte
* @description  This test class is the framework used to generate test data to be used by the other test classes
* @date         2015-06-29
* @group        Message Logs - Test Classes
*********************************************************************************************************/
@isTest
public class LOG_TestDataUtility {
   
    /********************************************************************************************************
    * @author       Karolinski Stephane
    * @date         2015-08-17
    * @description  This method generates a Log Message Custom setting with the parameters provided as input
    * @param        error (Boolean): indicates if the error logs must be logged
    * @param        warning (Boolean): indicates if the warning logs must be logged
    * @param        info (Boolean): indicates if the info logs must be logged
    * @param        debug (Boolean): indicates if the debug logs must be logged
    * @param        logPurge (Boolean): the number of day before the log messages must be deleted
    * @return       void
    *********************************************************************************************************/
    public static LOG_LogMessageSettings__c generateErrorMgtCustomSetting(Boolean error, Boolean warning , Boolean info, Boolean debug, Integer logPurge)    
    {
       //insert custom setting
       LOG_LogMessageSettings__c setg = new LOG_LogMessageSettings__c();
       setg.Name = 'Default';
       setg.LOG_Debug__c = debug;
       setg.LOG_Error__c = error;
       setg.LOG_Info__c = info;
       setg.LOG_Warning__c = warning;
       setg.LOG_Log_Purge__c = logPurge;
       insert setg;
        
       return setg;
    }
 
    /********************************************************************************************************
    * @author       Karolinski Stephane
    * @date         2015-08-17
    * @description  This method generates a list of test accounts
    * @param        nrOfAccounts (integer): the number of accounts to be created
    * @param        nameRoot (String): the rootname of the accounts being generated
    * @param        executeInsert (Boolean): True of the DML insert must be executed or not, False otherwise
    * @return       List<Account>: the list of generated accounts
    *********************************************************************************************************/
    public static List<Account> generateAccounts(integer nrOfAccounts, String nameRoot, Boolean executeInsert)
    {
        List<Account> accList = new List<Account>();
        for (integer i=1; i<= nrOfAccounts; i++)
        {
            Account acc = new Account();
            acc.Name = nameRoot + ' - ' + String.valueOf(i);
            
            accList.add(acc);
        }
        if (executeInsert)
            insert accList;
        
        return accList;
    }

    /********************************************************************************************************
    * @author       Karolinski Stephane
    * @date         2015-08-17
    * @description  This method generates a list of test contacts
    * @param        nrOfContacts (integer): the number of contacts to be created
    * @param        nameRoot (String): the rootname of the contacts being generated
    * @param        linkToAccount (Account): the account to which the contact must be linked to
    * @param        executeInsert (Boolean): True of the DML insert must be executed or not, False otherwise
    * @return       List<Contact>: the list of generated contacts
    *********************************************************************************************************/
    public static List<Contact> generateContacts(integer nrOfContacts, String nameRoot, Account linkToAccount, Boolean executeInsert)
    {
        List<Contact> ctcList = new List<Contact>();
        for (integer i=1; i <= nrOfContacts; i++)
        {
            Contact ctc = new Contact();
            ctc.AccountId = linkToAccount.Id;
            ctc.LastName = nameRoot + ' - ' + String.valueOf(i);
            
            ctcList.add(ctc);
        }
        
        if (executeInsert)
            insert ctcList;
        
        return ctcList;
    }

    /********************************************************************************************************
    * @author       Karolinski Stephane
    * @date         2015-08-17
    * @description  This method retireves the logMessage specified by the provided SFDC Id
    * @param        logId (Id): the SFDC Id of the Log message to be retrieved
    * @return       LOG_LogMessage__c: the Queried Log Message
    *********************************************************************************************************/ 
    public static LOG_LogMessage__c getInsertedLog(Id logId){
       LOG_LogMessage__c insertedMsg = [SELECT LOG_Age__c, LOG_Debug_Level__c, Id, LOG_Log_Code__c, LOG_Message__c, Name, LOG_Reference_Id__c, LOG_Reference_Info__c, LOG_Source__c, LOG_Source_Function__c, LOG_Stack_Trace__c, LOG_Timer__c, CreatedDate, LOG_Integration_Payload__c 
                                        FROM LOG_LogMessage__c
                                        WHERE Id = :logId
                                       LIMIT 1];
        return insertedMsg;
    }
     
}