force-app/main/default/objects/LOG_LogMessage__c/LOG_LogMessage__c.object-meta.xml
<CustomObject>
    <description>Container for custom exception/log messages</description>
    <label>Log Message</label>
    <nameField>
        <displayFormat>LOG-{000000}</displayFormat>
        <label>Log Message #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Application__c/SSP_Application__c.object-meta.xml
<CustomObject>
    <description>To store SSP Application and Case data</description>
    <label>SSP Application</label>
    <nameField>
        
        <displayFormat>{000000000}</displayFormat>
        
        <label>SSP_Application Name</label>
        
        <type>AutoNumber</type>
        
    </nameField>
    <pluralLabel>SSP Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Different types of status of an Application</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        
            <valueSetDefinition>
            
            
                <value>
                
                    <fullName>N</fullName>
                
                
                    <label>New</label>
                
                </value>
            
                <value>
                
                    <fullName>P</fullName>
                
                
                    <label>Pending</label>
                
                </value>
            
                <value>
                
                    <fullName>AP</fullName>
                
                
                    <label>Approved</label>
                
                </value>
            
                <value>
                
                    <fullName>UN</fullName>
                
                
                    <label>Unsubmitted</label>
                
                </value>
            
                <value>
                
                    <fullName>Inactive</fullName>
                
                
                    <label>Inactive</label>
                
                </value>
            
                <value>
                
                    <fullName>Blocked</fullName>
                
                
                    <label>Blocked</label>
                
                </value>
            
            </valueSetDefinition>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Notifications__c/SSP_Notifications__c.object-meta.xml
<CustomObject>
    <description>Object to store system notifications, To Dos, Notices/Messages, Announcements</description>
    <label>SSP Notifications</label>
    <nameField>
        
        <displayFormat>Msg-{0000000000}</displayFormat>
        
        <label>SSP_Notifications Name</label>
        
        <type>AutoNumber</type>
        
    </nameField>
    <pluralLabel>SSP Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Notifications__c/fields/Linked_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Linked_Record_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Linked Record Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Notifications__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetDefinition>
            
            
                <value>
                
                    <fullName>Active</fullName>
                
                
                    <label>Active</label>
                
                </value>
            
                <value>
                
                    <fullName>Expired</fullName>
                
                
                    <label>Expired</label>
                
                </value>
            
            </valueSetDefinition>
        
        </valueSet>
</CustomField>

force-app/main/default/classes/SSP_MsgCenterApplnNotifyExpireHandler.cls
public class SSP_MsgCenterApplnNotifyExpireHandler {
    public static boolean expireNotifications(List<SSP_Application__c>Triggerold , List<SSP_Application__c>Triggernew , Map<Id,SSP_Application__c>TriggernewMap){
       List<SSP_Notifications__c> updateStatus = new List<SSP_Notifications__c>();
		List<String> recordsToExpire = new List<string>();
        boolean status;
        try{
			for(SSP_Application__c appliRec : Triggerold){
				SSP_Application__c newAppliRec = TriggernewMap.get(appliRec.Id);
				if((newAppliRec.Status__c == 'P' || newAppliRec.Status__c == 'Inactive') && (newAppliRec.Status__c != appliRec.Status__c)){
					recordsToExpire.add(newAppliRec.Id);
				}
			}
			if(!recordsToExpire.isEmpty())
			{
				for(SSP_Notifications__c changeStatus : [select id , Linked_Record_Id__c , Status__c from SSP_Notifications__c where Linked_Record_Id__c IN :recordsToExpire]){
									changeStatus.Status__c = 'Expired';
									updateStatus.add(changeStatus);
				}
			}
			if(!updateStatus.isEmpty())
			{
				Database.update(updateStatus,false);
			}
        	status = true;    
		}catch(Exception ex){
			List<LOG_LogMessage__c> lstLogMessages = LOG_LogMessageUtility.logMessage(ex, 'SSP_MessageCenterApplicationReminder', 'execute', ex.getMessage() , true);
    		status = false;
        }
        return status;
    }
}