force-app/main/default/objects/LOG_LogMessage__c/LOG_LogMessage__c.object-meta.xml
<CustomObject>
    <description>Container for custom exception/log messages</description>
    <label>Log Message</label>
    <nameField>
        <displayFormat>LOG-{000000}</displayFormat>
        <label>Log Message #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LOG_LogMessage__c/fields/InterfaceName__c.field-meta.xml
<CustomField>
    <fullName>InterfaceName__c</fullName>
    <description>This field is used to capture the Interface class name</description>
    <inlineHelpText>This field is used to capture the Interface class name</inlineHelpText>
    <label>Interface Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LOG_LogMessage__c/fields/LOG_Debug_Level__c.field-meta.xml
<CustomField>
    <fullName>LOG_Debug_Level__c</fullName>
    <description>Debug Level</description>
    <label>Debug Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Debug</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SSP_ClaimsPaymentURLIntegrationTest.cls
/**
 * Class Name    : SSP_ClaimsPaymentURLIntegrationTest
 * Owner         : DELOITTE
 * Created Date  : 08/01/2020
 * Description   : This is unit test class for SSP_ClaimsPaymentURLIntegrationService
 *
 *                            M O D I F I C A T I O N   L O G                                          
 *
 *  Date        Developer            Description                                                         
 *  ----------  --------------     -------------------------------------------------------------------
 *  08/01/2020  Ragunathan          Initial Version
 */
@isTest(seeAllData=false)
public class SSP_ClaimsPaymentURLIntegrationTest {
    @isTest
    static void shouldInvokeCallout() {
        Map<String, Object> mapInputParams = new Map<String, Object>();
        Test.setMock(HttpCalloutMock.class, new SSP_ClaimsPaymentURLIntegrationMock());
        Test.startTest();
        List<Object> objList = IntegrationFactory.invokeCallout(SSP_InterfaceConstants.SSPGETURL_METADATANAME, mapInputParams);
        Test.stopTest();
        System.assert(!objList.isEmpty(), 'Check success response');
    }
    @isTest
    static void shouldThrownExceptionWhileInvokeCallout() {
        Map<String, Object> mapInputParams = new Map<String, Object>();
        Test.setMock(HttpCalloutMock.class, new SSP_ClaimsPaymentURLIntegrationErrorMock());
        
        Test.startTest();
        List<Object> objList = IntegrationFactory.invokeCallout(SSP_InterfaceConstants.SSPGETURL_METADATANAME, mapInputParams);
        Test.stopTest();
        LOG_LogMessage__c logMessage = [Select InterfaceName__c, LOG_Debug_Level__c from LOG_LogMessage__c];
        System.assertEquals(SSP_InterfaceConstants.SSPGETURL_METADATANAME, logMessage.InterfaceName__c, 'Verify the error log created for the Interface');
        System.assertEquals('Error', logMessage.LOG_Debug_Level__c, 'Verify the error log created');
    }
    
    public class SSP_ClaimsPaymentURLIntegrationMock implements HttpCalloutMock{
        
        public HTTPResponse respond(HTTPRequest req) {
            httpResponse response = new HttpResponse();
            response.setStatusCode(200);
            response.setBody(responseBody);
            return response;
        }
        
        String responseBody =   '   {  '  + 
            '     "AckResponse": {  '  + 
            '       "Success": true,  '  + 
            '       "Error": {} '  + 
            '     }  '  + 
            '  }  ' ; 
    }
    
    public class SSP_ClaimsPaymentURLIntegrationErrorMock implements HttpCalloutMock {
        public HttpResponse respond(HttpRequest request) {
            CalloutException e = (CalloutException)CalloutException.class.newInstance();
            e.setMessage('Read Time Out');
            throw e;
        }
    }
}