force-app/main/default/objects/LOG_LogMessage__c/LOG_LogMessage__c.object-meta.xml
<CustomObject>
    <description>Container for custom exception/log messages</description>
    <label>Log Message</label>
    <nameField>
        <displayFormat>LOG-{000000}</displayFormat>
        <label>Log Message #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Application__c/SSP_Application__c.object-meta.xml
<CustomObject>
    <description>To store SSP Application and Case data</description>
    <label>SSP Application</label>
    <nameField>
        
        <displayFormat>{000000000}</displayFormat>
        
        <label>SSP_Application Name</label>
        
        <type>AutoNumber</type>
        
    </nameField>
    <pluralLabel>SSP Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Application__c/fields/ProgramsApplied__c.field-meta.xml
<CustomField>
    <fullName>ProgramsApplied__c</fullName>
    <description>Used to store the list of programs applied for a household</description>
    <label>Programs Applied</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>BenefitPrograms</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/SSP_ApplicationIndividual__c.object-meta.xml
<CustomObject>
    <description>Custom junction object to maintain association between member and application</description>
    <label>SSP ApplicationIndividual</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>SSP_ApplicationIndividual Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SSP ApplicationIndividuals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/ProgramsApplied__c.field-meta.xml
<CustomField>
    <fullName>ProgramsApplied__c</fullName>
    <description>Different types of programs applied on an application for which this member is involved</description>
    <label>Application Programs Applied</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>BenefitPrograms</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/SSP_Application__c.field-meta.xml
<CustomField>
    <fullName>SSP_Application__c</fullName>
    <description>Indicates the application related to a member</description>
    <label>SSP_Application</label>
    <referenceTo>SSP_Application__c</referenceTo>
    <relationshipName>SSP_ApplicationIndividuals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/BenefitPrograms.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>MA</fullName>
        
        
        <label>Medicaid/KCHIP</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>KT</fullName>
        
        
        <label>KTAP (Cash Assistance)</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SN</fullName>
        
        
        <label>SNAP (Food Assistance)</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SS</fullName>
        
        
        <label>State Supplementation</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>DS</fullName>
        
        
        <label>DSNAP</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>CC</fullName>
        
        
        <label>Child Care Assistance</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>KP</fullName>
        
        
        <label>KI-HIPP (Health Insurance Premium Payments)</label>
        
    </customValue>
    
    <description>Different type of Benefit Programs available for a Citizen</description>
    
    <masterLabel>Benefit Programs</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/classes/SSP_IncomeSelectionScreenQueueRule.cls
/*
* classname     :  SSP_IncomeSelectionScreenQueueRule
* @description  :  Class for identifying whether to queue sspChangeExistingIncome screen for particular individual
* @author       :  Shrikant Raut   
* @date         :  03/09/2020
* MODIFICATION LOG:
* DEVELOPER                     DATE                               DESCRIPTION
* ---------------------------------------------------------------------------------------------

**/
public class SSP_IncomeSelectionScreenQueueRule extends BasicNavFlowRule{
 
    /**
* Invoked on workflow "next" action. If true is returned then the page will be marked as "required" in the
* current flow and so it will be queued to be loaded on its turn. If false is returned then the page
* will be marked as "not required" and hence will not be loaded in the flow.
*
* @param ctx Context object
* @param ctxData ContextData object
*
* @return boolean
*/
    public override boolean isRequired(Context ctx, ContextData ctxData){
        Boolean result = false;
        try{
            if(ctxData!=null && String.isNotBlank(ctxData.ApplicationId) && ctxData.queueObject != null && ctxData.modeValue != 'RAC'){ //Iron Dome fix
                 List<SSP_ApplicationIndividual__c> appIndividualList = ctxData.queueObject.applicationIndividualList != null ?
                     													ctxData.queueObject.applicationIndividualList : new List<SSP_ApplicationIndividual__c>();
                 if(!appIndividualList.isEmpty()){
                     String appPrograms= appIndividualList[0].ProgramsApplied__c;
                     List<String> programList = appPrograms.split(';');
                     Set<String> applicableProgList = SSP_GlobalConstants.SSP_INCOMESEL_MEMBERLEVEL_PROGRAMS;
                     result = SSP_Utility.checkApplicablePrograms(programList, applicableProgList);
                 }
                /*List<String> appLevelPrgList = new List<String>();
                Set<String> indvLevelPrgSet = new Set<String>();
                for(SSP_ApplicationIndividual__c appIndv : 
                    SSP_ApplicationIndividualSelector.queryApplicationIndividualData(
                        new Map<String, String>{SSP_GlobalConstants.SSP_OBJECT_NAME=>'SSP_ApplicationIndividual__c',SSP_GlobalConstants.SSP_OPERATOR=>'AND'}, 
                        new Set<String>{'Id',SSP_GlobalConstants.SSP_PROGRAMS_FIELD,'SSP_Application__r.'+SSP_GlobalConstants.SSP_PROGRAMS_FIELD}, 
                        new Map<String, String>{'SSP_Application__c'=>ctxData.ApplicationId})){
                            
                            if(appLevelPrgList.isEmpty()){
                           		appLevelPrgList = (appIndv.getSObject('SSP_Application__r') != null && appIndv.getSObject('SSP_Application__r').get(SSP_GlobalConstants.SSP_PROGRAMS_FIELD) != null) ? String.valueOf(appIndv.getSObject('SSP_Application__r').get(SSP_GlobalConstants.SSP_PROGRAMS_FIELD)).split(';') : appLevelPrgList;
                                if(appLevelPrgList != null && checkPrograms(new Set<String>(appLevelPrgList), SSP_GlobalConstants.SSP_APPLEVEL) ){
                                    result = true;
                                    break;
                                }
                            }
                            
                            List<String> indvPrgList = (appIndv.get(SSP_GlobalConstants.SSP_PROGRAMS_FIELD) != null ) ? String.valueOf(appIndv.get(SSP_GlobalConstants.SSP_PROGRAMS_FIELD)).split(';') : new List<String>();
                            indvLevelPrgSet.addAll(indvPrgList);
                        }
                if(indvLevelPrgSet != null && checkPrograms(indvLevelPrgSet, SSP_GlobalConstants.SSP_INDVLEVEL)){
                    result = true;
                }*/
            }
        }
        catch(Exception ex){            
            List<LOG_LogMessage__c> lstLogMessages = LOG_LogMessageUtility.logMessage(ex, 'SSP_IncomeSelectionScreenQueueRule', 'isRequired', ex.getMessage() , true);
        }
        return result;
    }
    
}