force-app/main/default/objects/LOG_LogMessage__c/LOG_LogMessage__c.object-meta.xml
<CustomObject>
    <description>Container for custom exception/log messages</description>
    <label>Log Message</label>
    <nameField>
        <displayFormat>LOG-{000000}</displayFormat>
        <label>Log Message #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_ApplicationIndividual__c/SSP_ApplicationIndividual__c.object-meta.xml
<CustomObject>
    <description>Custom junction object to maintain association between member and application</description>
    <label>SSP ApplicationIndividual</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>SSP_ApplicationIndividual Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SSP ApplicationIndividuals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/MedicaidType__c.field-meta.xml
<CustomField>
    <fullName>MedicaidType__c</fullName>
    <description>Used to store type of Medicaid Program - Magi/Non Magi</description>
    <label>Medicaid Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MAGI</fullName>
            </value>
            <value>
                <fullName>Non-MAGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/ProgramsApplied__c.field-meta.xml
<CustomField>
    <fullName>ProgramsApplied__c</fullName>
    <description>Different types of programs applied on an application for which this member is involved</description>
    <label>Application Programs Applied</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>BenefitPrograms</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/SSP_Member__c.field-meta.xml
<CustomField>
    <fullName>SSP_Member__c</fullName>
    <description>Indicates the member related to an application</description>
    <label>SSP_Member</label>
    <referenceTo>SSP_Member__c</referenceTo>
    <relationshipName>SSP_ApplicationIndividuals</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_Asset__c/SSP_Asset__c.object-meta.xml
<CustomObject>
    <description>Custom object to store details of Income, Expense, Resources, Employment Information.</description>
    <label>SSP Asset</label>
    <nameField>
        
        <displayFormat>A-{00000000}</displayFormat>
        
        <label>SSP_Asset Name</label>
        
        <type>AutoNumber</type>
        
    </nameField>
    <pluralLabel>SSP Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Asset__c/fields/ExpenseTypeCode__c.field-meta.xml
<CustomField>
    <fullName>ExpenseTypeCode__c</fullName>
    <description>This field is used to store Expense Type for an Asset</description>
    <label>Expense Type</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>ExpenseType</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Asset__c/fields/IsDeleted__c.field-meta.xml
<CustomField>
    <fullName>IsDeleted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to indicate whether the asset is deleted</description>
    <label>Is Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SSP_Asset__c/fields/SSP_Member__c.field-meta.xml
<CustomField>
    <fullName>SSP_Member__c</fullName>
    <description>This field is used to indicate a related member for an asset</description>
    <label>SSP_Member</label>
    <referenceTo>SSP_Member__c</referenceTo>
    <relationshipName>SSP_Assets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_Asset__c/recordTypes/Expense.recordType-meta.xml
<RecordType>
    <fullName>Expense</fullName>
    <active>true</active>
    <label>Expense</label>
</RecordType>

force-app/main/default/objects/SSP_Member__c/SSP_Member__c.object-meta.xml
<CustomObject>
    <description>Stores details about an individual member of a case/application such as gatepost reponse, incarceration, disability, living arrangement, pregnancy, address details. Also repurposed to store information of different individuals in the form of individual alien, alien sponsor, care taker,  care coordinator etc.</description>
    <label>SSP Member</label>
    <nameField>
        
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        
        <label>SSP_Member Name</label>
        
        <type>Text</type>
        
    </nameField>
    <pluralLabel>SSP Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/BenefitPrograms.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>MA</fullName>
        
        
        <label>Medicaid/KCHIP</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>KT</fullName>
        
        
        <label>KTAP (Cash Assistance)</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SN</fullName>
        
        
        <label>SNAP (Food Assistance)</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SS</fullName>
        
        
        <label>State Supplementation</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>DS</fullName>
        
        
        <label>DSNAP</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>CC</fullName>
        
        
        <label>Child Care Assistance</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>KP</fullName>
        
        
        <label>KI-HIPP (Health Insurance Premium Payments)</label>
        
    </customValue>
    
    <description>Different type of Benefit Programs available for a Citizen</description>
    
    <masterLabel>Benefit Programs</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/globalValueSets/ExpenseType.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>SE</fullName>
        
        
        <label>Shelter Expense</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>UE</fullName>
        
        
        <label>Utility Expense</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>EE</fullName>
        
        
        <label>Higher Education Expense</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>ME</fullName>
        
        
        <label>Medical Expense</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>CAE</fullName>
        
        
        <label>Child Support Expense</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>DCE</fullName>
        
        
        <label>Dependent Care Expense</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>DE</fullName>
        
        
        <label>Tax Deduction Expense</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>AL</fullName>
        
        
        <label>Alimony Expense</label>
        
    </customValue>
    
    <description>Different expense types</description>
    
    <masterLabel>Expense Type</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/classes/SSP_ExpenseDetailsQueueRule.cls
public with sharing class SSP_ExpenseDetailsQueueRule extends BasicNavFlowRule {
    public static final Id EXPENSERECORDTYPENAME = SSP_Utility.getRecrodTypeIdBySobjectAndDevName(SSP_GlobalConstants.ASSETOBJECTNAME, SSP_GlobalConstants.EXPENSERECORDTYPENAME);
    public override boolean isRequired(Context ctx, ContextData ctxData){
        Boolean result = false;
        try{
            /*if(ctxData.modeValue == 'RAC'){
                result = true;
            }
            else*/            
            if(ctxData!=null && String.isNotBlank(ctxData.MemberId)){ //Iron Dome Fix
                result = false;

                SSP_ApplicationIndividual__c appIndividualRecord = ctxData.queueObject.memberAppIndividualMap.get(ctxData.MemberId);
                List<String> lstAppPrograms = new List<String>();
                lstAppPrograms = appIndividualRecord != null ? appIndividualRecord.ProgramsApplied__c != null ? 
                                 appIndividualRecord.ProgramsApplied__c.split(';') : new List<String>() : new List<String>();
                if(lstAppPrograms.contains(SSP_GlobalConstants.MEDICAID) && appIndividualRecord.MedicaidType__c != null){
                    lstAppPrograms.add(appIndividualRecord.MedicaidType__c);
                }

                List<SSP_Asset__c> lstAssetReceived = ctxData.queueObject.mapMemberAsset != null ? ctxData.queueObject.mapMemberAsset.containsKey(ctxData.MemberId) ?
                    									ctxData.queueObject.mapMemberAsset.get(ctxData.MemberId) != null ? ctxData.queueObject.mapMemberAsset.get(ctxData.MemberId):
                    									new List<SSP_Asset__c>() : new List<SSP_Asset__c>(): new List<SSP_Asset__c>();
                List<String> lstExpenseBasedPrograms = SSP_ExpenseController.getApplicableExpensesBasedOnPrograms(lstAppPrograms);
                for(SSP_Asset__c exp : lstAssetReceived){
                    if(exp != null && exp.RecordTypeId == EXPENSERECORDTYPENAME && !exp.IsDeleted__c && lstExpenseBasedPrograms.contains(exp.ExpenseTypeCode__c) ){
                        result = true;
                        break;
                    }
                }
                /*for(SSP_Asset__c expense :
                    SSP_AssetSelector.queryAssetData(new Map<String, String>{'objectName'=>'SSP_Asset__c','operator'=>'AND'}, 
                                                     new Set<String>{'Id', 'IsDeleted__c'}, 
                                                     new Map<String, String>{'limit'=>'1000','SSP_Member__c'=> ctxData.MemberId, 'RecordType.DeveloperName'=>'Expense'})){
                                                         if(expense != null && !expense.IsDeleted__c){
                                                             result = true;
                                                             break;
                                                         }
                                                     }*/                
            }
        }
        catch(Exception ex){            
            List<LOG_LogMessage__c> lstLogMessages = LOG_LogMessageUtility.logMessage(ex, 'SSP_ExpenseDetailsQueueRule', 'isRequired', ex.getMessage() , true);
        }
        return result;
    }
}