force-app/main/default/objects/SSP_Asset__c/SSP_Asset__c.object-meta.xml
<CustomObject>
    <description>Custom object to store details of Income, Expense, Resources, Employment Information.</description>
    <label>SSP Asset</label>
    <nameField>
        
        <displayFormat>A-{00000000}</displayFormat>
        
        <label>SSP_Asset Name</label>
        
        <type>AutoNumber</type>
        
    </nameField>
    <pluralLabel>SSP Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Asset__c/fields/ActivityStartDate__c.field-meta.xml
<CustomField>
    <fullName>ActivityStartDate__c</fullName>
    <description>Used to store Activity Start Date</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Activity Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SSP_Asset__c/fields/ActivityType__c.field-meta.xml
<CustomField>
    <fullName>ActivityType__c</fullName>
    <description>Used to store Employment Activity Type</description>
    <label>Activity Type</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>EmploymentActivityType</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Asset__c/fields/BooksAmount__c.field-meta.xml
<CustomField>
    <fullName>BooksAmount__c</fullName>
    <description>Used to store the amount used to buy Books</description>
    <label>Books Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SSP_Asset__c/fields/BusinessTitle__c.field-meta.xml
<CustomField>
    <fullName>BusinessTitle__c</fullName>
    <description>This field is used to store Work Description for an asset</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Work Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Asset__c/fields/BusinessTypeCode__c.field-meta.xml
<CustomField>
    <fullName>BusinessTypeCode__c</fullName>
    <description>Used to store different types of Business</description>
    <label>Business Type Code</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>BusinessType</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Asset__c/fields/ChildName__c.field-meta.xml
<CustomField>
    <fullName>ChildName__c</fullName>
    <description>Used to store child Name</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Child Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Asset__c/fields/DependentCareProvider__c.field-meta.xml
<CustomField>
    <fullName>DependentCareProvider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to indicate dependent care provider for an Asset</description>
    <label>Dependent Care Provider</label>
    <referenceTo>SSP_Member__c</referenceTo>
    <relationshipName>SSPMemberDCP</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SSP_Asset__c/fields/DependentIndividual__c.field-meta.xml
<CustomField>
    <fullName>DependentIndividual__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to indicate dependent individual for an Asset</description>
    <label>Dependent Care for</label>
    <referenceTo>SSP_Member__c</referenceTo>
    <relationshipName>SSPMemberDI</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SSP_Asset__c/fields/EIN__c.field-meta.xml
<CustomField>
    <fullName>EIN__c</fullName>
    <description>This field is used to store EIN for a member on a particular asset</description>
    <label>Employer Identification Number (EIN)</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SSP_Asset__c/fields/EmployerAddress__c.field-meta.xml
<CustomField>
    <fullName>EmployerAddress__c</fullName>
    <description>This field is used to store Employer Address</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Employer Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Asset__c/fields/EmployerAddressLine2__c.field-meta.xml
<CustomField>
    <fullName>EmployerAddressLine2__c</fullName>
    <description>This field is used to store employer address line 2</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Employer Address Line2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Asset__c/fields/EmployerName__c.field-meta.xml
<CustomField>
    <fullName>EmployerName__c</fullName>
    <description>This field is used to store Employer Name of Citizen</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Employer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Asset__c/fields/EmploymentEndReason__c.field-meta.xml
<CustomField>
    <fullName>EmploymentEndReason__c</fullName>
    <description>This field is used to store the employment end Reason for an Asset</description>
    <label>Employment End Reason</label>
    <type>Picklist</type>
    <valueSet>
        
            <controllingField>IncomeTypeCode__c</controllingField>
        
            <restricted>true</restricted>
        
            <valueSetName>EmploymentEndReason</valueSetName>
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Asset__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <description>This field is used to store Asset End Date</description>
    <encryptionScheme>None</encryptionScheme>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SSP_Asset__c/fields/ExpenseAmount__c.field-meta.xml
<CustomField>
    <fullName>ExpenseAmount__c</fullName>
    <description>This field is used to store Expense Amount for an Asset</description>
    <label>Expense Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SSP_Asset__c/fields/ExpenseFrequencyCode__c.field-meta.xml
<CustomField>
    <fullName>ExpenseFrequencyCode__c</fullName>
    <description>This field is used to store Expense Frequency code for an Asset</description>
    <label>Expense Frequency</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>PayFrequency</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Asset__c/fields/ExpensesAmount__c.field-meta.xml
<CustomField>
    <fullName>ExpensesAmount__c</fullName>
    <description>This field is used to store Expenses Amount code for an Asset</description>
    <label>Expenses Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SSP_Asset__c/fields/ExpenseSubType__c.field-meta.xml
<CustomField>
    <fullName>ExpenseSubType__c</fullName>
    <description>This field is used to store Expense Sub type for an Asset</description>
    <label>Expense Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        
            <controllingField>ExpenseTypeCode__c</controllingField>
        
            <restricted>true</restricted>
        
            <valueSetName>ExpenseSubType</valueSetName>
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Asset__c/fields/FeesAmount__c.field-meta.xml
<CustomField>
    <fullName>FeesAmount__c</fullName>
    <description>This field is used to store Fees amount for an Asset</description>
    <label>Fees Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SSP_Asset__c/fields/IncomePayDetailHoursPerWeek__c.field-meta.xml
<CustomField>
    <fullName>IncomePayDetailHoursPerWeek__c</fullName>
    <description>This field is used to indicate income pay detail hours per week</description>
    <label>Income Pay Detail Hrs Per Week</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SSP_Asset__c/fields/IncomePayFrequency__c.field-meta.xml
<CustomField>
    <fullName>IncomePayFrequency__c</fullName>
    <description>This field is used to store the income pay frequency for an asset</description>
    <label>Income Pay Frequency</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>PayFrequency</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Asset__c/fields/IncomeSubtypeCode__c.field-meta.xml
<CustomField>
    <fullName>IncomeSubtypeCode__c</fullName>
    <description>This field is used to store the income sub type for an asset</description>
    <label>Income Subtype</label>
    <type>Picklist</type>
    <valueSet>
        
            <controllingField>IncomeTypeCode__c</controllingField>
        
            <restricted>true</restricted>
        
            <valueSetName>IncomeSubType</valueSetName>
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Asset__c/fields/IncomeTypeCode__c.field-meta.xml
<CustomField>
    <fullName>IncomeTypeCode__c</fullName>
    <description>This field is used to store the income type for an asset</description>
    <label>Income Type</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>IncomeType</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Asset__c/fields/MiscellaneousAmount__c.field-meta.xml
<CustomField>
    <fullName>MiscellaneousAmount__c</fullName>
    <description>This field is used to store miscellaneous amount</description>
    <label>Miscellaneous Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SSP_Asset__c/fields/PrimaryPhoneExtension__c.field-meta.xml
<CustomField>
    <fullName>PrimaryPhoneExtension__c</fullName>
    <description>primary phone number extension</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Primary Phone Extension</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Asset__c/fields/PrimaryPhoneNumber__c.field-meta.xml
<CustomField>
    <fullName>PrimaryPhoneNumber__c</fullName>
    <description>Primary phone number details</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Primary Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/SSP_Asset__c/fields/SSP_Member__c.field-meta.xml
<CustomField>
    <fullName>SSP_Member__c</fullName>
    <description>This field is used to indicate a related member for an asset</description>
    <label>SSP_Member</label>
    <referenceTo>SSP_Member__c</referenceTo>
    <relationshipName>SSP_Assets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_Asset__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <description>This field is used to store start date for an asset</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SSP_Asset__c/fields/Tips__c.field-meta.xml
<CustomField>
    <fullName>Tips__c</fullName>
    <description>This field is used to store tips on an asset</description>
    <label>Tips</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SSP_Asset__c/fields/TotalGrossAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalGrossAmount__c</fullName>
    <description>This field is used to store total gross amount on an asset</description>
    <label>Total Gross Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SSP_Asset__c/fields/TuitionAmount__c.field-meta.xml
<CustomField>
    <fullName>TuitionAmount__c</fullName>
    <description>This field is used to store tuition amount on an asset</description>
    <label>Tuition Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/SSP_Member__c.object-meta.xml
<CustomObject>
    <description>Stores details about an individual member of a case/application such as gatepost reponse, incarceration, disability, living arrangement, pregnancy, address details. Also repurposed to store information of different individuals in the form of individual alien, alien sponsor, care taker,  care coordinator etc.</description>
    <label>SSP Member</label>
    <nameField>
        
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        
        <label>SSP_Member Name</label>
        
        <type>Text</type>
        
    </nameField>
    <pluralLabel>SSP Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Member__c/fields/PrimaryPhoneExtension__c.field-meta.xml
<CustomField>
    <fullName>PrimaryPhoneExtension__c</fullName>
    <description>This field is used to store primary phone extension of a member</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Primary Phone Extension</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/PrimaryPhoneNumber__c.field-meta.xml
<CustomField>
    <fullName>PrimaryPhoneNumber__c</fullName>
    <description>This field is used to store primary phone number of a member</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Primary Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/globalValueSets/BusinessType.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>SF</fullName>
        
        
        <label>Farming</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>IA</fullName>
        
        
        <label>Illegal Activities</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SE</fullName>
        
        
        <label>Other Self Employment</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>RE</fullName>
        
        
        <label>Rental</label>
        
    </customValue>
    
    <description>Different Business Types</description>
    
    <masterLabel>Business Type</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/globalValueSets/EmploymentActivityType.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>PC</fullName>
        
        
        <label>Practicum</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>CL</fullName>
        
        
        <label>Clinical</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>ST</fullName>
        
        
        <label>Student Teaching</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>IT</fullName>
        
        
        <label>Internship</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>JT</fullName>
        
        
        <label>Job Training</label>
        
    </customValue>
    
    <description>Employment Activity Types</description>
    
    <masterLabel>Employment Activity Type</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/globalValueSets/IncomeType.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>DIR</fullName>
        
        
        <label>Dividends, Interest &amp; Royalties</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>IS</fullName>
        
        
        <label>Insurance Settlements &amp; Benefits Income</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>EA</fullName>
        
        
        <label>Job income from employer</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>OUI</fullName>
        
        
        <label>Other Goods, Payments, &amp; Services</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SE</fullName>
        
        
        <label>Self employment income</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SRP</fullName>
        
        
        <label>Social Security, Retirement, &amp; Pension</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SM</fullName>
        
        
        <label>Support &amp; Maintenance Income</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>UI</fullName>
        
        
        <label>Unpaid income</label>
        
    </customValue>
    
    <description>Income Types</description>
    
    <masterLabel>Income Type</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/globalValueSets/PayFrequency.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>BW</fullName>
        
        
        <label>Every 2 weeks</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>MO</fullName>
        
        
        <label>Monthly</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>QU</fullName>
        
        
        <label>Quarterly</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SM</fullName>
        
        
        <label>Twice a month</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>WE</fullName>
        
        
        <label>Weekly</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>YR</fullName>
        
        
        <label>Yearly</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>HO</fullName>
        
        
        <label>Hourly</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>DA</fullName>
        
        
        <label>Daily</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>IR</fullName>
        
        
        <label>Irregular</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SP</fullName>
        
        
        <label>Contractual/Single Payment Covering More than One Month</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>ON</fullName>
        
        
        <label>One Time Only - Lump sum</label>
        
    </customValue>
    
    <description>Frequency</description>
    
    <masterLabel>PayFrequency</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/classes/SSP_AssetSelector.cls
/*
* classname     :  SSP_AssetSelector
* @description  :  Selector class for SSP_Asset__c
* @author       :  Shrikant Raut   
* @date         :  11/14/2019
* MODIFICATION LOG:
* DEVELOPER                     DATE                               DESCRIPTION
* ---------------------------------------------------------------------------------------------*/
public class SSP_AssetSelector {

    /***************************************************************************************************
    * @author       Shrikant Raut
    * @date         11/14/2019
    * @methodname   queryAssetData
    * @description  This methods is to query records related to SSP_Asset__c object
    * @return       List<SSP_Asset__c>
    *****************************************************************************************************/ 
    public static List<SSP_Asset__c> queryAssetData(Map<String, String> mapDetails, Set<String> setFields, Map<String, String> mapConditions){
        List<SSP_Asset__c> lstAssets = new List<SSP_Asset__c>();
        lstAssets = (List<SSP_Asset__c>)SSP_Utility.fetchRecords(mapDetails, setFields, mapConditions);
        return lstAssets;
    }
    
    public static List<SSP_Asset__c> getDuplicateEmployerIncomeDetails(SSP_Asset__c objAsset){
        List<SSP_Asset__c> lstAssets = new List<SSP_Asset__c>();
        lstAssets = [SELECT Id, SSP_Member__c, EmployerName__c, EIN__c, EmployerAddress__c, EmployerAddressLine2__c,
                     BusinessTitle__c, ActivityType__c, IncomeTypeCode__c,
                     IncomeSubtypeCode__c, TotalGrossAmount__c, Tips__c, IncomePayDetailHoursPerWeek__c,
                     ExpenseAmount__c, ActivityStartDate__c, StartDate__c, EndDate__c, SSP_Member__r.PrimaryPhoneNumber__c,
                     SSP_Member__r.PrimaryPhoneExtension__c,BusinessTypeCode__c,toLabel(IncomePayFrequency__c) FROM SSP_Asset__c WHERE SSP_Member__c =:objAsset.SSP_Member__c AND EmployerName__c =:objAsset.EmployerName__c
                     AND TotalGrossAmount__c =:objAsset.TotalGrossAmount__c AND IncomePayFrequency__c = :objAsset.IncomePayFrequency__c];
        
        return lstAssets;
    }
    public static String getExpenseDetailsWithId(String sId){
        String sObjExpense = '';
        List<SSP_Asset__c> lstAssets = new List<SSP_Asset__c>();
        lstAssets = [SELECT Id, SSP_Member__c, ExpenseSubType__c,StartDate__c,EndDate__c,TuitionAmount__c,BooksAmount__c,FeesAmount__c,MiscellaneousAmount__c,
                     ExpenseFrequencyCode__c,ExpensesAmount__c,ChildName__c,DependentCareProvider__c,DependentCareProvider__r.name,DependentIndividual__c 
                     FROM SSP_Asset__c WHERE 
                     Id =:sId];
        if(!lstAssets.isEmpty()){
            sObjExpense = JSON.serialize(lstAssets[0]);
        }
        
        return sObjExpense;
    }
     public static String fetchExistingIncomeDetails(String sMemberId){
        String sObjExpense = '';
        List<SSP_Asset__c> lstAssets = new List<SSP_Asset__c>();
        lstAssets = [SELECT Id, SSP_Member__c, ExpenseSubType__c,StartDate__c,EndDate__c,TuitionAmount__c,BooksAmount__c,FeesAmount__c,MiscellaneousAmount__c,
                     ExpenseFrequencyCode__c,ExpensesAmount__c,ChildName__c,DependentCareProvider__c,DependentCareProvider__r.name,DependentIndividual__c,EmploymentEndReason__c 
                     FROM SSP_Asset__c WHERE 
                     SSP_Member__c =:sMemberId  AND EmploymentEndReason__c = null and EndDate__c= null];
        if(!lstAssets.isEmpty()){
            sObjExpense = JSON.serialize(lstAssets);
        }
        
        return sObjExpense;
    }
}