force-app/main/default/objects/SSP_Asset__c/SSP_Asset__c.object-meta.xml
<CustomObject>
    <description>Custom object to store details of Income, Expense, Resources, Employment Information.</description>
    <label>SSP Asset</label>
    <nameField>
        
        <displayFormat>A-{00000000}</displayFormat>
        
        <label>SSP_Asset Name</label>
        
        <type>AutoNumber</type>
        
    </nameField>
    <pluralLabel>SSP Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Asset__c/fields/ResourceTypeCode__c.field-meta.xml
<CustomField>
    <fullName>ResourceTypeCode__c</fullName>
    <description>This field is used to store resource type for an asset</description>
    <label>Resource Type</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>ResourceType</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Asset__c/fields/SSP_Member__c.field-meta.xml
<CustomField>
    <fullName>SSP_Member__c</fullName>
    <description>This field is used to indicate a related member for an asset</description>
    <label>SSP_Member</label>
    <referenceTo>SSP_Member__c</referenceTo>
    <relationshipName>SSP_Assets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_Asset__c/recordTypes/Resource.recordType-meta.xml
<RecordType>
    <fullName>Resource</fullName>
    <active>true</active>
    <label>SSPResource</label>
</RecordType>

force-app/main/default/objects/SSP_Member__c/SSP_Member__c.object-meta.xml
<CustomObject>
    <description>Stores details about an individual member of a case/application such as gatepost reponse, incarceration, disability, living arrangement, pregnancy, address details. Also repurposed to store information of different individuals in the form of individual alien, alien sponsor, care taker,  care coordinator etc.</description>
    <label>SSP Member</label>
    <nameField>
        
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        
        <label>SSP_Member Name</label>
        
        <type>Text</type>
        
    </nameField>
    <pluralLabel>SSP Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_ResourceMappings__mdt/SSP_ResourceMappings__mdt.object-meta.xml
<CustomObject>
    <label>SSP Resource Mapping</label>
    <pluralLabel>SSP Resource Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/SSP_ResourceMappings__mdt/fields/SobjectField__c.field-meta.xml
<CustomField>
    <fullName>SobjectField__c</fullName>
    <description>Member field mapping for a particular resource</description>
    <label>SObject Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/ResourceType.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>OR</fullName>
        
        
        <label>Other Liquid Resource</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>AC</fullName>
        
        
        <label>Account</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>AN</fullName>
        
        
        <label>Annuity</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>BF</fullName>
        
        
        <label>Burial Funds</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>BP</fullName>
        
        
        <label>Burial Plot</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>IN</fullName>
        
        
        <label>Investment</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>LE</fullName>
        
        
        <label>Life Estate</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>LI</fullName>
        
        
        <label>Life Insurance</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>LSC</fullName>
        
        
        <label>Life Settlement Contract</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>LTC</fullName>
        
        
        <label>Lifetime Care Agreement</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>OT</fullName>
        
        
        <label>Other Resource</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>PQ</fullName>
        
        
        <label>Partnership Qualified LTC Policy</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>FA</fullName>
        
        
        <label>Pre Arranged Funeral Contract</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>PN</fullName>
        
        
        <label>Promissory Note or Land Contract</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>RP</fullName>
        
        
        <label>Real Estate Property</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>TR</fullName>
        
        
        <label>Trust</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>VI</fullName>
        
        
        <label>Vehicle</label>
        
    </customValue>
    
    <description>Resource Types</description>
    
    <masterLabel>Resource Type</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/classes/SSP_ExistResourcesController.cls
/**
* @author: Karthik Gulla
* @Class Name: SSP_ExistResourcesController
* @desc This class is used as a controller to call ResourcesService for existing resources functionalities
* @Date 11-15-2019
MODIFICATION LOG :
* */ 
public with sharing class SSP_ExistResourcesController {
    public static Map<String,SSP_ResourceMappings__mdt> mapResourceTypeMappings;
    /**
    * @author: Karthik Gulla
    * @method: getExistingResourcesForChangeOrRemoval
    * @desc This method is used to get existing resource details for removal
    * @params {Map<String,String> mapInputs}
    * @return SSP_LightningResponse
    * */
    @AuraEnabled
    public static SSP_LightningResponse getExistingResourcesForChangeOrRemoval(Map<String,String> mapInputs, List<String> lstAppPrograms){
        SSP_LightningResponse clsLightningResponse = new SSP_LightningResponse();
        Set<Id> setMemberIds = new Set<Id>();
        try{
            String strMemberId = mapInputs.get(SSP_GlobalConstants.MEMBERID) != null ? mapInputs.get(SSP_GlobalConstants.MEMBERID) : ''; 
            setMemberIds.add(strMemberId);
            List<SSP_ResourcesWrapper> lstExistResources = new List<SSP_ResourcesWrapper>();
            List<SSP_Asset__c> lstExistResourceRecords = SSP_ResourcesService.getResourcesForMember(setMemberIds, true, SSP_ResourcesService.getApplicableResourcesBasedOnPrograms(lstAppPrograms));
            if(!lstExistResourceRecords.isEmpty()){
                for(SSP_Asset__c sspAssetResource : lstExistResourceRecords){
                    lstExistResources.add(SSP_ResourcesService.buildResourcesWrapper(sspAssetResource));
                }
            }
            clsLightningResponse = SSP_ResourcesService.buildResponse(SSP_GlobalConstants.EXISTINGRESOURCES, JSON.serializePretty(lstExistResources));
            clsLightningResponse.put('timeTravelDate', SSP_Utility.today());
        }catch(Exception e){
            LOG_LogMessageUtility.logMessage(e, 'SSP_ExistResourcesController', 'getExistingResourcesForChangeOrRemoval', e.getMessage(), true);
            clsLightningResponse.bIsSuccess = false;
        }
        return clsLightningResponse;
    }

     /**
    * @author: Karthik Gulla
    * @method: updateExistingResources
    * @desc This method is used to get update existing resource details
    * @params {String sUpdatedValues}
    * @return SSP_LightningResponse
    * */
    @AuraEnabled
    public static SSP_LightningResponse updateExistingResources(String sUpdatedValues, String sMemberId){
        SSP_Utility.isAuthenticatedUser();
        SSP_LightningResponse clsLightningResponse = new SSP_LightningResponse();
        Set<Id> setResourceIds = new Set<Id>();
        try{
            Set<String> setAccessFields = new Set<String>();
            List<SSP_Asset__c> lstToBeUpdatedAssets = (List<SSP_Asset__c>) JSON.deserialize(sUpdatedValues, List<SSP_Asset__c>.class);
            if(!lstToBeUpdatedAssets.isEmpty()){
                for(SSP_Asset__c sspAssetRecord : lstToBeUpdatedAssets){
                    setAccessFields.addAll(SSP_Utility.getFieldsNamesObject(sspAssetRecord));
                    setResourceIds.add(sspAssetRecord.Id);
                }
                //ESAPI.accessController().updateAsUser(new Map<ID,SSP_Asset__c>(lstToBeUpdatedAssets), new List<String>(setAccessFields));
                //Perf Fix:08/29 : SV
                SSP_GenericDMLHelper.updateRecords(lstToBeUpdatedAssets,  new List<String>(setAccessFields));

            }
            if(!setResourceIds.isEmpty() && sMemberId != null && sMemberId != ''){
                SSP_ExistResourcesController.updateGatepostQuestions(setResourceIds, sMemberId);
            }
            clsLightningResponse.bIsSuccess = true;
        }catch(Exception e){
            LOG_LogMessageUtility.logMessage(e, 'SSP_ExistResourcesController', 'updateExistingResources', e.getMessage(), true);
            clsLightningResponse.bIsSuccess = false;
        }
        return clsLightningResponse;
    }

     /**
    * @author: Karthik Gulla
    * @method: updateGatepostQuestions
    * @desc This method is used to get gatepost questions to No if it is the last resource type which is deleted
    * @params {String sUpdatedValues}
    * @return SSP_LightningResponse
    * */
    public static SSP_LightningResponse updateGatepostQuestions(Set<Id> setResourceIds, String sMemberId){
        SSP_LightningResponse clsLightningResponse = new SSP_LightningResponse();
        List<SSP_Asset__c> lstAssets = new List<SSP_Asset__c>();
        Set<Id> setMemberIds = new Set<Id>();
        Map<String,Integer> mapResourceTypeCount = new Map<String,Integer>();
        Set<String> setAccessFields = new Set<String>();
        Set<String> setExistResources = new Set<String>();
        Map<Boolean,List<SSP_Asset__c>> mapDataExistToListAssets = new Map<Boolean,List<SSP_Asset__c>>();
        try{
            setMemberIds.add(sMemberId);
            mapResourceTypeMappings = SSP_ResourcesService.getStaticResourceDetailsTypeMappings();
            mapDataExistToListAssets = SSP_ResourcesService.getResourcesForMember(setMemberIds, new List<String>());
            if(mapDataExistToListAssets != null && mapDataExistToListAssets.size()>0 && mapDataExistToListAssets.containsKey(true)){
                lstAssets = mapDataExistToListAssets.get(true);
            } else if(mapDataExistToListAssets != null && mapDataExistToListAssets.size()>0 && mapDataExistToListAssets.containsKey(false)) {
                lstAssets.addAll(mapDataExistToListAssets.get(false));
            }

            for(SSP_Asset__c sspAssetResource : lstAssets){
                setExistResources.add(sspAssetResource.ResourceTypeCode__c);
            }

            SSP_Member__c sspMemberRecord = new SSP_Member__c();
            sspMemberRecord.Id = sMemberId;            
            for(SSP_Asset__c sspAsset : SSP_ResourcesService.getResourceDetails(setResourceIds)){
                if(!setExistResources.contains(sspAsset.ResourceTypeCode__c)){
                    sspMemberRecord.put(mapResourceTypeMappings.get(sspAsset.ResourceTypeCode__c).SobjectField__c, SSP_GlobalConstants.NO);
                }
            }
            setAccessFields.addAll(SSP_Utility.getFieldsNamesObject(sspMemberRecord));
            if(!new List<String>(setAccessFields).isEmpty()){
                ESAPI.accessController().updateAsUser(sspMemberRecord, new List<String>(setAccessFields));
            }              
            clsLightningResponse.bIsSuccess = true;
        }catch(Exception e){
            LOG_LogMessageUtility.logMessage(e, 'SSP_ExistResourcesController', 'updateGatepostQuestions', e.getMessage(), true);
            clsLightningResponse.bIsSuccess = false;
        }
        return clsLightningResponse;
    }
}