force-app/main/default/objects/AppConfig__c/AppConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom setting to store app configuration data for SSP.</description>
    <label>App Config</label>
</CustomObject>

force-app/main/default/objects/CommunicationLog__c/CommunicationLog__c.object-meta.xml
<CustomObject>
    <description>Central object to send communications</description>
    <label>Communication Nub</label>
    <nameField>
        <displayFormat>CL-{0000}</displayFormat>
        <label>Communication Nub Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Communication Nub</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CommunicationLog__c/fields/EmailSubject__c.field-meta.xml
<CustomField>
    <fullName>EmailSubject__c</fullName>
    <label>Email Subject</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/CommunicationLog__c/fields/processed_reminder_batch__c.field-meta.xml
<CustomField>
    <fullName>processed_reminder_batch__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>to check if the record was created via application reminder batch and is processed only once</inlineHelpText>
    <label>processed_reminder_batch</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CommunicationLog__c/fields/Recipient_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Recipient_Phone_Number__c</fullName>
    <description>Recipient Phone Number</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Recipient Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/CommunicationLog__c/fields/Send_SMS__c.field-meta.xml
<CustomField>
    <fullName>Send_SMS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send SMS ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CommunicationLog__c/fields/SendersName__c.field-meta.xml
<CustomField>
    <fullName>SendersName__c</fullName>
    <label>Sender&apos;s Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CommunicationLog__c/fields/SendersPhone__c.field-meta.xml
<CustomField>
    <fullName>SendersPhone__c</fullName>
    <label>Sender&apos;s Phone</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CommunicationLog__c/fields/SendMail__c.field-meta.xml
<CustomField>
    <fullName>SendMail__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Field created to decide if the mail should be sent or not.</description>
    <label>Send Mail ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CommunicationLog__c/fields/SentDateTime__c.field-meta.xml
<CustomField>
    <fullName>SentDateTime__c</fullName>
    <label>Sent (Date/Time)</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CommunicationLog__c/fields/SMSReceivers__c.field-meta.xml
<CustomField>
    <fullName>SMSReceivers__c</fullName>
    <label>SMS Receivers</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CommunicationLog__c/fields/SourceSystem__c.field-meta.xml
<CustomField>
    <fullName>SourceSystem__c</fullName>
    <label>SourceSystem</label>
    <type>Picklist</type>
    <valueSet>
        
            <valueSetDefinition>
            
            
                <value>
                
                    <fullName>SSP</fullName>
                
                    <default>true</default>
                
                    <label>SSP</label>
                
                </value>
            
                <value>
                
                    <fullName>RE</fullName>
                
                
                    <label>RE</label>
                
                </value>
            
            </valueSetDefinition>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/CommunicationLog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetDefinition>
            
            
                <value>
                
                    <fullName>Completed</fullName>
                
                
                    <label>Completed</label>
                
                </value>
            
                <value>
                
                    <fullName>Failed</fullName>
                
                
                    <label>Failed</label>
                
                </value>
            
                <value>
                
                    <fullName>In Queue</fullName>
                
                
                    <label>In Queue</label>
                
                </value>
            
                <value>
                
                    <fullName>In Progress</fullName>
                
                
                    <label>In Progress</label>
                
                </value>
            
            </valueSetDefinition>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/CommunicationLog__c/fields/TemplateBody__c.field-meta.xml
<CustomField>
    <fullName>TemplateBody__c</fullName>
    <label>Template Body</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/CommunicationLog__c/fields/TemplateId__c.field-meta.xml
<CustomField>
    <fullName>TemplateId__c</fullName>
    <label>Template Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CommunicationLog__c/fields/TemplateName__c.field-meta.xml
<CustomField>
    <fullName>TemplateName__c</fullName>
    <label>Template Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CommunicationLog__c/fields/TriggeredRecordId__c.field-meta.xml
<CustomField>
    <fullName>TriggeredRecordId__c</fullName>
    <label>Triggered Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CommunicationLog__c/fields/TriggeredRecordName__c.field-meta.xml
<CustomField>
    <fullName>TriggeredRecordName__c</fullName>
    <label>Triggered Record Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LOG_LogMessage__c/LOG_LogMessage__c.object-meta.xml
<CustomObject>
    <description>Container for custom exception/log messages</description>
    <label>Log Message</label>
    <nameField>
        <displayFormat>LOG-{000000}</displayFormat>
        <label>Log Message #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/REIntegrationEndpoints__c/REIntegrationEndpoints__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom setting to store Integration End Point</description>
    <label>RE Integration Endpoints</label>
</CustomObject>

force-app/main/default/objects/REIntegrationEndpoints__c/fields/Client_Id__c.field-meta.xml
<CustomField>
    <fullName>Client_Id__c</fullName>
    <description>Captures the Client Id</description>
    <label>Client Id</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/REIntegrationEndpoints__c/fields/Client_Secret__c.field-meta.xml
<CustomField>
    <fullName>Client_Secret__c</fullName>
    <description>This field is used to capture the Client Secret</description>
    <label>Client Secret</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/SSP_TransactionalAPI.cls
public class SSP_TransactionalAPI implements Queueable, Database.AllowsCallouts{
    public SSP_TransactionalAPI() {

    }

    private String jsonData;
    public SSP_TransactionalAPI(String payload) {
        this.jsonData = payload;
    }
    //Method to perform a callout and return an httpResponse
    @InvocableMethod
    public static void sendComList(List < CommunicationLog__c > comList) {
        try {
            AppConfig__c config = AppConfig__c.getInstance('SFMC_DEFAULT_EMAIL');
            if(comList != null) {
                List<String> recipients = new List<String>();
                string payload = '{'+
                                    '"definitionKey":"CommNubRealTimeSending",'+
                                    '"recipients":[';
                for(Integer i = 0; i < comList.size(); i++) {
                    CommunicationLog__c comLog = comList[i];
                    string name;
                    string email_subject;
                    string created_by;
                    string email_template;
                    string external_id;
                    string from_email;
                    string last_modified_by;
                    string owner_id;
                    Boolean processed_reminder;
                    string recipient_phone;
                    Boolean send_mail;
                    Boolean send_sms = false;
                    string senders_name;
                    string senders_phone;
                    Datetime sent_date_time;
                    string sms_receivers;
                    string source_system;
                    string status;
                    string template_body;
                    string template_id;
                    string template_name;
                    string to_email;
                    string triggered_record_id;
                    string triggered_record_name;
                
                    if (String.isBlank(comLog.Name)) name = ''; else name = comLog.Name;
                    if (String.isBlank(comLog.EmailSubject__c)) email_subject = ''; else email_subject = comLog.EmailSubject__c;
                    if (String.isBlank(comLog.CreatedById)) created_by = ''; else created_by = comLog.CreatedById;
                    if (String.isBlank(comLog.Email_Template_Name__c)) email_template = ''; else email_template = comLog.Email_Template_Name__c;
                    if (String.isBlank(comLog.ExternalId__c)) external_id = ''; else external_id = comLog.ExternalId__c;
                    if (String.isBlank(comLog.FromEmail__c)) from_email = ''; else from_email = comLog.FromEmail__c;
                    if (String.isBlank(comLog.LastModifiedById)) last_modified_by = ''; else last_modified_by = comLog.LastModifiedById;
                    if (String.isBlank(comLog.OwnerId)) owner_id = ''; else owner_id = comLog.OwnerId;
                    if (comLog.processed_reminder_batch__c == null) processed_reminder = false; else processed_reminder = comLog.processed_reminder_batch__c;
                    if (String.isBlank(comLog.Recipient_Phone_Number__c)) recipient_phone = ''; else recipient_phone = comLog.Recipient_Phone_Number__c;
                    if (comLog.SendMail__c == null) send_mail = false; else send_mail = comLog.SendMail__c;
                    if (comLog.Send_SMS__c == null) send_sms = false; else send_sms = comLog.Send_SMS__c;
                    if (String.isBlank(comLog.SendersName__c)) senders_name = ''; else senders_name = comLog.SendersName__c;
                    if (String.isBlank(comLog.SendersPhone__c)) senders_phone = ''; else senders_phone = comLog.SendersPhone__c;
                    if (comLog.SentDateTime__c == null) sent_date_time = null; else sent_date_time = comLog.SentDateTime__c;
                    if (String.isBlank(comLog.SMSReceivers__c)) sms_receivers = ''; else sms_receivers = comLog.SMSReceivers__c;
                    if (String.isBlank(comLog.SourceSystem__c)) source_system = ''; else source_system = comLog.SourceSystem__c;
                    if (String.isBlank(comLog.Status__c)) status = ''; else status = comLog.Status__c;
                    if (String.isBlank(comLog.TemplateBody__c)) template_body = ''; else template_body = comLog.TemplateBody__c;
                    if (String.isBlank(comLog.TemplateId__c)) template_id = ''; else template_id = comLog.TemplateId__c;
                    if (String.isBlank(comLog.TemplateName__c)) template_name = ''; else template_name = comLog.TemplateName__c;
                    if (String.isBlank(comLog.ToEmail__c)) to_email = ''; else to_email = comLog.ToEmail__c;
                    if (String.isBlank(comLog.TriggeredRecordId__c)) triggered_record_id = ''; else triggered_record_id = comLog.TriggeredRecordId__c;
                    if (String.isBlank(comLog.TriggeredRecordName__c)) triggered_record_name = ''; else triggered_record_name = comLog.TriggeredRecordName__c;
                    
                    // correct formatting for template_body

                    string template_body_modified =    template_body.replace('\"','\\"') ;                          
                    
                    // replace newline of apex
                    template_body_modified = template_body_modified.replace('\r\n','<br/>');
                    template_body_modified = template_body_modified.replace('\n','<br/>');
                    template_body_modified = template_body_modified.replace('\r','<br/>');
                    //For SMS calls removing the HTML tags out of the template body
                    if(send_sms) {
                        template_body_modified = template_body_modified.stripHtmlTags();
                        template_body_modified = template_body_modified.replace('\"','\\"') ;
                        template_body_modified = template_body_modified.replace('\n',' ');
                    }
                    // end correct formatting
                    
                    recipients.add(
                        '{'+
                            '"contactKey":"' + (send_sms==true ? config.Value__c:to_email) + '",'+
                            '"to":"' + (send_sms==true ? config.Value__c:to_email) + '",'+
                            '"attributes":{'+
                                '"Communication Nub Name":"' + name + '",'+
                                '"Email Subject":"' + email_subject + '",'+
                                '"Created By":"' + created_by + '",'+
                                '"Email Template Name":"' + email_template + '",'+
                                '"ExternalId":"' + external_id + '",'+
                                '"From Email":"' + from_email + '",'+
                                '"Last Modified By":"' + last_modified_by + '",'+
                                '"Owner":"' + owner_id + '",'+
                                '"processed_reminder_batch":"' + processed_reminder + '",'+
                                '"Recipient Phone Number":"' + recipient_phone + '",'+
                                '"Send Mail":"' + send_mail + '",'+
                                '"Sender Name":"' + senders_name + '",'+
                                '"Sender Phone":"' + senders_phone + '",'+
                                '"Send SMS":"' + send_sms + '",'+
                                '"SMS Receivers":"' + sms_receivers + '",'+
                                '"SourceSystem":"' + source_system + '",'+
                                '"Status":"' + status + '",'+
                                '"Template Body":"' + template_body_modified + '",'+
                                '"Template Id":"' + template_id + '",'+
                                '"Template Name":"' + template_name + '",'+
                                '"To Email":"' + to_email + '",'+
                                '"Triggered Record Id":"' + triggered_record_id + '",'+
                                '"Triggered Record Name":"' + triggered_record_name + '"'+
                            '}'+
                        '}'
                    );
            }
            payload += String.join(recipients, ',');
            payload += ']'+'}';
            System.enqueueJob(new SSP_TransactionalAPI(payload));
            }
        } catch (Exception ex) {
            LOG_LogMessageUtility.logMessage(ex, 'SSP_TransactionalAPI', 'sendComList', 'Failed to Invoke SFMC service', true); 
        }
    }
    
    /**
     * This method is to invoke the SFMC services
     */
    public void sendComToMC() {
        try {
            // get access token
            String token;
            REIntegrationEndpoints__c endpointObj = REIntegrationEndpoints__c.getInstance('SSP_SFMC');
            SSP_SendComToMC_RequestWrapper request = new SSP_SendComToMC_RequestWrapper();
            request.grant_type = SSP_InterfaceConstants.SSP_SFMC_GRANT_TYPE;
            request.client_id = endpointObj.Client_Id__c; 
            request.client_secret = endpointObj.Client_Secret__c;
            request.account_id = SSP_InterfaceConstants.SSP_SFMC_ACCOUNT_ID;
            List<LOG_LogMessage__c> logMessages = new List<LOG_LogMessage__c>();
            Map<String,object> mapTokenParams = new Map<String,object>();
            mapTokenParams.put(SSP_InterfaceConstants.JSON_BODY,JSON.serialize(request));    
            List<object> tokenResponses = IntegrationFactory.invokeCallout(SSP_InterfaceConstants.SSP_SENDCOMTOMC_GENERATE_TKN, mapTokenParams);
            if(tokenResponses != null && !tokenResponses.isEmpty()) {
                if(tokenResponses.size() > 1) {
                    logMessages.add((LOG_LogMessage__c)tokenResponses[1]);
                }
                SSP_SendComToMC_ResponseWrapper tokenResponse = (SSP_SendComToMC_ResponseWrapper) tokenResponses[0];
                token = tokenResponse.access_token;
            }
            
            Map<String,object> mapEmailParams = new Map<String,object>();
            mapEmailParams.put('token', token);
            mapEmailParams.put(SSP_InterfaceConstants.JSON_BODY, jsonData); 
            List<object> mailResponse = IntegrationFactory.invokeCallout(SSP_InterfaceConstants.SSP_SENDCOMTOMC_EMAIL, mapEmailParams);
            if(mailResponse.size() > 1) {
                logMessages.add((LOG_LogMessage__c)mailResponse[1]);
            }

            if(!logMessages.isEmpty()) {
                insert logMessages;
            }
        } catch(Exception ex) {
            LOG_LogMessageUtility.logMessage(ex, 'SSP_TransactionalAPI', 'sendComToMC', 'Failed to Invoke SFMC service', true);
        }
    }

    /*
     * Method Name          : execute
     * Params               : context - Queable context
     * Description          : Method for enque job
     */
    public void execute(QueueableContext context) {
        sendComToMC();
    }
}