force-app/main/default/objects/Contact/fields/CacheKIHIPPSummary__c.field-meta.xml
<CustomField>
    <fullName>CacheKIHIPPSummary__c</fullName>
    <description>DAshboard data for KIHIPP Summary flag</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>DAshboard data for KIHIPP Summary flag</inlineHelpText>
    <label>CacheKIHIPPSummary</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/IndividualId__c.field-meta.xml
<CustomField>
    <fullName>IndividualId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Individual Id of a Contact</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>IndividualId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/MemberType__c.field-meta.xml
<CustomField>
    <fullName>MemberType__c</fullName>
    <description>This field is used to check if logged in user is HOH or Dependent.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>MemberType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/ImpersonatedIndividualId__c.field-meta.xml
<CustomField>
    <fullName>ImpersonatedIndividualId__c</fullName>
    <description>Individual Id impersonated after client search by this user</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Individual Id impersonated after client search by this user</inlineHelpText>
    <label>Impersonated Individual Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/SelectedRole__c.field-meta.xml
<CustomField>
    <fullName>SelectedRole__c</fullName>
    <description>Role selected by user from applicable roles.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Role selected by user from applicable roles.</inlineHelpText>
    <label>Selected Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SSP_CacheBuilderImplementation.cls
/*
* classname     :  SSP_CacheBuilderImplementation
* @description  :  Class for adding selected role and imperosnated individual id to session cache
* @author       :  Anuja Ingole   
* @date         :  4/28/2020
* MODIFICATION LOG: 
* DEVELOPER                     DATE                               DESCRIPTION
* ---------------------------------------------------------------------------------------------

**/
public with sharing class SSP_CacheBuilderImplementation implements Cache.CacheBuilder {
    public String doLoad(String key) {
        String value = '';
        User u;
        //Irondome IsAccessible Fix
        if(User.getSObjectType().getDescribe().isAccessible()){
         u = (User)[SELECT Id, ImpersonatedIndividualId__c, SelectedRole__c,profile.name,contact.IndividualId__c, contact.MemberType__c  FROM User WHERE id = :UserInfo.getUserId()];
        }
        
        Contact individualContact;
        if(key.equalsIgnoreCase(SSP_GlobalConstants.INDIVIDUAL_ID) && u != null){
           value = u.ImpersonatedIndividualId__c!= null ? u.ImpersonatedIndividualId__c:(U.contact.IndividualId__c !=null && (u.profile.name.equalsIgnoreCase(SSP_GlobalConstants.RE_CITIZEN_PROFILE) || u.SelectedRole__c.equalsIgnoreCase(SSP_GlobalConstants.CITIZEN_ROLE))) ? U.contact.IndividualId__c : '';
        }else if(key.equalsIgnoreCase(SSP_GlobalConstants.SELECTED_ROLE) && u != null){
           value = u.SelectedRole__c!= null ? u.SelectedRole__c : SSP_GlobalConstants.CITIZEN_ROLE;
        }else if(key.equalsIgnoreCase('isHeadOfHousehold') && u != null){
           value = u.Contact.MemberType__c != null ? (u.Contact.MemberType__c == 'DEP' ? 'true' : 'false' ) : 'false';
        }else if(SSP_GlobalConstants.ALL_AVAILABLE_PROGRAMS != null && SSP_GlobalConstants.ALL_AVAILABLE_PROGRAMS.contains(key)){
           value = String.valueOf(FeatureManagement.checkPermission(key));
        }
        else if(key.equalsIgnoreCase('showKIHIPPSummary')){
         individualContact = SSP_DashboardService.getIndividualContact(null);
         value = String.valueOf(individualContact.CacheKIHIPPSummary__c);
        }
        return value;
    }
}