force-app/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetDefinition>
            
            
                <value>
                
                    <fullName>Male</fullName>
                
                
                    <label>Male</label>
                
                </value>
            
                <value>
                
                    <fullName>Female</fullName>
                
                
                    <label>Female</label>
                
                </value>
            
                <value>
                
                    <fullName>Other</fullName>
                
                
                    <label>Other</label>
                
                </value>
            
            </valueSetDefinition>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/SSN__c.field-meta.xml
<CustomField>
    <fullName>SSN__c</fullName>
    <description>Social Security Number</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Social Security Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LOG_LogMessage__c/LOG_LogMessage__c.object-meta.xml
<CustomObject>
    <description>Container for custom exception/log messages</description>
    <label>Log Message</label>
    <nameField>
        <displayFormat>LOG-{000000}</displayFormat>
        <label>Log Message #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_InterfaceDetail__mdt/SSP_InterfaceDetail__mdt.object-meta.xml
<CustomObject>
    <description>Holds information about interface</description>
    <label>Interface Detail</label>
    <pluralLabel>Interface Details</pluralLabel>
</CustomObject>

force-app/main/default/objects/SSP_InterfaceDetail__mdt/fields/Is_Debug__c.field-meta.xml
<CustomField>
    <fullName>Is_Debug__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Field to track Info debugging on Interfaces</inlineHelpText>
    <label>Is Debug</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SSP_InterfaceDetail__mdt/fields/SSP_NamedCredential__c.field-meta.xml
<CustomField>
    <fullName>SSP_NamedCredential__c</fullName>
    <description>Stores the named credential name associated with the interface</description>
    <label>Named Credential</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_InterfaceDetail__mdt/fields/Timeout_Miliseconds__c.field-meta.xml
<CustomField>
    <fullName>Timeout_Miliseconds__c</fullName>
    <description>Contains timeout details in milliseconds</description>
    <label>Timeout (Miliseconds)</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SSP_MCIForBenefitIntegrationService.cls
/**
* Class Name    : SSP_MCIIntegrationService
* Owner         : DELOITTE
* Created Date  : 06/03/2020
* Description   : Class that holds utility methods for SSP MCI Service
*
*                            M O D I F I C A T I O N   L O G                                          
*
*  Date        Developer          			Description                                                         
*  ----------  -------------------------   -------------------------------------------------------------------
*  06/03/2020  Ragunathan                   Initial Version
*/
public with sharing class SSP_MCIForBenefitIntegrationService extends SOAPIntegrationService {

    public static final String SOURCE = 'SSP_MCIForBenefitIntegrationService';
    public static final String SOURCE_FUNCTION = 'invokeCallout';

    /**
    * method        : invokeCallout
    * @description  : This method is to make callout for MCI Service
    * @author       : Ragunathan
    * @param developerName : It is a metadata record Name. Here we can store the endpoint details.
    * @param mapInputParams : Request body in a map format
    * @return: List<Object>
    * */
    public static List<Object> invokeCallout(String sInterfaceName, Map<String, object> mapInputParams) {
        logMessageWrapper objLog = new logMessageWrapper();
        Log_LogMessage__c log;
        objLog.interfaceName = sInterfaceName;
        objLog.source = SOURCE;
        objLog.sourceFunction = SOURCE_FUNCTION;
        Datetime startTime = Datetime.now();
        Datetime endTime;
        List<Object> serviceResponse = new List<Object>();
        try {        
            
            SSP_MCIForBenefitRequestWrapper request = (SSP_MCIForBenefitRequestWrapper)JSON.deserialize((String)mapInputParams.get(SSP_InterfaceConstants.JSON_BODY), SSP_MCIForBenefitRequestWrapper.class);
            Contact con = request.con;
            
            kyHbeMciDatacontracts.MciEntitySearchResponse res = new kyHbeMciDatacontracts.MciEntitySearchResponse();
            SSP_InterfaceDetail__mdt objInterfaceDetail = getCertificateName(sInterfaceName);
            kyHbeMciDatacontracts.MciEntitySearchRequest req = new kyHbeMciDatacontracts.MciEntitySearchRequest();
            kyHbeMci.MciHttpsDefaultEndpoint stub = new kyHbeMci.MciHttpsDefaultEndpoint();
            stub.endpoint_x         = SSP_InterfaceConstants.SSP_CallOut+objInterfaceDetail.SSP_NamedCredential__c;
            if(objInterfaceDetail.Timeout_Miliseconds__c != null) {
                stub.timeout_x          = Integer.valueof(objInterfaceDetail.Timeout_Miliseconds__c);
            }            
            req.SourceSystemName    = 'HBE';
            req.FirstName           = con.firstName;
            req.LastName            = con.LastName;
            req.Dob                 = con.birthdate;
            if(con.ssn__c!=null){
                req.Ssn=con.ssn__c;  
            }
            req.Gender              = con.Gender__c;
            objLog.payload = JSON.serialize(req);
            objLog.endpoint = SSP_InterfaceConstants.SSP_CallOut+objInterfaceDetail.SSP_NamedCredential__c;
            objLog.startTime = SSP_IntegrationUtility.getTimeInMilliseconds();
            res = stub.EntityMciSearch(req);
            endTime = Datetime.now();
            objLog.timeTaken = endTime.getTime() - startTime.getTime();
            objLog.responseData = JSON.serialize(res);
            serviceResponse.add(res);

            if(objInterfaceDetail.Is_Debug__c) {
                log = (new SSP_IntegrationUtility()).createLogMessage(LOG_LogMessageUtility.LOG_LogLevel.Info, objLog, false);
                serviceResponse.add(log);
            }
    } catch(Exception e) {
        endTime = Datetime.now();
        objLog.timeTaken = endTime.getTime() - startTime.getTime();
        // create log for the exception
        log = (new SSP_IntegrationUtility()).handleException(e, objLog, true);
    }
        return serviceResponse;
    }
}