force-app/main/default/objects/Contact/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <description>This field is indicate a flag for an active assistors</description>
    <encryptionScheme>None</encryptionScheme>
    <label>IsActive</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NavFlowDetail__mdt/NavFlowDetail__mdt.object-meta.xml
<CustomObject>
    <description>Contains navigation flow details.</description>
    <label>Navigation Flow Detail</label>
    <pluralLabel>Navigation Flow Details</pluralLabel>
</CustomObject>

force-app/main/default/objects/NavFlowDetail__mdt/fields/Community_Page_URL__c.field-meta.xml
<CustomField>
    <fullName>Community_Page_URL__c</fullName>
    <description>Store the URL portion created as a part of Community tab Page.
For e.g.- for a community page for flow Intake Application as application-intake which is visible as a URL parameter whenever community page is created.</description>
    <label>Community Page URL</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NavFlowDetail__mdt/fields/FlowDisplayName__c.field-meta.xml
<CustomField>
    <fullName>FlowDisplayName__c</fullName>
    <description>Display name for the flow.
Example : Intake Application

If custom label is used then prefix with $.
Example : $IntakeApplication</description>
    <inlineHelpText>Display name for the flow.
Example : Intake Application

If custom label is used then prefix with $.
Example : $IntakeApplication</inlineHelpText>
    <label>Flow Display Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NavFlowDetail__mdt/fields/FlowName__c.field-meta.xml
<CustomField>
    <fullName>FlowName__c</fullName>
    <description>Flow unique name.</description>
    <label>Flow Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/NavFlowDetail__mdt/fields/NextActionGoToPage__c.field-meta.xml
<CustomField>
    <fullName>NextActionGoToPage__c</fullName>
    <description>Used to determine which page to load when next button is clicked. Assume the following example:
Current navigation flow status : CRCRR
Current page is the second page.

If this field value is &apos;Required&apos; then clicking next button will skip page 3 since it already completed and will load page 4.
If this field value is &apos;Completed&apos; then clicking next button will load page 3.

 If &apos;Required&apos; then next action will load the next required page. If the immediate next page is already completed then it will be skipped.</description>
    <inlineHelpText>Used to determine which page to load when next button is clicked. Assume the following example:
Current navigation flow status : CRCRR
Current page is the second page.

If value is &apos;Required&apos; then next button will skip page 3 and will load page 4.</inlineHelpText>
    <label>Next Action Go To Page</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Required</fullName>
                <default>true</default>
                <label>Required</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NavFlowPageConfig__mdt/NavFlowPageConfig__mdt.object-meta.xml
<CustomObject>
    <description>Contains navigation flow page configuration.</description>
    <label>Navigation Flow Page Configuration</label>
    <pluralLabel>Navigation Flow Page Configuration</pluralLabel>
</CustomObject>

force-app/main/default/objects/NavFlowPageConfig__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Flag to indicate if the page is active i.e., part of the flow. Use this flag to mark the pages which become no longer needed in the flow as per new configuration.</description>
    <inlineHelpText>Flag to indicate if the page is active i.e., part of the flow. Use this flag to mark the pages which become no longer needed in the flow as per new configuration.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NavFlowPageConfig__mdt/fields/ListenerPageNames__c.field-meta.xml
<CustomField>
    <fullName>ListenerPageNames__c</fullName>
    <description>Pages that are listening to this page during flow navigation. In other words, the pages that are depending on the values/conditions from this page. The flow rules of those listening pages will be triggered after this page&apos;s process is completed. This will determine page queues in the flow.</description>
    <inlineHelpText>Pages that are listening to this page during flow navigation. In other words, the pages that are depending on the values/conditions from this page. The flow rules of those listening pages will be triggered after this page&apos;s process is completed.</inlineHelpText>
    <label>Listener Page Names</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NavFlowPageConfig__mdt/fields/NavFlowRule__c.field-meta.xml
<CustomField>
    <fullName>NavFlowRule__c</fullName>
    <description>Rule condition to queue/show the page. If no rule is configured then by default the page will be queued/showed.</description>
    <inlineHelpText>Rule condition to queue/show the page. If no rule is configured then by default the page will be queued/showed.</inlineHelpText>
    <label>Navigation Flow Rule</label>
    <referenceTo>NavFlowRule__mdt</referenceTo>
    <relationshipLabel>Navigation Flow Page Configuration</relationshipLabel>
    <relationshipName>Navigation_Flow_Page_Configuration</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/NavFlowPageConfig__mdt/fields/NavigationFlowDetail__c.field-meta.xml
<CustomField>
    <fullName>NavigationFlowDetail__c</fullName>
    <label>Navigation Flow Detail</label>
    <referenceTo>NavFlowDetail__mdt</referenceTo>
    <relationshipLabel>Navigation Flow Page Configuration</relationshipLabel>
    <relationshipName>Navigation_Flow_Page_Configuration</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/NavFlowPageConfig__mdt/fields/PageDisplayName__c.field-meta.xml
<CustomField>
    <fullName>PageDisplayName__c</fullName>
    <description>Display name for the flow.
Example : Address

If blank, page display name from PageInfo meta data will be used.

If custom label is used then prefix with $.
Example : $Address</description>
    <inlineHelpText>Display name for the flow.
Example : Address

If blank, page display name from PageInfo meta data will be used.
If custom label is used then prefix with $.
Example : $Address</inlineHelpText>
    <label>Page Display Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NavFlowPageConfig__mdt/fields/PageInfo__c.field-meta.xml
<CustomField>
    <fullName>PageInfo__c</fullName>
    <description>Page info</description>
    <label>Page Info</label>
    <referenceTo>PageInfo__mdt</referenceTo>
    <relationshipLabel>Navigation Flow Page Configuration</relationshipLabel>
    <relationshipName>Navigation_Flow_Page_Configuration</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/NavFlowPageConfig__mdt/fields/SectionGroupName__c.field-meta.xml
<CustomField>
    <fullName>SectionGroupName__c</fullName>
    <description>Section or Group name. This will be used to display in the flow progress bar. Create a custom label with same name since framework will try to find out a label with this name.</description>
    <inlineHelpText>Section or Group name. This will be used to display in the flow progress bar. Create a custom label with same name since framework will try to find out a label with this name.</inlineHelpText>
    <label>Section/Group Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NavFlowPageConfig__mdt/fields/SequenceNumber__c.field-meta.xml
<CustomField>
    <fullName>SequenceNumber__c</fullName>
    <description>Page sequence number in the flow. Use increments of 3 to allow flexibility to insert new pages in an existing flow. Example:
Flow sequence numbers : 3, 6, 9, 12
If a new page needs to be inserted as 3rd page then the order could be: 3, 6, 7, 9, 12

This way there is no need to change existing page sequence numbers.</description>
    <inlineHelpText>Page sequence number in the flow. Use increments of 3 to allow flexibility to insert new pages in an existing flow. Example:
Flow sequence numbers : 3, 6, 9, 12
If a new page needs to be inserted as 3rd page then the order could be: 3, 6, 7, 9, 12</inlineHelpText>
    <label>Sequence Number</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NavFlowRule__mdt/NavFlowRule__mdt.object-meta.xml
<CustomObject>
    <description>Contains navigation flow rules.</description>
    <label>Navigation Flow Rule</label>
    <pluralLabel>Navigation Flow Rules</pluralLabel>
</CustomObject>

force-app/main/default/objects/NavFlowRule__mdt/fields/RuleName__c.field-meta.xml
<CustomField>
    <fullName>RuleName__c</fullName>
    <description>Rule unique name.</description>
    <label>Rule Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/NavFlowStatus__c/NavFlowStatus__c.object-meta.xml
<CustomObject>
    <description>Contains navigation flow status for specific contact, account etc., Primarily used for contact.</description>
    <label>Navigation Flow Status</label>
    <nameField>
        
        <displayFormat>NavFlow-{0000000}</displayFormat>
        
        <label>Navigation Flow Status Name</label>
        
        <type>AutoNumber</type>
        
    </nameField>
    <pluralLabel>Navigation Flow Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NavFlowStatus__c/fields/Community_Page_URL__c.field-meta.xml
<CustomField>
    <fullName>Community_Page_URL__c</fullName>
    <description>Stamp the url from navflowdetail record</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Community_Page_URL</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PageInfo__mdt/PageInfo__mdt.object-meta.xml
<CustomObject>
    <description>Contains page information like URL, component name etc.,</description>
    <label>Page Info</label>
    <pluralLabel>Page Info</pluralLabel>
</CustomObject>

force-app/main/default/objects/PageInfo__mdt/fields/LightningComponentName__c.field-meta.xml
<CustomField>
    <fullName>LightningComponentName__c</fullName>
    <description>Page lightning component name. If this is used then the component will be dynamically rendered in the container.</description>
    <inlineHelpText>Page lightning component name. If this is used then the component will be dynamically rendered in the container.</inlineHelpText>
    <label>Lightning Component Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PageInfo__mdt/fields/PageDisplayName__c.field-meta.xml
<CustomField>
    <fullName>PageDisplayName__c</fullName>
    <description>Display name for the flow. 
Example : Address 

If custom label is used then prefix with $. 
Example : $Address</description>
    <inlineHelpText>Display name for the flow. 
Example : Address 

If custom label is used then prefix with $. 
Example : $Address</inlineHelpText>
    <label>Page Display Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PageInfo__mdt/fields/PageName__c.field-meta.xml
<CustomField>
    <fullName>PageName__c</fullName>
    <description>Page unique name.</description>
    <label>Page Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PageInfo__mdt/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <description>Page URL.</description>
    <inlineHelpText>Page URL.</inlineHelpText>
    <label>URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NavFlowHelper.cls
/**
* Helper class to read Navigation Flow Configurations from <b>NavFlowDetail__mdt</b> object.
*
* @author Rahman A
* @date 08/28/2014
*
* @see NavFlowConfig
*/
public with sharing class NavFlowHelper {
    
    
    /**
* Reads the workflow based configuration for the given workflow name and returns NavFlowConfig object.
*
* @param ctx Context object.
* @param flowName String Flow name.
*
* @return NavFlowConfig.
*/  public static NavFlowStatus__c navStausExisting;
    //Shikha: adding extra argument to know the screens selected in RAC
    //Shikha: added a new column Community URL to navigate when application has to be resumed
    public static NavFlowDetail__mdt getNavFlowDetail(Context ctx, String flowName, List<String> SelectedScreen){
              
        NavFlowDetail__mdt navFlowObj = new NavFlowDetail__mdt();
        /* if(flowName == 'RAC' && SelectedScreen != null && !SelectedScreen.isEmpty()){

            //Shikha: added Method to Check NavRule 
            
            //SelectedPages.addAll(SelectedScreen);
            List<String> RuleScreenList = RACCheckRule.CheckRule();
            if(!RuleScreenList.isEmpty()){            
            SelectedScreen.addAll(RuleScreenList);
            }
            Set<String> SelectedPages = new Set<String>(SelectedScreen);


            navFlowObj = [ SELECT Id, FlowDisplayName__c, FlowName__c, NextActionGoToPage__c, 
            (SELECT Id, ListenerPageNames__c, NavigationFlowDetail__c, NavFlowRule__c, NavFlowRule__r.RuleName__c, PageInfo__c, PageDisplayName__c,
            PageInfo__r.PageName__c, PageInfo__r.PageDisplayName__c, PageInfo__r.URL__c, PageInfo__r.LightningComponentName__c, SectionGroupName__c, SequenceNumber__c
            FROM Navigation_Flow_Page_Configuration__r
            WHERE IsActive__c = TRUE AND PageInfo__r.PageName__c IN :SelectedPages                             	
            order by SequenceNumber__c)
            FROM NavFlowDetail__mdt
            WHERE FlowName__c =: flowName];
            }
            else{*/

         navFlowObj = [ SELECT Id, FlowDisplayName__c, FlowName__c, NextActionGoToPage__c, Community_Page_URL__c,
                      (SELECT Id, ListenerPageNames__c, NavigationFlowDetail__c, NavFlowRule__c, NavFlowRule__r.RuleName__c, PageInfo__c, toLabel(Page_Config_Display_Name_View__c),Programs__c,
                       PageInfo__r.PageName__c, toLabel(PageInfo__r.Page_Display_Name_View__c), PageInfo__r.URL__c, PageInfo__r.LightningComponentName__c, SectionGroupName__c, SequenceNumber__c
                       FROM Navigation_Flow_Page_Configuration__r
                       WHERE IsActive__c = TRUE 
                       order by SequenceNumber__c)
                      FROM NavFlowDetail__mdt
                      WHERE FlowName__c =: flowName];	
        //}

        return navFlowObj;
    }
    
    public static PageInfo__mdt getPageInfo(Context ctx, String pageInfoId) {
        return [SELECT Id, LightningComponentName__c, toLabel(Page_Display_Name_View__c), PageName__c, URL__c FROM PageInfo__mdt WHERE Id =: pageInfoId];
    }
    
    public static NavFlowStatus__c getNavFlowStatus(Context ctx, String navFlowStatusId) {
        return String.isBlank(navFlowStatusId) ? null : [SELECT Id, Name, Contact__c, FlowPageStatus__c, NavFlowName__c, RecordId__c, SSPApplication__c, InitiatedUser__c , Community_Page_URL__c,
                                                         Member__c, FlowDupStatus__c,Screen_Status__c, FlowCompleteStatus__c, IsEdit__c, FlowDupStatusCopy__c, FlowPageStatusCopy__c //#379955
                                                         FROM NavFlowStatus__c 
                                                         WHERE Id =: navFlowStatusId];
                                                             }
    
    //Shikha: Added New Method to fetch existin NavFlowStatus
    public static NavFlowStatus__c getNavFlowStausExisting(Context ctx, ContextData ctxData){
        if(navStausExisting == null ){
	        List<NavFlowStatus__c> existedNavFlowRecord = new List<NavFlowStatus__c>();
	        if(ctxData.recordId != Null){
	            existedNavFlowRecord =[SELECT Id, Name, Contact__c, FlowPageStatus__c, NavFlowName__c, RecordId__c,Screen_Status__c,
	                                   SSPApplication__c, InitiatedUser__c, Community_Page_URL__c, Member__c, FlowDupStatus__c, FlowCompleteStatus__c 
	                                   FROM NavFlowStatus__c 
	                                   WHERE NavFlowName__c = :ctxData.flowName
	                                   //AND InitiatedUser__c=:UserInfo.getUserId()
	                                   //AND Contact__c=:ctxData.contactId 
	                                   //AND RecordId__c = :ctxData.recordId 
	                                   AND SSPApplication__c =:ctxData.ApplicationId
	                                   AND Member__c =:ctxData.MemberId
	                                   ORDER BY CreatedDate ASC];
	        }
	        if(!existedNavFlowRecord.isEmpty()){
	            NavFlowStatus__c flowStatusObj = new NavFlowStatus__c(); 
	            List<NavFlowStatus__c> flowStatSet = new List<NavFlowStatus__c>();                       
	                flowStatusObj = existedNavFlowRecord[0];
	                for(integer i=1; i < existedNavFlowRecord.size(); i++){                    
	                    flowStatSet.add(existedNavFlowRecord[i]);
	                }
	            if(!flowStatSet.isEmpty() && Schema.sObjectType.NavFlowStatus__c.isDeletable()){
	             	delete flowStatSet;               
	            }                	
	                navStausExisting =  flowStatusObj;
	        }
        }
        return navStausExisting;
    }
    
    // this method can be useful when navigation flow status is not known but want to start latest flow using contact and flow name.
    public static NavFlowStatus__c getNavFlowStatus(Context ctx, String contactId, String flowName) {
        NavFlowStatus__c[] statuses = [SELECT Id, Name, Contact__c, Contact__r.Name,FlowPageStatus__c, NavFlowName__c, RecordId__c, InitiatedUser__c, Community_Page_URL__c,
                                       SSPApplication__c,Member__c,Screen_Status__c, FlowCompleteStatus__c, FlowDupStatus__c, FlowDupStatusCopy__c, FlowPageStatusCopy__c //#379955
                                       FROM NavFlowStatus__c 
                                       WHERE Contact__c =: contactId AND NavFlowName__c =: flowName ORDER BY LastModifiedDate DESC];
        return ((null == statuses || statuses.size() < 1)  ? null : statuses[0]);
    }
    
    public static NavFlowStatus__c storeNavFlowStatus(Context ctx, NavFlowStatus__c navFlowStatus, ContextData ctxData) {
        // Added by Durga Prasad and we need to change


        //Need to change the contact Id to record Id in where parameter
        //Shikha: added to check if record exists
        List<NavFlowStatus__c> lstofExistedNavFlowRecords  =[SELECT Id, Contact__c, FlowPageStatus__c, NavFlowName__c, RecordId__c, 
                                                             SSPApplication__c, InitiatedUser__c , Community_Page_URL__c, Member__c,Screen_Status__c
                                                             FROM NavFlowStatus__c WHERE NavFlowName__c = :navFlowStatus.NavFlowName__c                                                             
                                                             AND RecordId__c = :ctxData.recordId 
                                                             AND SSPApplication__c = :ctxData.ApplicationId
                                                             AND Member__c =:ctxData.MemberId
                                                             ORDER BY CreatedDate DESC LIMIT 1];
        //&& ctxData.flowName != 'ReportAchange'
        if(!lstofExistedNavFlowRecords.isEmpty()){
            
            navFlowStatus.id=lstofExistedNavFlowRecords[0].id;
        }
        
        UPSERT navFlowStatus;
        //NavFlowManager.isUpserted = true;
        return navFlowStatus;
    }
    
    public static NavFlowStatus__c storeNavFlowRACStatus(Context ctx, ContextData ctxData, NavFlowStatus__c navFlowStatus){
        
        List<NavFlowStatus__c> navFlowList = [SELECT Id FROM NavFlowStatus__c 
                                              WHERE SSPApplication__c =: ctxData.ApplicationId
                                              AND NavFlowName__c =:ctxData.flowName
                                              AND Member__c =: ctxData.MemberId];
        if(!navFlowList.isEmpty() && navFlowList.size()>1 && Schema.sObjectType.NavFlowStatus__c.isDeletable()){
            delete navFlowList;
        }
        else{
            navFlowStatus = !navFlowList.isEmpty() ? navFlowList[0] : navFlowStatus;
        }
        if(Schema.sObjectType.NavFlowStatus__c.isUpdateable()){
        	upsert navFlowStatus;   
        }        
        //NavFlowManager.isUpserted = true;
        return navFlowStatus;
    }
    
    public static NavFlowRule__mdt getNavFlowRule(Context ctx, String ruleId) {        
        NavFlowRule__mdt ruleMetadata = new NavFlowRule__mdt ();
        if(Schema.sObjectType.NavFlowRule__mdt.isAccessible()){
            ruleMetadata = [SELECT RuleApexClassName__c, RuleLogic__c, RuleName__c FROM NavFlowRule__mdt WHERE Id = : ruleId];
        }        
        return ruleMetadata;

    }
    //Manjunath
    public static NavFlowPageConfig__mdt getnavpageconfig (Context ctx, ContextData ctxData){
        
        set<string> setGroups = new set<string>();
        NavFlowPageConfig__mdt navFlowConfigList = new NavFlowPageConfig__mdt();
        if(Schema.sObjectType.NavFlowPageConfig__mdt.isAccessible()){      
            for( NavFlowPageConfig__mdt navflow : [select SectionGroupName__c  from NavFlowPageConfig__mdt where id=:ctxData.curNavFlowPageConfigId]){            
                setGroups.add(navflow.SectionGroupName__c);
            }
        }
        if(!setGroups.isEmpty() && Schema.sObjectType.NavFlowPageConfig__mdt.isAccessible()){
           navFlowConfigList = [SELECT Id, ListenerPageNames__c, NavigationFlowDetail__c, NavFlowRule__c, NavFlowRule__r.RuleName__c, PageInfo__c, toLabel(Page_Config_Display_Name_View__c),PageInfo__r.PageName__c, toLabel(PageInfo__r.Page_Display_Name_View__c), PageInfo__r.URL__c, PageInfo__r.LightningComponentName__c, SectionGroupName__c, SequenceNumber__c FROM NavFlowPageConfig__mdt
                WHERE IsActive__c = TRUE and SectionGroupName__c IN :setGroups order by SequenceNumber__c limit 1];
        }
        return navFlowConfigList;        
    }

    //Shikha: Added to fetch Member Details
    public static SSP_Member__c getMemberDetails(String MemberId){
        return [SELECT Id, FirstName__c, LastName__c from SSP_Member__c
                WHERE Id = :MemberId];
    }

    public static List<NavFlowStatus__c> getNavFlowRACStatus (String memberId, String appId, String flowName){
        List<NavFlowStatus__c> navFlowStatList = [SELECT Id, Name, Contact__c, FlowPageStatus__c, NavFlowName__c, RecordId__c,Screen_Status__c,IsEdit__c,
                                   				  SSPApplication__c, InitiatedUser__c, Community_Page_URL__c, Member__c, FlowDupStatus__c, FlowCompleteStatus__c 
                                   				  FROM NavFlowStatus__c  
                                                  WHERE navFlowName__c = :flowName AND SSPApplication__c =:appId AND
                                                  Member__c = :memberId];
        return navFlowStatList;
    }
        
}