force-app/main/default/objects/AccountContactRelation/fields/ProgramsApplied__c.field-meta.xml
<CustomField>
    <fullName>ProgramsApplied__c</fullName>
    <label>Programs Applied</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetDefinition>
            
            
                <value>
                
                    <fullName>MA</fullName>
                
                
                    <label>Medicaid/KCHIP</label>
                
                </value>
            
                <value>
                
                    <fullName>KT</fullName>
                
                
                    <label>KTAP (Cash Assistance)</label>
                
                </value>
            
                <value>
                
                    <fullName>SN</fullName>
                
                
                    <label>SNAP (Food Assistance)</label>
                
                </value>
            
                <value>
                
                    <fullName>SS</fullName>
                
                
                    <label>State Supplementation</label>
                
                </value>
            
                <value>
                
                    <fullName>DS</fullName>
                
                
                    <label>DSNAP</label>
                
                </value>
            
                <value>
                
                    <fullName>CC</fullName>
                
                
                    <label>Child Care Assistance</label>
                
                </value>
            
                <value>
                
                    <fullName>KP</fullName>
                
                
                    <label>KI-HIPP (Health Insurance Premium Payments)</label>
                
                </value>
            
            </valueSetDefinition>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Related Account</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Citizen.recordType-meta.xml
<RecordType>
    <fullName>Citizen</fullName>
    <active>true</active>
    <description>This Record type is used for Residents</description>
    <label>Citizen</label>
</RecordType>

force-app/main/default/objects/SSP_Application__c/SSP_Application__c.object-meta.xml
<CustomObject>
    <description>To store SSP Application and Case data</description>
    <label>SSP Application</label>
    <nameField>
        
        <displayFormat>{000000000}</displayFormat>
        
        <label>SSP_Application Name</label>
        
        <type>AutoNumber</type>
        
    </nameField>
    <pluralLabel>SSP Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Application__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Shows the related Account to an Application</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>SSP_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_Application__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Shows the related Contact to an Application</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>SSP_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SSP_Application__c/fields/ProgramsApplied__c.field-meta.xml
<CustomField>
    <fullName>ProgramsApplied__c</fullName>
    <description>Used to store the list of programs applied for a household</description>
    <label>Programs Applied</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>BenefitPrograms</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/SSP_ApplicationIndividual__c.object-meta.xml
<CustomObject>
    <description>Custom junction object to maintain association between member and application</description>
    <label>SSP ApplicationIndividual</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>SSP_ApplicationIndividual Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SSP ApplicationIndividuals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/IsHeadOfHousehold__c.field-meta.xml
<CustomField>
    <fullName>IsHeadOfHousehold__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to determine if the member is Head of Household</description>
    <label>Is Head Of Household</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/MedicaidType__c.field-meta.xml
<CustomField>
    <fullName>MedicaidType__c</fullName>
    <description>Used to store type of Medicaid Program - Magi/Non Magi</description>
    <label>Medicaid Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MAGI</fullName>
            </value>
            <value>
                <fullName>Non-MAGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/ProgramsApplied__c.field-meta.xml
<CustomField>
    <fullName>ProgramsApplied__c</fullName>
    <description>Different types of programs applied on an application for which this member is involved</description>
    <label>Application Programs Applied</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>BenefitPrograms</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/SSP_Application__c.field-meta.xml
<CustomField>
    <fullName>SSP_Application__c</fullName>
    <description>Indicates the application related to a member</description>
    <label>SSP_Application</label>
    <referenceTo>SSP_Application__c</referenceTo>
    <relationshipName>SSP_ApplicationIndividuals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/SSP_Member__c.field-meta.xml
<CustomField>
    <fullName>SSP_Member__c</fullName>
    <description>Indicates the member related to an application</description>
    <label>SSP_Member</label>
    <referenceTo>SSP_Member__c</referenceTo>
    <relationshipName>SSP_ApplicationIndividuals</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_Asset__c/SSP_Asset__c.object-meta.xml
<CustomObject>
    <description>Custom object to store details of Income, Expense, Resources, Employment Information.</description>
    <label>SSP Asset</label>
    <nameField>
        
        <displayFormat>A-{00000000}</displayFormat>
        
        <label>SSP_Asset Name</label>
        
        <type>AutoNumber</type>
        
    </nameField>
    <pluralLabel>SSP Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Asset__c/fields/BusinessTypeCode__c.field-meta.xml
<CustomField>
    <fullName>BusinessTypeCode__c</fullName>
    <description>Used to store different types of Business</description>
    <label>Business Type Code</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>BusinessType</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Asset__c/fields/EmployerName__c.field-meta.xml
<CustomField>
    <fullName>EmployerName__c</fullName>
    <description>This field is used to store Employer Name of Citizen</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Employer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_Asset__c/fields/IncomePayDetailHoursPerWeek__c.field-meta.xml
<CustomField>
    <fullName>IncomePayDetailHoursPerWeek__c</fullName>
    <description>This field is used to indicate income pay detail hours per week</description>
    <label>Income Pay Detail Hrs Per Week</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SSP_Asset__c/fields/IncomePayFrequency__c.field-meta.xml
<CustomField>
    <fullName>IncomePayFrequency__c</fullName>
    <description>This field is used to store the income pay frequency for an asset</description>
    <label>Income Pay Frequency</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>PayFrequency</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Asset__c/fields/IncomeTypeCode__c.field-meta.xml
<CustomField>
    <fullName>IncomeTypeCode__c</fullName>
    <description>This field is used to store the income type for an asset</description>
    <label>Income Type</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>IncomeType</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Asset__c/fields/SSP_Application__c.field-meta.xml
<CustomField>
    <fullName>SSP_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to identify the related application on an Asset</description>
    <label>SSP Application</label>
    <referenceTo>SSP_Application__c</referenceTo>
    <relationshipName>SSP_Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SSP_Asset__c/fields/SSP_Member__c.field-meta.xml
<CustomField>
    <fullName>SSP_Member__c</fullName>
    <description>This field is used to indicate a related member for an asset</description>
    <label>SSP_Member</label>
    <referenceTo>SSP_Member__c</referenceTo>
    <relationshipName>SSP_Assets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_Asset__c/fields/Tips__c.field-meta.xml
<CustomField>
    <fullName>Tips__c</fullName>
    <description>This field is used to store tips on an asset</description>
    <label>Tips</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SSP_Asset__c/fields/TotalGrossAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalGrossAmount__c</fullName>
    <description>This field is used to store total gross amount on an asset</description>
    <label>Total Gross Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/SSP_Member__c.object-meta.xml
<CustomObject>
    <description>Stores details about an individual member of a case/application such as gatepost reponse, incarceration, disability, living arrangement, pregnancy, address details. Also repurposed to store information of different individuals in the form of individual alien, alien sponsor, care taker,  care coordinator etc.</description>
    <label>SSP Member</label>
    <nameField>
        
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        
        <label>SSP_Member Name</label>
        
        <type>Text</type>
        
    </nameField>
    <pluralLabel>SSP Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Member__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>This field is used to indicate the related contact for a member</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>SSP_Member</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/IsHeadOfHousehold__c.field-meta.xml
<CustomField>
    <fullName>IsHeadOfHousehold__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Head Of Household</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SSP_NonCustodialParent__c/SSP_NonCustodialParent__c.object-meta.xml
<CustomObject>
    <description>Stores information about non custodial parent applicable for an application or case</description>
    <label>SSP NonCustodialParent</label>
    <nameField>
        
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        
        <label>SSP_NonCustodialParent Name</label>
        
        <type>Text</type>
        
    </nameField>
    <pluralLabel>SSP NonCustodialParent</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_NonCustodialParent__c/fields/SSP_Member__c.field-meta.xml
<CustomField>
    <fullName>SSP_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to indicate the member for a Non Custodial Parent</description>
    <label>SSP_Member</label>
    <referenceTo>SSP_Member__c</referenceTo>
    <relationshipName>SSP_NonCustodialParent</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SSP_NonCustodialParent__c/recordTypes/ChildMedicalSupport.recordType-meta.xml
<RecordType>
    <fullName>ChildMedicalSupport</fullName>
    <active>true</active>
    <label>Child/Medical Support</label>
</RecordType>

force-app/main/default/objects/SSP_NoncustodialRelationship__c/SSP_NoncustodialRelationship__c.object-meta.xml
<CustomObject>
    <description>Junction between SSP_Member and SSP_Noncustodialparent</description>
    <label>SSP NonCustodialRelationship</label>
    <nameField>
        
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        
        <label>NoncustodialRelationship Name</label>
        
        <type>Text</type>
        
    </nameField>
    <pluralLabel>SSP NonCustodialRelationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_NoncustodialRelationship__c/fields/HasChildSupportToggle__c.field-meta.xml
<CustomField>
    <fullName>HasChildSupportToggle__c</fullName>
    <description>Used to identify if primary applicant agree to cooperate with medical support</description>
    <label>HasChildSupportToggle</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>YesNo</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_NoncustodialRelationship__c/fields/SSP_Member__c.field-meta.xml
<CustomField>
    <fullName>SSP_Member__c</fullName>
    <description>This field is used to indicate the related member for a non custodial relationship record</description>
    <label>Member</label>
    <referenceTo>SSP_Member__c</referenceTo>
    <relationshipName>NoncustodialRelationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_NoncustodialRelationship__c/fields/SSP_NonCustodialParent__c.field-meta.xml
<CustomField>
    <fullName>SSP_NonCustodialParent__c</fullName>
    <description>This field is used to indicate the Non custodial parent involved in the Junction record</description>
    <label>Non Custodial Parent</label>
    <referenceTo>SSP_NonCustodialParent__c</referenceTo>
    <relationshipName>NoncustodialRelationships</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/BenefitPrograms.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>MA</fullName>
        
        
        <label>Medicaid/KCHIP</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>KT</fullName>
        
        
        <label>KTAP (Cash Assistance)</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SN</fullName>
        
        
        <label>SNAP (Food Assistance)</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SS</fullName>
        
        
        <label>State Supplementation</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>DS</fullName>
        
        
        <label>DSNAP</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>CC</fullName>
        
        
        <label>Child Care Assistance</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>KP</fullName>
        
        
        <label>KI-HIPP (Health Insurance Premium Payments)</label>
        
    </customValue>
    
    <description>Different type of Benefit Programs available for a Citizen</description>
    
    <masterLabel>Benefit Programs</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/globalValueSets/BusinessType.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>SF</fullName>
        
        
        <label>Farming</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>IA</fullName>
        
        
        <label>Illegal Activities</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SE</fullName>
        
        
        <label>Other Self Employment</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>RE</fullName>
        
        
        <label>Rental</label>
        
    </customValue>
    
    <description>Different Business Types</description>
    
    <masterLabel>Business Type</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/globalValueSets/IncomeType.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>DIR</fullName>
        
        
        <label>Dividends, Interest &amp; Royalties</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>IS</fullName>
        
        
        <label>Insurance Settlements &amp; Benefits Income</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>EA</fullName>
        
        
        <label>Job income from employer</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>OUI</fullName>
        
        
        <label>Other Goods, Payments, &amp; Services</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SE</fullName>
        
        
        <label>Self employment income</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SRP</fullName>
        
        
        <label>Social Security, Retirement, &amp; Pension</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SM</fullName>
        
        
        <label>Support &amp; Maintenance Income</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>UI</fullName>
        
        
        <label>Unpaid income</label>
        
    </customValue>
    
    <description>Income Types</description>
    
    <masterLabel>Income Type</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/globalValueSets/PayFrequency.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>BW</fullName>
        
        
        <label>Every 2 weeks</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>MO</fullName>
        
        
        <label>Monthly</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>QU</fullName>
        
        
        <label>Quarterly</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SM</fullName>
        
        
        <label>Twice a month</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>WE</fullName>
        
        
        <label>Weekly</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>YR</fullName>
        
        
        <label>Yearly</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>HO</fullName>
        
        
        <label>Hourly</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>DA</fullName>
        
        
        <label>Daily</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>IR</fullName>
        
        
        <label>Irregular</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SP</fullName>
        
        
        <label>Contractual/Single Payment Covering More than One Month</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>ON</fullName>
        
        
        <label>One Time Only - Lump sum</label>
        
    </customValue>
    
    <description>Frequency</description>
    
    <masterLabel>PayFrequency</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/globalValueSets/YesNo.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>Y</fullName>
        
        
        <label>YES</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>N</fullName>
        
        
        <label>NO</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>U</fullName>
        
        
        <label>Unknown</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>NULL</fullName>
        
        
        <label>NULL</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>H</fullName>
        
        
        <label>Historical</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>I don&apos;t know</fullName>
        
        
        <label>I don&apos;t know</label>
        
    </customValue>
    
    <description>Used to store different types of toggle picklist values</description>
    
    <masterLabel>YesNo</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/classes/SSP_MedicalEnforcementControllerTest.cls
/*
* classname     :  SSP_MedicalEnforcementControllerTest 
* @description  : Test  Class For Medical Enforcement Screen
* @author       :  Kireeti Gora
* @date         :  12/19/2019
* MODIFICATION LOG:
* DEVELOPER                     DATE                               DESCRIPTION
* ---------------------------------------------------------------------------------------------*/

   /**
@author : Kireeti Gora
Method to setup test data*/ 
@isTest(seeAllData=false)
public class SSP_MedicalEnforcementControllerTest { 
    @testSetup static void setup() { 
        SSP_TestDataFactory.setupTestData();  
        
        List<Account> lstAcc = SSP_TestDataFactory.createAccounts(1, false);
        lstAcc[0].Name = 'medicalEnforcementController';
        insert lstAcc;
        
        List<Contact> lstCon = [SELECT Id, FirstName, LastName FROM Contact WHERE FirstName = 'Citizen' AND LastName = 'User' LIMIT 1];//= SSP_TestDataFactory.createContacts(1, false); 
        
        AccountContactRelation acr = new AccountContactRelation(); 
        acr.Accountid = lstAcc[0].Id;
        acr.Contactid = lstCon[0].Id;
        acr.IsActive = true;
        insert acr;
        
        List<SSP_Application__c> lstAppln = SSP_TestDataFactory.createSSPApplications(1, false);
        lstAppln[0].Account__c=lstAcc[0].Id;        
        lstAppln[0].Contact__c = lstCon[0].Id;
        insert lstAppln;
        
        List<SSP_Member__c> lstMem = SSP_TestDataFactory.createSSPMembers(1, false);
        lstMem[0].contact__c=lstCon[0].Id; 
         lstMem[0].isHeadOfHousehold__c = true;
        insert lstMem;
        
        
        List<SSP_NonCustodialParent__c> lstNonCustodialParent = SSP_TestDataFactory.createNoncustodialParentRecords(1, true, lstMem[0].Id);
        
        SSP_NoncustodialRelationship__c objNonCustodialParent = new SSP_NoncustodialRelationship__c();
        objNonCustodialParent.SSP_Member__c = lstMem[0].Id;
        objNonCustodialParent.HasChildSupportToggle__c ='Y';
        objNonCustodialParent.SSP_NonCustodialParent__c=lstNonCustodialParent[0].Id;
       //objNonCustodialParent.RecordTypeId =Schema.SObjectType.SSP_NoncustodialRelationship__c.getRecordTypeInfosByDeveloperName()
    //.get('ChildMedicalSupport').getRecordTypeId();
        insert objNonCustodialParent;
        
        List<SSP_ApplicationIndividual__c> lstAppInd = SSP_TestDataFactory.createApplicationIndividuals(1, false); 
        lstAppInd[0].SSP_Application__c=lstAppln[0].Id;
        lstAppInd[0].SSP_Member__c=lstMem[0].Id;
        lstAppInd[0].ProgramsApplied__c = 'KT';
         lstAppInd[0].MedicaidType__c = 'MAGI';
        insert lstAppInd; 
        
    }
       /**
@author : Kireeti Gora
Method to test getMedicalEnforcementDetailsWithId method*/
    @isTest
    public static void test_getMedicalEnforcementDetailsWithId(){
        User citizen  = [SELECT Id FROM User WHERE UserName = 'citizen@abc.xyz' LIMIT 1][0];
        System.runAs(citizen){
            List<SSP_ApplicationIndividual__c> appIndvList = [SELECT Id, SSP_Member__c, SSP_Application__c FROM SSP_ApplicationIndividual__c WHERE SSP_Application__r.Account__r.Name = 'medicalEnforcementController'];
            
            List<SSP_Asset__c> assetList = [SELECT Id, Name, BusinessTypeCode__c, EmployerName__c, Tips__c, IncomeTypeCode__c, IncomePayFrequency__c, TotalGrossAmount__c, IncomePayDetailHoursPerWeek__c FROM SSP_Asset__c WHERE SSP_Member__c = :appIndvList[0].SSP_Member__c];
            
            
            test.startTest();
            
            SSP_LightningResponse response = SSP_MedicalEnforcementController.getMedicalEnforcementDetailsWithId( appIndvList[0].SSP_Application__c,appIndvList[0].SSP_Member__c);
            system.assertNotEquals(null, response.mapResponse);
            system.assert(response.mapResponse.containsKey('applicationIndividualPrograms'));  
            system.assert(response.mapResponse.containsKey('nonCustodialRelationshipRecord'));
            
            
            test.stopTest();
        }
        
    }
           /**
@author : Kireeti Gora
Method to test getMedicalEnforcementDetailsWithId method negatively*/
     @isTest
    public static void test_getMedicalEnforcementDetailsWithId_false(){
        User citizen  = [SELECT Id FROM User WHERE UserName = 'citizen@abc.xyz' LIMIT 1][0];
        System.runAs(citizen){
         
            test.startTest();
            
            SSP_LightningResponse response = SSP_MedicalEnforcementController.getMedicalEnforcementDetailsWithId( 'fhsjk','fsj');
           
            system.assert(!response.mapResponse.containsKey('applicationIndividualPrograms'));  
            system.assert(!response.mapResponse.containsKey('nonCustodialParentRecord'));
            
            
            test.stopTest();
        }
        
    }
           /**
@author : Kireeti Gora
Method to test updateNonCustodRecords method */    
      @isTest
    public static void test_updateNonCustodRecords(){
        User citizen  = [SELECT Id FROM User WHERE UserName = 'citizen@abc.xyz' LIMIT 1][0];
          SSP_NoncustodialRelationship__c objNonCustodialParent= New SSP_NoncustodialRelationship__c();
         objNonCustodialParent =[SELECT Id,HasChildSupportToggle__c,GoodCauseCode__c,MedicalSupportComments__c,SSP_Member__c FROM SSP_NoncustodialRelationship__c limit 1][0];
        System.runAs(citizen){
        
            objNonCustodialParent.HasChildSupportToggle__c='N';
            objNonCustodialParent.GoodCauseCode__c='Y';
            objNonCustodialParent.MedicalSupportComments__c='abc';
            
            test.startTest();
            
            Boolean response = SSP_MedicalEnforcementController.updateNonCustodRecords( JSON.serialize(objNonCustodialParent));
            Boolean responseNegative = SSP_MedicalEnforcementController.updateNonCustodRecords('null');
           
            system.assert(response);  
           
            test.stopTest();
        }
        
    }
     /********************************************************************************************
    * @author      Kireeti Gora
    * @date         02/18/2020
    * @methodname   isRequiredTest
    * @description  Test method for isRequired
    * @param        none
    * @return       none
    ********************************************************************************************/
    @isTest
    public static void isRequiredTest(){
       
            test.startTest();
       SSP_ApplicationIndividual__c objApp = [SELECT Id,SSP_Member__c,SSP_Application__c FROM SSP_ApplicationIndividual__c limit 1];
        
        Context ctx = new Context();
        ContextData ctxData = new ContextData();
        ctxData.MemberId = objApp.SSP_Member__c;
        ctxData.ApplicationId = objApp.SSP_Application__c;
        
        SSP_ChildMedicalEnforcementRule cls = new SSP_ChildMedicalEnforcementRule();
        boolean result = cls.isRequired(ctx, ctxData);
        System.assertNotEquals(result, null);
        
        boolean result1 = cls.isRequired(null, null);
        System.assertNotEquals(result1, null);
        
        SSP_MedicalEnforcementRule clsMedical = new SSP_MedicalEnforcementRule();
        boolean resultMedical = clsMedical.isRequired(ctx, ctxData);
        System.assertNotEquals(result, null);
        
        boolean result1Medical = clsMedical.isRequired(null, null);
        System.assertNotEquals(result1, null);
            test.stopTest();
    
    }
}