force-app/main/default/objects/AccountContactRelation/fields/ProgramsApplied__c.field-meta.xml
<CustomField>
    <fullName>ProgramsApplied__c</fullName>
    <label>Programs Applied</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetDefinition>
            
            
                <value>
                
                    <fullName>MA</fullName>
                
                
                    <label>Medicaid/KCHIP</label>
                
                </value>
            
                <value>
                
                    <fullName>KT</fullName>
                
                
                    <label>KTAP (Cash Assistance)</label>
                
                </value>
            
                <value>
                
                    <fullName>SN</fullName>
                
                
                    <label>SNAP (Food Assistance)</label>
                
                </value>
            
                <value>
                
                    <fullName>SS</fullName>
                
                
                    <label>State Supplementation</label>
                
                </value>
            
                <value>
                
                    <fullName>DS</fullName>
                
                
                    <label>DSNAP</label>
                
                </value>
            
                <value>
                
                    <fullName>CC</fullName>
                
                
                    <label>Child Care Assistance</label>
                
                </value>
            
                <value>
                
                    <fullName>KP</fullName>
                
                
                    <label>KI-HIPP (Health Insurance Premium Payments)</label>
                
                </value>
            
            </valueSetDefinition>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Related Account</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/IndividualId__c.field-meta.xml
<CustomField>
    <fullName>IndividualId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Individual Id of a Contact</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>IndividualId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/NavFlowStatus__c/NavFlowStatus__c.object-meta.xml
<CustomObject>
    <description>Contains navigation flow status for specific contact, account etc., Primarily used for contact.</description>
    <label>Navigation Flow Status</label>
    <nameField>
        
        <displayFormat>NavFlow-{0000000}</displayFormat>
        
        <label>Navigation Flow Status Name</label>
        
        <type>AutoNumber</type>
        
    </nameField>
    <pluralLabel>Navigation Flow Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NavFlowStatus__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Navigation Flow Status</relationshipLabel>
    <relationshipName>Navigation_Flow_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NavFlowStatus__c/fields/FlowDupStatus__c.field-meta.xml
<CustomField>
    <fullName>FlowDupStatus__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>FlowDupStatus</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NavFlowStatus__c/fields/FlowDupStatusCopy__c.field-meta.xml
<CustomField>
    <fullName>FlowDupStatusCopy__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Flow Dup Status Copy</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NavFlowStatus__c/fields/FlowPageStatus__c.field-meta.xml
<CustomField>
    <fullName>FlowPageStatus__c</fullName>
    <description>A string representing each pages status in the flow. Value is set by navigation flow framework.
Example: CCNRRR

Flow status codes:
R - Required
N - Not Required
C - Completed</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <inlineHelpText>A string representing each pages status in the flow. Value is set by navigation flow framework.
Example: CCNRRR

Flow status codes:
R - Required
N - Not Required
C - Completed</inlineHelpText>
    <label>Flow Page Status</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NavFlowStatus__c/fields/FlowPageStatusCopy__c.field-meta.xml
<CustomField>
    <fullName>FlowPageStatusCopy__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Flow Page Status Copy</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NavFlowStatus__c/fields/Screen_Status__c.field-meta.xml
<CustomField>
    <fullName>Screen_Status__c</fullName>
    <description>JSON string to store status</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Screen Status</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NavFlowStatus__c/fields/ScreenStatusCopy__c.field-meta.xml
<CustomField>
    <fullName>ScreenStatusCopy__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Screen Status Copy</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NavFlowStatus__c/fields/SSP_Application__c.field-meta.xml
<CustomField>
    <fullName>SSP_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SSP_Application</label>
    <referenceTo>SSP_Application__c</referenceTo>
    <relationshipName>NavFlowStatus</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NavFlowStatus__c/fields/SSP_Member__c.field-meta.xml
<CustomField>
    <fullName>SSP_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SSP_Member</label>
    <referenceTo>SSP_Member__c</referenceTo>
    <relationshipName>NavFlowStatus</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SSP_Application__c/SSP_Application__c.object-meta.xml
<CustomObject>
    <description>To store SSP Application and Case data</description>
    <label>SSP Application</label>
    <nameField>
        
        <displayFormat>{000000000}</displayFormat>
        
        <label>SSP_Application Name</label>
        
        <type>AutoNumber</type>
        
    </nameField>
    <pluralLabel>SSP Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Application__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Shows the related Account to an Application</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>SSP_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_Application__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Shows the related Contact to an Application</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>SSP_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SSP_Application__c/fields/ProgramsApplied__c.field-meta.xml
<CustomField>
    <fullName>ProgramsApplied__c</fullName>
    <description>Used to store the list of programs applied for a household</description>
    <label>Programs Applied</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>BenefitPrograms</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Application__c/fields/ProgramsAppliedCopy__c.field-meta.xml
<CustomField>
    <fullName>ProgramsAppliedCopy__c</fullName>
    <description>To store original programs when readonly user opens the application</description>
    <encryptionScheme>None</encryptionScheme>
    <label>ProgramsAppliedCopy</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/SSP_ApplicationIndividual__c.object-meta.xml
<CustomObject>
    <description>Custom junction object to maintain association between member and application</description>
    <label>SSP ApplicationIndividual</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>SSP_ApplicationIndividual Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SSP ApplicationIndividuals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/IsHeadOfHousehold__c.field-meta.xml
<CustomField>
    <fullName>IsHeadOfHousehold__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to determine if the member is Head of Household</description>
    <label>Is Head Of Household</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/MemberProgramsApplied__c.field-meta.xml
<CustomField>
    <fullName>MemberProgramsApplied__c</fullName>
    <description>This field is used to store different types of programs member has applied on a particular application</description>
    <label>Member Programs Applied</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>BenefitPrograms</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/MemberProgramsAppliedCopy__c.field-meta.xml
<CustomField>
    <fullName>MemberProgramsAppliedCopy__c</fullName>
    <description>Used to store/backup original programs when readonly user opens the application</description>
    <encryptionScheme>None</encryptionScheme>
    <label>MemberProgramsAppliedCopy</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/MemberStatus__c.field-meta.xml
<CustomField>
    <fullName>MemberStatus__c</fullName>
    <description>This field is used to determine the status of member</description>
    <label>Member Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Edited</fullName>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/ProgramsApplied__c.field-meta.xml
<CustomField>
    <fullName>ProgramsApplied__c</fullName>
    <description>Different types of programs applied on an application for which this member is involved</description>
    <label>Application Programs Applied</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetName>BenefitPrograms</valueSetName>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/SSP_Application__c.field-meta.xml
<CustomField>
    <fullName>SSP_Application__c</fullName>
    <description>Indicates the application related to a member</description>
    <label>SSP_Application</label>
    <referenceTo>SSP_Application__c</referenceTo>
    <relationshipName>SSP_ApplicationIndividuals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/SSP_Member__c.field-meta.xml
<CustomField>
    <fullName>SSP_Member__c</fullName>
    <description>Indicates the member related to an application</description>
    <label>SSP_Member</label>
    <referenceTo>SSP_Member__c</referenceTo>
    <relationshipName>SSP_ApplicationIndividuals</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/SSP_Member__c.object-meta.xml
<CustomObject>
    <description>Stores details about an individual member of a case/application such as gatepost reponse, incarceration, disability, living arrangement, pregnancy, address details. Also repurposed to store information of different individuals in the form of individual alien, alien sponsor, care taker,  care coordinator etc.</description>
    <label>SSP Member</label>
    <nameField>
        
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        
        <label>SSP_Member Name</label>
        
        <type>Text</type>
        
    </nameField>
    <pluralLabel>SSP Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Member__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>This field is used to indicate the related contact for a member</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>SSP_Member</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/IndividualId__c.field-meta.xml
<CustomField>
    <fullName>IndividualId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>This field is used to store individual Id of a member</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>IndividualId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SSP_Member__c/fields/IsHeadOfHousehold__c.field-meta.xml
<CustomField>
    <fullName>IsHeadOfHousehold__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Head Of Household</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/BenefitPrograms.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>MA</fullName>
        
        
        <label>Medicaid/KCHIP</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>KT</fullName>
        
        
        <label>KTAP (Cash Assistance)</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SN</fullName>
        
        
        <label>SNAP (Food Assistance)</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>SS</fullName>
        
        
        <label>State Supplementation</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>DS</fullName>
        
        
        <label>DSNAP</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>CC</fullName>
        
        
        <label>Child Care Assistance</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>KP</fullName>
        
        
        <label>KI-HIPP (Health Insurance Premium Payments)</label>
        
    </customValue>
    
    <description>Different type of Benefit Programs available for a Citizen</description>
    
    <masterLabel>Benefit Programs</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/classes/SSP_RoleSelectionTest.cls
/*
* classname     :  SSP_RoleSelectionTest
* @description  :  Test class for SSP_RoleSelection
* @author       :  Shrikant Raut   
* @date         :  05/26/2020
* MODIFICATION LOG:
* DEVELOPER                     DATE                               DESCRIPTION
* ---------------------------------------------------------------------------------------------

**/
@isTest
public class SSP_RoleSelectionTest {
    @testSetup static void testSetUpData() {
		User nonCitizenUser = SSP_TestDataFactory.setUpNonCitizenUser();
        
        List<SSP_Member__c> lstMem = SSP_TestDataFactory.createSSPMembers(1, false);        
        lstMem[0].contact__c = nonCitizenUser.ContactId;
        lstMem[0].IndividualId__c = '823968274';
        insert lstMem;
        
        Contact nonCitizenContact = new Contact(Id = nonCitizenUser.ContactId);
        nonCitizenContact.IndividualId__c = '823968274';
        update nonCitizenContact;
        
        List<Account> lstAcc = SSP_TestDataFactory.createAccounts(1, false);
        lstAcc[0].Name = 'updateApplicationPrograms';
        insert lstAcc;
        
        AccountContactRelation acr = new AccountContactRelation(); 
        acr.Accountid = lstAcc[0].Id;
        acr.Contactid = nonCitizenContact.Id;
        acr.IsActive = true;
        insert acr;
        
        List<SSP_Application__c> lstAppln = SSP_TestDataFactory.createSSPApplications(1, false);
        lstAppln[0].Account__c=lstAcc[0].Id;        
        lstAppln[0].Contact__c = nonCitizenContact.Id;
        lstAppln[0].ProgramsApplied__c = 'MA;SN;CC;KP;KT;SS';
        lstAppln[0].ProgramsAppliedCopy__c = 'CC;KP;KT;SS';
        insert lstAppln;
        
        List<SSP_ApplicationIndividual__c> lstAppInd = SSP_TestDataFactory.createApplicationIndividuals(1, false); 
        lstAppInd[0].SSP_Application__c=lstAppln[0].Id;
        lstAppInd[0].SSP_Member__c=lstMem[0].Id;
        lstAppInd[0].isHeadOfHouseHold__c = true;
        lstAppInd[0].memberStatus__c = SSP_GlobalConstants.MEMBER_STATUS_New;
        lstAppInd[0].MemberProgramsApplied__c = 'MA;SN;CC;KP;KT;SS';
        lstAppInd[0].MemberProgramsAppliedCopy__c = 'CC;KP;KT;SS';
        insert lstAppInd;
        
    }
    
    @isTest
    public static void updateApplicationPrograms_SSP_DashboardServiceTest(){ 
        User nonCitizen  = [SELECT Id FROM User WHERE UserName = 'noncitizen@abc.xyz' LIMIT 1][0]; 	
        Test.startTest();      
        List<SSP_Application__c> appList = [SELECT Id FROM SSP_Application__c LIMIT 1];
        NavFlowStatus__c navFlow = new NavFlowStatus__c();
        navFlow.Screen_Status__c = 'CCCCC';
        navFlow.FlowDupStatus__c = 'CCCCC';
        navFlow.FlowPageStatus__c =  'CCCCC';
        navFlow.ScreenStatusCopy__c = 'CCNCC';
        navFlow.FlowDupStatusCopy__c = 'CCNCC';
        navFlow.FlowPageStatusCopy__c =  'CCNCC';
        navFlow.SSPApplication__c = appList[0].Id;
        navFlow.NavFlowName__c = 'test';
        insert navFlow;
        System.runAs(nonCitizen){
            Cache.SessionPartition sessionPart = Cache.Session.getPartition(SSP_GlobalConstants.CACHE_PARTITION_NAME);
            sessionPart.put(SSP_GlobalConstants.SELECTED_ROLE, SSP_GlobalConstants.ORGANISATION_AUTH_REP);
                        
            List<SSP_ApplicationIndividual__c> appIndvList = [SELECT SSP_Application__r.Account__c, SSP_Application__r.ProgramsApplied__c, SSP_Member__r.Contact__c, SSP_Member__r.Contact__r.Is_Eligible_For_RSSPDC__c,SSP_Application__r.ProgramsAppliedCopy__c,MemberProgramsAppliedCopy__c FROM SSP_ApplicationIndividual__c WHERE SSP_Application__c = :appList[0].Id AND IsHeadOfHouseHold__c = true LIMIT 10];
            SSP_DashboardService.updateApplicationPrograms(appList[0].Id, appIndvList[0], SSP_GlobalConstants.SSP_INTAKE_FLOW); //#385177
            
            navFlow  = [SELECT Id, FlowDupStatusCopy__c, FlowPageStatusCopy__c, ScreenStatusCopy__c FROM NavFlowStatus__c WHERE SSPApplication__c = :appList[0].Id LIMIT 1][0];
            System.assert(String.isBlank(navFlow.FlowDupStatusCopy__c));
            System.assert(String.isBlank(navFlow.FlowDupStatusCopy__c));
            System.assert(String.isBlank(navFlow.FlowPageStatusCopy__c));
        }
        Test.stopTest();
    }
    
    @isTest
    public static void copyNavflowStatus_SSP_DashboardServiceTest(){ 
        User nonCitizen  = [SELECT Id FROM User WHERE UserName = 'noncitizen@abc.xyz' LIMIT 1][0]; 	
        Test.startTest();      
        List<SSP_Application__c> appList = [SELECT Id FROM SSP_Application__c LIMIT 1];
        NavFlowStatus__c navFlow = new NavFlowStatus__c();
        navFlow.Screen_Status__c = 'CCCCC';
        navFlow.FlowDupStatus__c = 'CCCCC';
        navFlow.FlowPageStatus__c =  'CCCCC';
        navFlow.SSPApplication__c = appList[0].Id;
        navFlow.NavFlowName__c = 'test';
        insert navFlow;
        System.runAs(nonCitizen){
            Cache.SessionPartition sessionPart = Cache.Session.getPartition(SSP_GlobalConstants.CACHE_PARTITION_NAME);
            sessionPart.put(SSP_GlobalConstants.SELECTED_ROLE, 'PROD_Support_Read_Only');
            
           
            List<SSP_ApplicationIndividual__c> appIndvList = [SELECT SSP_Application__r.Account__c, SSP_Application__r.ProgramsApplied__c, SSP_Member__r.Contact__c, SSP_Member__r.Contact__r.Is_Eligible_For_RSSPDC__c,SSP_Application__r.ProgramsAppliedCopy__c,MemberProgramsAppliedCopy__c FROM SSP_ApplicationIndividual__c WHERE SSP_Application__c = :appList[0].Id AND IsHeadOfHouseHold__c = true LIMIT 10];
			SSP_DashboardService.updateApplicationPrograms(appList[0].Id, appIndvList[0], SSP_GlobalConstants.SSP_INTAKE_FLOW); //#385177
            
            navFlow  = [SELECT Id, FlowDupStatusCopy__c, FlowPageStatusCopy__c, ScreenStatusCopy__c FROM NavFlowStatus__c WHERE SSPApplication__c = :appList[0].Id LIMIT 1][0];
            System.assert(String.isNotBlank(navFlow.FlowDupStatusCopy__c));
            System.assert(String.isNotBlank(navFlow.FlowPageStatusCopy__c));
            System.assert(String.isNotBlank(navFlow.ScreenStatusCopy__c));
        }
        Test.stopTest();
    }
    
    
    @isTest
    public static void getRequiredDetailsTest(){ 
        User nonCitizen  = [SELECT Id FROM User WHERE UserName = 'noncitizen@abc.xyz' LIMIT 1][0];
        SSPIntegrationEndpoints__c customSetting = new SSPIntegrationEndpoints__c();
        customSetting.Name = 'PE_URL_Redirect';
        customSetting.URL__c = 'url for waiver';
        insert customSetting;
        
        EncryptionDecryptionSettings__c encryptionSetting = new EncryptionDecryptionSettings__c();
        encryptionSetting.Name = 'SSPKey';
        encryptionSetting.Key__c = 'r5u8x!A%D*G-KaPdSgVkYp3s6v9y$B?E';
        insert encryptionSetting; 	 
        Test.startTest();      
        System.runAs(nonCitizen){
            SSP_LightningResponse response_New = SSP_RoleSelection.getRequiredDetails('gkm2TnwILNm2TTD1azbj0OQyFP7SzDqgYV9AtYo4F6jwkYzQerY4JLJW81mE1M0csbkD7QvEmsLhNAbnF0OP69Hh+72BhfV5ivELlaYYtHkQBrOeVTKufJjtcyM9ISklHITcaEecjpq2+T6HzDjoag==', null);
            SSP_LightningResponse response = SSP_RoleSelection.getRequiredDetails(null, '');
            System.assertEquals(true, response.bIsSuccess); 
            System.assertNotEquals(null, response.mapResponse.get('detailsWrap'));
            //System.assertEquals('Insurance_Agent', ((SSP_DashboardService.UserDetailsWrapper)response.mapResponse.get('detailsWrap')).selectedRole);
            System.assert(((SSP_DashboardService.UserDetailsWrapper)response.mapResponse.get('detailsWrap')).showCitizenDashboardLink);

            
            
        }
        Test.stopTest();
    }
    
    
    @isTest
    public static void updateRoleName_test(){ 
        User nonCitizen  = [SELECT Id FROM User WHERE UserName = 'noncitizen@abc.xyz' LIMIT 1][0]; 	 
        Test.startTest();      
        System.runAs(nonCitizen){
            Contact con = SSP_RoleSelection.updateRoleName('{"IndividualId":"222222222","CaseNumber":"123456789","SourceSystem":"SSP","UserId":null,"roleId":"5"}');        
            System.assertNotEquals(null, con);

            SSP_LightningResponse response = SSP_RoleSelection.impersonateCitizenOnLoad(JSON.serialize(con));
            System.assert(response.bIsSuccess);

            try{
                Contact con_New = SSP_RoleSelection.decrypt('gkm2TnwILNm2TTD1azbj0OQyFP7SzDqgYV9AtYo4F6jwkYzQerY4JLJW81mE1M0csbkD7QvEmsLhNAbnF0OP69Hh+72BhfV5ivELlaYYtHkQBrOeVTKufJjtcyM9ISklHITcaEecjpq2+T6HzDjoag==');
                system.assertNotEquals(null, con_New);
            }
            Catch(Exception ex){
                system.assertNotEquals(null, ex);
            }

            SSP_LightningResponse response_Negative = SSP_RoleSelection.impersonateCitizenOnLoad('1111');
            System.assert(!response_Negative.bIsSuccess);
        }
        Test.stopTest();
    }
    
    
    @isTest
    public static void constructDetailsWrapper_SSP_DashboardServiceTest(){ 
        User nonCitizen  = [SELECT Id FROM User WHERE UserName = 'noncitizen@abc.xyz' LIMIT 1][0];
        SSPIntegrationEndpoints__c customSetting = new SSPIntegrationEndpoints__c();
        customSetting.Name = 'PE_URL_Redirect';
        customSetting.URL__c = 'url for waiver';
        insert customSetting; 	
        Test.startTest();      
        System.runAs(nonCitizen){            
            SSP_DashboardService.UserDetailsWrapper userDetailsWrapper = SSP_DashboardService.constructDetailsWrapper(UserInfo.getUserId(), true);
            
            System.assertNotEquals(null, userDetailsWrapper);
            System.assertEquals('DAIL_Worker', userDetailsWrapper.selectedRole);
            System.assert(userDetailsWrapper.showCitizenDashboardLink);
        }
        Test.stopTest();
    }
    

    
    @isTest
    public static void invokeFlowForPermissionSetTest_Negative(){ 
        User nonCitizen  = [SELECT Id FROM User WHERE UserName = 'noncitizen@abc.xyz' LIMIT 1][0]; 	
        Test.startTest();      
        System.runAs(nonCitizen){
            SSP_LightningResponse response = SSP_RoleSelection.invokeFlowForPermissionSet('ABC', new User(),true);
            System.assertEquals(false, response.bIsSuccess);             
        }
        Test.stopTest();
    }
    
    @isTest
    public static void getMemberId_SSP_DashboardServiceTest(){ 
        User nonCitizen  = [SELECT Id FROM User WHERE UserName = 'noncitizen@abc.xyz' LIMIT 1][0]; 	
        Test.startTest();      
        System.runAs(nonCitizen){
            Contact con = SSP_DashboardService.getIndividualContact('823968274');            
            System.assertNotEquals(null, con);
            
            String memberId = SSP_DashboardService.getMemberId(con.Id);
            System.assertNotEquals(null, memberId);
        }
        Test.stopTest();
    }
    
    @isTest
    public static void resetDashboardRefreshFlagTest(){ 
        User nonCitizen  = [SELECT Id, ContactId FROM User WHERE UserName = 'noncitizen@abc.xyz' LIMIT 1][0]; 	
        Test.startTest();      
        System.runAs(nonCitizen){
            SSP_RoleSelection.resetDashboardRefreshFlag();            
            Contact con = [SELECT Id, IsDashboardRefreshNeeded__c FROM Contact WHERE Id = :nonCitizen.ContactId LIMIT 1];
            System.assert(con.IsDashboardRefreshNeeded__c);
            
        }
        Test.stopTest();
    }
    
	  
}