force-app/main/default/objects/AccountContactRelation/fields/RequestAccessPermission__c.field-meta.xml
<CustomField>
    <fullName>RequestAccessPermission__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Request Access Permission</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Related Account</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>This field is used to store Role of the user. Consider only records with &apos;Individual Authorized Representative&apos; or &apos;Organization Authorized Representative&apos;.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Role</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Assister.recordType-meta.xml
<RecordType>
    <fullName>Assister</fullName>
    <active>true</active>
    <description>assistor contact record</description>
    <label>Assister</label>
</RecordType>

force-app/main/default/objects/ScreenPermissions__mdt/ScreenPermissions__mdt.object-meta.xml
<CustomObject>
    <description>Security Matrix - screen permissions for different roles</description>
    <label>Screen Permissions</label>
    <pluralLabel>Screen Permissions</pluralLabel>
</CustomObject>

force-app/main/default/objects/ScreenPermissions__mdt/fields/Permission__c.field-meta.xml
<CustomField>
    <fullName>Permission__c</fullName>
    <description>level of permission as per security matrix.
R - ReadOnly
CR-Editable
CRU-Editable
Blank-NotAccessible
RU-Editable
CRUD-Editable
CRD-Editable</description>
    <inlineHelpText>level of permission as per security matrix.
R - ReadOnly
CR-Editable
CRU-Editable
Blank-NotAccessible
RU-Editable
CRUD-Editable
CRD-Editable</inlineHelpText>
    <label>Permission</label>
    <type>Picklist</type>
    <valueSet>
        
            <restricted>true</restricted>
        
            <valueSetDefinition>
            
            
                <value>
                
                    <fullName>ReadOnly</fullName>
                
                    <default>true</default>
                
                    <label>ReadOnly</label>
                
                </value>
            
                <value>
                
                    <fullName>Editable</fullName>
                
                
                    <label>Editable</label>
                
                </value>
            
                <value>
                
                    <fullName>NotAccessible</fullName>
                
                
                    <label>NotAccessible</label>
                
                </value>
            
            </valueSetDefinition>
        
        </valueSet>
</CustomField>

force-app/main/default/objects/SSP_Application__c/SSP_Application__c.object-meta.xml
<CustomObject>
    <description>To store SSP Application and Case data</description>
    <label>SSP Application</label>
    <nameField>
        
        <displayFormat>{000000000}</displayFormat>
        
        <label>SSP_Application Name</label>
        
        <type>AutoNumber</type>
        
    </nameField>
    <pluralLabel>SSP Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_Application__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Shows the related Account to an Application</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>SSP_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_Application__c/recordTypes/Case.recordType-meta.xml
<RecordType>
    <fullName>Case</fullName>
    <active>true</active>
    <label>Case</label>
</RecordType>

force-app/main/default/objects/SSP_ApplicationIndividual__c/SSP_ApplicationIndividual__c.object-meta.xml
<CustomObject>
    <description>Custom junction object to maintain association between member and application</description>
    <label>SSP ApplicationIndividual</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>SSP_ApplicationIndividual Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SSP ApplicationIndividuals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SSP_ApplicationIndividual__c/fields/SSP_Application__c.field-meta.xml
<CustomField>
    <fullName>SSP_Application__c</fullName>
    <description>Indicates the application related to a member</description>
    <label>SSP_Application</label>
    <referenceTo>SSP_Application__c</referenceTo>
    <relationshipName>SSP_ApplicationIndividuals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SSP_RoleIdentifier__mdt/SSP_RoleIdentifier__mdt.object-meta.xml
<CustomObject>
    <label>Role Identifier</label>
    <pluralLabel>Role Identifiers</pluralLabel>
</CustomObject>

force-app/main/default/objects/SSP_RoleIdentifier__mdt/fields/Role_API__c.field-meta.xml
<CustomField>
    <fullName>Role_API__c</fullName>
    <label>Role API</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSP_RoleIdentifier__mdt/fields/RoleId__c.field-meta.xml
<CustomField>
    <fullName>RoleId__c</fullName>
    <label>RoleId</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/SelectedRole__c.field-meta.xml
<CustomField>
    <fullName>SelectedRole__c</fullName>
    <description>Role selected by user from applicable roles.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Role selected by user from applicable roles.</inlineHelpText>
    <label>Selected Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Waiver_OrgId__c.field-meta.xml
<CustomField>
    <fullName>Waiver_OrgId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Waiver OrgId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Waiver_UserId__c.field-meta.xml
<CustomField>
    <fullName>Waiver_UserId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Waiver UserId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SSP_NonCitizenDashboardService.cls
/*
* classname     :  SSP_NonCitizenDashboardService
* @description  :  Helper class SSP_NonCitizenDashboardController for with sharing feature for searching 
* @author       :  Chandra Shekhar   
* @date         :  05/15/2020
* MODIFICATION LOG:
* DEVELOPER                     DATE                                DESCRIPTION
* ---------------------------------------------------------------------------------------------
* Chandra Shekhar             05/15/2020                             Created.
* ---------------------------------------------------------------------------------------------
**/
public with sharing class SSP_NonCitizenDashboardService {

  /***************************************************************************************************
* @author       Chandra Shekhar
* @date         05/25/2020
* @methodname   searchClientRealtedToIndividual
* @description  This method takes userId,userRole,searchQuery and returns List of Application realted to Individual user
* @return       list<SSP_ApplicationIndividual__c>
*****************************************************************************************************/
    
    public static list<SSP_ApplicationIndividual__c> searchClientRealtedToIndividual(String userId,String userRole,String searchQuery){   
        SSP_Utility.isAuthenticatedUser();            
        
        Map<String, String> conditionMap = new Map<String, String>();
        conditionMap.put('limit','1000');
        conditionMap.put('Account.Recordtype.DeveloperName',SSP_GlobalConstants.APPLICATION);
        conditionMap.put('Roles',userRole);
        //Defect 385706 - Start
        if(userRole.equalsIgnoreCase('Assister') || userRole.equalsIgnoreCase('Individual_Auth_Rep')){
            conditionMap.put('RequestAccessPermission__c','#null#');
        }
        //Defect 385706 - End
        list<User> loggedInUser = SSP_UserSelector.queryUserData(new Map<String, String>{'objectName'=>'User','operator'=>'AND'},new Set<String>{'Id', 'ContactId'}, 
                                                  new Map<String, String>{'limit'=>'1','Id'=> userId});   
        conditionMap.put('contactId',loggedInUser[0].ContactId);
        
        
        list<AccountContactRelation> acrRecords = SSP_AccountContactRelationSelector.queryACRData(new Map<String, String>{'objectName'=>'AccountContactRelation','operator'=>'AND'}, 
                                                                              new Set<String>{'Id','Contact.FirstName','Contact.LastName','Roles','ContactId','AccountId','RequestAccessPermission__c'}, 
                                                                              conditionMap);

        for(AccountContactRelation acrRecord : acrRecords){
             SSP_NonCitizenDashboardController.setofClientAccountId.add(String.valueOf(acrRecord.AccountId));
        }
        SSP_NonCitizenDashboardController.queryAccessAssociated=SSP_NonCitizenDashboardController.queryAccessAssociated.remove('AND SSP_Application__r.Account__c in :setofClientAccountId');
        if(String.isBlank(searchQuery)){
            SSP_NonCitizenDashboardController.queryAccessAssociated=SSP_NonCitizenDashboardController.queryAccessAssociated.remove('$searchQuery$');            
        } else{
            String whereClause=SSP_NonCitizenDashboardController.buildWhereClause(searchQuery,userRole);
            SSP_NonCitizenDashboardController.queryAccessAssociated=SSP_NonCitizenDashboardController.queryAccessAssociated.replace('$searchQuery$',whereClause);              
        }      
        //return (List<SSP_ApplicationIndividual__c>)Database.query(SSP_NonCitizenDashboardController.queryAccessAssociated);
        //Defect 385706 - Start
        List<SSP_ApplicationIndividual__c> lstAppIndivToReturn = new List<SSP_ApplicationIndividual__c>();
        List<SSP_ApplicationIndividual__c> lstAppIndividuals = (List<SSP_ApplicationIndividual__c>)Database.query(SSP_NonCitizenDashboardController.queryAccessAssociated);            
        if(userRole.equalsIgnoreCase('Assister') || userRole.equalsIgnoreCase('Individual_Auth_Rep')){                        
            for(SSP_ApplicationIndividual__c app : lstAppIndividuals){

                if(SSP_NonCitizenDashboardController.setofClientAccountId.contains(app.SSP_Application__r.Account__c)){
                    lstAppIndivToReturn.add(app);
                }
            }   
        }
        else{
            lstAppIndivToReturn = lstAppIndividuals;
        }
        return lstAppIndivToReturn; //Defect 385706 - End
    }  
  /***************************************************************************************************
* @author       Chandra Shekhar
* @date         06/16/2020
* @methodname   redirectToIndividualDashboard
* @description  this method redirects the Waiver user to Individual Dashboard
* @return       ssp_LightningResponse
*****************************************************************************************************/
    @AuraEnabled
    public static Contact redirectToIndividualDashboard(String tokenId){
        User updateUser= new User();
        updateUser.Waiver_OrgId__c='';
        updateUser.Waiver_UserId__c='';
        SSP_WDT_ConsumeRequestWrapper consumeRequest = new SSP_WDT_ConsumeRequestWrapper();           
        consumeRequest.tokenId                  = tokenId;
        consumeRequest.requestType              = 'ConsumeToken';
        consumeRequest.currentApplicationName   = 'SSP';        
        Map<String, Object> mapConsumeParams = new Map<String, Object> {SSP_InterfaceConstants.JSON_BODY => JSON.serialize(consumeRequest)};
        List<Object> consumeResponse = IntegrationFactory.invokeCallout(SSP_InterfaceConstants.SSP_WDT_Consume, mapConsumeParams);
        SSP_WDT_ConsumeResponseWrapper consumeWrapResponse =  (SSP_WDT_ConsumeResponseWrapper)consumeResponse[0];
        
        String redirectedUserRole=   consumeWrapResponse.tokenAttributes.get('MWMARole') ;
        updateUser.Id=UserInfo.getUserId();
        if(String.isNotBlank(redirectedUserRole)){
            switch on redirectedUserRole{//386561
                when 'WAIVER DIRECT SERVICE PROVIDER SUPERVISOR'{
                    redirectedUserRole = 'WAIVER DIRECT SERVICE PROVIDER SUPERVISO';
                }
                when 'Case Management Administrator (Read Only)'{
                    redirectedUserRole = 'Case Management Administrator (Read Only';
                }
            }            
            SSP_RoleIdentifier__mdt roleName = [Select Id, Role_API__c,RoleId__c from SSP_RoleIdentifier__mdt WHERE label = :redirectedUserRole];
            updateUser.SelectedRole__c=roleName.Role_API__c;
        }
        if(consumeWrapResponse.tokenAttributes.containsKey('UserId')){
            updateUser.Waiver_UserId__c=consumeWrapResponse.tokenAttributes.get('UserId');
        }
        if(consumeWrapResponse.tokenAttributes.containsKey('OrganizationEmployeedId')){
            updateUser.Waiver_OrgId__c=consumeWrapResponse.tokenAttributes.get('OrganizationEmployeedId');
        }                       
        SSP_GenericDMLHelper.updateRecords(new List<User>{updateUser},new List<String>{'SelectedRole__c','Waiver_OrgId__c','Waiver_UserId__c'});        
        
        Contact con= new Contact();
        Con.FirstName=consumeWrapResponse.tokenAttributes.get('IndividualFirstName') ;
        Con.LastName=consumeWrapResponse.tokenAttributes.get('IndividualLastName') ;
        Con.MiddleName=consumeWrapResponse.tokenAttributes.get('IndividualMiddleInitial');     
        Con.IndividualId__c=consumeWrapResponse.tokenAttributes.get('IndividualId') ;
        return con;
    }
    
    @AuraEnabled
    public static String updateRoleAndPermissionForWaiver(String tokenId){
        User updateUser= new User();
        updateUser.Waiver_OrgId__c='';
        updateUser.Waiver_UserId__c='';
        SSP_WDT_ConsumeRequestWrapper consumeRequest = new SSP_WDT_ConsumeRequestWrapper();           
        consumeRequest.tokenId                  = tokenId;
        consumeRequest.requestType              = 'ConsumeToken';
        consumeRequest.currentApplicationName   = 'SSP';
        
        Map<String, Object> mapConsumeParams = new Map<String, Object> {SSP_InterfaceConstants.JSON_BODY => JSON.serialize(consumeRequest)};
        List<Object> consumeResponse = IntegrationFactory.invokeCallout(SSP_InterfaceConstants.SSP_WDT_Consume, mapConsumeParams);
        SSP_WDT_ConsumeResponseWrapper consumeWrapResponse =  (SSP_WDT_ConsumeResponseWrapper)consumeResponse[0];
        String redirectedUserRole=   consumeWrapResponse.tokenAttributes.get('MWMARole') ;
        updateUser.Id=UserInfo.getUserId();
        if(String.isNotBlank(redirectedUserRole)){
            SSP_RoleIdentifier__mdt roleName = [Select Id, Role_API__c,RoleId__c from SSP_RoleIdentifier__mdt WHERE label = :redirectedUserRole];
            updateUser.SelectedRole__c=roleName.Role_API__c;
            updateUser.ShowCitizenDashboard__c = false;
        }
        if(consumeWrapResponse.tokenAttributes.containsKey('UserId')){
            updateUser.Waiver_UserId__c=consumeWrapResponse.tokenAttributes.get('UserId');
        }
        if(consumeWrapResponse.tokenAttributes.containsKey('OrganizationEmployeedId')){
            updateUser.Waiver_OrgId__c=consumeWrapResponse.tokenAttributes.get('OrganizationEmployeedId');
        }                       
        SSP_GenericDMLHelper.updateRecords(new List<User>{updateUser},new List<String>{'SelectedRole__c','Waiver_OrgId__c','Waiver_UserId__c'}); 
        
        return String.valueOf(updateUser.SelectedRole__c);
        
    }
        /***************************************************************************************************
* @author       Chandra Shekhar
* @date         06/11/2020
* @methodname   getWantToDashboardLinkVisibility
* @description  This method takes a user role and retunrs Visibility of links on dashboard
* @return       ssp_LightningResponse
*****************************************************************************************************/
    @AuraEnabled
    public static SSP_LightningResponse getWantToDashboardLinkVisibility(String userId){
        SSP_Utility.isAuthenticatedUser(); 
        SSP_LightningResponse dataToSend = new SSP_LightningResponse();
        try{  
            String userRole=SSP_Utility.getUserDetails(userId).get('userRole');          
            Map<String,Boolean> permissonToAccess=new Map<String,Boolean>();
            Map<String,Boolean> linkRoleVisibility=new Map<String,Boolean>();
            permissonToAccess.put('NotAccessible',false);
            permissonToAccess.put('Editable',true);            
            permissonToAccess.put('ReadOnly',true);
            for(FieldPermissions__mdt fieldPermissions :  (List<FieldPermissions__mdt>)SSP_Utility.fetchRecords(
                new Map<String, String>{SSP_GlobalConstants.SSP_OBJECT_NAME => SSP_GlobalConstants.MDT_FIELD_PERMISSIONS, SSP_GlobalConstants.SSP_OPERATOR => SSP_GlobalConstants.OPERATOR_AND},SSP_GlobalConstants.MDT_FIELD_PERMISSIONS_FIELDS, new Map<String, String>{SSP_GlobalConstants.KEY_LIMIT=>'1000','Role__c'=>userRole,'ScreenName__c'=>'SSP_NonCitDash_WantTo'})){
                    linkRoleVisibility.put(fieldPermissions.FieldElementName__c, permissonToAccess.get(fieldPermissions.Permission__c));
                }            
            dataToSend.put('linkRoleVisibility', linkRoleVisibility);             
            dataToSend.put('bIsSuccess', true);
        }
        catch(Exception ex){
            List<LOG_LogMessage__c> lstLogMessages = LOG_LogMessageUtility.logMessage(ex, 'SSP_NonCitizenDashboardController', 'getWantToDashboardLinkVisibility', ex.getMessage() , true);            
            dataToSend.put('bIsSuccess', false);            
            dataToSend.put('error', lstLogMessages[0].Id);
            dataToSend.addException(ex, lstLogMessages[0].Id);
        } 
        return dataToSend;
    }
     /***************************************************************************************************
* @author       Chandra Shekhar
* @date         06/03/2020
* @methodname   getScreenPermissionBasedOnRole
* @description  This method takes userId and returns screen Visibility of Client Case Notes
* @return       SSP_LightningResponse
*****************************************************************************************************/
    @AuraEnabled
    public static SSP_LightningResponse getScreenPermissionBasedOnRole(String userId){
        SSP_Utility.isAuthenticatedUser(); 
        SSP_LightningResponse dataToSend = new SSP_LightningResponse();
        try{
            String userRole=SSP_Utility.getUserDetails(userId).get('userRole');
            Map<String,Boolean> permissonToAccess=new Map<String,Boolean>();
            permissonToAccess.put('NotAccessible',false);
            permissonToAccess.put('Editable',true);            
            permissonToAccess.put('ReadOnly',true);
            Map<String,String> screenPermissionsMap =new Map<String,String>();
            for(ScreenPermissions__mdt screenPermissions :  (List<ScreenPermissions__mdt>)SSP_Utility.fetchRecords(
                new Map<String, String>{SSP_GlobalConstants.SSP_OBJECT_NAME => SSP_GlobalConstants.MDT_SCREEN_PERMISSIONS, SSP_GlobalConstants.SSP_OPERATOR => SSP_GlobalConstants.OPERATOR_AND},
                SSP_GlobalConstants.MDT_SCREEN_PERMISSIONS_FIELDS, 
                new Map<String, String>{SSP_GlobalConstants.KEY_LIMIT=>'1','Role__c'=>userRole,'ScreenName__c'=>'SSP_Dash_CaseNote'})){
                    screenPermissionsMap.put(userRole,screenPermissions.Permission__c);
                }
            dataToSend.put('screenPermissionsMap', screenPermissionsMap);             
            dataToSend.put('bIsSuccess', true);
        }
        catch(Exception ex){
            List<LOG_LogMessage__c> lstLogMessages = LOG_LogMessageUtility.logMessage(ex, 'SSP_NonCitizenDashboardService', 'getScreenPermissionBasedOnRole', ex.getMessage() , true);            
            dataToSend.put('bIsSuccess', false);            
            dataToSend.put('error', lstLogMessages[0].Id);
            dataToSend.addException(ex, lstLogMessages[0].Id);
        } 
        return dataToSend;        
    } 
}