force-app/main/default/objects/ClaimMySiteRequest__c/ClaimMySiteRequest__c.object-meta.xml
<CustomObject>
    <description>Claim My Site Request object contains fields, layouts, profile specific record types and other information related to the claim request made by the Organization owner.</description>
    <label>Claim</label>
    <nameField>
        <displayFormat>CLM-{0000}</displayFormat>
        <label>Access Request No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ClaimMySiteRequest__c/fields/DateOfRequest__c.field-meta.xml
<CustomField>
    <fullName>DateOfRequest__c</fullName>
    <description>Date the request is made</description>
    <label>Date Requested</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ClaimMySiteRequest__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email Address of the Organization holder.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <inlineHelpText>Email</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/ClaimMySiteRequest__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>First Name of the Requester</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClaimMySiteRequest__c/fields/ReasonForDenial__c.field-meta.xml
<CustomField>
    <fullName>ReasonForDenial__c</fullName>
    <description>If state user is denying the request, it must provide a Reason for Denial that will be communicated to the requester.</description>
    <label>Reason For Denial</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ClaimMySiteRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>A picklist field containing the different values for the status of the request made by the Organization holder, as the request furthers in the approval flow.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of contact-Active or Inactive</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Email_Text_Communication_Settings__c/Email_Text_Communication_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Email Text Communication Settings</label>
</CustomObject>

force-app/main/default/objects/Email_Text_Communication_Settings__c/fields/Email_Communication__c.field-meta.xml
<CustomField>
    <fullName>Email_Communication__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Email Communication</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Email_Text_Communication_Settings__c/fields/Text_Communication__c.field-meta.xml
<CustomField>
    <fullName>Text_Communication__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Text Communication</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EmailSetting__c/EmailSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Email Setting</label>
</CustomObject>

force-app/main/default/objects/EmailSetting__c/fields/Is_on__c.field-meta.xml
<CustomField>
    <fullName>Is_on__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is on?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/RE_ClaimSiteRequestCtrlTest.cls
/**
 * Class Name    : RE_ClaimSiteRequestTest{
 * Owner         : DELOITTE
 * Created Date  : 05/27/2019
 * Description   : Claim my site request record insertion test class
 *
 *                            M O D I F I C A T I O N   L O G                                          
 *
 *  Date        Developer       Description                                                         
 *  ----------  -----------     -------------------------------------------------------------------
 *  05/27/2019  Arun       Initial Version
 *  Test checkin
 **/
@IsTest
public class RE_ClaimSiteRequestCtrlTest {
    @testSetup static void testClaimRequestData()  {
        //RecordType claimRecordType=GeneralUtility.fetchRecordType(RE_GlobalConstants.strClaimRecordTypeDeveloperName, RE_GlobalConstants.strClaimObjectName);
        RecordType objRecordType = GeneralUtility.fetchRecordType(System.Label.ClaimRecordTypeStaff, 'ClaimMySiteRequest__c');
        ClaimMySiteRequest__c claimReq=new ClaimMySiteRequest__c();
        claimReq.FirstName__c=RE_GlobalConstants.strClaimReqFirstName; 
        claimReq.Status__c = 'Approved';
        insert claimReq;
       
        ClaimMySiteRequest__c newclaimReq=new ClaimMySiteRequest__c();
        newclaimReq.FirstName__c=RE_GlobalConstants.strClaimReqFirstName; 
        newclaimReq.Status__c = 'New';
        newclaimReq.Email__c = 'test@test.com';
        newclaimReq.Status__c = 'New';
        newclaimReq.RecordTypeId = objRecordType.Id;
        insert newclaimReq;
        EmailSetting__c EMailSetting= new EmailSetting__c();
        EMailSetting.Name='Claim Site request submission mail';
        EMailSetting.Is_on__c = true;
        insert EMailSetting;
        EmailSetting__c EMailSettingTwo= new EmailSetting__c();
        EMailSettingTwo.Name='Claim Site Denial mail';
        EMailSettingTwo.Is_on__c = true;
        insert EMailSettingTwo;
        EmailSetting__c EMailSettingThree= new EmailSetting__c();
        EMailSettingThree.Name='Claim Site Approval mail';
        EMailSettingThree.Is_on__c = true;
        insert EMailSettingThree;
        
        TestDataFactory.testDataSetup();
        Profile objProfile = [SELECT Id FROM Profile WHERE Name =: RE_GlobalConstants.STANDARD_USER_PROFILE_TEST];
        insert new Email_Text_Communication_Settings__c(SetupOwnerId=objProfile.Id, Email_Communication__c=true,Text_Communication__c=true);
        Id sContactId = [Select Id FROM Contact  Where Email =: RE_GlobalConstants.CPADMIN_USER1_EMAIL_TEST LIMIT 1].Id;
        User objREUser = TestDataFactory.createSpecificCommunityUser('reusr',null, 'REUser',RE_GlobalConstants.SAMPLE_USER_NAME_TEST, RE_GlobalConstants.SAMPLE_USER_EMAIL_TEST, RE_GlobalConstants.SAMPLE_USER_EMAIL_TEST, objProfile.Id, true);
       
    }
    @isTest static void testGetClaimRequestDetails(){
        insert new Email_Text_Communication_Settings__c(Email_Communication__c=true,Text_Communication__c=true);
        Test.startTest();
        ClaimMySiteRequest__c objClaimRequest = new ClaimMySiteRequest__c();
        objClaimRequest.FirstName__c = RE_GlobalConstants.strClaimReqFirstName;
        objClaimRequest.Email__c = 'test@test.com';
        objClaimRequest.Status__c = 'Approved';
        RE_CreateLightningServerResponse response = RE_ClaimSiteRequestCtrl.saveClaimSiteRequest(objClaimRequest);
        RE_CreateLightningServerResponse roleResponse = RE_ClaimSiteRequestCtrl.fetchOrgRolePickValues();
        System.assertEquals(response.isSuccessful, true,'Success');
        Test.stopTest();
    }
    
    
    
    @isTest static void testGetClaimRequest(){
        User objUser = [SELECT Id, ContactId FROM User WHERE Email =: RE_GlobalConstants.COMMUNITY_USER_EMAIL_TEST LIMIT 1];
        RecordType objRecordType = GeneralUtility.fetchRecordType(System.Label.ClaimRecordTypeStaff, 'ClaimMySiteRequest__c');
        System.runAs(objUser) {
            Test.startTest();
            ClaimMySiteRequest__c objClaimRequest = new ClaimMySiteRequest__c();
            objClaimRequest.FirstName__c = RE_GlobalConstants.strClaimReqFirstName;
            objClaimRequest.Email__c = 'test@test.com';
            objClaimRequest.Status__c = 'New';
            objClaimRequest.RecordTypeId = objRecordType.Id;
            objClaimRequest.DateOfRequest__c = System.today();
            insert objClaimRequest;
            RE_CreateLightningServerResponse response = RE_ClaimSiteRequestCtrl.saveClaimSiteRequest(objClaimRequest);
            RE_CreateLightningServerResponse roleResponse = RE_ClaimSiteRequestCtrl.fetchOrgRolePickValues();
            System.assertEquals(response.isSuccessful, false,'Success');
            Test.stopTest();
        }        
    }
        
    @isTest static void testcreateCommunicationNubecord(){
        User objUser = [SELECT Id, ContactId FROM User WHERE Email =: RE_GlobalConstants.COMMUNITY_USER_EMAIL_TEST LIMIT 1];
        insert new Email_Text_Communication_Settings__c(Email_Communication__c=true,Text_Communication__c=true);
        System.runAs(objUser) {
            Test.startTest();
            
            ClaimMySiteRequest__c objClaimRequest = new ClaimMySiteRequest__c();
            objClaimRequest.FirstName__c = RE_GlobalConstants.strClaimReqFirstName;
            objClaimRequest.Email__c = 'test@test.com';
            objClaimRequest.Status__c = 'Approved';
            insert objClaimRequest;
            List<Id> lstId = new List<Id>();
            lstId.add(objClaimRequest.Id);
            RE_ClaimSiteRequestCtrl.createCommunicationNubecord(lstId);
            RE_CreateLightningServerResponse response  = RE_ClaimSiteRequestCtrl.saveClaimSiteRequest(objClaimRequest);
            System.assertEquals(response.isSuccessful, false,'Success');
            Test.stopTest();
        }        
    }
    @isTest static void testcreateCommunication(){
        User objUser = [SELECT Id, ContactId FROM User WHERE Email =: RE_GlobalConstants.COMMUNITY_USER_EMAIL_TEST LIMIT 1];
        insert new Email_Text_Communication_Settings__c(Email_Communication__c=true,Text_Communication__c=true);
        System.runAs(objUser) {
            Test.startTest();
            
            
            ClaimMySiteRequest__c objClaimRequest = new ClaimMySiteRequest__c();
            objClaimRequest.FirstName__c = RE_GlobalConstants.strClaimReqFirstName;
            objClaimRequest.Email__c = 'test123@test.com';
            objClaimRequest.Status__c = 'Denied';
            objClaimRequest.ReasonForDenial__c = 'Test Denial';
            insert objClaimRequest;
            List<Id> lstId = new List<Id>();
            lstId.add(objClaimRequest.Id);
            RE_ClaimSiteRequestCtrl.createCommunicationNubecord(lstId);
            RE_CreateLightningServerResponse response = RE_ClaimSiteRequestCtrl.saveClaimSiteRequest(null);
            System.assertEquals(response.isSuccessful, false,'Success');
            Test.stopTest();
        }        
    }
    
}